#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from typing import Optional

import pytest

from cmk.base.plugins.agent_based.agent_based_api.v1 import Attributes, Result, State, TableRow
from cmk.base.plugins.agent_based.agent_based_api.v1.type_defs import StringTable
from cmk.base.plugins.agent_based.utils.interfaces import Interface
from cmk.base.plugins.agent_based.winperf_if import (
    check_if_dhcp,
    inventory_winperf_if,
    parse_winperf_if,
    Section,
    SubSection,
)


@pytest.mark.parametrize(
    "string_table, section",
    [
        pytest.param(
            [
                ["1630928323.48", "510", "10000000"],
                ["1", "instances:", "Intel[R]_PRO_1000_MT_Desktop_Adapter"],
                ["-122", "61386860", "bulk_count"],
                ["-110", "48930", "bulk_count"],
                ["-244", "43033", "bulk_count"],
                ["-58", "5897", "bulk_count"],
                ["10", "1000000000", "large_rawcount"],
                ["-246", "60023498", "bulk_count"],
                ["14", "42348", "bulk_count"],
                ["16", "685", "bulk_count"],
                ["18", "0", "large_rawcount"],
                ["20", "0", "large_rawcount"],
                ["22", "0", "large_rawcount"],
                ["-4", "1363362", "bulk_count"],
                ["26", "5771", "bulk_count"],
                ["28", "126", "bulk_count"],
                ["30", "0", "large_rawcount"],
                ["32", "0", "large_rawcount"],
                ["34", "0", "large_rawcount"],
                ["1086", "0", "large_rawcount"],
                ["1088", "0", "large_rawcount"],
                ["1090", "0", "bulk_count"],
                ["1092", "0", "bulk_count"],
                ["1094", "0", "large_rawcount"],
            ],
            (
                1630928323.48,
                [
                    Interface(
                        index="1",
                        descr="Intel[R] PRO 1000 MT Desktop Adapter",
                        alias="Intel[R] PRO 1000 MT Desktop Adapter",
                        type="6",
                        speed=1000000000,
                        oper_status="1",
                        in_octets=60023498,
                        in_ucast=42348,
                        in_mcast=0,
                        in_bcast=685,
                        in_discards=0,
                        in_errors=0,
                        out_octets=1363362,
                        out_ucast=5771,
                        out_mcast=0,
                        out_bcast=126,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=61386860,
                    )
                ],
                {},
            ),
            id="native agent data only",
        ),
        pytest.param(
            [
                ["1425370325.75", "510"],
                [
                    "9",
                    "instances:",
                    "QLogic_1_10GbE_Server_Adapter__2",
                    "QLogic_1_10GbE_Server_Adapter",
                    "Intel[R]_I350_Gigabit_Network_Connection",
                    "Intel[R]_I350_Gigabit_Network_Connection__2",
                    "Intel[R]_I350_Gigabit_Network_Connection__3",
                    "Intel[R]_I350_Gigabit_Network_Connection__4",
                    "IBM_USB_Remote_NDIS_Network_Device__2",
                    "isatap.{A447D54F-0E4B-40B3-9FBA-228F7DCE8FC7}",
                    "isatap.{4FCE4C48-6217-465A-B807-B61499AE570C}",
                ],
                [
                    "-122",
                    "8902209474",
                    "23935663",
                    "0",
                    "0",
                    "0",
                    "0",
                    "622938240",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "-110",
                    "10989775",
                    "27949",
                    "0",
                    "0",
                    "0",
                    "0",
                    "6788061",
                    "0",
                    "0",
                    "bulk_count",
                ],
                ["-244", "6349287", "19102", "0", "0", "0", "0", "3098296", "0", "0", "bulk_count"],
                ["-58", "4640488", "8847", "0", "0", "0", "0", "3689765", "0", "0", "bulk_count"],
                [
                    "10",
                    "10000000000",
                    "10000000000",
                    "0",
                    "0",
                    "0",
                    "0",
                    "9728000",
                    "100000",
                    "100000",
                    "large_rawcount",
                ],
                [
                    "-246",
                    "6273480850",
                    "20846807",
                    "0",
                    "0",
                    "0",
                    "0",
                    "293841578",
                    "0",
                    "0",
                    "bulk_count",
                ],
                ["14", "5756369", "18266", "0", "0", "0", "0", "3089007", "0", "0", "bulk_count"],
                ["16", "592918", "836", "0", "0", "0", "0", "9289", "0", "0", "bulk_count"],
                ["18", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                ["20", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                ["22", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                [
                    "-4",
                    "2628728624",
                    "3088856",
                    "0",
                    "0",
                    "0",
                    "0",
                    "329096662",
                    "0",
                    "0",
                    "bulk_count",
                ],
                ["26", "4625712", "8741", "0", "0", "0", "0", "3089008", "0", "0", "bulk_count"],
                ["28", "14776", "106", "0", "0", "0", "0", "600757", "0", "0", "bulk_count"],
                ["30", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                ["32", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                ["34", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                ["1086", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                ["1088", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                ["1090", "0", "0", "0", "0", "0", "0", "0", "0", "0", "bulk_count"],
                ["1092", "0", "0", "0", "0", "0", "0", "0", "0", "0", "bulk_count"],
                ["1094", "0", "0", "0", "0", "0", "0", "0", "0", "0", "large_rawcount"],
                [
                    "Node",
                    "MACAddress",
                    "Name",
                    "NetConnectionID",
                    "NetConnectionStatus",
                    "Speed",
                    "GUID",
                ],
                [
                    "TBWAW-VEEAM01",
                    "42:F2:E9:21:BE:D1 ",
                    "IBM USB Remote NDIS Network Device #2 ",
                    "Local Area Connection 2 ",
                    "2 ",
                    "9728000 ",
                    "{A447D54F-0E4B-40B3-9FBA-228F7DCE8FC7}",
                ],
                [
                    "TBWAW-VEEAM01",
                    "40:F2:E9:21:BE:D2 ",
                    "Intel(R) I350 Gigabit Network Connection ",
                    "Ethernet 3 ",
                    "7 ",
                    "9223372036854775807 ",
                    "{1C656D16-F30D-4714-9A7E-B3D3F9AD52FA}",
                ],
                [
                    "TBWAW-VEEAM01",
                    "40:F2:E9:21:BE:D3 ",
                    "Intel(R) I350 Gigabit Network Connection #2 ",
                    "Ethernet 4 ",
                    "7 ",
                    "9223372036854775807 ",
                    "{F9C89525-0500-4A6B-95AC-95F66BDA739A}",
                ],
                [
                    "TBWAW-VEEAM01",
                    "40:F2:E9:21:BE:D4 ",
                    "Intel(R) I350 Gigabit Network Connection #3 ",
                    "Ethernet 5 ",
                    "7 ",
                    "9223372036854775807 ",
                    "{A0D28181-6DF8-4A80-9837-D2933D013510}",
                ],
                [
                    "TBWAW-VEEAM01",
                    "40:F2:E9:21:BE:D5 ",
                    "Intel(R) I350 Gigabit Network Connection #4 ",
                    "Ethernet 6 ",
                    "7 ",
                    "9223372036854775807 ",
                    "{95CA2691-7AFA-4842-A769-F521FE6173B2}",
                ],
                [
                    "TBWAW-VEEAM01",
                    "5C:F3:FC:37:2A:30 ",
                    "QLogic 1/10GbE Server Adapter ",
                    "Ethernet 2 ",
                    "2 ",
                    " ",
                    "{2B232067-0EE5-41EE-B498-0CA2FE8715D0}",
                ],
                [
                    "TBWAW-VEEAM01",
                    "5C:F3:FC:37:2A:34 ",
                    "QLogic 1/10GbE Server Adapter ",
                    "Ethernet ",
                    "1 ",
                    " ",
                    "{11477AB1-0A73-449C-8768-A17F47C02A1F}",
                ],
                [
                    "TBWAW-VEEAM01",
                    "5C:F3:FC:37:2A:30 ",
                    "Microsoft Network Adapter Multiplexor Driver ",
                    "LAN ",
                    "2 ",
                    "20000000000 ",
                    "{4FCE4C48-6217-465A-B807-B61499AE570C}",
                ],
            ],
            (
                1425370325.75,
                [
                    Interface(
                        index="1",
                        descr="QLogic 1 10GbE Server Adapter 2",
                        alias="QLogic 1 10GbE Server Adapter 2",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=6273480850,
                        in_ucast=5756369,
                        in_mcast=0,
                        in_bcast=592918,
                        in_discards=0,
                        in_errors=0,
                        out_octets=2628728624,
                        out_ucast=4625712,
                        out_mcast=0,
                        out_bcast=14776,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=8902209474,
                    ),
                    Interface(
                        index="2",
                        descr="QLogic 1 10GbE Server Adapter",
                        alias="Ethernet 2",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=20846807,
                        in_ucast=18266,
                        in_mcast=0,
                        in_bcast=836,
                        in_discards=0,
                        in_errors=0,
                        out_octets=3088856,
                        out_ucast=8741,
                        out_mcast=0,
                        out_bcast=106,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="\\óü7*0",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=23935663,
                    ),
                    Interface(
                        index="3",
                        descr="Intel[R] I350 Gigabit Network Connection",
                        alias="Ethernet 3",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="@òé!¾Ò",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="4",
                        descr="Intel[R] I350 Gigabit Network Connection 2",
                        alias="Ethernet 4",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="@òé!¾Ó",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="5",
                        descr="Intel[R] I350 Gigabit Network Connection 3",
                        alias="Ethernet 5",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="@òé!¾Ô",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="6",
                        descr="Intel[R] I350 Gigabit Network Connection 4",
                        alias="Ethernet 6",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="@òé!¾Õ",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="7",
                        descr="IBM USB Remote NDIS Network Device 2",
                        alias="Local Area Connection 2",
                        type="6",
                        speed=9728000,
                        oper_status="1",
                        in_octets=293841578,
                        in_ucast=3089007,
                        in_mcast=0,
                        in_bcast=9289,
                        in_discards=0,
                        in_errors=0,
                        out_octets=329096662,
                        out_ucast=3089008,
                        out_mcast=0,
                        out_bcast=600757,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="Bòé!¾Ñ",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=622938240,
                    ),
                    Interface(
                        index="8",
                        descr="isatap.{A447D54F-0E4B-40B3-9FBA-228F7DCE8FC7}",
                        alias="isatap.{A447D54F-0E4B-40B3-9FBA-228F7DCE8FC7}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="9",
                        descr="isatap.{4FCE4C48-6217-465A-B807-B61499AE570C}",
                        alias="isatap.{4FCE4C48-6217-465A-B807-B61499AE570C}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                ],
                {},
            ),
            id="additional Win32_NetworkAdapter data",
        ),
        pytest.param(
            [
                ["1498114570.10", "5102343752"],
                [
                    "12",
                    "instances:",
                    "Intel[R]_Gigabit_4P_I350-t_rNDC",
                    "Intel[R]_Ethernet_10G_2P_X520_Adapter",
                    "Intel[R]_Ethernet_10G_2P_X520_Adapter__2",
                    "Intel[R]_Gigabit_4P_I350-t_rNDC__2",
                    "Intel[R]_Gigabit_4P_I350-t_rNDC__3",
                    "Intel[R]_Gigabit_4P_I350-t_rNDC__4",
                    "Intel[R]_Ethernet_10G_2P_X520_Adapter__3",
                    "Intel[R]_Ethernet_10G_2P_X520_Adapter__4",
                    "isatap.corp.nintendo.eu",
                    "isatap.{0143C2F2-BFF1-4839-8766-82C6EB3FC440}",
                    "isatap.{16377083-0A9A-456B-AB35-9A37E78B3FD4}",
                    "isatap.{7A093D2B-D64D-43DF-A0F6-050996EE8D9A}",
                ],
                [
                    "-122",
                    "176685745",
                    "5355972550276",
                    "1581894368422",
                    "0",
                    "0",
                    "0",
                    "271891678",
                    "145209040",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "-110",
                    "2414588",
                    "5942719462",
                    "1210382147",
                    "0",
                    "0",
                    "0",
                    "3033012",
                    "2099072",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "-244",
                    "2345712",
                    "3020015564",
                    "376780642",
                    "0",
                    "0",
                    "0",
                    "3033012",
                    "2099072",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "-58",
                    "68876",
                    "2922703898",
                    "833601505",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "10",
                    "1000000000",
                    "10000000000",
                    "10000000000",
                    "0",
                    "0",
                    "0",
                    "10000000000",
                    "10000000000",
                    "100000",
                    "100000",
                    "100000",
                    "100000",
                    "large_rawcount",
                ],
                [
                    "-246",
                    "168300731",
                    "2568258242370",
                    "410232131549",
                    "0",
                    "0",
                    "0",
                    "271891678",
                    "145209040",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "14",
                    "5438",
                    "3012412853",
                    "376555354",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "16",
                    "2340274",
                    "7601145",
                    "225288",
                    "0",
                    "0",
                    "0",
                    "3033012",
                    "2099072",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "18",
                    "0",
                    "1566",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "20",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "22",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "-4",
                    "8385014",
                    "2787714307906",
                    "1171662236873",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "26",
                    "3614",
                    "2922261424",
                    "833538016",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "28",
                    "65262",
                    "442474",
                    "63489",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "30",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "32",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "34",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "1086",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "1088",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                ["1090", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "bulk_count"],
                ["1092", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "bulk_count"],
                [
                    "1094",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                ["[teaming_start]"],
                [
                    "TeamName",
                    "TeamingMode",
                    "LoadBalancingAlgorithm",
                    "MemberMACAddresses",
                    "MemberNames",
                    "MemberDescriptions",
                    "Speed",
                    "GUID",
                ],
                [
                    "DAG-NET ",
                    "SwitchIndependent ",
                    "Dynamic ",
                    "A0:36:9F:B0:A3:60;A0:36:9F:B0:B3:66",
                    "SLOT 6 Port 1 DAG;SLOT 4 Port 2 DAG",
                    "Intel(R) Ethernet 10G 2P X520 Adapter #2;Intel(R) Ethernet 10G 2P X520 Adapter #4",
                    "10000000000;10000000000",
                    "{70F3DEC7-8347-4157-B066-95F5672F39BA};{9C4971CB-95AA-4B01-B828-F61B339E4F19}",
                ],
                [
                    "MAPI-NET ",
                    "SwitchIndependent ",
                    "Dynamic ",
                    "A0:36:9F:B0:A3:62;A0:36:9F:B0:B3:64",
                    "SLOT 6 Port 2 MAPI;SLOT 4 Port 1 MAPI",
                    "Intel(R) Ethernet 10G 2P X520 Adapter;Intel(R) Ethernet 10G 2P X520 Adapter #3",
                    "10000000000;10000000000",
                    "{4C88A19B-5EE4-44A6-ACBB-262131EE1560};{9BD62095-22A8-49CA-BA8B-A7846C6B5FDB}",
                ],
                ["[teaming_end]"],
            ],
            (
                1498114570.1,
                [
                    Interface(
                        index="1",
                        descr="Intel[R] Gigabit 4P I350-t rNDC",
                        alias="Intel[R] Gigabit 4P I350-t rNDC",
                        type="6",
                        speed=1000000000,
                        oper_status="1",
                        in_octets=168300731,
                        in_ucast=5438,
                        in_mcast=0,
                        in_bcast=2340274,
                        in_discards=0,
                        in_errors=0,
                        out_octets=8385014,
                        out_ucast=3614,
                        out_mcast=0,
                        out_bcast=65262,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=176685745,
                    ),
                    Interface(
                        index="2",
                        descr="Intel[R] Ethernet 10G 2P X520 Adapter",
                        alias="Intel[R] Ethernet 10G 2P X520 Adapter",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=2568258242370,
                        in_ucast=3012412853,
                        in_mcast=0,
                        in_bcast=7601145,
                        in_discards=1566,
                        in_errors=0,
                        out_octets=2787714307906,
                        out_ucast=2922261424,
                        out_mcast=0,
                        out_bcast=442474,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=5355972550276,
                    ),
                    Interface(
                        index="3",
                        descr="Intel[R] Ethernet 10G 2P X520 Adapter 2",
                        alias="Intel[R] Ethernet 10G 2P X520 Adapter 2",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=410232131549,
                        in_ucast=376555354,
                        in_mcast=0,
                        in_bcast=225288,
                        in_discards=0,
                        in_errors=0,
                        out_octets=1171662236873,
                        out_ucast=833538016,
                        out_mcast=0,
                        out_bcast=63489,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=1581894368422,
                    ),
                    Interface(
                        index="4",
                        descr="Intel[R] Gigabit 4P I350-t rNDC 2",
                        alias="Intel[R] Gigabit 4P I350-t rNDC 2",
                        type="6",
                        speed=0,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="5",
                        descr="Intel[R] Gigabit 4P I350-t rNDC 3",
                        alias="Intel[R] Gigabit 4P I350-t rNDC 3",
                        type="6",
                        speed=0,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="6",
                        descr="Intel[R] Gigabit 4P I350-t rNDC 4",
                        alias="Intel[R] Gigabit 4P I350-t rNDC 4",
                        type="6",
                        speed=0,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="7",
                        descr="Intel[R] Ethernet 10G 2P X520 Adapter 3",
                        alias="Intel[R] Ethernet 10G 2P X520 Adapter 3",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=271891678,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=3033012,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=271891678,
                    ),
                    Interface(
                        index="8",
                        descr="Intel[R] Ethernet 10G 2P X520 Adapter 4",
                        alias="Intel[R] Ethernet 10G 2P X520 Adapter 4",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=145209040,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=2099072,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=145209040,
                    ),
                    Interface(
                        index="9",
                        descr="isatap.corp.nintendo.eu",
                        alias="isatap.corp.nintendo.eu",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="10",
                        descr="isatap.{0143C2F2-BFF1-4839-8766-82C6EB3FC440}",
                        alias="isatap.{0143C2F2-BFF1-4839-8766-82C6EB3FC440}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="11",
                        descr="isatap.{16377083-0A9A-456B-AB35-9A37E78B3FD4}",
                        alias="isatap.{16377083-0A9A-456B-AB35-9A37E78B3FD4}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="12",
                        descr="isatap.{7A093D2B-D64D-43DF-A0F6-050996EE8D9A}",
                        alias="isatap.{7A093D2B-D64D-43DF-A0F6-050996EE8D9A}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                ],
                {},
            ),
            id="additional teaming info",
        ),
        pytest.param(
            [
                ["1498114570.10", "5102343752"],
                [
                    "12",
                    "instances:",
                    "Intel[R]_Gigabit_4P_I350-t_rNDC",
                    "Intel[R]_Ethernet_10G_2P_X520_Adapter",
                    "Intel[R]_Ethernet_10G_2P_X520_Adapter__2",
                    "Intel[R]_Gigabit_4P_I350-t_rNDC__2",
                    "Intel[R]_Gigabit_4P_I350-t_rNDC__3",
                    "Intel[R]_Gigabit_4P_I350-t_rNDC__4",
                    "Intel[R]_Ethernet_10G_2P_X520_Adapter__3",
                    "Intel[R]_Ethernet_10G_2P_X520_Adapter__4",
                    "isatap.corp.nintendo.eu",
                    "isatap.{0143C2F2-BFF1-4839-8766-82C6EB3FC440}",
                    "isatap.{16377083-0A9A-456B-AB35-9A37E78B3FD4}",
                    "isatap.{7A093D2B-D64D-43DF-A0F6-050996EE8D9A}",
                ],
                [
                    "-122",
                    "176685745",
                    "5355972550276",
                    "1581894368422",
                    "0",
                    "0",
                    "0",
                    "271891678",
                    "145209040",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "-110",
                    "2414588",
                    "5942719462",
                    "1210382147",
                    "0",
                    "0",
                    "0",
                    "3033012",
                    "2099072",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "-244",
                    "2345712",
                    "3020015564",
                    "376780642",
                    "0",
                    "0",
                    "0",
                    "3033012",
                    "2099072",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "-58",
                    "68876",
                    "2922703898",
                    "833601505",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "10",
                    "1000000000",
                    "10000000000",
                    "10000000000",
                    "0",
                    "0",
                    "0",
                    "10000000000",
                    "10000000000",
                    "100000",
                    "100000",
                    "100000",
                    "100000",
                    "large_rawcount",
                ],
                [
                    "-246",
                    "168300731",
                    "2568258242370",
                    "410232131549",
                    "0",
                    "0",
                    "0",
                    "271891678",
                    "145209040",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "14",
                    "5438",
                    "3012412853",
                    "376555354",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "16",
                    "2340274",
                    "7601145",
                    "225288",
                    "0",
                    "0",
                    "0",
                    "3033012",
                    "2099072",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "18",
                    "0",
                    "1566",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "20",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "22",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "-4",
                    "8385014",
                    "2787714307906",
                    "1171662236873",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "26",
                    "3614",
                    "2922261424",
                    "833538016",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "28",
                    "65262",
                    "442474",
                    "63489",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "bulk_count",
                ],
                [
                    "30",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "32",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "34",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "1086",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                [
                    "1088",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                ["1090", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "bulk_count"],
                ["1092", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "bulk_count"],
                [
                    "1094",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "large_rawcount",
                ],
                ["[teaming_start]"],
                [
                    "TeamName",
                    "TeamingMode",
                    "LoadBalancingAlgorithm",
                    "MemberMACAddresses",
                    "MemberNames",
                    "MemberDescriptions",
                    "Speed",
                    "GUID",
                ],
                [
                    "DAG-NET ",
                    "SwitchIndependent ",
                    "Dynamic ",
                    "A0:36:9F:B0:A3:60;A0:36:9F:B0:B3:66",
                    "SLOT 6 Port 1 DAG;SLOT 4 Port 2 DAG",
                    "Intel(R) Ethernet 10G 2P X520 Adapter #2;Intel(R) Ethernet 10G 2P X520 Adapter #4",
                    "10000000000;10000000000",
                    "{70F3DEC7-8347-4157-B066-95F5672F39BA};{9C4971CB-95AA-4B01-B828-F61B339E4F19}",
                ],
                [
                    "MAPI-NET ",
                    "SwitchIndependent ",
                    "Dynamic ",
                    "A0:36:9F:B0:A3:62;A0:36:9F:B0:B3:64",
                    "SLOT 6 Port 2 MAPI;SLOT 4 Port 1 MAPI",
                    "Intel(R) Ethernet 10G 2P X520 Adapter;Intel(R) Ethernet 10G 2P X520 Adapter #3",
                    "10000000000;10000000000",
                    "{4C88A19B-5EE4-44A6-ACBB-262131EE1560};{9BD62095-22A8-49CA-BA8B-A7846C6B5FDB}",
                ],
                ["[teaming_end]"],
                [
                    "Node",
                    "MACAddress",
                    "Name",
                    "NetConnectionID",
                    "NetConnectionStatus",
                    "Speed",
                    "GUID",
                ],
                [
                    "PWEX02 ",
                    " 24:6E:96:17:2F:38 ",
                    " Intel(R) Gigabit 4P I350-t rNDC ",
                    " NIC1 ",
                    " 2 ",
                    " 1000000000 ",
                    " {AD68A885-C33E-4E9E-AA6E-3650513F72B3}",
                ],
                [
                    "PWEX02 ",
                    " A0:36:9F:B0:A3:62 ",
                    " Intel(R) Ethernet 10G 2P X520 Adapter ",
                    " SLOT 6 Port 2 MAPI ",
                    " 2 ",
                    "  ",
                    " {4C88A19B-5EE4-44A6-ACBB-262131EE1560}",
                ],
                [
                    "PWEX02 ",
                    " A0:36:9F:B0:A3:60 ",
                    " Intel(R) Ethernet 10G 2P X520 Adapter ",
                    " SLOT 6 Port 1 DAG ",
                    " 2 ",
                    "  ",
                    " {70F3DEC7-8347-4157-B066-95F5672F39BA}",
                ],
                [
                    "PWEX02 ",
                    " 24:6E:96:17:2F:39 ",
                    " Intel(R) Gigabit 4P I350-t rNDC #2 ",
                    " NIC2 ",
                    " 7 ",
                    " 9223372036854775807 ",
                    " {84E4243F-9832-4923-93FB-F0A48F88FB1C}",
                ],
                [
                    "PWEX02 ",
                    " 24:6E:96:17:2F:3A ",
                    " Intel(R) Gigabit 4P I350-t rNDC #3 ",
                    " NIC3 ",
                    " 7 ",
                    " 9223372036854775807 ",
                    " {5EF9E8A8-5A85-42E7-AE8A-E3E63558D571}",
                ],
                [
                    "PWEX02 ",
                    " 24:6E:96:17:2F:3B ",
                    " Intel(R) Gigabit 4P I350-t rNDC #4 ",
                    " NIC4 ",
                    " 7 ",
                    " 9223372036854775807 ",
                    " {D7FE624A-1554-41D6-BC35-7EDDE1D396C3}",
                ],
                [
                    "PWEX02 ",
                    " A0:36:9F:B0:B3:64 ",
                    " Intel(R) Ethernet 10G 2P X520 Adapter ",
                    " SLOT 4 Port 1 MAPI ",
                    " 2 ",
                    "  ",
                    " {9BD62095-22A8-49CA-BA8B-A7846C6B5FDB}",
                ],
                [
                    "PWEX02 ",
                    " A0:36:9F:B0:B3:66 ",
                    " Intel(R) Ethernet 10G 2P X520 Adapter ",
                    " SLOT 4 Port 2 DAG ",
                    " 2 ",
                    "  ",
                    " {9C4971CB-95AA-4B01-B828-F61B339E4F19}",
                ],
                [
                    "PWEX02 ",
                    " A0:36:9F:B0:B3:64 ",
                    " Microsoft Network Adapter Multiplexor Driver ",
                    " MAPI-NET ",
                    " 2 ",
                    " 10000000000 ",
                    " {0143C2F2-BFF1-4839-8766-82C6EB3FC440}",
                ],
                [
                    "PWEX02 ",
                    " A0:36:9F:B0:A3:60 ",
                    " Microsoft Network Adapter Multiplexor Driver #2 ",
                    " DAG-NET ",
                    " 2 ",
                    " 10000000000 ",
                    " {16377083-0A9A-456B-AB35-9A37E78B3FD4}",
                ],
            ],
            (
                1498114570.1,
                [
                    Interface(
                        index="1",
                        descr="Intel[R] Gigabit 4P I350-t rNDC",
                        alias="NIC1",
                        type="6",
                        speed=1000000000,
                        oper_status="1",
                        in_octets=168300731,
                        in_ucast=5438,
                        in_mcast=0,
                        in_bcast=2340274,
                        in_discards=0,
                        in_errors=0,
                        out_octets=8385014,
                        out_ucast=3614,
                        out_mcast=0,
                        out_bcast=65262,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="$n\x96\x17/8",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=176685745,
                    ),
                    Interface(
                        index="2",
                        descr="Intel[R] Ethernet 10G 2P X520 Adapter",
                        alias="SLOT 6 Port 2 MAPI",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=2568258242370,
                        in_ucast=3012412853,
                        in_mcast=0,
                        in_bcast=7601145,
                        in_discards=1566,
                        in_errors=0,
                        out_octets=2787714307906,
                        out_ucast=2922261424,
                        out_mcast=0,
                        out_bcast=442474,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="\xa06\x9f°£b",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group="MAPI-NET",
                        node=None,
                        admin_status=None,
                        total_octets=5355972550276,
                    ),
                    Interface(
                        index="3",
                        descr="Intel[R] Ethernet 10G 2P X520 Adapter 2",
                        alias="SLOT 6 Port 1 DAG",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=410232131549,
                        in_ucast=376555354,
                        in_mcast=0,
                        in_bcast=225288,
                        in_discards=0,
                        in_errors=0,
                        out_octets=1171662236873,
                        out_ucast=833538016,
                        out_mcast=0,
                        out_bcast=63489,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="\xa06\x9f°£`",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group="DAG-NET",
                        node=None,
                        admin_status=None,
                        total_octets=1581894368422,
                    ),
                    Interface(
                        index="4",
                        descr="Intel[R] Gigabit 4P I350-t rNDC 2",
                        alias="NIC2",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="$n\x96\x17/9",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="5",
                        descr="Intel[R] Gigabit 4P I350-t rNDC 3",
                        alias="NIC3",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="$n\x96\x17/:",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="6",
                        descr="Intel[R] Gigabit 4P I350-t rNDC 4",
                        alias="NIC4",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="$n\x96\x17/;",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="7",
                        descr="Intel[R] Ethernet 10G 2P X520 Adapter 3",
                        alias="SLOT 4 Port 1 MAPI",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=271891678,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=3033012,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="\xa06\x9f°³d",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group="MAPI-NET",
                        node=None,
                        admin_status=None,
                        total_octets=271891678,
                    ),
                    Interface(
                        index="8",
                        descr="Intel[R] Ethernet 10G 2P X520 Adapter 4",
                        alias="SLOT 4 Port 2 DAG",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=145209040,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=2099072,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="\xa06\x9f°³f",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group="DAG-NET",
                        node=None,
                        admin_status=None,
                        total_octets=145209040,
                    ),
                    Interface(
                        index="9",
                        descr="isatap.corp.nintendo.eu",
                        alias="isatap.corp.nintendo.eu",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="10",
                        descr="isatap.{0143C2F2-BFF1-4839-8766-82C6EB3FC440}",
                        alias="isatap.{0143C2F2-BFF1-4839-8766-82C6EB3FC440}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="11",
                        descr="isatap.{16377083-0A9A-456B-AB35-9A37E78B3FD4}",
                        alias="isatap.{16377083-0A9A-456B-AB35-9A37E78B3FD4}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="12",
                        descr="isatap.{7A093D2B-D64D-43DF-A0F6-050996EE8D9A}",
                        alias="isatap.{7A093D2B-D64D-43DF-A0F6-050996EE8D9A}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                ],
                {},
            ),
            id="teaming and additional plugin data",
        ),
        pytest.param(
            [
                ["1631082981.52", "510", "10000000"],
                ["1", "instances:", "Intel[R]_PRO_1000_MT_Desktop_Adapter"],
                ["-122", "4535948", "bulk_count"],
                ["-110", "5645", "bulk_count"],
                ["-244", "4097", "bulk_count"],
                ["-58", "1548", "bulk_count"],
                ["10", "1000000000", "large_rawcount"],
                ["-246", "3575404", "bulk_count"],
                ["14", "3638", "bulk_count"],
                ["16", "459", "bulk_count"],
                ["18", "0", "large_rawcount"],
                ["20", "0", "large_rawcount"],
                ["22", "0", "large_rawcount"],
                ["-4", "960544", "bulk_count"],
                ["26", "1467", "bulk_count"],
                ["28", "81", "bulk_count"],
                ["30", "0", "large_rawcount"],
                ["32", "0", "large_rawcount"],
                ["34", "0", "large_rawcount"],
                ["1086", "0", "large_rawcount"],
                ["1088", "0", "large_rawcount"],
                ["1090", "0", "bulk_count"],
                ["1092", "0", "bulk_count"],
                ["1094", "0", "large_rawcount"],
                ["[dhcp_start]"],
                ["Description", "DHCPEnabled"],
                ["Microsoft", "Kernel", "Debug", "Network", "Adapter", "TRUE"],
                ["Intel(R)", "PRO/1000", "MT", "Desktop", "Adapter", "TRUE"],
                ["WAN", "Miniport", "(SSTP)", "FALSE"],
                ["WAN", "Miniport", "(IKEv2)", "FALSE"],
                ["WAN", "Miniport", "(L2TP)", "FALSE"],
                ["WAN", "Miniport", "(PPTP)", "FALSE"],
                ["WAN", "Miniport", "(PPPOE)", "FALSE"],
                ["WAN", "Miniport", "(IP)", "FALSE"],
                ["WAN", "Miniport", "(IPv6)", "FALSE"],
                ["WAN", "Miniport", "(Network", "Monitor)", "FALSE"],
                ["[dhcp_end]"],
            ],
            (
                1631082981.52,
                [
                    Interface(
                        index="1",
                        descr="Intel[R] PRO 1000 MT Desktop Adapter",
                        alias="Intel[R] PRO 1000 MT Desktop Adapter",
                        type="6",
                        speed=1000000000,
                        oper_status="1",
                        in_octets=3575404,
                        in_ucast=3638,
                        in_mcast=0,
                        in_bcast=459,
                        in_discards=0,
                        in_errors=0,
                        out_octets=960544,
                        out_ucast=1467,
                        out_mcast=0,
                        out_bcast=81,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=4535948,
                    )
                ],
                {
                    "Microsoft Kernel Debug Network Adapter": {
                        "Description": "Microsoft Kernel Debug Network Adapter",
                        "DHCPEnabled": "TRUE",
                    },
                    "Intel[R] PRO 1000 MT Desktop Adapter": {
                        "Description": "Intel(R) PRO/1000 MT Desktop Adapter",
                        "DHCPEnabled": "TRUE",
                    },
                    "WAN Miniport [SSTP]": {
                        "Description": "WAN Miniport (SSTP)",
                        "DHCPEnabled": "FALSE",
                    },
                    "WAN Miniport [IKEv2]": {
                        "Description": "WAN Miniport (IKEv2)",
                        "DHCPEnabled": "FALSE",
                    },
                    "WAN Miniport [L2TP]": {
                        "Description": "WAN Miniport (L2TP)",
                        "DHCPEnabled": "FALSE",
                    },
                    "WAN Miniport [PPTP]": {
                        "Description": "WAN Miniport (PPTP)",
                        "DHCPEnabled": "FALSE",
                    },
                    "WAN Miniport [PPPOE]": {
                        "Description": "WAN Miniport (PPPOE)",
                        "DHCPEnabled": "FALSE",
                    },
                    "WAN Miniport [IP]": {
                        "Description": "WAN Miniport (IP)",
                        "DHCPEnabled": "FALSE",
                    },
                    "WAN Miniport [IPv6]": {
                        "Description": "WAN Miniport (IPv6)",
                        "DHCPEnabled": "FALSE",
                    },
                    "WAN Miniport [Network Monitor]": {
                        "Description": "WAN Miniport (Network Monitor)",
                        "DHCPEnabled": "FALSE",
                    },
                },
            ),
        ),
    ],
)
def test_parse_winperf_if(
    string_table: StringTable,
    section: Section,
) -> None:
    assert parse_winperf_if(string_table) == section


_DHCP_INFO: SubSection = {
    "Microsoft Kernel Debug Network Adapter": {
        "Description": "Microsoft Kernel Debug Network Adapter",
        "DHCPEnabled": "TRUE",
    },
    "Intel[R] PRO 1000 MT Desktop Adapter": {
        "Description": "Intel(R) PRO/1000 MT Desktop Adapter",
        "DHCPEnabled": "TRUE",
    },
    "WAN Miniport [SSTP]": {
        "Description": "WAN Miniport (SSTP)",
        "DHCPEnabled": "FALSE",
    },
    "WAN Miniport [IKEv2]": {
        "Description": "WAN Miniport (IKEv2)",
        "DHCPEnabled": "FALSE",
    },
    "WAN Miniport [L2TP]": {
        "Description": "WAN Miniport (L2TP)",
        "DHCPEnabled": "FALSE",
    },
    "WAN Miniport [PPTP]": {
        "Description": "WAN Miniport (PPTP)",
        "DHCPEnabled": "FALSE",
    },
    "WAN Miniport [PPPOE]": {
        "Description": "WAN Miniport (PPPOE)",
        "DHCPEnabled": "FALSE",
    },
    "WAN Miniport [IP]": {
        "Description": "WAN Miniport (IP)",
        "DHCPEnabled": "FALSE",
    },
    "WAN Miniport [IPv6]": {
        "Description": "WAN Miniport (IPv6)",
        "DHCPEnabled": "FALSE",
    },
    "WAN Miniport [Network Monitor]": {
        "Description": "WAN Miniport (Network Monitor)",
        "DHCPEnabled": "FALSE",
    },
}


@pytest.mark.parametrize(
    "item, result",
    [
        pytest.param(
            "Intel[R] PRO 1000 MT Desktop Adapter",
            Result(
                state=State.WARN,
                summary="DHCP: enabled",
            ),
            id="item found, dhcp on",
        ),
        pytest.param(
            "WAN Miniport [IPv6]",
            Result(
                state=State.OK,
                summary="DHCP: FALSE",
            ),
            id="item found, dhcp off",
        ),
        pytest.param(
            "1",
            None,
            id="item not found",
        ),
    ],
)
def test_check_if_dhcp(
    item: str,
    result: Optional[Result],
) -> None:
    assert (
        check_if_dhcp(
            item,
            _DHCP_INFO,
        )
        == result
    )


def test_inventory_winperf_if() -> None:
    assert list(
        inventory_winperf_if(
            (
                1425370325.75,
                [
                    Interface(
                        index="1",
                        descr="QLogic 1 10GbE Server Adapter 2",
                        alias="QLogic 1 10GbE Server Adapter 2",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=6273480850,
                        in_ucast=5756369,
                        in_mcast=0,
                        in_bcast=592918,
                        in_discards=0,
                        in_errors=0,
                        out_octets=2628728624,
                        out_ucast=4625712,
                        out_mcast=0,
                        out_bcast=14776,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=8902209474,
                    ),
                    Interface(
                        index="2",
                        descr="QLogic 1 10GbE Server Adapter",
                        alias="Ethernet 2",
                        type="6",
                        speed=10000000000,
                        oper_status="1",
                        in_octets=20846807,
                        in_ucast=18266,
                        in_mcast=0,
                        in_bcast=836,
                        in_discards=0,
                        in_errors=0,
                        out_octets=3088856,
                        out_ucast=8741,
                        out_mcast=0,
                        out_bcast=106,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="\\óü7*0",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=23935663,
                    ),
                    Interface(
                        index="3",
                        descr="Intel[R] I350 Gigabit Network Connection",
                        alias="Ethernet 3",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="@òé!¾Ò",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="4",
                        descr="Intel[R] I350 Gigabit Network Connection 2",
                        alias="Ethernet 4",
                        type="6",
                        speed=0,
                        oper_status="7",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="@òé!¾Ó",
                        oper_status_name="Media disconnected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                    Interface(
                        index="7",
                        descr="IBM USB Remote NDIS Network Device 2",
                        alias="Local Area Connection 2",
                        type="6",
                        speed=9728000,
                        oper_status="1",
                        in_octets=293841578,
                        in_ucast=3089007,
                        in_mcast=0,
                        in_bcast=9289,
                        in_discards=0,
                        in_errors=0,
                        out_octets=329096662,
                        out_ucast=3089008,
                        out_mcast=0,
                        out_bcast=600757,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="Bòé!¾Ñ",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=622938240,
                    ),
                    Interface(
                        index="8",
                        descr="isatap.{A447D54F-0E4B-40B3-9FBA-228F7DCE8FC7}",
                        alias="isatap.{A447D54F-0E4B-40B3-9FBA-228F7DCE8FC7}",
                        type="6",
                        speed=100000,
                        oper_status="1",
                        in_octets=0,
                        in_ucast=0,
                        in_mcast=0,
                        in_bcast=0,
                        in_discards=0,
                        in_errors=0,
                        out_octets=0,
                        out_ucast=0,
                        out_mcast=0,
                        out_bcast=0,
                        out_discards=0,
                        out_errors=0,
                        out_qlen=0,
                        phys_address="",
                        oper_status_name="Connected",
                        speed_as_text="",
                        group=None,
                        node=None,
                        admin_status=None,
                        total_octets=0,
                    ),
                ],
                {},
            ),
        )
    ) == [
        TableRow(
            path=["networking", "interfaces"],
            key_columns={
                "index": 1,
                "description": "QLogic 1 10GbE Server Adapter 2",
                "alias": "QLogic 1 10GbE Server Adapter 2",
                "speed": 10000000000,
                "phys_address": "",
                "oper_status": 1,
                "port_type": 6,
                "available": False,
            },
            inventory_columns={},
            status_columns={},
        ),
        TableRow(
            path=["networking", "interfaces"],
            key_columns={
                "index": 2,
                "description": "QLogic 1 10GbE Server Adapter",
                "alias": "Ethernet 2",
                "speed": 10000000000,
                "phys_address": "5C:F3:FC:37:2A:30",
                "oper_status": 1,
                "port_type": 6,
                "available": False,
            },
            inventory_columns={},
            status_columns={},
        ),
        TableRow(
            path=["networking", "interfaces"],
            key_columns={
                "index": 7,
                "description": "IBM USB Remote NDIS Network Device 2",
                "alias": "Local Area Connection 2",
                "speed": 9728000,
                "phys_address": "42:F2:E9:21:BE:D1",
                "oper_status": 1,
                "port_type": 6,
                "available": False,
            },
            inventory_columns={},
            status_columns={},
        ),
        TableRow(
            path=["networking", "interfaces"],
            key_columns={
                "index": 8,
                "description": "isatap.{A447D54F-0E4B-40B3-9FBA-228F7DCE8FC7}",
                "alias": "isatap.{A447D54F-0E4B-40B3-9FBA-228F7DCE8FC7}",
                "speed": 100000,
                "phys_address": "",
                "oper_status": 1,
                "port_type": 6,
                "available": False,
            },
            inventory_columns={},
            status_columns={},
        ),
        Attributes(
            path=["networking"],
            inventory_attributes={
                "available_ethernet_ports": 0,
                "total_ethernet_ports": 4,
                "total_interfaces": 6,
            },
            status_attributes={},
        ),
    ]
