#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from cmk.base.plugins.agent_based.agent_based_api.v1 import (
    Metric,
    Result,
    Service,
    State,
)
from cmk.base.plugins.agent_based.aws_lambda_summary import parse_aws_lambda_summary

from cmk.base.plugins.agent_based.aws_lambda_performance import (
    _DEFAULT_PARAMETERS,
    _MORE_THAN_ONE_PER_HOUR,
    check_aws_lambda_performance,
    discover_aws_lambda,
    LambdaCloudwatchMetrics,
    parse_aws_lambda,
)

import pytest

_STRING_TABLE_AWS_LAMBDA_SUMMARY = [
    [
        '[{"FunctionName":', '"my_python_test_function",', '"FunctionArn":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Runtime":', '"python3.8",', '"Role":',
        '"arn:aws:iam::710145618630:role/service-role/my_python_test_function-role-uehtayw3",',
        '"Handler":', '"lambda_function.lambda_handler",', '"CodeSize":', '375,', '"Description":',
        '"",', '"Timeout":', '1,', '"MemorySize":', '128,', '"LastModified":',
        '"2021-06-28T09:13:25.232+0000",', '"CodeSha256":',
        '"1EwrRdaekBcaqZ+4V9ymuvyciq+xQOCu8gzLmB2ubS0=",', '"Version":', '"$LATEST",',
        '"TracingConfig":', '{"Mode":', '"PassThrough"},', '"RevisionId":',
        '"7f26e9a4-b0e2-4ff4-a6a1-7c52a90bd689"}]'
    ],
    [
        '[{"FunctionName":', '"myLambdaTestFunction",', '"FunctionArn":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Runtime":',
        '"python3.8",', '"Role":',
        '"arn:aws:iam::710145618630:role/service-role/myLambdaTestFunction-role-jp7mgseb",',
        '"Handler":', '"lambda_function.lambda_handler",', '"CodeSize":', '299,', '"Description":',
        '"",', '"Timeout":', '1,', '"MemorySize":', '128,', '"LastModified":',
        '"2021-06-24T12:46:32.415+0000",', '"CodeSha256":',
        '"fI06ZlRH/KN6Ra3twvdRllUYaxv182Tjx0qNWNlKIhI=",', '"Version":', '"$LATEST",',
        '"TracingConfig":', '{"Mode":', '"PassThrough"},', '"RevisionId":',
        '"2b10d3f5-827c-4e21-9647-c61ba360c8eb"}]'
    ]
]

# this is the metric data when a lambda function is not used in the last monitoring interval
_STRING_TABLE_AWS_LAMBDA_NOT_USED = [
    [
        '[{"Id":', '"id_0_ConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DeadLetterErrors",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DestinationDeliveryFailures",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Duration",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Errors",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Invocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_IteratorAge",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_PostRuntimeExtensionsDuration",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyInvocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencySpilloverInvocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyUtilization",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Throttles",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_UnreservedConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"}]'
    ],
    [
        '[{"Id":', '"id_0_ConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DeadLetterErrors",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DestinationDeliveryFailures",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Duration",',
        '"Label":', '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Errors",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Invocations",',
        '"Label":', '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_IteratorAge",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_PostRuntimeExtensionsDuration",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyInvocations",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencySpilloverInvocations",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyUtilization",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Throttles",',
        '"Label":', '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_UnreservedConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"}]'
    ]
]

# this is the metric data for three invocations of my_python_test_function
_STRING_TABLE_AWS_LAMBDA = [
    [
        '[{"Id":', '"id_0_ConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DeadLetterErrors",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DestinationDeliveryFailures",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Duration",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '["2021-07-08 10:55:00+00:00"],', '"Values":',
        '[[902.3766666666667, null]],', '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Errors",',
        '"Label":', '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '["2021-07-08 10:55:00+00:00"],', '"Values":', '[[0.0, 600]],',
        '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Invocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '["2021-07-08 10:55:00+00:00"],', '"Values":', '[[3.0, 600]],',
        '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_IteratorAge",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_PostRuntimeExtensionsDuration",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyInvocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencySpilloverInvocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyUtilization",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Throttles",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '["2021-07-08 10:55:00+00:00"],', '"Values":', '[[0.0, 600]],',
        '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_UnreservedConcurrentExecutions",',
        '"Label":', '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"}]'
    ],
    [
        '[{"Id":', '"id_0_ConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DeadLetterErrors",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DestinationDeliveryFailures",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Duration",',
        '"Label":', '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Errors",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Invocations",',
        '"Label":', '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_IteratorAge",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_PostRuntimeExtensionsDuration",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyInvocations",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencySpilloverInvocations",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyUtilization",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Throttles",',
        '"Label":', '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_UnreservedConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-north-1:710145618630:function:myLambdaTestFunction",', '"Timestamps":',
        '[],', '"Values":', '[],', '"StatusCode":', '"Complete"}]'
    ]
]

# this is the artificial metric data for possible misbehaviour of AWS lambda or the agent (duration is zero)
_STRING_TABLE_AWS_LAMBDA_INVALID_DATA = [
    [
        '[{"Id":', '"id_0_ConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DeadLetterErrors",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_DestinationDeliveryFailures",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Duration",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '["2021-07-08 10:55:00+00:00"],', '"Values":', '[[0.0, null]],',
        '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Errors",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '["2021-07-08 10:55:00+00:00"],', '"Values":', '[[0.0, 600]],',
        '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_Invocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '["2021-07-08 10:55:00+00:00"],', '"Values":', '[[0.0, 600]],',
        '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_IteratorAge",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_PostRuntimeExtensionsDuration",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyInvocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencySpilloverInvocations",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrencyUtilization",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_ProvisionedConcurrentExecutions",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"},', '{"Id":',
        '"id_0_Throttles",', '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '["2021-07-08 10:55:00+00:00"],', '"Values":', '[[0.0, 600]],',
        '"StatusCode":', '"Complete"},', '{"Id":', '"id_0_UnreservedConcurrentExecutions",',
        '"Label":', '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":', '[],', '"Values":', '[],', '"StatusCode":', '"Complete"}]'
    ],
]

# this is the artificial metric data for missing metrics. This would be an error of AWS lambda or the agent
_STRING_TABLE_AWS_LAMBDA_MISSING_MANDATORY_METRIC = [
    [
        '[{"Id":',
        '"id_0_ConcurrentExecutions",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_DeadLetterErrors",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_DestinationDeliveryFailures",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        # metric for duration is missing
        '{"Id":',
        '"id_0_Errors",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '["2021-07-08 10:55:00+00:00"],',
        '"Values":',
        '[[0.0, 600]],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_Invocations",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '["2021-07-08 10:55:00+00:00"],',
        '"Values":',
        '[[0.0, 600]],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_IteratorAge",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_PostRuntimeExtensionsDuration",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_ProvisionedConcurrencyInvocations",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_ProvisionedConcurrencySpilloverInvocations",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_ProvisionedConcurrencyUtilization",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_ProvisionedConcurrentExecutions",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_Throttles",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '["2021-07-08 10:55:00+00:00"],',
        '"Values":',
        '[[0.0, 600]],',
        '"StatusCode":',
        '"Complete"},',
        '{"Id":',
        '"id_0_UnreservedConcurrentExecutions",',
        '"Label":',
        '"arn:aws:lambda:eu-central-1:710145618630:function:my_python_test_function",',
        '"Timestamps":',
        '[],',
        '"Values":',
        '[],',
        '"StatusCode":',
        '"Complete"}]'
    ],
]

PARAMETER_DURATION_ABSOLUTE = dict(_DEFAULT_PARAMETERS)
PARAMETER_DURATION_ABSOLUTE["levels_duration_absolute"] = (5.0, 10.0)


@pytest.mark.parametrize(
    "item, params, string_table_aws_lambda_summary, string_table_aws_lambda, results", [
        (
            'eu-central-1 my_python_test_function',
            _DEFAULT_PARAMETERS,
            _STRING_TABLE_AWS_LAMBDA_SUMMARY,
            _STRING_TABLE_AWS_LAMBDA_NOT_USED,
            [
                Result(state=State.OK, summary='Invocations: 0.0000'),
                Metric('aws_lambda_invocations', 0.0),
            ],
        ),
        (
            'eu-central-1 my_python_test_function',
            _DEFAULT_PARAMETERS,
            _STRING_TABLE_AWS_LAMBDA_SUMMARY,
            _STRING_TABLE_AWS_LAMBDA,
            [
                Result(
                    state=State.WARN,
                    summary=
                    'Duration in percent of AWS Lambda "timeout" limit: 90.24% (warn/crit at 90.00%/95.00%)'
                ),
                Metric('aws_lambda_duration_in_percent', 90.23766666666667, levels=(90.0, 95.0)),
                Result(state=State.OK, summary='Errors: 0.0000'),
                Metric('error_rate', 0.0, levels=(0.00028, 0.00028)),
                Result(state=State.OK, summary='Invocations: 0.0050'),
                Metric('aws_lambda_invocations', 0.005),
                Result(state=State.OK, summary='Throttles: 0.0000'),
                Metric('aws_lambda_throttles', 0.0, levels=(0.00028, 0.00028)),
            ],
        ),
        (
            'eu-central-1 my_python_test_function',
            _DEFAULT_PARAMETERS,
            _STRING_TABLE_AWS_LAMBDA_SUMMARY,
            _STRING_TABLE_AWS_LAMBDA_INVALID_DATA,
            [
                Result(state=State.OK,
                       summary='Duration in percent of AWS Lambda "timeout" limit: 0%'),
                Metric('aws_lambda_duration_in_percent', 0.0, levels=(90.0, 95.0)),
                Result(state=State.OK, summary='Errors: 0.0000'),
                Metric('error_rate', 0.0, levels=(0.00028, 0.00028)),
                Result(state=State.OK, summary='Invocations: 0.0000'),
                Metric('aws_lambda_invocations', 0.000),
                Result(state=State.OK, summary='Throttles: 0.0000'),
                Metric('aws_lambda_throttles', 0.0, levels=(0.00028, 0.00028)),
            ],
        ),
        (
            'eu-central-1 my_python_test_function',
            PARAMETER_DURATION_ABSOLUTE,
            _STRING_TABLE_AWS_LAMBDA_SUMMARY,
            _STRING_TABLE_AWS_LAMBDA,
            [
                Result(
                    state=State.WARN,
                    summary=
                    'Duration in percent of AWS Lambda "timeout" limit: 90.24% (warn/crit at 90.00%/95.00%)'
                ),
                Metric('aws_lambda_duration_in_percent', 90.23766666666667, levels=(90.0, 95.0)),
                Result(state=State.OK, summary='Duration with absolute limits: 902 milliseconds'),
                Metric('aws_lambda_duration', 0.9023766666666667, levels=(5.0, 10.0)),
                Result(state=State.OK, summary='Errors: 0.0000'),
                Metric('error_rate', 0.0,
                       levels=(_MORE_THAN_ONE_PER_HOUR, _MORE_THAN_ONE_PER_HOUR)),
                Result(state=State.OK, summary='Invocations: 0.0050'),
                Metric('aws_lambda_invocations', 0.005),
                Result(state=State.OK, summary='Throttles: 0.0000'),
                Metric('aws_lambda_throttles',
                       0.0,
                       levels=(_MORE_THAN_ONE_PER_HOUR, _MORE_THAN_ONE_PER_HOUR)),
            ],
        ),
    ])
def test_end_to_end_parsing_and_check(item, params, string_table_aws_lambda_summary,
                                      string_table_aws_lambda, results):
    assert list(
        check_aws_lambda_performance(
            item,
            params,
            parse_aws_lambda_summary(string_table_aws_lambda_summary),
            parse_aws_lambda(string_table_aws_lambda),
        )) == results


@pytest.mark.parametrize("string_table_aws_lambda, results", [
    (
        _STRING_TABLE_AWS_LAMBDA_MISSING_MANDATORY_METRIC,
        None,
    ),
])
def test_parse_aws_lambda_missing_mandatory_metric(string_table_aws_lambda, results):
    with pytest.raises(TypeError):
        assert list(parse_aws_lambda(string_table_aws_lambda)) == results


SECTION_AWS_LAMBDA = {
    'eu-central-1 my_python_test_function': LambdaCloudwatchMetrics(
        ConcurrentExecutions=0.005,
        DeadLetterErrors=None,
        DestinationDeliveryFailures=None,
        Duration=902.43,
        Errors=0.0,
        Invocations=0.005,
        IteratorAge=None,
        PostRuntimeExtensionsDuration=None,
        ProvisionedConcurrencyInvocations=None,
        ProvisionedConcurrencySpilloverInvocations=None,
        ProvisionedConcurrencyUtilization=None,
        ProvisionedConcurrentExecutions=None,
        Throttles=0.0,
        UnreservedConcurrentExecutions=None)
}

SECTION_AWS_LAMBDA_SUMMARY = {
    'eu-central-1 my_python_test_function': 1.0,
    'eu-north-1 myLambdaTestFunction': 1.0,
}


@pytest.mark.parametrize("section_aws_lambda_summary, section_aws_lambda, results", [
    (
        None,
        None,
        [],
    ),
    (
        SECTION_AWS_LAMBDA_SUMMARY,
        SECTION_AWS_LAMBDA,
        [
            Service(item='eu-central-1 my_python_test_function'),
            Service(item='eu-north-1 myLambdaTestFunction')
        ],
    ),
])
def test_discover_aws_lambda(section_aws_lambda_summary, section_aws_lambda, results):
    assert list(discover_aws_lambda(section_aws_lambda_summary, section_aws_lambda)) == results
