# Stubs for kubernetes.stream.stream (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def stream(func: Any, *args: Any, **kwargs: Any): ...
