# Stubs for kubernetes.stream.ws_client_test (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest
from .ws_client import get_websocket_url

class WSClientTest(unittest.TestCase):
    def test_websocket_client(self) -> None: ...
