RRDTOOL := rrdtool

RRDTOOL_INSTALL := $(BUILD_HELPER_DIR)/$(RRDTOOL)-install

RRDTOOL_INSTALL_DIR := $(INTERMEDIATE_INSTALL_BASE)/$(RRDTOOL)

.PHONY: $(RRDTOOL_BUILD) $(RRDTOOL_INTERMEDIATE_INSTALL) $(RRDTOOL_INSTALL)

# Used by other OMD packages (e.g. mk-livestatus.make)
PACKAGE_RRDTOOL_DESTDIR := $(RRDTOOL_INSTALL_DIR)

$(RRDTOOL_INSTALL): $(INTERMEDIATE_INSTALL_BAZEL)
	$(RSYNC) --exclude='.modulebuildrc' $(RRDTOOL_INSTALL_DIR)/ $(DESTDIR)$(OMD_ROOT)/
