#!groovy

/// file: build-cmk-source_tgz.groovy

// todo:
// - check different editions (agents for community?)
// - compare with source package generated by build-cmk-packages
// - check why providing agent binaries takes longer as expected

// groovylint-disable MethodSize
void main() {
    check_job_parameters([
        ["DISABLE_CACHE", true],
        ["EDITION", true],
        ["FAKE_ARTIFACTS", false],
        ["VERSION", true],
    ]);

    def versioning = load("${checkout_dir}/buildscripts/scripts/utils/versioning.groovy");
    def package_helper = load("${checkout_dir}/buildscripts/scripts/utils/package_helper.groovy");

    def safe_branch_name = versioning.safe_branch_name();
    def branch_version = versioning.get_branch_version(checkout_dir);
    def cmk_version_rc_aware = versioning.get_cmk_version(safe_branch_name, branch_version, version);
    def cmk_version = versioning.strip_rc_number_from_version(cmk_version_rc_aware);

    def disable_cache = params.DISABLE_CACHE;
    def edition = params.EDITION;
    def fake_artifacts = params.FAKE_ARTIFACTS;
    def force_build = params.DISABLE_JENKINS_CACHE == true;
    def version = params.VERSION;

    def stages = [:];

    print(
        """
        |===== CONFIGURATION ===============================
        |branch_version:........... │${branch_version}│
        |checkout_dir:............. │${checkout_dir}│
        |cmk_version:.............. │${cmk_version}│
        |cmk_version_rc_aware:..... │${cmk_version_rc_aware}│
        |disable_cache:............ │${disable_cache}│
        |edition:.................. │${edition}│
        |force_build:.............. │${force_build}│
        |fake_artifacts:........... │${fake_artifacts}│
        |safe_branch_name:......... │${safe_branch_name}│
        |===================================================
        """.stripMargin());

    currentBuild.description += (
        """
        |Edition: ${edition}<br>
        |""".stripMargin());

    inside_container(ulimit_nofile: 2048) {
        smart_stage(name: "Prepare workspace") {
            dir("${checkout_dir}") {
                sh("make buildclean");
                versioning.configure_checkout_folder(edition, cmk_version);
            }
        }
    }

    if (!fake_artifacts) {
        stages += package_helper.provide_agent_binaries(
            version: version,
            cmk_version: cmk_version,
            edition: edition,
            disable_cache: disable_cache,
            bisect_comment: params.CIPARAM_BISECT_COMMENT,
            artifacts_base_dir: "tmp_artifacts",
            need_windows_python_cab: true,
        );
    } else {
        smart_stage(name: 'Fake agent binaries') {
            dir("${checkout_dir}") {
                sh("scripts/fake-artifacts");
            }
        }
    }

    inside_container_minimal(safe_branch_name: safe_branch_name) {
        currentBuild.result = parallel(stages).values().every { it } ? "SUCCESS" : "FAILURE";
    }

    package_helper.cleanup_provided_agent_binaries("tmp_artifacts");

    // groovylint-disable-next-line DuplicateMapLiteral
    def container_safe_branch_name = safe_branch_name.replace(".", "-");
    container("ubuntu-2404-${container_safe_branch_name}-latest") {
        // `make dist` expects a real check-mk-agent.noarch.rpm,
        // check-mk-agent_all.deb, and (non-community editions)
        // cmk-update-agent binary at fixed paths - build them here.
        // TODO: CMK-28961: When `make dist` is ported to Bazel, combine it with the following stage (Create source package)
        smart_stage(name: "Build agent packages", condition: !fake_artifacts) {
            dir("${checkout_dir}") {
                withCredentials([
                    file(credentialsId: "Check_MK_Release_Key", variable: "GPG_KEY_FILE"),
                    usernamePassword(
                        credentialsId: "9d7aca31-0043-4cd0-abeb-26a249d68261",
                        passwordVariable: "GPG_PASSPHRASE",
                        usernameVariable: "GPG_USERNAME",
                    ),
                ]) {
                    withNexusCredentials {
                        def agent_targets = "//agents:check-mk-agent-rpm_signed //agents:check-mk-agent-deb";
                        if (edition != "community") {
                            agent_targets += " //non-free/packages/cmk-update-agent:cmk-update-agent_bin";
                        }
                        sh("""
                            set -e
                            gpg_passphrase_file="\$(mktemp)"
                            docker_config_dir="\$(mktemp -d)"
                            trap 'rm -f "\$gpg_passphrase_file"; rm -rf "\$docker_config_dir"' EXIT
                            (umask 077; printf '%s' "\$GPG_PASSPHRASE" > "\$gpg_passphrase_file")
                            (
                                umask 077
                                printf '{"auths":{"%s":{"username":"%s","password":"%s"}}}' \
                                    '${docker_registry_no_http}' "\$NEXUS_USERNAME" "\$NEXUS_PASSWORD" \
                                    > "\$docker_config_dir/config.json"
                            )
                            bazel build \
                                --cmk_version=${cmk_version} \
                                --cmk_edition=${edition} \
                                --//bazel/rules:signing_key_file="\$GPG_KEY_FILE" \
                                --//bazel/rules:signing_key_passphrase_file="\$gpg_passphrase_file" \
                                --//non-free/packages/cmk-update-agent:docker_config_dir="\$docker_config_dir" \
                                ${agent_targets}
                            cp bazel-bin/agents/signed/check-mk-agent.rpm agents/check-mk-agent.noarch.rpm
                            cp --no-preserve=mode bazel-bin/agents/check-mk-agent__all.deb agents/check-mk-agent_all.deb
                            if [ "${edition}" != "community" ]; then
                                install -m 755 bazel-bin/non-free/packages/cmk-update-agent/cmk-update-agent-built \
                                    non-free/packages/cmk-update-agent/cmk-update-agent
                            fi
                        """);
                    }
                }
            }
        }

        def source_package_name = {
            dir("${checkout_dir}") {
                stage("Create source package") {
                    withNexusCredentials {
                        // TODO CMK-28961: as soon as make dist is ported to bazel - use "use_faked_artifacts" here
                        sh("make dist");
                    }
                }
                cmd_output("ls check-mk-${edition}-${cmk_version}.tar.gz")
                ?:
                error("Found no source package path matching ${checkout_dir}/check-mk-${edition}-${cmk_version}.tar.gz");
            }
        }();

        stage("Test source package") {
            package_helper.test_package(
                package_path: "${checkout_dir}/${source_package_name}",
                name: "source",
                workspace: WORKSPACE,
                source_dir: checkout_dir,
                cmk_version: cmk_version,
                fake_artifacts: fake_artifacts,
            );
        }

        stage("Archive stuff") {
            dir("${checkout_dir}") {
                show_duration("archiveArtifacts") {
                    archiveArtifacts(
                        artifacts: source_package_name,
                        fingerprint: true,
                    );
                }
            }
        }
    }
}

return this;
