#!groovy

/// file: build-cmk-source_tgz.groovy

// todo:
// - check different editions (agents for community?)
// - compare with source package generated by build-cmk-packages
// - check why providing agent binaries takes longer as expected

void main() {
    check_job_parameters([
        ["EDITION", true],
        ["VERSION", true],
        ["DISABLE_CACHE", true],
        ["FAKE_ARTIFACTS", false],
    ]);

    def versioning = load("${checkout_dir}/buildscripts/scripts/utils/versioning.groovy");
    def package_helper = load("${checkout_dir}/buildscripts/scripts/utils/package_helper.groovy");

    def edition = params.EDITION;
    def version = params.VERSION;
    def disable_cache = params.DISABLE_CACHE;
    def force_build = params.DISABLE_JENKINS_CACHE == true;
    def safe_branch_name = versioning.safe_branch_name();
    def branch_version = versioning.get_branch_version(checkout_dir);
    def cmk_version_rc_aware = versioning.get_cmk_version(safe_branch_name, branch_version, version);
    def cmk_version = versioning.strip_rc_number_from_version(cmk_version_rc_aware);

    print(
        """
        |===== CONFIGURATION ===============================
        |checkout_dir:............. │${checkout_dir}│
        |safe_branch_name:......... │${safe_branch_name}│
        |force_build:.............. │${force_build}│
        |branch_version:........... │${branch_version}│
        |cmk_version:.............. │${cmk_version}│
        |edition:.................. │${edition}│
        |cmk_version_rc_aware:..... │${cmk_version_rc_aware}│
        |===================================================
        """.stripMargin());

    currentBuild.description += (
        """
        |Edition: ${edition}<br>
        |""".stripMargin());

    inside_container(ulimit_nofile: 2048) {
        smart_stage(name: "Prepare workspace") {
            dir("${checkout_dir}") {
                sh("make buildclean");
                versioning.configure_checkout_folder(edition, cmk_version);
            }
        }
    }

    def stages = [:];

    if (!params.FAKE_ARTIFACTS) {
        stages += package_helper.provide_agent_binaries(
            version: version,
            cmk_version: cmk_version,
            edition: edition,
            disable_cache: disable_cache,
            bisect_comment: params.CIPARAM_BISECT_COMMENT,
            artifacts_base_dir: "tmp_artifacts",
        );
    } else {
        smart_stage(name: 'Fake agent binaries') {
            dir("${checkout_dir}") {
                sh("scripts/fake-artifacts");
            }
        }
    }

    inside_container_minimal(safe_branch_name: safe_branch_name) {
        currentBuild.result = parallel(stages).values().every { it } ? "SUCCESS" : "FAILURE";
    }

    package_helper.cleanup_provided_agent_binaries("tmp_artifacts");

    // groovylint-disable-next-line DuplicateMapLiteral
    inside_container(ulimit_nofile: 2048) {
        def source_package_name = {
            dir("${checkout_dir}") {
                stage("Create source package") {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'nexus',
                            passwordVariable: 'NEXUS_PASSWORD',
                            usernameVariable: 'NEXUS_USERNAME')
                    ]) {
                        // TODO CMK-28961: as soon as make dist is ported to bazel - use "use_faked_artifacts" here
                        sh("make dist");
                    }
                }
                cmd_output("ls check-mk-${edition}-${cmk_version}.tar.gz")
                ?:
                error("Found no source package path matching ${checkout_dir}/check-mk-${edition}-${cmk_version}.tar.gz");
            }
        }();

        stage("Test source package") {
            package_helper.test_package(
                package_path: "${checkout_dir}/${source_package_name}",
                name: "source",
                workspace: WORKSPACE,
                source_dir: checkout_dir,
                cmk_version: cmk_version,
                fake_artifacts: params.FAKE_ARTIFACTS,
            );
        }

        stage("Archive stuff") {
            dir("${checkout_dir}") {
                show_duration("archiveArtifacts") {
                    archiveArtifacts(
                        artifacts: source_package_name,
                        fingerprint: true,
                    );
                }
            }
        }
    }
}

return this;
