/**
 * Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
 * This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
 * conditions defined in the file COPYING, which is part of this source code package.
 */
import { fetchRestAPI } from '@/lib/cmkFetch.ts'

import type { DashboardConstants } from '@/dashboard-wip/types/dashboard.ts'

const API_ROOT = 'api/unstable'

export const dashboardAPI = {
  // TODO: replace return with autogenerated Dashboard type
  getDashboard: async (dashboardName: string): Promise<Record<string, unknown>> => {
    const url = `${API_ROOT}/objects/dashboard/${dashboardName}`
    const response = await fetchRestAPI(url, 'GET')
    await response.raiseForStatus()
    return await response.json()
  },
  getDashboardConstants: async (): Promise<DashboardConstants> => {
    const url = `${API_ROOT}/objects/constant/dashboard`
    const response = await fetchRestAPI(url, 'GET')
    await response.raiseForStatus()
    const content = await response.json()
    return content.extensions
  }
}
