type = "Component"
display_name = "Plugins: File Stats"
has_support_component = true
members_required = 0
tier = 3
product_managers = ["andrea.vaccaro@checkmk.com"]
description = """
Plugins for per-file/per-directory statistics.
"""
