#!/usr/bin/env python3
# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# mypy: disable-error-code="no-any-return"
# mypy: disable-error-code="possibly-undefined"
# mypy: disable-error-code="redundant-expr"
# mypy: disable-error-code="type-arg"

from cmk.gui.utils.html import HTML
from cmk.gui.valuespec import ValueSpec
from cmk.gui.view_utils import CSSClass

from .annotations import (
    delete_annotation,
    find_annotation,
    get_annotation_date_render_function,
    get_relevant_annotations,
    load_annotations,
    save_annotations,
    update_annotations,
)
from .bi import (
    BIAggregationGroupTitle,
    BIAggregationTitle,
    BITimelineEntry,
    BITreeState,
    compute_bi_timelines,
    create_bi_timeline_entry,
    DEFAULT_MAX_TIME_RANGE,
    get_bi_availability,
    get_bi_availability_rawdata,
    get_bi_leaf_history,
    get_bi_merged_rows_by_id,
    get_bi_split_history_data,
    get_timeline_containers,
    reclassify_bi_rows,
    split_time_range,
    TimelineContainer,
)
from .columns import AvailabilityColumns
from .computation import (
    cell_active,
    check_av_levels,
    compute_availability,
    compute_availability_groups,
    filter_groups_of_entries,
    get_av_groups,
    history_url_of,
    key_av_entry,
    melt_short_intervals,
    merge_timeline,
    object_title,
    pass_availability_filter,
    reclassify_by_annotations,
    reclassify_config_by_annotation,
    reclassify_history_by_annotation,
    reclassify_history_by_annotations,
    reclassify_times_by_annotation,
    ReclassifyConfig,
    spans_by_object,
)
from .layout import (
    get_object_cells,
    layout_availability_table,
    layout_timeline,
    layout_timeline_choords,
    object_column_titles,
    omit_urls,
)
from .options import (
    get_av_computation_options,
    get_av_display_options,
    get_availability_options_from_request,
    get_default_avoptions,
    get_outage_statistic_options,
    prepare_avo_timeformats,
    render_number_function,
    vs_rangespec,
)
from .rawdata import get_availability_rawdata
from .type_defs import (
    AVAnnotationEntry,
    AVAnnotationKey,
    AVAnnotations,
    AVBIObjectSpec,
    AVBIPhaseData,
    AVBIPhases,
    AVBITimelineState,
    AVBITimelineStates,
    AVData,
    AVEntry,
    AVGroupIds,
    AVGroupKey,
    AVGroups,
    AVHostOrServiceObjectSpec,
    AVIconSpec,
    AVLayoutTable,
    AVLayoutTableRow,
    AVLayoutTimeline,
    AVLayoutTimelineRow,
    AVLevels,
    AVMode,
    AVObjectCells,
    AVObjectSpec,
    AVObjectType,
    AVOptions,
    AVOptionValueSpecs,
    AVOutageStatistics,
    AVOutageStatisticsAggregations,
    AVOutageStatisticsStates,
    AVRangeSpec,
    AVRawData,
    AVRawServices,
    AVRowCells,
    AVSpan,
    AVTimeFormats,
    AVTimeformatSpec,
    AVTimeformatSpecLegacy,
    AVTimelineLabelling,
    AVTimelineRow,
    AVTimelineRows,
    AVTimelineSpan,
    AVTimelineStateName,
    AVTimelineStates,
    AVTimelineStatistics,
    AVTimelineStyle,
    AVTimeRange,
    AVTimeStamp,
    HostOrServiceGroupName,
    SiteHost,
    SiteHostSvc,
)

__all__ = [
    "AVAnnotationEntry",
    "AVAnnotationKey",
    "AVAnnotations",
    "AVBIObjectSpec",
    "AVBIPhaseData",
    "AVBIPhases",
    "AVBITimelineState",
    "AVBITimelineStates",
    "AVData",
    "AVEntry",
    "AVGroupIds",
    "AVGroupKey",
    "AVGroups",
    "AVHostOrServiceObjectSpec",
    "AVIconSpec",
    "AVLayoutTable",
    "AVLayoutTableRow",
    "AVLayoutTimeline",
    "AVLayoutTimelineRow",
    "AVLevels",
    "AVMode",
    "AVObjectCells",
    "AVObjectSpec",
    "AVObjectType",
    "AVOptionValueSpecs",
    "AVOptions",
    "AVOutageStatistics",
    "AVOutageStatisticsAggregations",
    "AVOutageStatisticsStates",
    "AVRangeSpec",
    "AVRawData",
    "AVRawServices",
    "AVRowCells",
    "AVSpan",
    "AVTimeFormats",
    "AVTimeRange",
    "AVTimeStamp",
    "AVTimeformatSpec",
    "AVTimeformatSpecLegacy",
    "AVTimelineLabelling",
    "AVTimelineRow",
    "AVTimelineRows",
    "AVTimelineSpan",
    "AVTimelineStateName",
    "AVTimelineStates",
    "AVTimelineStatistics",
    "AVTimelineStyle",
    "AvailabilityColumns",
    "BIAggregationGroupTitle",
    "BIAggregationTitle",
    "BITimelineEntry",
    "BITreeState",
    "CSSClass",
    "DEFAULT_MAX_TIME_RANGE",
    "HTML",
    "HostOrServiceGroupName",
    "ReclassifyConfig",
    "SiteHost",
    "SiteHostSvc",
    "TimelineContainer",
    "ValueSpec",
    "cell_active",
    "check_av_levels",
    "compute_availability",
    "compute_availability_groups",
    "compute_bi_timelines",
    "create_bi_timeline_entry",
    "delete_annotation",
    "filter_groups_of_entries",
    "find_annotation",
    "get_annotation_date_render_function",
    "get_av_computation_options",
    "get_av_display_options",
    "get_av_groups",
    "get_availability_options_from_request",
    "get_availability_rawdata",
    "get_bi_availability",
    "get_bi_availability_rawdata",
    "get_bi_leaf_history",
    "get_bi_merged_rows_by_id",
    "get_bi_split_history_data",
    "get_default_avoptions",
    "get_object_cells",
    "get_outage_statistic_options",
    "get_relevant_annotations",
    "get_timeline_containers",
    "history_url_of",
    "key_av_entry",
    "layout_availability_table",
    "layout_timeline",
    "layout_timeline_choords",
    "load_annotations",
    "melt_short_intervals",
    "merge_timeline",
    "object_column_titles",
    "object_title",
    "omit_urls",
    "pass_availability_filter",
    "prepare_avo_timeformats",
    "reclassify_bi_rows",
    "reclassify_by_annotations",
    "reclassify_config_by_annotation",
    "reclassify_history_by_annotation",
    "reclassify_history_by_annotations",
    "reclassify_times_by_annotation",
    "render_number_function",
    "save_annotations",
    "spans_by_object",
    "split_time_range",
    "update_annotations",
    "vs_rangespec",
]
