type = "Component"
display_name = "Plugins: ARTEC"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["mohamed.saleh@checkmk.com"]
description = """
Plugins for ARTEC IT Solutions email-archiving appliances.
"""
