# Stubs for kubernetes.utils.create_from_yaml (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def create_from_yaml(k8s_client: Any, yaml_file: Any, verbose: bool = ..., **kwargs: Any): ...
