# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 14
# Label requiring a response
responseRequiredLabel: information-needed
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  This ticket was closed because there has been no response to a request for information for more than 14 days.
  To be able to process this issue further, we need more information or another update of this ticket.
  Please let us know as soon as you have more information so that we can process this issue further.
