/**
 * Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
 * This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
 * conditions defined in the file COPYING, which is part of this source code package.
 */
import * as fs from 'fs'
import * as path from 'path'
import * as vscode from 'vscode'

import { notifyInfo } from '../../core/log'

const SOURCE_PATH = 'bazel/tools/prettier.config.cjs'
const TARGET_PATH = '.vscode/.prettier.config.cjs'

export function generatePrettierConfig(wsPath: string): boolean {
  const sourcePath = path.join(wsPath, SOURCE_PATH)
  if (!fs.existsSync(sourcePath)) return false

  const source = fs.readFileSync(sourcePath, 'utf8')

  const converted = source.replace(/require\(['"]([^'"]+)['"]\)/g, "'$1'")

  const header = [
    '// AUTO-GENERATED by CMK Dev Tools for VS Code',
    `// Source: ${SOURCE_PATH}`,
    `// Generated: ${new Date().toISOString()}`,
    '//',
    '// Converts require() plugin loading to string-based loading',
    '// (VSCode Prettier extension does not support require() in config)',
    '//',
    ''
  ].join('\n')

  const content = header + converted

  const targetPath = path.join(wsPath, TARGET_PATH)
  const targetDir = path.dirname(targetPath)
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true })
  }

  const existing = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, 'utf8') : ''
  const normalize = (s: string) => s.replace(/\/\/ Generated:.*\n/, '')
  if (normalize(existing) === normalize(content)) {
    return false
  }

  fs.writeFileSync(targetPath, content, 'utf8')
  return true
}

function needsGeneration(wsPath: string): boolean {
  const targetPath = path.join(wsPath, TARGET_PATH)
  const sourcePath = path.join(wsPath, SOURCE_PATH)

  if (!fs.existsSync(targetPath)) return true
  if (!fs.existsSync(sourcePath)) return false

  const targetStat = fs.statSync(targetPath)
  const sourceStat = fs.statSync(sourcePath)
  return sourceStat.mtimeMs > targetStat.mtimeMs
}

export function registerPrettierConfigWatcher(): vscode.Disposable[] {
  const wsPath = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath
  if (!wsPath) return []

  const disposables: vscode.Disposable[] = []

  if (needsGeneration(wsPath)) {
    const changed = generatePrettierConfig(wsPath)
    if (changed) {
      notifyInfo(
        'CMK: Regenerated .vscode/.prettier.config.cjs from bazel/tools/prettier.config.cjs'
      )
    }
  }

  const watcher = vscode.workspace.createFileSystemWatcher(
    new vscode.RelativePattern(wsPath, SOURCE_PATH)
  )

  watcher.onDidChange(() => {
    const changed = generatePrettierConfig(wsPath)
    if (changed) {
      notifyInfo(
        'CMK: Regenerated .vscode/.prettier.config.cjs from bazel/tools/prettier.config.cjs'
      )
    }
  })

  disposables.push(watcher)

  return disposables
}
