CHECK_HTTP := check-http
CHECK_HTTP_DIR := $(CHECK_HTTP)
CHECK_HTTP_DEPLOYED := check_httpv2

CHECK_HTTP_BUILD := $(BUILD_HELPER_DIR)/$(CHECK_HTTP)-build
CHECK_HTTP_INSTALL := $(BUILD_HELPER_DIR)/$(CHECK_HTTP)-install

.PHONY: $(CHECK_HTTP_BUILD)
$(CHECK_HTTP_BUILD):
	$(BAZEL_BUILD) //packages/$(CHECK_HTTP):$(CHECK_HTTP)

.PHONY: $(CHECK_HTTP_INSTALL)
$(CHECK_HTTP_INSTALL): $(CHECK_HTTP_BUILD)
	install -m 755 $(BAZEL_BIN)/packages/$(CHECK_HTTP_DIR)/$(CHECK_HTTP) $(DESTDIR)$(OMD_ROOT)/lib/nagios/plugins/$(CHECK_HTTP_DEPLOYED)
	patchelf --set-rpath "\$$ORIGIN/../../../lib" $(DESTDIR)$(OMD_ROOT)/lib/nagios/plugins/$(CHECK_HTTP_DEPLOYED)
