####################################################################################################
# ordered mapping of (virtual) package names to their module name prefixes, first match wins
####################################################################################################
package-definitions:
  # packages shipped with Python 3 itself, can be imported everywhere ------------------------------
  stdlib: [
    __future__, abc, aifc, antigravity, argparse, ast, asynchat, asyncio, asyncore, atexit, base64,
    bdb, binascii, binhex, bisect, bz2, cProfile, calendar, cgi, cgitb, chunk, cmd, code, codecs,
    codeop, collections, colorsys, compileall, concurrent, configparser, contextlib, contextvars,
    copy, copyreg, crypt, csv, ctypes, curses, dataclasses, datetime, dbm, decimal, difflib, dis,
    distutils, doctest, email, encodings, ensurepip, enum, errno, fcntl, filecmp, fileinput,
    fnmatch, fractions, ftplib, functools, gc, genericpath, getopt, getpass, gettext, glob,
    graphlib, grp, gzip, hashlib, heapq, hmac, html, http, imaplib, imghdr, imp, importlib, inspect,
    io, ipaddress, itertools, json, keyword, lib2to3, linecache, locale, logging, lzma, mailbox,
    mailcap, marshal, math, mimetypes, modulefinder, multiprocessing, netrc, nntplib, ntpath,
    nturl2path, numbers, opcode, operator, optparse, os, pathlib, pdb, pickle, pickletools, pipes,
    pkg_resources, pkgutil, platform, plistlib, poplib, posix, posixpath, pprint, profile, pstats,
    pty, py_compile, pyclbr, pwd, pydoc, queue, quopri, random, re, reprlib, resource, rlcompleter,
    runpy, sched, select, secrets, selectors, shelve, shlex, shutil, signal, site, sitecustomize,
    smtpd, smtplib, sndhdr, socket, socketserver, sqlite3, sre_compile, sre_constants, sre_parse,
    ssl, stat, statistics, string, stringprep, struct, subprocess, sunau, symtable, sys, sysconfig,
    syslog, tabnanny, tarfile, telnetlib, tempfile, termios, test, textwrap, this, threading, time,
    timeit, token, tokenize, trace, traceback, tracemalloc, tty, turtle, types, typing, unittest,
    urllib, uu, uuid, venv, warnings, wave, weakref, webbrowser, winreg, wsgiref, xdrlib, xml,
    xmlrpc, zipapp, zipfile, zipimport, zlib, zoneinfo,
    _typeshed.wsgi  # HACK, replace this with wsgiref in Python 3.11
  ]
  # third party packages ---------------------------------------------------------------------------
  adal: [adal]
  apispec: [apispec]
  apispec-oneofschema: [apispec_oneofschema]
  astroid: [astroid]
  beautifulsoup4: [bs4]
  black: [black]
  boto3: [boto3]
  botocore: [botocore]
  bson: [bson]
  colorama: [colorama]
  cryptography: [cryptography]
  cx_Oracle: [cx_Oracle]
  deepdiff: [deepdiff]
  dicttoxml: [dicttoxml]
  docker: [docker]
  dockerpty: [dockerpty]
  docstring_parser: [docstring_parser]
  exchangelib: [exchangelib]
  fastapi: [fastapi]
  fakeredis: [fakeredis]
  fido2: [fido2]
  freezegun: [freezegun]
  google-cloud-asset : [
    google.cloud.asset,
    google.cloud.asset_v1,
    google.cloud.asset_v1p1beta1,
    google.cloud.asset_v1p2beta1,
    google.cloud.asset_v1p4beta1,
    google.cloud.asset_v1p5beta1
  ]
  google-api-python-client: [googleapiclient]
  google-auth: [google.auth, google.oauth2]
  google-cloud-monitoring: [google.cloud.monitoring, google.cloud.monitoring_v3]
  ibm_db: [ibm_db, ibm_db_dbi]
  isort: [isort]
  jinja2: [jinja2]
  jira: [jira]
  jsonschema: [jsonschema]
  kubernetes: [kubernetes]
  lxml: [lxml]
  marshmallow: [marshmallow]
  marshmallow-oneofschema: [marshmallow_oneofschema]
  matplotlib: [matplotlib]
  mock: [mock]
  mocket: [mocket]
  mpld3: [mpld3]
  mypy_extensions: [mypy_extensions]
  mysqlclient: [MySQLdb]
  net-snmp: [netsnmp]
  numpy: [numpy]
  oauthlib: [oauthlib]
  openapi-spec-validator: [openapi_spec_validator]
  opsgenie-sdk: [opsgenie_sdk]
  ordereddict: [ordereddict]
  paho: [paho]
  paramiko: [paramiko]
  Pillow: [PIL]
  pipfile: [pipfile]
  playwright: [playwright]
  protobuf: [google.protobuf]
  psutil: [psutil]
  psycopg2-binary: [psycopg2]
  pyasn1: [pyasn1]
  pycryptodomex: [Cryptodome]
  pydantic: [pydantic]
  pydantic_factories: [pydantic_factories]
  pyghmi: [pyghmi]
  pyinotify: [pyinotify]
  pymongo: [pymongo]
  pymssql: [pymssql]
  pylint: [pylint]
  PyMySQL: [pymysql]
  pyopenssl: [OpenSSL]
  pyparsing: [pyparsing]
  PyPDF3: [PyPDF3]
  pysmb: [nmb, smb]
  pysmi: [pysmi]
  pysnmp: [pysnmp]
  pytest: [_pytest, pytest]
  python-active-directory: [activedirectory]
  python-dateutil: [dateutil]
  python-ldap: [ldap]
  python-snap7: [snap7]
  pytz: [pytz]
  pywin32: [win32api, win32evtlog]
  pyyaml: [yaml]
  pytest-mock: [pytest_mock]
  redis: [redis]
  reportlab: [reportlab]
  requests: [requests]
  requests_kerberos: [requests_kerberos]
  requests_oauthlib: [requests_oauthlib]
  responses: [responses]
  roman: [roman]
  rrdtool: [rrdtool]
  sapnwrfc: [sapnwrfc]
  semver: [semver]
  setproctitle: [setproctitle]
  setuptools: [setuptools]
  simplejson: [simplejson]
  six: [six]
  sqlanydb: [sqlanydb]
  starlette: [starlette]
  stdlib2: [ConfigParser, cStringIO, urllib2]  # Python 2 packages/modules not in Python 3
  tinkerforge: [tinkerforge]
  urllib3: [urllib3]
  uvicorn: [uvicorn]
  vcrpy: [vcr]
  webtest: [webtest]
  Werkzeug: [werkzeug]
  # our own packages -------------------------------------------------------------------------------
  checkmk-active_checks: [active_checks]
  checkmk-agent-receiver: [agent-receiver, agent_receiver]
  checkmk-agents-plugins: [
    agents.plugins,
    mk_jolokia  # HACK needed because of sys.path fiddling for mk_jolokia
    ]
  checkmk-agents-special: [agents.special]
  checkmk-agents-wnx-misc: [agents.wnx.patch_windows_agent_version, agents.wnx.scripts.check_crlf]
  checkmk-agents-wnx-tests: [agents.wnx.tests]
  checkmk-bin: [bin]
  checkmk-cma: [cma, cma_net]
  checkmk-cmk-active_checks: [cmk.active_checks]
  checkmk-cmk-base: [cmk.base]
  checkmk-cmk-bi: [cmk.bi]
  checkmk-cmk-ec-export: [cmk.ec.export]
  checkmk-cmk-ec: [cmk.ec]
  checkmk-cmk-fields: [cmk.fields]
  checkmk-cmk-gui: [cmk.gui]
  checkmk-cmk-post_rename_site: [cmk.post_rename_site]
  checkmk-cmk-special_agents: [cmk.special_agents]
  checkmk-cmk-update_config: [cmk.update_config]
  checkmk-cmk-utils: [cmk.utils]
  checkmk-cmk: [cmk]
  checkmk-doc: [
    doc.agent_based_api,  # HACK because of wrong structure
    doc.helpers,
    doc.mkeventd,
    doc.plugin-api.source,
    doc.skeleton_check,
    example_singlesite,  # HACK because the directory name "python" seems to be special
    example_multisite,  # HACK because the directory name "python" seems to be special
    make_nagvis_map  # HACK because the directory name "python" seems to be special
  ]
  checkmk-enterprise-agents: [
    enterprise.agents,
    cmk_update_agent  # HACK needed because of sys.path fiddling in tests
  ]
  checkmk-enterprise-alert_handlers: [enterprise.alert_handlers]
  checkmk-enterprise-bin: [enterprise.bin]
  checkmk-enterprise-cmk: [enterprise.cmk]
  checkmk-enterprise-core: [enterprise.core]
  checkmk-livestatus: [livestatus]
  checkmk-managed-cmk: [managed.cmk]
  checkmk-notifications: [notifications]
  checkmk-omd-packages-appliance: [omd.packages.appliance]
  checkmk-omd-packages-maintenance: [omd.packages.maintenance]
  checkmk-omdlib: [omdlib]
  checkmk-patch-pipfile: [patch_pipfile]
  checkmk-plus-cmk: [plus.cmk]
  checkmk-scripts: [check-absolute-imports, create-changelog, create-ntop-mkp, precompile-werks]
  checkmk-tests: [
    tests,
    testlib.base  # HACK needed because of sys.path fiddling in generate_config.py
    ]
  checkmk-web-app: [web.app]
  checkmk-werk: [werk]
####################################################################################################
# mapping of (virtual) package names to a collection of allowed (virtual) package names for imports
####################################################################################################
allowed-package-relationships:
  checkmk-active_checks: [
    cx_Oracle,
    ibm_db,
    paramiko,
    psycopg2-binary,
    pymssql,
    PyMySQL,
    requests,
    requests_kerberos,
    sqlanydb,
    urllib3,
    checkmk-cmk-active_checks,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-agents-plugins: [
    bson,
    docker,
    mysqlclient,
    ordereddict,
    pyinotify,
    pymongo,
    pywin32,
    requests,
    sapnwrfc,
    simplejson,
    stdlib2,
    tinkerforge
  ]
  checkmk-agent-receiver: [
    cryptography,
    fastapi,
    pydantic,
    requests,
    setuptools,  # HACK only for setup.py
    starlette,
    uvicorn
  ]
  checkmk-agents-special: [
    checkmk-cmk-special_agents
  ]
  checkmk-agents-wnx-misc: []
  checkmk-agents-wnx-tests: [
    pytest,
    pywin32,
    pyyaml
  ]
  checkmk-bin: [
    psutil,
    pycryptodomex,
    pyopenssl,
    semver,
    setproctitle,
    six,
    checkmk-cma,
    checkmk-cmk-base,
    checkmk-cmk-ec,  # TODO: We should export main in cmk.ec.export
    checkmk-cmk-gui,
    checkmk-cmk-post_rename_site,
    checkmk-cmk-update_config,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-cmk-base: [
    marshmallow,
    pydantic,
    python-dateutil,
    requests,
    six,
    checkmk-cmk,
    checkmk-cmk-ec-export,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-cmk-bi: [
    marshmallow,
    marshmallow-oneofschema,
    checkmk-cmk-fields,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-cmk-ec: [
    pyasn1,
    pymongo,
    pysnmp,
    python-dateutil,
    setproctitle,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-cmk-ec-export: [
    checkmk-cmk-ec
  ]
  checkmk-cmk-fields: [
    marshmallow,
    checkmk-cmk-utils
  ]
  checkmk-cmk-gui: [
    apispec,
    apispec-oneofschema,
    black,
    cryptography,
    dicttoxml,
    docstring_parser,
    fido2,
    jinja2,
    marshmallow,
    marshmallow-oneofschema,
    mock,
    mypy_extensions,
    openapi-spec-validator,
    Pillow,
    psutil,
    pycryptodomex,
    pydantic,
    pyopenssl,
    pyparsing,
    pysmi,
    python-active-directory,
    python-dateutil,
    python-ldap,
    pytz,
    redis,
    reportlab,
    requests,
    setproctitle,
    six,
    urllib3,
    Werkzeug,
    checkmk-cmk,  # TODO: For cmk.automations and cmk.snmplib. New packages?
    checkmk-cmk-base,  # TODO: For cmk.base.export, this dependency *must* be removed!
    checkmk-cmk-bi,
    checkmk-cmk-ec-export,
    checkmk-cmk-fields,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-cmk-update_config: [
    checkmk-cmk-base,
    checkmk-cmk-gui,
    checkmk-cmk-utils
  ]
  checkmk-cmk-utils: [
    cryptography,
    deepdiff,
    exchangelib,
    jinja2,
    pycryptodomex,
    pyopenssl,
    python-dateutil,
    pyyaml,
    redis,
    six,
    urllib3,
    checkmk-cmk-ec-export,  # TODO: cmk.utils.packaging causes this cycle!
    checkmk-livestatus
  ]
  checkmk-doc: [
    Pillow,
    checkmk-livestatus
  ]
  checkmk-enterprise-cmk: [
    cryptography,
    jira,
    marshmallow,
    matplotlib,
    mpld3,
    net-snmp,
    numpy,
    Pillow,
    protobuf,
    psutil,
    pydantic,
    pyopenssl,
    PyPDF3,
    pyyaml,
    redis,
    reportlab,
    requests,
    roman,
    rrdtool,
    setproctitle,
    six,
    urllib3,
    Werkzeug,
    checkmk-cmk,
    checkmk-cmk-base,
    checkmk-cmk-fields,
    checkmk-cmk-gui,
    checkmk-cmk-post_rename_site,
    checkmk-cmk-update_config,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-enterprise-agents: []
  checkmk-enterprise-alert_handlers: []
  checkmk-enterprise-bin: [
    checkmk-cmk,
    checkmk-cmk-base,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-enterprise-core: [
    pytest,
    checkmk-cmk-base,
    checkmk-cmk-utils,
    checkmk-tests
  ]
  checkmk-livestatus: []
  checkmk-managed-cmk: [
    Pillow,
    checkmk-cmk-bi,
    checkmk-cmk-ec-export,
    checkmk-cmk-gui,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-omd-packages-appliance: [
    checkmk-cmk-gui,
    checkmk-cmk-utils
  ]
  checkmk-omd-packages-maintenance: [
    checkmk-cmk-utils
  ]
  checkmk-notifications: [
    checkmk-cmk  # TODO: Add package for cmk.notification_plugins?
  ]
  checkmk-omdlib: [
    psutil,
    checkmk-cmk-utils
  ]
  checkmk-patch-pipfile: [
    colorama
  ]
  checkmk-plus-cmk: [
    checkmk-cmk,
    checkmk-cmk-base,
    checkmk-cmk-fields,
    checkmk-cmk-gui,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-cmk: [
    opsgenie-sdk,
    pydantic,
    pyghmi,
    requests,
    six,
    checkmk-cmk-utils
  ]
  checkmk-cmk-post_rename_site: [
    checkmk-cmk-gui,
    checkmk-cmk-utils,
    checkmk-livestatus
  ]
  checkmk-cmk-special_agents: [
    adal,
    boto3,
    botocore,
    google-api-python-client,
    google-auth,
    google-cloud-asset,
    google-cloud-monitoring,
    jira,
    kubernetes,
    lxml,
    oauthlib,
    paho,
    paramiko,
    pydantic,
    pysmb,
    pytest,
    python-dateutil,
    python-snap7,
    pytz,
    requests,
    requests_oauthlib,
    tinkerforge,
    urllib3,
    vcrpy,
    checkmk-agents-plugins,  # HACK needed because of sys.path fiddling for mk_jolokia
    checkmk-cmk-ec-export,
    checkmk-cmk-utils
  ]
  checkmk-scripts: [
    checkmk-cmk-utils
  ]
  checkmk-tests: [
    apispec,
    astroid,
    beautifulsoup4,
    bson,
    cryptography,
    docker,
    dockerpty,
    fakeredis,
    fastapi,
    freezegun,
    google-cloud-asset,
    google-cloud-monitoring,
    isort,
    jsonschema,
    kubernetes,
    lxml,
    marshmallow,
    mock,
    mocket,
    net-snmp,
    openapi-spec-validator,
    ordereddict,
    pipfile,
    playwright,
    protobuf,
    pydantic,
    pydantic_factories,
    pyghmi,
    pylint,
    pymongo,
    pyopenssl,
    pysmb,
    pytest,
    pytest-mock,
    python-dateutil,
    pytz,
    pyyaml,
    requests,
    responses,
    rrdtool,
    semver,
    six,
    starlette,
    urllib3,
    vcrpy,
    webtest,
    Werkzeug,
    checkmk-agent-receiver,
    checkmk-agents-plugins,
    checkmk-cmk,
    checkmk-cmk-active_checks,
    checkmk-cmk-base,
    checkmk-cmk-bi,
    checkmk-cmk-ec,
    checkmk-cmk-ec-export,
    checkmk-cmk-fields,
    checkmk-cmk-gui,
    checkmk-cmk-post_rename_site,
    checkmk-cmk-special_agents,
    checkmk-cmk-update_config,
    checkmk-cmk-utils,
    checkmk-enterprise-agents,
    checkmk-livestatus,
    checkmk-omdlib,
    checkmk-plus-cmk
  ]
  checkmk-web-app: [
    Werkzeug,
    checkmk-cmk-gui
  ]
  checkmk-werk: []
####################################################################################################
# the package relationships should of course be acyclic, but we have exceptions for now... :-/
####################################################################################################
known-package-cycles:
- [checkmk-cmk-ec, checkmk-cmk-ec-export, checkmk-cmk-utils]
