UPSTREAM_MIRROR_URL = "https://artifacts.lan.tribe29.com/repository/upstream-archives/"
RUFF_VERSION = "0.14.11"  # keep in sync with the multitool hub

# TODO: Re-work this with edition_deps + check for duplicate in cmk/BUILD
edition_python_deps = {
    "cloud": select({
        "@//:gpl+nonfree_repo": [
            "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger",
            "//non-free/packages/cmk-metric-backend",
            "//non-free/packages/cmk-mknotifyd",
            "//non-free/packages/cmk-otel-collector",
            "//non-free/packages/cmk-update-agent:cmk-update-agent-py",
        ],
        "@//:gpl_repo": [],
    }),
    "community": [
    ],
    "pro": select({
        "@//:gpl+nonfree_repo": [
            "//non-free/packages/cmk-mknotifyd",
            "//non-free/packages/cmk-update-agent:cmk-update-agent-py",
        ],
        "@//:gpl_repo": [],
    }),
    "ultimate": select({
        "@//:gpl+nonfree_repo": [
            "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger",
            "//non-free/packages/cmk-metric-backend",
            "//non-free/packages/cmk-mknotifyd",
            "//non-free/packages/cmk-otel-collector",
            "//non-free/packages/cmk-update-agent:cmk-update-agent-py",
        ],
        "@//:gpl_repo": [],
    }),
    "ultimatemt": select({
        "@//:gpl+nonfree_repo": [
            "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger",
            "//non-free/packages/cmk-metric-backend",
            "//non-free/packages/cmk-mknotifyd",
            "//non-free/packages/cmk-otel-collector",
            "//non-free/packages/cmk-update-agent:cmk-update-agent-py",
        ],
        "@//:gpl_repo": [],
    }),
}

edition_deps = {
    "cloud": select({
        "@//:gpl+nonfree_repo": [
            "//cmk:cmk_tar_cloud",
            "//cmk:cmk_tar_ultimate",
            "//cmk:cmk_tar_pro",
            "//cmk:cmk_tar_community",
            "//non-free/packages/cmc-protocols:pkg_tar",
            "//non-free/packages/cmk-core-helpers:pkg_tar",
            "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger-pkg_tar",
            "//non-free/packages/cmk-metric-backend:pkg_tar",
            "//non-free/packages/cmk-mknotifyd:pkg_tar",
            "//non-free/packages/cmk-otel-collector:pkg_tar",
            "//non-free/packages/cmk-update-agent:pkg_tar",
            "//omd/non-free/packages/alert-handling:pkg_tar",
            "//omd/non-free/packages/cmc:pkg_tar",
            "//omd/non-free/packages/cmk-dcd:pkg_tar",
            "//omd/non-free/packages/cmk-liveproxyd:pkg_tar",
            "//omd/non-free/packages/legal-docs:cloud_pkg_tar",
            "//omd/non-free/packages/licensing:pkg_tar",
            "//omd/non-free/packages/reporting:pkg_tar",
            "//omd/non-free/packages/robotmk:pkg_tar",
            "//omd/non-free/packages/saml2:pkg_tar",
            "//omd/non-free/relay:relay_install_pkg",
        ],
        "@//:gpl_repo": [],
    }),
    # NOTES:
    # * jaeger should be added to all editions EXCEPT cloud - cloud has its own tracing collector
    # * nagvis should be added to all editions EXCEPT cloud - see CMK-14926
    "community": [
        "//cmk:cmk_tar_community",
        "//omd/packages/jaeger:pkg_tar",
        "//omd/packages/nagvis:pkg_tar",
    ],
    "pro": select({
        "@//:gpl+nonfree_repo": [
            "//cmk:cmk_tar_pro",
            "//cmk:cmk_tar_community",
            "//non-free/packages/cmc-protocols:pkg_tar",
            "//non-free/packages/cmk-core-helpers:pkg_tar",
            "//non-free/packages/cmk-mknotifyd:pkg_tar",
            "//non-free/packages/cmk-update-agent:pkg_tar",
            "//omd/non-free/packages/alert-handling:pkg_tar",
            "//omd/non-free/packages/cmc:pkg_tar",
            "//omd/non-free/packages/cmk-dcd:pkg_tar",
            "//omd/non-free/packages/cmk-liveproxyd:pkg_tar",
            "//omd/non-free/packages/legal-docs:enterprise_pkg_tar",
            "//omd/non-free/packages/licensing:pkg_tar",
            "//omd/non-free/packages/reporting:pkg_tar",
            "//omd/non-free/packages/robotmk:pkg_tar",
            "//omd/non-free/packages/saml2:pkg_tar",
            "//omd/packages/jaeger:pkg_tar",
            "//omd/packages/nagvis:pkg_tar",
        ],
        "@//:gpl_repo": [],
    }),
    "ultimate": select({
        "@//:gpl+nonfree_repo": [
            "//cmk:cmk_tar_ultimate",
            "//cmk:cmk_tar_pro",
            "//cmk:cmk_tar_community",
            "//non-free/packages/cmc-protocols:pkg_tar",
            "//non-free/packages/cmk-core-helpers:pkg_tar",
            "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger-pkg_tar",
            "//non-free/packages/cmk-metric-backend:pkg_tar",
            "//non-free/packages/cmk-mknotifyd:pkg_tar",
            "//non-free/packages/cmk-otel-collector:pkg_tar",
            "//non-free/packages/cmk-update-agent:pkg_tar",
            "//omd/non-free/packages/alert-handling:pkg_tar",
            "//omd/non-free/packages/cmc:pkg_tar",
            "//omd/non-free/packages/cmk-dcd:pkg_tar",
            "//omd/non-free/packages/cmk-liveproxyd:pkg_tar",
            "//omd/non-free/packages/legal-docs:cloud_pkg_tar",
            "//omd/non-free/packages/licensing:pkg_tar",
            "//omd/non-free/packages/metric-backend:pkg_tar",
            "//omd/non-free/packages/reporting:pkg_tar",
            "//omd/non-free/packages/robotmk:pkg_tar",
            "//omd/non-free/packages/saml2:pkg_tar",
            "//omd/non-free/relay:relay_install_pkg",
            "//omd/packages/jaeger:pkg_tar",
            "//omd/packages/nagvis:pkg_tar",
            "//non-free/packages/otel-collector",
        ],
        "@//:gpl_repo": [],
    }),
    "ultimatemt": select({
        "@//:gpl+nonfree_repo": [
            "//cmk:cmk_tar_ultimatemt",
            "//cmk:cmk_tar_ultimate",
            "//cmk:cmk_tar_pro",
            "//cmk:cmk_tar_community",
            "//non-free/packages/cmc-protocols:pkg_tar",
            "//non-free/packages/cmk-core-helpers:pkg_tar",
            "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger-pkg_tar",
            "//non-free/packages/cmk-metric-backend:pkg_tar",
            "//non-free/packages/cmk-mknotifyd:pkg_tar",
            "//non-free/packages/cmk-otel-collector:pkg_tar",
            "//non-free/packages/cmk-relay-engine:pkg_tar",
            "//non-free/packages/cmk-update-agent:pkg_tar",
            "//omd/non-free/packages/alert-handling:pkg_tar",
            "//omd/non-free/packages/cmc:pkg_tar",
            "//omd/non-free/packages/cmk-dcd:pkg_tar",
            "//omd/non-free/packages/cmk-liveproxyd:pkg_tar",
            "//omd/non-free/packages/legal-docs:cloud_pkg_tar",
            "//omd/non-free/packages/licensing:pkg_tar",
            "//omd/non-free/packages/metric-backend:pkg_tar",
            "//omd/non-free/packages/reporting:pkg_tar",
            "//omd/non-free/packages/robotmk:pkg_tar",
            "//omd/non-free/packages/saml2:pkg_tar",
            "//omd/non-free/relay:relay_install_pkg",
            "//omd/packages/jaeger:pkg_tar",
            "//omd/packages/nagvis:pkg_tar",
            "//non-free/packages/otel-collector",
        ],
        "@//:gpl_repo": [],
    }),
}

edition_skel_permissions = {
    "cloud": select({
        "@//:gpl+nonfree_repo": [
            "//non-free/packages/cmk-mknotifyd:skel.permissions",
            "//omd/non-free/packages/cmc:skel.permissions",
            "//omd/non-free/packages/cmk-dcd:skel.permissions",
            "//omd/non-free/packages/cmk-liveproxyd:skel.permissions",
            "//omd/non-free/packages/licensing:skel.permissions",
            "//omd/non-free/packages/metric-backend:skel.permissions",
            "//omd/non-free/packages/reporting:skel.permissions",
            "//omd/non-free/packages/saml2:skel.permissions",
            "//omd/packages/apache-omd:skel.permissions",
            "//omd/packages/check_mk:skel.permissions",
            "//omd/packages/maintenance:skel.permissions",
            "//omd/packages/nagios:skel.permissions",
            "//omd/packages/omd:skel.permissions",
            "//omd/packages/pnp4nagios:skel.permissions",
            "//omd/packages/rabbitmq:skel.permissions",
            "//omd/packages/redis:skel.permissions",
            "//omd/packages/rrdtool:skel.permissions",
            "//omd/packages/stunnel:skel.permissions",
            "//omd/packages/openssl:skel.permissions",
            "//omd/packages/perl-modules:skel.permissions",
        ],
        "@//:gpl_repo": [],
    }),
    "community": [
        "//omd/packages/apache-omd:skel.permissions",
        "//omd/packages/check_mk:skel.permissions",
        "//omd/packages/jaeger:skel.permissions",
        "//omd/packages/maintenance:skel.permissions",
        "//omd/packages/nagios:skel.permissions",
        "//omd/packages/nagvis:skel.permissions",
        "//omd/packages/omd:skel.permissions",
        "//omd/packages/pnp4nagios:skel.permissions",
        "//omd/packages/rabbitmq:skel.permissions",
        "//omd/packages/redis:skel.permissions",
        "//omd/packages/rrdtool:skel.permissions",
        "//omd/packages/stunnel:skel.permissions",
        "//omd/packages/openssl:skel.permissions",
        "//omd/packages/perl-modules:skel.permissions",
    ],
    "pro": select({
        "@//:gpl+nonfree_repo": [
            "//omd/packages/apache-omd:skel.permissions",
            "//non-free/packages/cmk-mknotifyd:skel.permissions",
            "//omd/non-free/packages/cmc:skel.permissions",
            "//omd/non-free/packages/cmk-dcd:skel.permissions",
            "//omd/non-free/packages/cmk-liveproxyd:skel.permissions",
            "//omd/non-free/packages/saml2:skel.permissions",
            "//omd/packages/check_mk:skel.permissions",
            "//omd/packages/jaeger:skel.permissions",
            "//omd/packages/maintenance:skel.permissions",
            "//omd/packages/nagios:skel.permissions",
            "//omd/packages/nagvis:skel.permissions",
            "//omd/packages/omd:skel.permissions",
            "//omd/packages/pnp4nagios:skel.permissions",
            "//omd/packages/rabbitmq:skel.permissions",
            "//omd/packages/redis:skel.permissions",
            "//omd/packages/rrdtool:skel.permissions",
            "//omd/packages/stunnel:skel.permissions",
            "//omd/packages/openssl:skel.permissions",
            "//omd/packages/perl-modules:skel.permissions",
        ],
        "@//:gpl_repo": [],
    }),
    "ultimate": select({
        "@//:gpl+nonfree_repo": [
            "//omd/packages/apache-omd:skel.permissions",
            "//non-free/packages/cmk-mknotifyd:skel.permissions",
            "//non-free/packages/otel-collector:skel.permissions",
            "//omd/non-free/packages/cmc:skel.permissions",
            "//omd/non-free/packages/cmk-dcd:skel.permissions",
            "//omd/non-free/packages/cmk-liveproxyd:skel.permissions",
            "//omd/non-free/packages/licensing:skel.permissions",
            "//omd/non-free/packages/metric-backend:skel.permissions",
            "//omd/non-free/packages/reporting:skel.permissions",
            "//omd/non-free/packages/saml2:skel.permissions",
            "//omd/packages/check_mk:skel.permissions",
            "//omd/packages/jaeger:skel.permissions",
            "//omd/packages/maintenance:skel.permissions",
            "//omd/packages/nagios:skel.permissions",
            "//omd/packages/nagvis:skel.permissions",
            "//omd/packages/omd:skel.permissions",
            "//omd/packages/pnp4nagios:skel.permissions",
            "//omd/packages/rabbitmq:skel.permissions",
            "//omd/packages/redis:skel.permissions",
            "//omd/packages/rrdtool:skel.permissions",
            "//omd/packages/stunnel:skel.permissions",
            "//omd/packages/openssl:skel.permissions",
            "//omd/packages/perl-modules:skel.permissions",
        ],
        "@//:gpl_repo": [],
    }),
    "ultimatemt": select({
        "@//:gpl+nonfree_repo": [
            "//omd/packages/apache-omd:skel.permissions",
            "//non-free/packages/cmk-mknotifyd:skel.permissions",
            "//non-free/packages/otel-collector:skel.permissions",
            "//omd/non-free/packages/cmc:skel.permissions",
            "//omd/non-free/packages/cmk-dcd:skel.permissions",
            "//omd/non-free/packages/cmk-liveproxyd:skel.permissions",
            "//omd/non-free/packages/licensing:skel.permissions",
            "//omd/non-free/packages/metric-backend:skel.permissions",
            "//omd/non-free/packages/reporting:skel.permissions",
            "//omd/non-free/packages/saml2:skel.permissions",
            "//omd/packages/check_mk:skel.permissions",
            "//omd/packages/jaeger:skel.permissions",
            "//omd/packages/maintenance:skel.permissions",
            "//omd/packages/nagios:skel.permissions",
            "//omd/packages/nagvis:skel.permissions",
            "//omd/packages/omd:skel.permissions",
            "//omd/packages/pnp4nagios:skel.permissions",
            "//omd/packages/rabbitmq:skel.permissions",
            "//omd/packages/redis:skel.permissions",
            "//omd/packages/rrdtool:skel.permissions",
            "//omd/packages/stunnel:skel.permissions",
            "//omd/packages/openssl:skel.permissions",
            "//omd/packages/perl-modules:skel.permissions",
        ],
        "@//:gpl_repo": [],
    }),
}
