UPSTREAM_MIRROR_URL = "https://artifacts.lan.tribe29.com/repository/upstream-archives/"
RUFF_VERSION = "0.14.11"  # keep in sync with the multitool hub

# TODO: Re-work this with edition_deps + check for duplicate in cmk/BUILD
edition_python_deps = select({
    "@cmk//edition:cloud": [
        "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger",
        "//non-free/packages/cmk-metric-backend",
        "//non-free/packages/cmk-mknotifyd",
        "//non-free/packages/cmk-otel-collector",
        "//non-free/packages/cmk-update-agent:cmk-update-agent-py",
    ],
    "@cmk//edition:community": [],
    "@cmk//edition:pro": [
        "//non-free/packages/cmk-mknotifyd",
        "//non-free/packages/cmk-update-agent:cmk-update-agent-py",
    ],
    "@cmk//edition:ultimate": [
        "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger",
        "//non-free/packages/cmk-metric-backend",
        "//non-free/packages/cmk-mknotifyd",
        "//non-free/packages/cmk-otel-collector",
        "//non-free/packages/cmk-update-agent:cmk-update-agent-py",
    ],
    "@cmk//edition:ultimatemt": [
        "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger",
        "//non-free/packages/cmk-metric-backend",
        "//non-free/packages/cmk-mknotifyd",
        "//non-free/packages/cmk-otel-collector",
        "//non-free/packages/cmk-update-agent:cmk-update-agent-py",
    ],
})

# NOTES:
# * jaeger should be added to all editions EXCEPT cloud - cloud has its own tracing collector
# * nagvis should be added to all editions EXCEPT cloud - see CMK-14926
edition_deps = select({
    "@cmk//edition:cloud": [
        "//cmk:cmk_tar",
        "//non-free/packages/cmc-protocols:pkg_tar",
        "//non-free/packages/cmk-core-helpers:pkg_tar",
        "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger-pkg_tar",
        "//non-free/packages/cmk-metric-backend:pkg_tar",
        "//non-free/packages/cmk-mknotifyd:pkg_tar",
        "//non-free/packages/cmk-otel-collector:pkg_tar",
        "//non-free/packages/cmk-update-agent:pkg_tar",
        "//omd/non-free/packages/alert-handling:pkg_tar",
        "//omd/non-free/packages/cmc:pkg_tar",
        "//omd/non-free/packages/cmk-dcd:pkg_tar",
        "//omd/non-free/packages/cmk-liveproxyd:pkg_tar",
        "//omd/non-free/packages/legal-docs:cloud_pkg_tar",
        "//omd/non-free/packages/licensing:pkg_tar",
        "//omd/non-free/packages/reporting:pkg_tar",
        "//omd/non-free/packages/robotmk:pkg_tar",
        "//omd/non-free/packages/saml2:pkg_tar",
        "//omd/non-free/relay:relay_install_pkg",
    ],
    "@cmk//edition:community": [
        "//cmk:cmk_tar",
        "//omd/packages/jaeger:pkg_tar",
        "//omd/packages/nagvis:pkg_tar",
    ],
    "@cmk//edition:pro": [
        "//cmk:cmk_tar",
        "//non-free/packages/cmc-protocols:pkg_tar",
        "//non-free/packages/cmk-core-helpers:pkg_tar",
        "//non-free/packages/cmk-mknotifyd:pkg_tar",
        "//non-free/packages/cmk-update-agent:pkg_tar",
        "//omd/non-free/packages/alert-handling:pkg_tar",
        "//omd/non-free/packages/cmc:pkg_tar",
        "//omd/non-free/packages/cmk-dcd:pkg_tar",
        "//omd/non-free/packages/cmk-liveproxyd:pkg_tar",
        "//omd/non-free/packages/legal-docs:enterprise_pkg_tar",
        "//omd/non-free/packages/licensing:pkg_tar",
        "//omd/non-free/packages/reporting:pkg_tar",
        "//omd/non-free/packages/robotmk:pkg_tar",
        "//omd/non-free/packages/saml2:pkg_tar",
        "//omd/packages/jaeger:pkg_tar",
        "//omd/packages/nagvis:pkg_tar",
    ],
    "@cmk//edition:ultimate": [
        "//cmk:cmk_tar",
        "//non-free/packages/cmc-protocols:pkg_tar",
        "//non-free/packages/cmk-core-helpers:pkg_tar",
        "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger-pkg_tar",
        "//non-free/packages/cmk-metric-backend:pkg_tar",
        "//non-free/packages/cmk-mknotifyd:pkg_tar",
        "//non-free/packages/cmk-otel-collector:pkg_tar",
        "//non-free/packages/cmk-update-agent:pkg_tar",
        "//omd/non-free/packages/alert-handling:pkg_tar",
        "//omd/non-free/packages/cmc:pkg_tar",
        "//omd/non-free/packages/cmk-dcd:pkg_tar",
        "//omd/non-free/packages/cmk-liveproxyd:pkg_tar",
        "//omd/non-free/packages/legal-docs:cloud_pkg_tar",
        "//omd/non-free/packages/licensing:pkg_tar",
        "//omd/non-free/packages/metric-backend:pkg_tar",
        "//omd/non-free/packages/reporting:pkg_tar",
        "//omd/non-free/packages/robotmk:pkg_tar",
        "//omd/non-free/packages/saml2:pkg_tar",
        "//omd/non-free/relay:relay_install_pkg",
        "//omd/packages/jaeger:pkg_tar",
        "//omd/packages/nagvis:pkg_tar",
        "//non-free/packages/otel-collector",
    ],
    "@cmk//edition:ultimatemt": [
        "//cmk:cmk_tar",
        "//non-free/packages/cmc-protocols:pkg_tar",
        "//non-free/packages/cmk-core-helpers:pkg_tar",
        "//non-free/packages/cmk-core-helpers:relay-fetcher-trigger-pkg_tar",
        "//non-free/packages/cmk-metric-backend:pkg_tar",
        "//non-free/packages/cmk-mknotifyd:pkg_tar",
        "//non-free/packages/cmk-otel-collector:pkg_tar",
        "//non-free/packages/cmk-relay-engine:pkg_tar",
        "//non-free/packages/cmk-update-agent:pkg_tar",
        "//omd/non-free/packages/alert-handling:pkg_tar",
        "//omd/non-free/packages/cmc:pkg_tar",
        "//omd/non-free/packages/cmk-dcd:pkg_tar",
        "//omd/non-free/packages/cmk-liveproxyd:pkg_tar",
        "//omd/non-free/packages/legal-docs:cloud_pkg_tar",
        "//omd/non-free/packages/licensing:pkg_tar",
        "//omd/non-free/packages/metric-backend:pkg_tar",
        "//omd/non-free/packages/reporting:pkg_tar",
        "//omd/non-free/packages/robotmk:pkg_tar",
        "//omd/non-free/packages/saml2:pkg_tar",
        "//omd/non-free/relay:relay_install_pkg",
        "//omd/packages/jaeger:pkg_tar",
        "//omd/packages/nagvis:pkg_tar",
        "//non-free/packages/otel-collector",
    ],
})

edition_skel_permissions = select({
    "@cmk//edition:cloud": [
        "//non-free/packages/cmk-mknotifyd:skel.permissions",
        "//omd/non-free/packages/cmc:skel.permissions",
        "//omd/non-free/packages/cmk-dcd:skel.permissions",
        "//omd/non-free/packages/cmk-liveproxyd:skel.permissions",
        "//omd/non-free/packages/licensing:skel.permissions",
        "//omd/non-free/packages/metric-backend:skel.permissions",
        "//omd/non-free/packages/reporting:skel.permissions",
        "//omd/non-free/packages/saml2:skel.permissions",
        "//omd/packages/apache-omd:skel.permissions",
        "//omd/packages/check_mk:skel.permissions",
        "//omd/packages/maintenance:skel.permissions",
        "//omd/packages/nagios:skel.permissions",
        "//omd/packages/omd:skel.permissions",
        "//omd/packages/pnp4nagios:skel.permissions",
        "//omd/packages/rabbitmq:skel.permissions",
        "//omd/packages/redis:skel.permissions",
        "//omd/packages/rrdtool:skel.permissions",
        "//omd/packages/stunnel:skel.permissions",
        "//omd/packages/openssl:skel.permissions",
        "//omd/packages/perl-modules:skel.permissions",
    ],
    "@cmk//edition:community": [
        "//omd/packages/apache-omd:skel.permissions",
        "//omd/packages/check_mk:skel.permissions",
        "//omd/packages/jaeger:skel.permissions",
        "//omd/packages/maintenance:skel.permissions",
        "//omd/packages/nagios:skel.permissions",
        "//omd/packages/nagvis:skel.permissions",
        "//omd/packages/omd:skel.permissions",
        "//omd/packages/pnp4nagios:skel.permissions",
        "//omd/packages/rabbitmq:skel.permissions",
        "//omd/packages/redis:skel.permissions",
        "//omd/packages/rrdtool:skel.permissions",
        "//omd/packages/stunnel:skel.permissions",
        "//omd/packages/openssl:skel.permissions",
        "//omd/packages/perl-modules:skel.permissions",
    ],
    "@cmk//edition:pro": [
        "//omd/packages/apache-omd:skel.permissions",
        "//non-free/packages/cmk-mknotifyd:skel.permissions",
        "//omd/non-free/packages/cmc:skel.permissions",
        "//omd/non-free/packages/cmk-dcd:skel.permissions",
        "//omd/non-free/packages/cmk-liveproxyd:skel.permissions",
        "//omd/non-free/packages/saml2:skel.permissions",
        "//omd/packages/check_mk:skel.permissions",
        "//omd/packages/jaeger:skel.permissions",
        "//omd/packages/maintenance:skel.permissions",
        "//omd/packages/nagios:skel.permissions",
        "//omd/packages/nagvis:skel.permissions",
        "//omd/packages/omd:skel.permissions",
        "//omd/packages/pnp4nagios:skel.permissions",
        "//omd/packages/rabbitmq:skel.permissions",
        "//omd/packages/redis:skel.permissions",
        "//omd/packages/rrdtool:skel.permissions",
        "//omd/packages/stunnel:skel.permissions",
        "//omd/packages/openssl:skel.permissions",
        "//omd/packages/perl-modules:skel.permissions",
    ],
    "@cmk//edition:ultimate": [
        "//omd/packages/apache-omd:skel.permissions",
        "//non-free/packages/cmk-mknotifyd:skel.permissions",
        "//non-free/packages/otel-collector:skel.permissions",
        "//omd/non-free/packages/cmc:skel.permissions",
        "//omd/non-free/packages/cmk-dcd:skel.permissions",
        "//omd/non-free/packages/cmk-liveproxyd:skel.permissions",
        "//omd/non-free/packages/licensing:skel.permissions",
        "//omd/non-free/packages/metric-backend:skel.permissions",
        "//omd/non-free/packages/reporting:skel.permissions",
        "//omd/non-free/packages/saml2:skel.permissions",
        "//omd/packages/check_mk:skel.permissions",
        "//omd/packages/jaeger:skel.permissions",
        "//omd/packages/maintenance:skel.permissions",
        "//omd/packages/nagios:skel.permissions",
        "//omd/packages/nagvis:skel.permissions",
        "//omd/packages/omd:skel.permissions",
        "//omd/packages/pnp4nagios:skel.permissions",
        "//omd/packages/rabbitmq:skel.permissions",
        "//omd/packages/redis:skel.permissions",
        "//omd/packages/rrdtool:skel.permissions",
        "//omd/packages/stunnel:skel.permissions",
        "//omd/packages/openssl:skel.permissions",
        "//omd/packages/perl-modules:skel.permissions",
    ],
    "@cmk//edition:ultimatemt": [
        "//omd/packages/apache-omd:skel.permissions",
        "//non-free/packages/cmk-mknotifyd:skel.permissions",
        "//non-free/packages/otel-collector:skel.permissions",
        "//omd/non-free/packages/cmc:skel.permissions",
        "//omd/non-free/packages/cmk-dcd:skel.permissions",
        "//omd/non-free/packages/cmk-liveproxyd:skel.permissions",
        "//omd/non-free/packages/licensing:skel.permissions",
        "//omd/non-free/packages/metric-backend:skel.permissions",
        "//omd/non-free/packages/reporting:skel.permissions",
        "//omd/non-free/packages/saml2:skel.permissions",
        "//omd/packages/check_mk:skel.permissions",
        "//omd/packages/jaeger:skel.permissions",
        "//omd/packages/maintenance:skel.permissions",
        "//omd/packages/nagios:skel.permissions",
        "//omd/packages/nagvis:skel.permissions",
        "//omd/packages/omd:skel.permissions",
        "//omd/packages/pnp4nagios:skel.permissions",
        "//omd/packages/rabbitmq:skel.permissions",
        "//omd/packages/redis:skel.permissions",
        "//omd/packages/rrdtool:skel.permissions",
        "//omd/packages/stunnel:skel.permissions",
        "//omd/packages/openssl:skel.permissions",
        "//omd/packages/perl-modules:skel.permissions",
    ],
})
