/**
 * Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
 * This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
 * conditions defined in the file COPYING, which is part of this source code package.
 */

/**
 * Extra search keywords per icon, so icons can be found by what they look like
 * or mean rather than only by their exact name (e.g. searching "checkmark"
 * finds the "accept" icon). Keys are icon names; values are lowercase synonyms.
 * The grid already substring-matches the icon name itself, so these are purely
 * additive concept/appearance terms.
 */
export const iconSearchLabels: Record<string, string[]> = {
  '2fa': ['two factor', 'authentication', 'mfa', 'security', 'otp'],
  '2fa-backup-codes': ['two factor', 'recovery', 'mfa', 'security'],
  abort: ['x', 'close', 'stop', 'cross', 'red', 'no', 'cancel'],
  'about-checkmk': ['info', 'version', 'details'],
  accept: ['checkmark', 'check', 'tick', 'confirm', 'yes', 'approve', 'green'],
  'accept-all': ['checkmark', 'confirm all', 'approve', 'yes', 'green'],
  ack: ['acknowledge', 'confirm', 'checkmark', 'yes'],
  'acknowledge-test': ['confirm', 'checkmark', 'trial'],
  action: ['run', 'execute', 'lightning', 'command'],
  activate: ['enable', 'turn on', 'apply', 'deploy'],
  add: ['plus', 'new', 'create', 'insert'],
  'add-dashlet': ['plus', 'new widget', 'dashboard element'],
  'add-rule': ['plus', 'new rule', 'create policy'],
  'agent-output': ['data', 'monitoring data', 'raw'],
  'agent-registration': ['register collector', 'enroll agent', 'connect client'],
  agents: ['collectors', 'clients', 'endpoints'],
  aggr: ['aggregate', 'bi', 'business intelligence', 'rollup'],
  'aggr-single': ['aggregate', 'bi', 'single tree'],
  'aggr-single-problem': ['aggregate', 'bi', 'issue', 'tree problem'],
  aggrcomp: ['aggregate', 'bi', 'component'],
  'aix-tgz': ['ibm', 'unix', 'tarball', 'package', 'archive'],
  alert: ['notification', 'bell', 'warning'],
  'alert-ack': ['acknowledge notification', 'bell', 'confirm'],
  'alert-ackstop': ['stop acknowledge', 'bell'],
  'alert-alert-handler-failed': ['handler error', 'notification failed'],
  'alert-alert-handler-started': ['handler running', 'notification begin'],
  'alert-alert-handler-stopped': ['handler halted', 'notification end'],
  'alert-cmk-notify': ['checkmk notification', 'bell'],
  'alert-command': ['notification action', 'execute'],
  'alert-crit': ['critical alert', 'red', 'severe', 'danger'],
  'alert-down': ['host down', 'offline notification', 'red'],
  'alert-downtime': ['scheduled', 'maintenance notification', 'pause'],
  'alert-downtimestop': ['end maintenance', 'resume', 'notification'],
  'alert-flapping': ['unstable', 'fluctuating', 'notification'],
  'alert-handlers': ['notification handlers', 'actions'],
  'alert-notify': ['bell', 'notification', 'send'],
  'alert-notify-progress': ['notification running', 'in progress', 'bell'],
  'alert-notify-result': ['notification outcome', 'bell'],
  'alert-ok': ['recovery', 'green', 'checkmark', 'notification'],
  'alert-overview': ['notification summary', 'list'],
  'alert-reload': ['refresh notification', 'sync', 'circular arrow'],
  'alert-restart': ['reboot notification', 'circular arrow'],
  'alert-start': ['begin notification', 'play'],
  'alert-stop': ['halt notification', 'square'],
  'alert-timeline': ['history', 'notification timeline', 'events'],
  'alert-unknown': ['question', 'notification', 'grey'],
  'alert-unreach': ['unreachable', 'no connection', 'notification'],
  'alert-up': ['host up', 'online notification', 'green'],
  'alert-warn': ['warning notification', 'triangle', 'yellow', 'caution'],
  alerts: ['notifications', 'bells', 'warnings'],
  'all-states': ['statuses', 'conditions'],
  analysis: ['examine', 'inspect', 'chart'],
  analyze: ['examine', 'inspect', 'investigate'],
  'analyze-config': ['examine settings', 'inspect configuration'],
  annotation: ['note', 'comment', 'label', 'marker'],
  api: ['interface', 'integration', 'rest', 'programming'],
  'app-monitoring-topic': ['application', 'software'],
  apply: ['confirm', 'save', 'checkmark', 'activate'],
  'ar-simulate': ['augmented reality', 'simulation', 'test'],
  'archive-event': ['store event', 'box', 'save'],
  assign: ['allocate', 'attach', 'designate'],
  'assume-0': ['override state', 'force ok', 'green'],
  'assume-1': ['override state', 'force warn', 'yellow'],
  'assume-2': ['override state', 'force critical', 'red'],
  'assume-3': ['override state', 'force unknown', 'grey'],
  'assume-bg': ['override background', 'force'],
  'assume-none': ['no override', 'clear assumption'],
  auditlog: ['history', 'log', 'trail', 'record'],
  autherr: ['authentication error', 'login failed', 'red'],
  authok: ['authentication success', 'login ok', 'green', 'checkmark'],
  'av-computation': ['availability calculation', 'uptime'],
  availability: ['uptime', 'sla', 'percentage'],
  aws: ['amazon', 'cloud', 'web services'],
  'aws-logo': ['amazon', 'cloud', 'web services'],
  azure: ['microsoft', 'cloud'],
  'azure-storage': ['microsoft', 'cloud', 'disk', 'blob'],
  'azure-vms': ['microsoft', 'cloud', 'virtual machines'],
  back: ['arrow left', 'previous', 'return'],
  'back-off': ['arrow left disabled', 'previous', 'greyed'],
  'background-job-details': ['task info', 'process details'],
  'background-jobs': ['tasks', 'processes', 'queue'],
  backup: ['save', 'archive', 'copy'],
  'backup-restore-stop': ['halt restore', 'stop recovery'],
  'backup-start': ['begin backup', 'play', 'save'],
  'backup-state': ['backup status', 'save condition'],
  'backup-stop': ['halt backup', 'square'],
  'backup-target-edit': ['edit destination', 'pencil', 'save location'],
  'backup-targets': ['destinations', 'save locations'],
  bake: ['build', 'compile', 'agent package', 'oven'],
  'bake-result': ['build outcome', 'agent package result'],
  barplot: ['bar chart', 'graph', 'histogram', 'columns'],
  'bi-freeze': ['business intelligence', 'lock aggregation', 'snapshot'],
  bilist: ['business intelligence', 'list', 'aggregations'],
  bitree: ['business intelligence', 'tree', 'hierarchy', 'aggregation'],
  'bookmark-list': ['favorites', 'saved', 'marks'],
  bottom: ['arrow down', 'end', 'last', 'go to bottom'],
  'broken-chain': ['unlink', 'disconnect', 'link', 'severed'],
  bulk: ['batch', 'multiple', 'mass', 'group'],
  'bulk-import': ['batch upload', 'mass import', 'multiple'],
  cached: ['stored', 'memory', 'saved', 'clock'],
  cancel: ['x', 'close', 'stop', 'cross', 'red', 'no', 'abort'],
  'cancel-notifications': ['stop alerts', 'mute notifications', 'bell off'],
  'cannot-reschedule': ['no retry', 'blocked', 'disabled'],
  certificate: ['ssl', 'tls', 'credential', 'badge', 'security'],
  chain: ['link', 'connect', 'url', 'associate'],
  changes: ['pending', 'modifications', 'edits', 'activate'],
  check: ['service', 'monitored', 'test', 'probe'],
  'check-circle': ['checkmark', 'tick', 'confirm', 'green', 'yes'],
  'check-parameters': ['thresholds', 'settings', 'rules'],
  'check-plugins': ['monitoring plugins', 'extensions', 'checks'],
  checkbox: ['tickbox', 'select', 'option', 'square'],
  'checkbox-hover-bg': ['tickbox', 'select highlight'],
  checkmark: ['check', 'tick', 'confirm', 'yes', 'ok', 'green'],
  'checkmark-bare': ['check', 'tick', 'confirm', 'yes', 'ok'],
  'checkmark-bg-white': ['check', 'tick', 'confirm', 'white background'],
  'checkmark-orange': ['check', 'tick', 'confirm', 'orange'],
  'checkmark-plus': ['check add', 'tick plus', 'confirm new'],
  checkmk: ['logo', 'brand', 'cmk'],
  'checkmk-logo': ['brand', 'cmk', 'company'],
  'checkmk-logo-min': ['brand', 'cmk', 'small logo', 'favicon'],
  'chevron-down': ['arrow down', 'expand', 'collapse', 'caret', 'dropdown'],
  'chevron-left': ['arrow left', 'back', 'previous', 'caret'],
  'chevron-right': ['arrow right', 'forward', 'next', 'caret'],
  'chevron-up': ['arrow up', 'collapse', 'caret'],
  cleanup: ['clear', 'tidy', 'remove', 'sweep', 'broom'],
  clear: ['remove', 'erase', 'empty', 'trash'],
  clipboard: ['copy', 'paste', 'board'],
  clock: ['time', 'watch', 'schedule'],
  clone: ['duplicate', 'copy', 'replicate'],
  close: ['x', 'cross', 'dismiss', 'shut'],
  closetimewarp: ['exit history', 'close replay'],
  cloud: ['sky', 'hosted', 'saas'],
  cluster: ['group', 'nodes', 'ha', 'high availability'],
  'cmkcode-copied': [
    'copy code',
    'code copied',
    'clipboard',
    'duplicated',
    'snippet',
    'green',
    'checkmark'
  ],
  collapse: ['minimize', 'fold', 'shrink', 'hide'],
  'collapse-arrow': ['minimize', 'fold', 'arrow'],
  'color-mode': ['theme', 'dark light', 'appearance'],
  commands: ['actions', 'terminal', 'run'],
  comment: ['note', 'remark', 'speech bubble', 'annotation'],
  condition: ['rule', 'criteria', 'if', 'filter'],
  configuration: ['gear', 'settings', 'setup', 'config'],
  'connection-tests': ['network test', 'ping', 'diagnose'],
  contactgroups: ['teams', 'people', 'notification groups'],
  continue: ['proceed', 'next', 'play', 'resume', 'arrow right'],
  copied: ['duplicated', 'clipboard', 'checkmark'],
  counting: ['tally', 'count', 'numbers'],
  crash: ['error', 'broken', 'failure', 'bug', 'report'],
  'crash-glow': ['error highlight', 'broken', 'failure'],
  'crit-problem': ['critical', 'red', 'severe', 'danger', 'issue'],
  critical: ['red', 'severe', 'danger', 'error', 'crit'],
  cross: ['x', 'close', 'no', 'red', 'abort', 'cancel'],
  'cross-bg-white': ['x', 'close', 'no', 'white background'],
  'cross-grey': ['x', 'close', 'disabled', 'no', 'grey'],
  'custom-attr': ['attribute', 'custom field', 'property'],
  'custom-graph': ['chart', 'user defined', 'plot'],
  'custom-snapin': ['sidebar element', 'widget', 'panel'],
  'customer-management': ['client', 'tenant', 'msp'],
  customize: ['personalize', 'configure', 'settings', 'adjust'],
  d146n0571c5: ['diagnostics', 'easter egg', 'hidden', 'leetspeak'],
  dash: ['line', 'minus', 'hyphen'],
  dashboard: ['overview', 'panel', 'home', 'widgets'],
  'dashboard-controls': ['overview settings', 'widget controls'],
  'dashboard-edit': ['pencil', 'modify overview', 'change widgets'],
  'dashboard-grid': ['overview layout', 'widget grid', 'tiles'],
  'dashboard-main': ['home overview', 'default panel'],
  'dashboard-menuarrow': ['overview menu', 'dropdown arrow', 'caret'],
  'dashboard-problems': ['issues overview', 'errors panel'],
  'dashboard-system': ['infrastructure overview', 'server panel'],
  'dashlet-anchor': ['widget anchor', 'pin'],
  'dashlet-clone': ['duplicate widget', 'copy dashboard element'],
  'dashlet-delete': ['trash widget', 'remove dashboard element', 'bin'],
  'dashlet-edit': ['pencil', 'modify widget', 'change dashboard element'],
  'dashlet-network-topology': ['widget map', 'network diagram'],
  'dashlet-nodata': ['empty widget', 'no data'],
  'dashlet-notifications-bar-chart': ['widget chart', 'notifications graph'],
  'dashlet-resize': ['widget resize', 'scale'],
  'dashlet-url': ['widget link', 'embed'],
  'db-widget-clone': ['duplicate widget', 'copy dashboard element'],
  'db-widget-delete': ['trash', 'remove widget', 'bin'],
  'db-widget-edit': ['pencil', 'modify widget'],
  'dcd-connections': ['dynamic config', 'auto discovery links'],
  'dcd-execute': ['run discovery', 'dynamic config'],
  'dcd-history': ['discovery log', 'dynamic config history'],
  delayed: ['postponed', 'waiting', 'clock', 'pending'],
  delete: ['trash', 'bin', 'remove', 'garbage'],
  'deploy-agents': ['push agents', 'install collectors', 'rollout'],
  'deployment-error': ['rollout failed', 'red', 'install error'],
  'deployment-status': ['rollout state', 'install progress'],
  'derived-downtime': ['inherited maintenance', 'pause', 'scheduled'],
  detail: ['info', 'zoom', 'magnifier', 'details'],
  'developer-resources': ['dev tools', 'documentation', 'code'],
  development: ['dev', 'engineering', 'code', 'team'],
  diagnose: ['troubleshoot', 'stethoscope', 'examine', 'debug'],
  diagnostics: ['troubleshoot', 'debug', 'examine'],
  'diagnostics-dump-file': ['debug dump', 'support file', 'export'],
  'disable-test': ['turn off trial', 'deactivate'],
  disabled: ['off', 'inactive', 'greyed', 'turned off'],
  'disabled-service': ['off check', 'inactive monitored'],
  'dissolve-operation': ['undo merge', 'break apart', 'ungroup'],
  docker: ['container', 'containerization'],
  down: ['arrow down', 'offline', 'red', 'host down'],
  download: ['arrow down', 'save', 'import', 'get'],
  'download-agents': ['arrow down', 'get collectors', 'save clients'],
  'download-csv': ['arrow down', 'export spreadsheet', 'save table'],
  'download-json': ['arrow down', 'export data', 'save'],
  downtime: ['pause', 'scheduled', 'maintenance'],
  'downtime-for-report': ['maintenance report', 'scheduled pause'],
  drag: ['move', 'reorder', 'grab', 'handle'],
  edit: ['pencil', 'modify', 'change'],
  'edit-custom-graph': ['pencil', 'modify chart'],
  'edit-forecast-model': ['pencil', 'modify prediction'],
  email: ['mail', 'envelope', 'message', 'notification'],
  empty: ['blank', 'nothing', 'none'],
  'enable-test': ['turn on trial', 'activate'],
  enabled: ['on', 'active', 'turned on'],
  encrypted: ['lock', 'secure', 'padlock', 'ssl'],
  end: ['finish', 'stop', 'last'],
  error: ['red', 'failure', 'problem', 'exclamation'],
  event: ['log entry', 'occurrence', 'alert'],
  'event console-status': ['event state', 'ec status'],
  'event-console': ['ec', 'syslog', 'log events'],
  expand: ['maximize', 'unfold', 'grow', 'show'],
  export: ['arrow out', 'save', 'download', 'send'],
  'export-link': ['save link', 'download url', 'arrow out'],
  'export-rule': ['save rule', 'download rule'],
  external: ['outbound', 'open new tab', 'arrow out', 'link'],
  factoryreset: ['restore defaults', 'wipe', 'reset all'],
  'fake-check-result': ['simulate', 'force result', 'test'],
  favicon: ['site icon', 'tab icon', 'brand'],
  favorite: ['star', 'bookmark', 'favourite', 'saved'],
  filter: ['funnel', 'narrow', 'refine', 'search'],
  'filter-line': ['funnel', 'narrow', 'refine'],
  'filters-set': ['funnel applied', 'active filters'],
  fixall: ['repair all', 'accept all', 'resolve everything'],
  flapping: ['unstable', 'fluctuating', 'toggling'],
  folder: ['directory'],
  'folder-blue': ['directory', 'blue folder'],
  'folder-closed': ['directory', 'shut folder'],
  'folder-hi': ['directory highlighted', 'active folder'],
  'folder-open': ['directory open', 'expanded folder'],
  folderproperties: ['directory settings', 'folder config'],
  'forecast-graph': ['prediction chart', 'trend', 'future'],
  'foreign-changes': ['other user edits', 'external changes'],
  forth: ['forward', 'arrow right', 'next'],
  'forth-off': ['forward disabled', 'arrow right greyed'],
  frameurl: ['embed link', 'iframe'],
  gauge: ['meter', 'dial', 'speedometer'],
  gcp: ['google', 'cloud', 'platform'],
  'global-settings': ['gear', 'cog', 'config', 'settings', 'preferences'],
  globe: ['world', 'internet', 'web', 'earth'],
  graph: ['chart', 'plot', 'line'],
  'graph-collection': ['charts group', 'plots'],
  'graph-time': ['chart timerange', 'plot duration'],
  'graph-tuning': ['chart settings', 'plot adjust'],
  'gui-design': ['interface', 'appearance', 'layout'],
  guitest: ['interface test', 'ui trial'],
  'hard-states': ['confirmed states', 'stable status'],
  hardware: ['physical', 'device', 'machine', 'components'],
  help: ['question mark', 'support', 'assistance', 'info'],
  'help-activated': ['question mark on', 'help mode'],
  hierarchy: ['tree', 'structure', 'levels', 'nesting'],
  history: ['past', 'log', 'timeline', 'previous'],
  home: ['house', 'start', 'main', 'dashboard'],
  host: ['server', 'machine', 'computer'],
  'host-graph': ['server chart', 'machine plot'],
  'host-problems': ['server', 'issues', 'machine errors'],
  'host-state': ['server status', 'machine condition'],
  'host-state-summary': ['server status overview', 'machine summary'],
  'host-statistics': ['server stats', 'machine metrics'],
  'host-svc-problems': ['server service issues', 'machine check errors'],
  'host-svc-problems-dark': ['server service issues', 'machine check errors'],
  hostgroups: ['server groups', 'machine clusters'],
  hyphen: ['dash', 'minus', 'line'],
  ical: ['calendar', 'schedule', 'ics'],
  icons: ['symbols', 'glyphs', 'pictograms'],
  ignore: ['skip', 'mute', 'disable', 'dismiss'],
  inactive: ['off', 'disabled', 'idle', 'greyed'],
  'influxdb-connections': ['time series db', 'metrics database'],
  info: ['information', 'i', 'details', 'blue'],
  'info-circle': ['information', 'i', 'details', 'blue'],
  'inline-error': ['red', 'validation', 'field error'],
  insert: ['add', 'plus', 'place'],
  insertdate: ['add date', 'calendar', 'timestamp'],
  install: ['setup', 'add software', 'deploy'],
  'integrations-custom': ['custom plugins', 'extensions'],
  'integrations-other': ['misc plugins', 'extensions'],
  inv: ['inventory', 'hardware software list'],
  inventory: ['hardware software', 'asset list', 'stock'],
  'inventory-failed': ['asset scan error', 'red'],
  inverted: ['flipped', 'negated', 'opposite'],
  kubernetes: ['k8s', 'container orchestration', 'cloud'],
  'laptop-50': ['notebook', 'computer', 'client', 'device'],
  ldap: ['directory', 'active directory', 'authentication'],
  'learning-beginner': ['tutorial', 'starter', 'education'],
  'learning-checkmk': ['tutorial', 'education', 'docs'],
  'learning-forum': ['community', 'discussion', 'education'],
  'learning-guide': ['manual', 'documentation', 'education'],
  'learning-video-tutorials': ['videos', 'education', 'watch'],
  'license-failed': ['red', 'activation error', 'key invalid'],
  'license-successful': ['green', 'activated', 'key valid', 'checkmark'],
  'license-unknown-state': ['grey', 'unclear license', 'question'],
  licensing: ['key', 'subscription', 'activation'],
  lightbulb: ['idea', 'tip', 'hint', 'suggestion'],
  'lightbulb-idea': ['tip', 'hint', 'suggestion', 'innovation'],
  link: ['chain', 'connect', 'url', 'hyperlink'],
  linux: ['penguin', 'tux', 'os', 'unix'],
  'linux-deb': ['debian', 'ubuntu', 'package'],
  'linux-rpm': ['redhat', 'fedora', 'centos', 'package'],
  'linux-tgz': ['tarball', 'archive', 'package'],
  'load-graph': ['cpu chart', 'utilization plot'],
  localrule: ['local check', 'custom rule'],
  log: ['record', 'history', 'journal'],
  login: ['sign in', 'enter', 'authenticate'],
  'logo-cmk-small': ['brand', 'checkmk', 'small'],
  logwatch: ['log monitoring', 'syslog', 'tail'],
  'magic-move': ['auto arrange', 'smart move', 'wand'],
  'main-changes': ['pending changes menu', 'activate'],
  'main-changes-active': ['pending changes menu', 'activate'],
  'main-customize': ['personalize menu', 'settings'],
  'main-customize-active': ['personalize menu', 'settings'],
  'main-help': ['help menu', 'question mark'],
  'main-help-active': ['help menu', 'question mark'],
  'main-monitoring': ['monitoring menu', 'watch'],
  'main-monitoring-active': ['monitoring menu', 'watch'],
  'main-search': ['magnifier', 'find menu', 'lookup'],
  'main-search-active': ['magnifier', 'find menu', 'lookup'],
  'main-setup': ['gear', 'config menu', 'settings'],
  'main-setup-active': ['gear', 'config menu', 'settings'],
  'main-user': ['person', 'account menu', 'profile'],
  'main-user-active': ['person', 'account menu', 'profile'],
  manual: ['documentation', 'guide', 'handbook'],
  'manual-active': ['documentation', 'guide', 'handbook'],
  matrix: ['grid', 'table', 'array'],
  menu: ['hamburger', 'list', 'navigation', 'options'],
  'menu-item-checked': ['selected', 'checkmark', 'ticked option'],
  'menu-item-unchecked': ['unselected', 'empty option'],
  message: ['chat', 'speech', 'comment', 'note'],
  'migrate-users': ['transfer accounts', 'move people'],
  missing: ['absent', 'not found', 'gone', 'lost'],
  'mkeventd-rules': ['event console rules', 'ec rules'],
  mkps: ['packages', 'extensions', 'plugins bundle'],
  'monitored-service': ['watched check', 'active service', 'green'],
  monitoring: ['watch', 'observe', 'surveillance'],
  move: ['drag', 'relocate', 'arrows', 'reposition'],
  movedown: ['arrow down', 'lower', 'reorder'],
  moveup: ['arrow up', 'raise', 'reorder'],
  nagios: ['monitoring', 'legacy core'],
  nagvis: ['visualization', 'maps', 'nagios'],
  'need-replicate': ['sync required', 'replication pending'],
  'need-restart': ['reboot required', 'circular arrow', 'pending'],
  network: ['connections', 'ethernet', 'topology'],
  'network-services': ['ports', 'connections', 'tcp'],
  'network-topology': ['map', 'diagram', 'connections', 'nodes'],
  networking: ['network', 'connections', 'ethernet'],
  new: ['plus', 'add', 'create', 'fresh'],
  'new-cluster': ['plus', 'add group', 'create nodes'],
  'new-mkp': ['plus', 'add package', 'create extension'],
  newfolder: ['plus', 'add directory', 'create folder'],
  'no-entry': ['forbidden', 'blocked', 'prohibited', 'red'],
  'no-pending-changes': ['nothing to activate', 'clean', 'green'],
  'no-revert': ['cannot undo', 'blocked', 'irreversible'],
  nodowntime: ['no maintenance', 'no pause', 'active'],
  notes: ['comments', 'annotations', 'memo'],
  'notif-disabled': ['notifications off', 'bell muted', 'silent'],
  'notif-enabled': ['notifications on', 'bell active'],
  'notif-man-disabled': ['notifications manually off', 'bell muted'],
  'notification-enabled': ['bell on', 'alerts active'],
  'notification-timeline': ['bell history', 'alerts timeline'],
  notifications: ['bells', 'alerts', 'messages'],
  npassive: ['passive check', 'no active'],
  ntop: ['network traffic', 'flows', 'bandwidth'],
  ooservice: ['out of service', 'unmonitored', 'disabled check'],
  'open-telemetry': ['otel', 'observability', 'tracing', 'metrics'],
  opentelemetry: ['otel', 'observability', 'tracing', 'metrics'],
  'os-other': ['operating system', 'misc os'],
  'otel-collector': ['opentelemetry', 'observability', 'gather metrics'],
  'outof-serviceperiod': ['outside hours', 'off schedule', 'not active'],
  outofnot: ['out of notification period', 'off schedule'],
  packages: ['bundles', 'extensions', 'boxes', 'mkp'],
  'pagetype-topic': ['category', 'section', 'page kind'],
  pageurl: ['page link', 'address'],
  painteroptions: ['display options', 'column settings', 'view config'],
  'painteroptions-down-hi': ['display options expand', 'column settings'],
  'painteroptions-down-lo': ['display options collapse', 'column settings'],
  'painteroptions-off': ['display options disabled', 'column settings'],
  parentscan: ['network parents', 'topology scan'],
  passwords: ['credentials', 'keys', 'secrets', 'lock'],
  pause: ['halt', 'wait', 'suspend', 'two bars'],
  'pending-changes': ['unsaved', 'to activate', 'modifications'],
  'pending-task': ['waiting job', 'queued', 'clock'],
  'percentage-of-service-problems': ['check issues percent', 'ratio'],
  'performance-data': ['metrics', 'perfdata', 'measurements'],
  persist: ['save', 'keep', 'store', 'retain'],
  'pie-chart': ['circle chart', 'graph', 'proportions'],
  play: ['start', 'begin', 'run', 'triangle', 'go'],
  'plugins-agentless': ['no agent checks', 'remote plugins'],
  'plugins-app': ['application plugins', 'software checks'],
  'plugins-cloud': ['cloud plugins', 'hosted checks'],
  'plugins-containerization': ['docker plugins', 'kubernetes checks'],
  'plugins-generic': ['general plugins', 'misc checks'],
  'plugins-hw': ['hardware plugins', 'device checks'],
  'plugins-os': ['operating system plugins', 'os checks'],
  'plugins-virtual': ['virtualization plugins', 'vm checks'],
  pluginurl: ['plugin link', 'extension address'],
  plus: ['add', 'new', 'create', 'insert'],
  pnp: ['graphing', 'rrd graphs', 'performance data'],
  'predefined-conditions': ['preset rules', 'saved criteria'],
  prediction: ['forecast', 'trend', 'future', 'estimate'],
  problem: ['issue', 'error', 'trouble', 'alert'],
  product: ['team', 'product management', 'pm'],
  prometheus: ['metrics', 'monitoring', 'time series'],
  'proxmox-ve': ['virtualization', 'hypervisor', 'vm', 'pve'],
  qa: ['quality assurance', 'testing', 'team'],
  'qs-aws': ['quick setup amazon', 'cloud wizard'],
  'qs-azure': ['quick setup microsoft', 'cloud wizard'],
  'qs-gcp': ['quick setup google', 'cloud wizard'],
  'qs-otel': ['quick setup opentelemetry', 'observability wizard'],
  'qs-prometheus': ['quick setup metrics', 'wizard'],
  'qs-proxmox-ve': ['quick setup proxmox', 'virtualization wizard'],
  'qs-relay': ['quick setup relay', 'proxy wizard'],
  'quick-setup-aws': ['amazon wizard', 'cloud onboarding'],
  quicksearch: ['magnifier', 'find', 'lookup', 'glass'],
  'quicksearch-field-bg': ['search box', 'find field'],
  random: ['shuffle', 'dice', 'arbitrary'],
  rank: ['order', 'priority', 'position', 'rating'],
  'read-only': ['locked', 'view only', 'no edit'],
  'recreate-broker-certificate': ['regenerate cert', 'renew ssl', 'messaging'],
  redo: ['repeat', 'forward arrow', 'again'],
  'relay-menu': ['proxy menu', 'forwarder'],
  'release-automated': ['auto release', 'publish', 'rollout'],
  'release-deploy': ['publish', 'rollout', 'ship'],
  'release-mkp': ['publish package', 'ship extension'],
  'release-mkp-yellow': ['publish package warning', 'ship extension'],
  'release-scale': ['publish scaled', 'rollout'],
  reload: ['refresh', 'circular arrow', 'sync', 'retry'],
  'reload-cmk': ['refresh checkmk', 'circular arrow', 'sync'],
  reloadsnapin: ['refresh sidebar', 'circular arrow'],
  'reloadsnapin-lo-alt': ['refresh sidebar', 'circular arrow'],
  'rename-host': ['rename server', 'pencil', 'change name'],
  'repl-25': ['replication 25 percent', 'sync progress'],
  'repl-50': ['replication half', 'sync progress'],
  'repl-75': ['replication 75 percent', 'sync progress'],
  'repl-failed': ['replication error', 'sync failed', 'red'],
  'repl-locked': ['replication locked', 'sync blocked'],
  'repl-pending': ['replication waiting', 'sync queued'],
  'repl-success': ['replication done', 'sync ok', 'green', 'checkmark'],
  replay: ['repeat', 'redo', 'playback', 'again'],
  replicate: ['sync', 'copy', 'mirror', 'distribute'],
  report: ['document', 'pdf', 'summary'],
  'report-element': ['document part', 'report widget'],
  'report-fixed': ['document static', 'report snapshot'],
  'report-store': ['saved reports', 'document library'],
  reportscheduler: ['report timer', 'scheduled documents'],
  reset: ['clear', 'restore', 'default', 'circular arrow'],
  resetcounters: ['clear counts', 'zero counters'],
  resize: ['scale', 'stretch', 'drag corner'],
  'resize-graph': ['scale chart', 'stretch plot'],
  restart: ['reboot', 'circular arrow', 'power cycle'],
  restore: ['recover', 'undo', 'bring back'],
  revert: ['undo', 'rollback', 'back', 'discard'],
  'rj45-50': ['ethernet', 'network port', 'lan cable'],
  roles: ['permissions', 'groups', 'access levels'],
  'rotate-left': ['turn counterclockwise', 'circular arrow'],
  rule: ['policy', 'criteria', 'setting'],
  'rule-no': ['disabled rule', 'x', 'red'],
  'rule-no-off': ['disabled rule greyed', 'x'],
  'rule-yes': ['enabled rule', 'checkmark', 'green'],
  'rule-yes-off': ['enabled rule greyed', 'checkmark'],
  rules: ['policies', 'criteria', 'settings'],
  rulesets: ['rule groups', 'policies', 'settings'],
  'rulesets-deprecated': ['obsolete rules', 'old policies'],
  'rulesets-ineffective': ['unused rules', 'inactive policies'],
  saas: ['software as a service', 'cloud', 'hosted'],
  saml: ['single sign on', 'sso', 'authentication', 'federation'],
  save: ['disk', 'floppy', 'store', 'keep'],
  'save-dashboard': ['disk', 'store overview'],
  'save-graph': ['disk', 'store chart'],
  'save-to-folder': ['disk', 'store directory'],
  'save-to-services': ['disk', 'store checks'],
  'save-view': ['disk', 'store layout'],
  scatterplot: ['dot chart', 'graph', 'points', 'xy'],
  search: ['magnifier', 'find', 'lookup', 'glass'],
  'search-action': ['magnifier action', 'find command'],
  'search-action-button': ['magnifier button', 'find action'],
  'select-arrow': ['dropdown arrow', 'caret', 'chevron'],
  'service-discovery': ['find checks', 'scan', 'detect services'],
  'service-duration': ['check time', 'uptime length'],
  'service-graph': ['check chart', 'monitored plot'],
  'service-label-add': ['plus', 'tag check', 'add marker'],
  'service-label-remove': ['minus', 'untag check', 'delete marker'],
  'service-label-update': ['edit tag', 'change marker'],
  'service-state': ['check status', 'monitored condition'],
  'service-to-disabled': ['check turned off', 'deactivate monitored'],
  'service-to-ignored': ['check skipped', 'mute monitored'],
  'service-to-monitored': ['check activated', 'watch monitored'],
  'service-to-new': ['check found', 'new monitored'],
  'service-to-removed': ['check deleted', 'gone monitored'],
  'service-to-unchanged': ['check same', 'no change monitored'],
  'service-to-undecided': ['check pending', 'undecided monitored'],
  servicegroups: ['check groups', 'monitored clusters'],
  services: ['checks', 'monitored items'],
  'services-blue': ['checks', 'monitored items', 'blue'],
  'services-fix-all': ['accept all checks', 'repair discovery'],
  'services-green': ['checks ok', 'healthy monitored'],
  'services-refresh': ['rescan checks', 'circular arrow', 'sync discovery'],
  'services-stop': ['halt checks', 'square'],
  'services-tabula-rasa': ['reset checks', 'clean slate discovery'],
  setup: ['gear', 'cog', 'config', 'settings', 'preferences'],
  share: ['send', 'distribute', 'export', 'publish'],
  'show-less': ['collapse', 'minus', 'hide details', 'fold'],
  'show-less-green': ['collapse', 'hide details', 'fold'],
  'show-more': ['expand', 'plus', 'details', 'unfold'],
  'show-more-green': ['expand', 'details', 'unfold'],
  showbi: ['business intelligence', 'aggregation view'],
  showhide: ['toggle visibility', 'eye', 'reveal'],
  sidebar: ['panel', 'navigation', 'side menu'],
  'sidebar-folded': ['panel collapsed', 'side menu hidden'],
  'sidebar-logout': ['sign out', 'exit', 'leave'],
  'sidebar-position': ['panel placement', 'side menu location'],
  'sidebar-top': ['panel top', 'side menu top'],
  sign: ['sigil', 'symbol', 'mark'],
  'signature-key': ['sign key', 'credential', 'gpg', 'security'],
  'signature-key-partial': ['incomplete key', 'partial credential'],
  'single-metric': ['one value', 'kpi', 'number'],
  'site-dead': ['instance down', 'server offline', 'red'],
  'site-disabled': ['instance off', 'server inactive', 'greyed'],
  'site-down': ['instance offline', 'server down', 'red'],
  'site-globals': ['site settings', 'global config'],
  'site-globals-modified': ['site settings changed', 'edited config'],
  'site-missing': ['instance absent', 'server not found'],
  'site-overview': ['instance summary', 'site dashboard'],
  'site-unreach': ['instance unreachable', 'no connection'],
  'site-waiting': ['instance pending', 'server connecting', 'clock'],
  sites: ['instances', 'servers', 'locations'],
  sla: ['service level', 'agreement', 'uptime target'],
  'sla-configuration': ['service level settings', 'agreement config'],
  'snapin-greyswitch-off': ['sidebar toggle off', 'disabled'],
  'snapin-greyswitch-on': ['sidebar toggle on', 'enabled'],
  snapshot: ['backup', 'copy', 'save state'],
  'snapshot-checksum': ['backup verified', 'hash ok', 'green'],
  'snapshot-nchecksum': ['backup no checksum', 'unverified'],
  'snapshot-pchecksum': ['backup partial checksum', 'partly verified'],
  snmp: ['network protocol', 'device monitoring'],
  snmpmib: ['snmp mib', 'network protocol definition'],
  software: ['programs', 'applications', 'installed'],
  'solaris-pkg': ['oracle', 'unix', 'package'],
  'solaris-tgz': ['oracle', 'unix', 'tarball', 'archive'],
  someproblem: ['partial issue', 'warning', 'trouble'],
  sparkle: ['shine', 'ai', 'magic', 'stars'],
  'sparkle-white': ['shine', 'ai', 'magic', 'stars', 'white'],
  speedometer: ['gauge', 'dial', 'meter', 'performance'],
  stale: ['outdated', 'old data', 'expired', 'grey'],
  starred: ['favorite', 'bookmark', 'favourite'],
  start: ['play', 'begin', 'run', 'go'],
  'static-checks': ['manual checks', 'fixed monitored'],
  'static-text': ['label', 'fixed text', 'plain'],
  status: ['state', 'condition', 'health'],
  'status-report': ['state document', 'health summary'],
  success: ['green', 'checkmark', 'done', 'ok', 'complete'],
  suggestion: ['lightbulb', 'tip', 'hint', 'idea'],
  'svc-problems': ['service issues', 'check errors'],
  'sync-graphs': ['align charts', 'match plots', 'circular arrow'],
  'sync-mkp': ['sync package', 'circular arrow', 'update extension'],
  'synthetic-monitoring-purple': ['robot', 'scripted checks', 'simulated'],
  'synthetic-monitoring-topic': ['robot', 'scripted checks', 'simulated'],
  'synthetic-monitoring-yellow': ['robot', 'scripted checks', 'simulated'],
  'table-actions-off': ['row actions hidden', 'table menu off'],
  'table-actions-on': ['row actions shown', 'table menu on'],
  tag: ['label', 'marker', 'category'],
  tick: ['checkmark', 'check', 'confirm', 'yes'],
  timeline: ['history', 'events', 'chronology'],
  timeperiods: ['schedules', 'time windows', 'hours'],
  timewarp: ['history', 'replay', 'go back in time'],
  'timewarp-off': ['history disabled', 'replay off'],
  tls: ['ssl', 'encryption', 'secure', 'certificate'],
  'toggle-context': ['switch menu', 'right click'],
  'toggle-details': ['show hide info', 'expand collapse'],
  'toggle-off': ['switch off', 'disabled', 'inactive'],
  'toggle-on': ['switch on', 'enabled', 'active'],
  top: ['arrow up', 'first', 'go to top', 'beginning'],
  'top-list': ['ranking', 'leaderboard', 'highest'],
  'topic-2fa': ['two factor section', 'mfa category'],
  'topic-administration': ['admin section', 'management category'],
  'topic-agents': ['collectors section', 'clients category'],
  'topic-analyze': ['analysis section', 'examine category'],
  'topic-applications': ['apps section', 'software category'],
  'topic-bi': ['business intelligence section', 'aggregation category'],
  'topic-change-password': ['password section', 'credentials category'],
  'topic-checkmk': ['checkmk section', 'cmk category'],
  'topic-events': ['events section', 'log category'],
  'topic-exporter': ['export section', 'exporter category'],
  'topic-general': ['general section', 'misc category'],
  'topic-graphs': ['charts section', 'plots category'],
  'topic-history': ['history section', 'past category'],
  'topic-hosts': ['servers section', 'machines category'],
  'topic-inventory': ['asset section', 'hardware software category'],
  'topic-maintenance': ['maintenance section', 'downtime category'],
  'topic-monitoring': ['monitoring section', 'watch category'],
  'topic-my-workplace': ['personal section', 'workspace category'],
  'topic-network': ['network section', 'connections category'],
  'topic-other': ['misc section', 'other category'],
  'topic-overview': ['summary section', 'overview category'],
  'topic-problems': ['issues section', 'errors category'],
  'topic-profile': ['account section', 'person category'],
  'topic-quick-setups': ['wizards section', 'onboarding category'],
  'topic-reporting': ['reports section', 'documents category'],
  'topic-services': ['checks section', 'monitored category'],
  'topic-site': ['instance section', 'site category'],
  'topic-system': ['system section', 'infrastructure category'],
  'topic-user-interface': ['ui section', 'appearance category'],
  'topic-users': ['accounts section', 'people category'],
  'topic-visualization': ['charts section', 'diagrams category'],
  trans: ['transparent', 'translucent', 'see through'],
  'tree-closed': ['collapsed tree', 'folder closed', 'expand'],
  trust: ['verify', 'secure', 'trusted', 'shield'],
  twofa: ['two factor', 'authentication', 'mfa', 'otp', 'security'],
  'twofa-backup-codes': ['two factor recovery', 'mfa codes'],
  'unacknowledge-test': ['remove confirm', 'unconfirm trial'],
  unavailable: ['not available', 'offline', 'grey', 'disabled'],
  'undecided-service': ['pending check', 'unsorted monitored', 'question'],
  undo: ['revert', 'back arrow', 'rollback'],
  'unpackaged-files': ['loose files', 'unbundled'],
  unusedbirules: ['unused aggregation rules', 'inactive bi'],
  up: ['arrow up', 'online', 'green', 'host up'],
  update: ['refresh', 'upgrade', 'sync', 'newer'],
  'update-discovery-parameters': ['refresh discovery settings', 'sync params'],
  'update-host-labels': ['refresh server tags', 'sync markers'],
  'update-service-labels': ['refresh check tags', 'sync markers'],
  upgrade: ['arrow up', 'newer version', 'improve'],
  upload: ['arrow up', 'send', 'import file', 'put'],
  url: ['link', 'address', 'web', 'hyperlink'],
  usedrulesets: ['active rules', 'applied policies'],
  user: ['person', 'account', 'profile', 'avatar'],
  'user-interface': ['ui', 'appearance', 'layout', 'display', 'theme'],
  'user-locked': ['account locked', 'person blocked', 'disabled'],
  users: ['people', 'group', 'team', 'accounts'],
  ux: ['user experience', 'design', 'team'],
  'validation-error': ['red', 'invalid', 'form error'],
  video: ['play', 'film', 'watch', 'movie'],
  view: ['eye', 'look', 'display', 'see'],
  'view-columns': ['table columns', 'layout'],
  'view-copy': ['duplicate view', 'clone layout'],
  'view-link': ['view url', 'connect display'],
  'view-refresh': ['reload view', 'circular arrow', 'update display'],
  vsphere: ['vmware', 'virtualization', 'esxi', 'hypervisor'],
  waiting: ['pending', 'hourglass', 'loading', 'in progress', 'spinner'],
  warning: ['triangle', 'caution', 'alert', 'exclamation', 'yellow'],
  wato: ['setup', 'configuration', 'admin', 'gear'],
  'wato-changes': ['setup changes', 'config edits'],
  'wato-nochanges': ['setup clean', 'no config edits'],
  'werk-ack': ['changelog confirm', 'acknowledge change'],
  'widget-clone': ['duplicate widget', 'copy element'],
  'widget-delete': ['trash', 'remove widget', 'bin'],
  'widget-edit': ['pencil', 'modify widget'],
  wikisearch: ['magnifier', 'find docs', 'lookup wiki'],
  'windows-msi': ['microsoft', 'installer', 'windows'],
  'wrong-agent': ['mismatched collector', 'agent error'],
  www: ['web', 'internet', 'globe', 'url'],
  zoom: ['magnifier', 'enlarge', 'scale', 'glass']
}
