@startuml
!include <awslib/AWSCommon>
!include <awslib/General/Users>

/' README
Always include this file in your diagram!

Add definitions to this file in case:
* you are reusing those definitions in multiple diagrams
* you want to apply styles for all diagrams
'/

' GLOBAL STYLE SETTINGS: These will apply for all diagrams!
' linetype ortho messes-up the label positioning:
' https://github.com/plantuml/plantuml/issues/149
' skinparam linetype ortho

' GLOBAL DIAGRAM DEFINITIONS
Users(end_user, "End User", "checkmk User")
Users(third_party, "3rd Party", "external systems")

@enduml
