[toolchain]
channel = "1.87.0" # must be in sync with MODULE.bazel run.ps1

[toolchain.windows]
targets = ["i686-pc-windows-msvc"]

[toolchain.linux]
targets = ["x86_64-unknown-linux-musl", "x86_64-unknown-linux-gnu"]
