#!/usr/bin/python
# encoding: utf-8

import os
import sys
import pylint_cmk

pylint_cmk.ensure_equal_branches()

search_paths = [
    "../bin",
    "../notifications",
    "../agents/plugins",
    "../doc/treasures/active_checks",
    "../../cmc/agents/plugins",
    "../../cmc/bin",
    "../../cmc/misc",
]

worst = 0
for path in search_paths:
    worst = max(worst, pylint_cmk.run_pylint(path))

sys.exit(worst)
