type = "Component"
display_name = "Plugins: LSI MegaRAID"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["mohamed.saleh@checkmk.com"]
description = """
Plugins for LSI/Avago/Broadcom MegaRAID controllers.
"""
