#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from cmk.plugins.lib.node_exporter import NodeExporter, PromQLMetric


def test_process_kernel_info() -> None:
    cpu_total: list[PromQLMetric] = [
        {"value": 16048481.0, "labels": {"instance": "minikube", "mode": "idle"}},
        {"value": 84976.0, "labels": {"instance": "minikube", "mode": "iowait"}},
        {"value": 0.0, "labels": {"instance": "minikube", "mode": "irq"}},
        {"value": 46007.0, "labels": {"instance": "minikube", "mode": "nice"}},
        {"value": 15703.0, "labels": {"instance": "minikube", "mode": "softirq"}},
        {"value": 0.0, "labels": {"instance": "minikube", "mode": "steal"}},
        {"value": 288526.0, "labels": {"instance": "minikube", "mode": "system"}},
        {"value": 721459.0, "labels": {"instance": "minikube", "mode": "user"}},
    ]

    cpu: list[PromQLMetric] = [
        {
            "value": 1975249.0000000002,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "idle",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 15080.000000000002,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "iowait",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "irq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 7995.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 4192.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "softirq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "steal",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 51023.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "system",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 98319.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 1992845.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "idle",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 13538.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "iowait",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "irq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 7561.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 2283.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "softirq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "steal",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 34862.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "system",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 97253.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 2016018.9999999998,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "idle",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 11532.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "iowait",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "irq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 6196.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 1923.9999999999998,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "softirq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "steal",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 31514.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "system",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 81139.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 2019413.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "idle",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 8916.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "iowait",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "irq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 5272.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 1687.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "softirq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "steal",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 30991.000000000004,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "system",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 85161.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 1999434.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "idle",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 11460.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "iowait",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "irq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 6225.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 1473.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "softirq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "steal",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 37300.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "system",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 93617.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 2004221.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "idle",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 9883.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "iowait",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "irq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 5274.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 1313.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "softirq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "steal",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 36764.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "system",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 92237.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 2014041.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "idle",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 8369.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "iowait",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "irq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 4372.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 1283.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "softirq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "steal",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 34441.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "system",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 88981.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 2027259.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "idle",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 6198.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "iowait",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "irq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 3112.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 1548.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "softirq",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "steal",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 31631.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "system",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 84752.0,
            "labels": {
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
    ]

    guest_total: list[PromQLMetric] = [
        {"value": 0.0, "labels": {"instance": "minikube", "mode": "nice"}},
        {"value": 0.0, "labels": {"instance": "minikube", "mode": "user"}},
    ]

    guest: list[PromQLMetric] = [
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "0",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "1",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "2",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "3",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "4",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "5",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "6",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "nice",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
        {
            "value": 0.0,
            "labels": {
                "__name__": "node_cpu_guest_seconds_total",
                "container": "kube-rbac-proxy",
                "cpu": "7",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "mode": "user",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        },
    ]

    ctxt: list[PromQLMetric] = [
        {
            "value": 279562310.0,
            "labels": {
                "__name__": "node_context_switches_total",
                "container": "kube-rbac-proxy",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        }
    ]
    pswpin: list[PromQLMetric] = [
        {
            "value": 186582.0,
            "labels": {
                "__name__": "node_vmstat_pswpin",
                "container": "kube-rbac-proxy",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        }
    ]
    pwpout: list[PromQLMetric] = [
        {
            "value": 1576740.0,
            "labels": {
                "__name__": "node_vmstat_pswpout",
                "container": "kube-rbac-proxy",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        }
    ]
    pgmajfault: list[PromQLMetric] = [
        {
            "value": 155971.0,
            "labels": {
                "__name__": "node_vmstat_pgmajfault",
                "container": "kube-rbac-proxy",
                "endpoint": "https",
                "instance": "minikube",
                "job": "node-exporter",
                "namespace": "monitoring",
                "pod": "node-exporter-rhmm5",
                "service": "node-exporter",
            },
        }
    ]

    expected = (
        "<<<kernel>>>\n"
        "1700000000\n"
        "cpu 721459 46007 288526 16048481 84976 0 15703 0 0 0\n"
        "cpu0 98319 7995 51023 1975249 15080 0 4192 0 0 0\n"
        "cpu1 97253 7561 34862 1992845 13538 0 2283 0 0 0\n"
        "cpu2 81139 6196 31514 2016018 11532 0 1923 0 0 0\n"
        "cpu3 85161 5272 30991 2019413 8916 0 1687 0 0 0\n"
        "cpu4 93617 6225 37300 1999434 11460 0 1473 0 0 0\n"
        "cpu5 92237 5274 36764 2004221 9883 0 1313 0 0 0\n"
        "cpu6 88981 4372 34441 2014041 8369 0 1283 0 0 0\n"
        "cpu7 84752 3112 31631 2027259 6198 0 1548 0 0 0\n"
        "ctxt 279562310\n"
        "pswpin 186582\n"
        "pwpout 1576740\n"
        "pgmajfault 155971"
    )

    assert NodeExporter.process_kernel_info(
        1700000000,
        [
            ("cpu", cpu_total),
            ("cpu", cpu),
            ("guest", guest_total),
            ("guest", guest),
            ("ctxt", ctxt),
            ("pswpin", pswpin),
            ("pwpout", pwpout),
            ("pgmajfault", pgmajfault),
        ],
    ) == {"minikube": expected}
