[project]
name = "cmk-agent-receiver"
version = "1.0.0"
dependencies = [
    "cryptography~=41.0",
    "fastapi~=0.103.1",
    "gunicorn==20.1.0",
    "python-dateutil==2.8.2",
    "python-multipart==0.0.*",
    "requests~=2.28",
    "uvicorn==0.20.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"cmk.agent_receiver" = ["py.typed"]

[tool.bandit]

[tool.black]
line_length = 100
quiet = true

[tool.isort]
profile = "black"
order_by_type = false
line_length = 100
py_version = 311

[tool.mypy]
explicit_package_bases = true
packages = ["cmk", "tests"]
strict = true
# Miscellaneous stuff not in --strict
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_expr = false
disallow_any_generics = true
disallow_any_unimported = true
disallow_subclassing_any = true
no_implicit_optional = true
strict_optional = true
warn_unreachable = true
# hidden flags for PEP 688 compat, see https://github.com/python/mypy/issues/15313
disable_bytearray_promotion = true
disable_memoryview_promotion = true

[tool.pylint.format]
max-line-length = 100
persistent = "no"
score = "no"

[tool.pylint.messages_control]
disable = "missing-docstring,fixme"

[tool.pytest.ini_options]
pythonpath = [ "." ]
testpaths = [ "cmk", "tests" ]
addopts = "--doctest-modules --import-mode=importlib"
