[project]
name = "cmk-agent-receiver"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-data]
"cmk.agent_receiver" = ["py.typed"]

[tool.bandit]
