#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


def inv_allnet_ip_sensoric(parsed, inventory_tree):

    model = parsed.get("system", {}).get("devicetype")
    if model:
        node = inventory_tree.get_dict("hardware.system.")
        node["model"] = model


inv_info["allnet_ip_sensoric"] = {
    "inv_function": inv_allnet_ip_sensoric,
}
