#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


def parse_docker_container_node_name(info):
    # pylint: disable=undefined-variable
    version = docker_get_version(info)
    if version is None:
        return {"NodeName": parse_legacy_docker_container_node_name(info)}

    return docker_json_get_obj(info[1]) or {}


def inv_docker_container_node_name(info, inventory_tree):
    parsed = parse_docker_container_node_name(info)
    container = inventory_tree.get_dict("software.applications.docker.container.")

    if parsed.get("NodeName") is not None:
        container["node_name"] = parsed["NodeName"]


inv_info['docker_container_node_name'] = {  # pylint: disable=undefined-variable
    'includes': ['docker.include', 'legacy_docker.include'],
    'inv_function': inv_docker_container_node_name,
}
