#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# Example output:
# <<<esx_vsphere_clusters:sep(9)>>>
# datacenter-41  hostsystems VM-Cluster-Clients-Neu  abl-h1-esx84.abl.ads.bayerwald.de
# datacenter-41  vms VM-Cluster-Clients-Neu  abl-h1-w7v232   abl-h1-w7v233   abl-h1-w7v236


def inv_esx_vsphere_clusters(info):
    node = inv_tree_list("software.applications.vmwareesx:")
    datacenters = {}
    for line in info:
        datacenter, what, cluster = line[0:3]
        entries = line[3:]

        datacenters.setdefault(datacenter, {})
        datacenters[datacenter].setdefault(cluster, {})
        datacenters[datacenter][cluster]["name"] = cluster
        datacenters[datacenter][cluster][what] = ", ".join(entries)

    for dc_name, clusters in datacenters.items():
        data = {"name": dc_name, "clusters": []}
        for cluster_name, values in clusters.items():
            cluster_data = {"name": cluster_name}
            cluster_data.update(values)
            data["clusters"].append(cluster_data)
        node.append(data)


inv_info['esx_vsphere_clusters'] = {
    "inv_function": inv_esx_vsphere_clusters,
}
