#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


def inv_suseconnect(parsed, params):
    node = inv_tree("software.os.")

    items = [
        ("starts_at", "License Begin"),
        ("expires_at", "License Expiration"),
        ("regcode", "Registration Code"),
        ("status", "Registration Status"),
        ("subscription_status", "Subscription Status"),
        ("type", "Subscription Type"),
    ]

    for key, description in items:
        node[description] = parsed.get(key, "Unknown")


inv_info["suseconnect"] = {"inv_function": inv_suseconnect}
