UNIXCAT := unixcat
UNIXCAT_PACKAGE := packages/$(UNIXCAT)

UNIXCAT_BUILD := $(BUILD_HELPER_DIR)/unixcat-build
UNIXCAT_INSTALL := $(BUILD_HELPER_DIR)/unixcat-install

.PHONY: $(UNIXCAT_BUILD)
$(UNIXCAT_BUILD):
	$(BAZEL_CMD) build //$(UNIXCAT_PACKAGE)

$(UNIXCAT_INSTALL): $(UNIXCAT_BUILD)
	install -m 755 $(REPO_PATH)/bazel-bin/$(UNIXCAT_PACKAGE)/$(UNIXCAT) $(DESTDIR)/$(OMD_ROOT)/bin/
	$(TOUCH) $@
