#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# mypy: disable-error-code="misc"
# mypy: disable-error-code="no-untyped-call"
# mypy: disable-error-code="no-untyped-def"

from collections.abc import Mapping, Sequence
from typing import Any

import pytest

from cmk.agent_based.v2 import StringTable
from cmk.base.check_legacy_includes import size_trend
from cmk.base.legacy_checks import ibm_svc_mdiskgrp


@pytest.fixture
def empty_value_store(monkeypatch: pytest.MonkeyPatch) -> None:
    store = dict[str, object]()
    monkeypatch.setattr(size_trend, "get_value_store", lambda: store)


@pytest.mark.parametrize(
    "string_table, expected_discoveries",
    [
        (
            [
                [
                    "0",
                    "Quorum_2",
                    "online",
                    "1",
                    "0",
                    "704.00MB",
                    "64",
                    "704.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0",
                    "0",
                    "auto",
                    "inactiv  e",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "1",
                    "stp5_450G_03",
                    "online",
                    "18",
                    "6",
                    "29.43TB",
                    "256",
                    "21.68TB",
                    "8.78TB",
                    "7.73TB",
                    "7.75TB",
                    "29",
                    "80",
                    "auto",
                    "i  nactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "4",
                    "stp5_450G_02",
                    "online",
                    "15",
                    "14",
                    "24.53TB",
                    "256",
                    "277.00GB",
                    "24.26TB",
                    "24.26TB",
                    "24.26TB",
                    "98",
                    "80",
                    "a  uto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "9",
                    "stp6_450G_03",
                    "online",
                    "18",
                    "6",
                    "29.43TB",
                    "256",
                    "21.68TB",
                    "8.78TB",
                    "7.73TB",
                    "7.75TB",
                    "29",
                    "80",
                    "auto",
                    "i  nactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "10",
                    "stp6_450G_02",
                    "online",
                    "15",
                    "14",
                    "24.53TB",
                    "256",
                    "277.00GB",
                    "24.26TB",
                    "24.26TB",
                    "24.26TB",
                    "98",
                    "80",
                    "  auto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "15",
                    "stp6_300G_01",
                    "online",
                    "15",
                    "23",
                    "16.34TB",
                    "256",
                    "472.50GB",
                    "15.88TB",
                    "15.88TB",
                    "15.88TB",
                    "97",
                    "80",
                    "  auto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "16",
                    "stp5_300G_01",
                    "online",
                    "15",
                    "23",
                    "16.34TB",
                    "256",
                    "472.50GB",
                    "15.88TB",
                    "15.88TB",
                    "15.88TB",
                    "97",
                    "80",
                    "  auto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "17",
                    "Quorum_1",
                    "online",
                    "1",
                    "0",
                    "512.00MB",
                    "256",
                    "512.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0",
                    "80",
                    "auto",
                    "inac  tive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "18",
                    "Quorum_0",
                    "online",
                    "1",
                    "0",
                    "512.00MB",
                    "256",
                    "512.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0",
                    "80",
                    "auto",
                    "inac  tive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "21",
                    "stp5_450G_01",
                    "online",
                    "12",
                    "31",
                    "19.62TB",
                    "256",
                    "320.00GB",
                    "19.31TB",
                    "19.31TB",
                    "19.31TB",
                    "98",
                    "0",
                    "a  uto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "22",
                    "stp6_450G_01",
                    "online",
                    "12",
                    "31",
                    "19.62TB",
                    "256",
                    "320.00GB",
                    "19.31TB",
                    "19.31TB",
                    "19.31TB",
                    "98",
                    "0",
                    "a  uto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "23",
                    "stp5_600G_01",
                    "online",
                    "3",
                    "2",
                    "6.54TB",
                    "256",
                    "512.00MB",
                    "6.54TB",
                    "6.54TB",
                    "6.54TB",
                    "99",
                    "80",
                    "auto",
                    "i  nactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "24",
                    "stp6_600G_01",
                    "online",
                    "3",
                    "2",
                    "6.54TB",
                    "256",
                    "512.00MB",
                    "6.54TB",
                    "6.54TB",
                    "6.54TB",
                    "99",
                    "80",
                    "auto",
                    "i  nactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
            ],
            [
                ("Quorum_0", {}),
                ("Quorum_1", {}),
                ("Quorum_2", {}),
                ("stp5_300G_01", {}),
                ("stp5_450G_01", {}),
                ("stp5_450G_02", {}),
                ("stp5_450G_03", {}),
                ("stp5_600G_01", {}),
                ("stp6_300G_01", {}),
                ("stp6_450G_01", {}),
                ("stp6_450G_02", {}),
                ("stp6_450G_03", {}),
                ("stp6_600G_01", {}),
            ],
        ),
    ],
)
def test_discovery_ibm_svc_mdiskgrp(
    string_table: StringTable, expected_discoveries: Sequence[tuple[str, Mapping[str, Any]]]
) -> None:
    """Test discovery function for ibm_svc_mdiskgrp check."""
    parsed = ibm_svc_mdiskgrp.parse_ibm_svc_mdiskgrp(string_table)
    result = list(ibm_svc_mdiskgrp.discover_ibm_svc_mdiskgrp(parsed))
    assert sorted(result) == sorted(expected_discoveries)


@pytest.mark.usefixtures("empty_value_store")
@pytest.mark.parametrize(
    "item, params, string_table, expected_results",
    [
        (
            "Quorum_0",
            {
                "levels": (80.0, 90.0),
                "magic_normsize": 20,
                "levels_low": (50.0, 60.0),
                "trend_range": 24,
                "trend_perfdata": True,
                "show_levels": "onmagic",
                "inodes_levels": (10.0, 5.0),
                "show_inodes": "onlow",
                "show_reserved": False,
            },
            [
                [
                    "0",
                    "Quorum_2",
                    "online",
                    "1",
                    "0",
                    "704.00MB",
                    "64",
                    "704.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0",
                    "0",
                    "auto",
                    "inactiv  e",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "1",
                    "stp5_450G_03",
                    "online",
                    "18",
                    "6",
                    "29.43TB",
                    "256",
                    "21.68TB",
                    "8.78TB",
                    "7.73TB",
                    "7.75TB",
                    "29",
                    "80",
                    "auto",
                    "i  nactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "4",
                    "stp5_450G_02",
                    "online",
                    "15",
                    "14",
                    "24.53TB",
                    "256",
                    "277.00GB",
                    "24.26TB",
                    "24.26TB",
                    "24.26TB",
                    "98",
                    "80",
                    "a  uto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "9",
                    "stp6_450G_03",
                    "online",
                    "18",
                    "6",
                    "29.43TB",
                    "256",
                    "21.68TB",
                    "8.78TB",
                    "7.73TB",
                    "7.75TB",
                    "29",
                    "80",
                    "auto",
                    "i  nactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "10",
                    "stp6_450G_02",
                    "online",
                    "15",
                    "14",
                    "24.53TB",
                    "256",
                    "277.00GB",
                    "24.26TB",
                    "24.26TB",
                    "24.26TB",
                    "98",
                    "80",
                    "  auto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "15",
                    "stp6_300G_01",
                    "online",
                    "15",
                    "23",
                    "16.34TB",
                    "256",
                    "472.50GB",
                    "15.88TB",
                    "15.88TB",
                    "15.88TB",
                    "97",
                    "80",
                    "  auto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "16",
                    "stp5_300G_01",
                    "online",
                    "15",
                    "23",
                    "16.34TB",
                    "256",
                    "472.50GB",
                    "15.88TB",
                    "15.88TB",
                    "15.88TB",
                    "97",
                    "80",
                    "  auto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "17",
                    "Quorum_1",
                    "online",
                    "1",
                    "0",
                    "512.00MB",
                    "256",
                    "512.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0",
                    "80",
                    "auto",
                    "inac  tive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "18",
                    "Quorum_0",
                    "online",
                    "1",
                    "0",
                    "512.00MB",
                    "256",
                    "512.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                    "0",
                    "80",
                    "auto",
                    "inac  tive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "21",
                    "stp5_450G_01",
                    "online",
                    "12",
                    "31",
                    "19.62TB",
                    "256",
                    "320.00GB",
                    "19.31TB",
                    "19.31TB",
                    "19.31TB",
                    "98",
                    "0",
                    "a  uto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "22",
                    "stp6_450G_01",
                    "online",
                    "12",
                    "31",
                    "19.62TB",
                    "256",
                    "320.00GB",
                    "19.31TB",
                    "19.31TB",
                    "19.31TB",
                    "98",
                    "0",
                    "a  uto",
                    "inactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "23",
                    "stp5_600G_01",
                    "online",
                    "3",
                    "2",
                    "6.54TB",
                    "256",
                    "512.00MB",
                    "6.54TB",
                    "6.54TB",
                    "6.54TB",
                    "99",
                    "80",
                    "auto",
                    "i  nactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
                [
                    "24",
                    "stp6_600G_01",
                    "online",
                    "3",
                    "2",
                    "6.54TB",
                    "256",
                    "512.00MB",
                    "6.54TB",
                    "6.54TB",
                    "6.54TB",
                    "99",
                    "80",
                    "auto",
                    "i  nactive",
                    "no",
                    "0.00MB",
                    "0.00MB",
                    "0.00MB",
                ],
            ],
            [
                (
                    0,
                    "Used: 0% - 0 B of 512 MiB",
                    [
                        ("fs_used", 0.0, 409.5999994277954, 460.79999923706055, 0.0, 512.0),
                        ("fs_free", 512.0, None, None, 0.0, None),
                        ("fs_used_percent", 0.0, 79.99999988824129, 89.99999985098839, 0.0, 100.0),
                        ("fs_size", 512.0, None, None, 0, None),
                    ],
                ),
                (0, "Provisioning: 0%", [("fs_provisioning", 0.0, None, None, 0, 536870912.0)]),
            ],
        ),
    ],
)
def test_check_ibm_svc_mdiskgrp(item, params, string_table, expected_results):
    """Test check function for ibm_svc_mdiskgrp check."""
    parsed = ibm_svc_mdiskgrp.parse_ibm_svc_mdiskgrp(string_table)
    result = list(ibm_svc_mdiskgrp.check_ibm_svc_mdiskgrp(item, params, parsed))
    assert result == expected_results
