#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# mypy: disable-error-code="misc"
# mypy: disable-error-code="no-untyped-call"

from collections.abc import Mapping, Sequence
from typing import Any

import pytest

from cmk.agent_based.v2 import StringTable
from cmk.base.legacy_checks.ucs_c_rack_server_psu import (
    check_ucs_c_rack_server_psu,
    discover_ucs_c_rack_server_psu,
    parse_ucs_c_rack_server_psu,
)


@pytest.mark.parametrize(
    "string_table, expected_discoveries",
    [
        (
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [
                ("Rack Unit 1 PSU 1", {}),
                ("Rack Unit 1 PSU 2", {}),
                ("Rack Unit 1 PSU 3", {}),
                ("Rack Unit 1 PSU 4", {}),
                ("Rack Unit 2 PSU 1", {}),
                ("Rack Unit 2 PSU 2", {}),
                ("Rack Unit 2 PSU 3", {}),
                ("Rack Unit 2 PSU 4", {}),
                ("Rack Unit 2 PSU 5", {}),
            ],
        ),
    ],
)
def test_discover_ucs_c_rack_server_psu(
    string_table: StringTable, expected_discoveries: Sequence[tuple[str, Mapping[str, Any]]]
) -> None:
    """Test discovery function for ucs_c_rack_server_psu check."""
    parsed = parse_ucs_c_rack_server_psu(string_table)
    result = list(discover_ucs_c_rack_server_psu(parsed))
    assert sorted(result) == sorted(expected_discoveries)


@pytest.mark.parametrize(
    "item, params, string_table, expected_results",
    [
        (
            "Rack Unit 1 PSU 1",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(0, "Status: operable")],
        ),
        (
            "Rack Unit 1 PSU 2",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(1, "Status: removed")],
        ),
        (
            "Rack Unit 1 PSU 3",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(2, "Status: performance-problem")],
        ),
        (
            "Rack Unit 1 PSU 4",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(0, "Status: operable")],
        ),
        (
            "Rack Unit 2 PSU 1",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(0, "Status: operable")],
        ),
        (
            "Rack Unit 2 PSU 2",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(0, "Status: operable")],
        ),
        (
            "Rack Unit 2 PSU 3",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(0, "Status: operable")],
        ),
        (
            "Rack Unit 2 PSU 4",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(3, "Status: unknown[unknownOperabilityStatus]")],
        ),
        (
            "Rack Unit 2 PSU 5",
            {},
            [
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-2",
                    "id 2",
                    "model blablub",
                    "operability removed",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-3",
                    "id 3",
                    "model blablub",
                    "operability performance-problem",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-1/psu-4",
                    "id 4",
                    "model blablub",
                    "operability operable",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-1",
                    "id 1",
                    "model blablub",
                    "operability operable",
                    "voltage lower-non-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-2",
                    "id 2",
                    "model blablub",
                    "operability operable",
                    "voltage upper-critical",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-3",
                    "id 3",
                    "model blablub",
                    "operability operable",
                    "voltage unkonwn",
                ],
                [
                    "equipmentPsu",
                    "dn sys/rack-unit-2/psu-4",
                    "id 4",
                    "model blablub",
                    "operability unknownOperabilityStatus",
                    "voltage ok",
                ],
                [
                    "equipmentPsu",
                    "id sys/rack-unit-2/psu-5",
                    "id 5",
                    "model blablub",
                    "operability operable",
                    "voltage unknownVoltageStatus",
                ],
            ],
            [(0, "Status: operable")],
        ),
    ],
)
def test_check_ucs_c_rack_server_psu(
    item: str, params: Mapping[str, Any], string_table: StringTable, expected_results: Sequence[Any]
) -> None:
    """Test check function for ucs_c_rack_server_psu check."""
    parsed = parse_ucs_c_rack_server_psu(string_table)
    result = list(check_ucs_c_rack_server_psu(item, params, parsed))
    assert result == expected_results
