#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from collections.abc import Mapping, Sequence
from typing import Any

import pytest

from cmk.agent_based.v1.type_defs import StringTable
from cmk.base.legacy_checks.emcvnx_storage_pools import (
    check_emcvnx_storage_pools,
    inventory_emcvnx_storage_pools,
    parse_emcvnx_storage_pools,
)


@pytest.mark.parametrize(
    "string_table, expected_discoveries",
    [
        (
            [
                ["[[[storage_pools]]]"],
                ["Pool Name", "  Pool 0"],
                ["Pool ID", "  0"],
                ["Raid Type", "  r_5"],
                ["Percent Full Threshold", "  70"],
                ["Description", "  "],
                ["Disk Type", "  SAS"],
                ["State", "  Ready"],
                ["Status", "  OK(0x0)"],
                ["Current Operation", "  None"],
                ["Current Operation State", "  N/A"],
                ["Current Operation Status", "  N/A"],
                ["Current Operation Percent Completed", "  0"],
                ["Raw Capacity (Blocks)", "  40527668736"],
                ["Raw Capacity (GBs)", "  19325.098"],
                ["User Capacity (Blocks)", "  35990175744"],
                ["User Capacity (GBs)", "  17161.453"],
                ["Consumed Capacity (Blocks)", "  20201398272"],
                ["Consumed Capacity (GBs)", "  9632.777"],
                ["Available Capacity (Blocks)", "  15788777472"],
                ["Available Capacity (GBs)", "  7528.676"],
                ["Percent Full", "  56.130"],
                ["LUN Allocation (Blocks)", "  19501416448"],
                ["LUN Allocation (GBs)", "  9299.000"],
                ["Snapshot Allocation (Blocks)", "  0"],
                ["Snapshot Allocation (GBs)", "  0.000"],
                ["Metadata Allocation (Blocks)", "  699981824"],
                ["Metadata Allocation (GBs)", "  333.777"],
                ["Total Subscribed Capacity (Blocks)", "  20201398272"],
                ["Total Subscribed Capacity (GBs)", "  9632.777"],
                ["Percent Subscribed", "  56.130"],
                ["Oversubscribed by (Blocks)", "  0"],
                ["Oversubscribed by (GBs)", "  0.000"],
                ["LUN Subscribed Capacity (Blocks)", "  19501416448"],
                ["LUN Subscribed Capacity (GBs)", "  9299.000"],
                ["Snapshot Subscribed Capacity (Blocks)", "  0"],
                ["Snapshot Subscribed Capacity (GBs)", "  0.000"],
                ["Metadata Subscribed Capacity (Blocks)", "  699981824"],
                ["Metadata Subscribed Capacity (GBs)", "  333.777"],
                ["Compression Savings (Blocks)", "  N/A"],
                ["Compression Savings (GBs)", "  N/A"],
                [""],
                ["Tier Name", "  Performance"],
                ["Raid Type", "  r_5"],
                ["Raid Drive Count", "  9"],
                ["User Capacity (GBs)", "  17161.45"],
                ["Consumed Capacity (GBs)", "  9632.78"],
                ["Available Capacity (GBs)", "  7528.68"],
                ["Percent Subscribed", "  56.13%"],
                ["Disks (Type)", ""],
                ["Bus 1 Enclosure 0 Disk 1 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 8 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 13 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 10 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 7 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 9 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 10 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 12 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 14 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 1 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 3 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 5 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 7 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 9 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 0 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 10 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 7 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 9 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 12 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 3 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 5 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 6 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 8 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 2 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 0 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 11 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 14 (Unknown)"],
                ["Bus 1 Enclosure 0 Disk 6 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 2 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 4 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 11 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 13 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 4 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 6 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 8 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 11 (SAS)"],
                [""],
                ["Rebalance Percent Complete", "  N/A"],
                ["Disks", ""],
                ["Bus 1 Enclosure 0 Disk 1"],
                ["Bus 1 Enclosure 0 Disk 13"],
                ["Bus 1 Enclosure 0 Disk 8"],
                ["Bus 0 Enclosure 1 Disk 10"],
                ["Bus 0 Enclosure 0 Disk 14"],
                ["Bus 0 Enclosure 0 Disk 12"],
                ["Bus 0 Enclosure 0 Disk 10"],
                ["Bus 0 Enclosure 0 Disk 9"],
                ["Bus 0 Enclosure 0 Disk 7"],
                ["Bus 0 Enclosure 1 Disk 9"],
                ["Bus 0 Enclosure 1 Disk 7"],
                ["Bus 0 Enclosure 1 Disk 5"],
                ["Bus 0 Enclosure 1 Disk 3"],
                ["Bus 0 Enclosure 1 Disk 1"],
                ["Bus 0 Enclosure 1 Disk 0"],
                ["Bus 1 Enclosure 0 Disk 10"],
                ["Bus 1 Enclosure 0 Disk 12"],
                ["Bus 1 Enclosure 0 Disk 9"],
                ["Bus 1 Enclosure 0 Disk 7"],
                ["Bus 1 Enclosure 0 Disk 5"],
                ["Bus 1 Enclosure 0 Disk 3"],
                ["Bus 0 Enclosure 0 Disk 8"],
                ["Bus 0 Enclosure 0 Disk 6"],
                ["Bus 0 Enclosure 1 Disk 2"],
                ["Bus 1 Enclosure 0 Disk 0"],
                ["Bus 1 Enclosure 0 Disk 11"],
                ["Bus 1 Enclosure 0 Disk 14"],
                ["Bus 1 Enclosure 0 Disk 6"],
                ["Bus 1 Enclosure 0 Disk 4"],
                ["Bus 1 Enclosure 0 Disk 2"],
                ["Bus 0 Enclosure 0 Disk 13"],
                ["Bus 0 Enclosure 0 Disk 11"],
                ["Bus 0 Enclosure 1 Disk 11"],
                ["Bus 0 Enclosure 1 Disk 8"],
                ["Bus 0 Enclosure 1 Disk 6"],
                ["Bus 0 Enclosure 1 Disk 4"],
                [
                    "LUNs",
                    "  136, 120, 111, 127, 131, 130, 121, 133, 102, 132, 103, 107, 126, 138, 137, 134, 105, 101, 109, 128, 122, 106, 129, 110, 123, 124, 135, 104, 100, 108, 125",
                ],
                ["FAST Cache", "  N/A"],
                ["Auto-Delete Pool Full Threshold Enabled", "  Off"],
                ["Auto-Delete Pool Full High Watermark", "  95.00"],
                ["Auto-Delete Pool Full Low Watermark", "  85.00"],
                ["Auto-Delete Pool Full State", "  Idle"],
                ["Auto-Delete Snapshot Space Used Threshold Enabled", "  Off"],
                ["Auto-Delete Snapshot Space Used High Watermark", "  25.00"],
                ["Auto-Delete Snapshot Space Used Low Watermark", "  20.00"],
                ["Auto-Delete Snapshot Space Used State", "  Idle"],
                [""],
                ["[[[auto_tiering]]]"],
                ["Auto-tiering is not supported on this system."],
                ["Unrecognized option", " (-info)."],
            ],
            [("Pool 0", {})],
        ),
    ],
)
def test_inventory_emcvnx_storage_pools(
    string_table: StringTable, expected_discoveries: Sequence[tuple[str, Mapping[str, Any]]]
) -> None:
    """Test discovery function for emcvnx_storage_pools check."""
    parsed = parse_emcvnx_storage_pools(string_table)
    result = list(inventory_emcvnx_storage_pools(parsed))
    assert sorted(result) == sorted(expected_discoveries)


@pytest.mark.parametrize(
    "item, params, string_table, expected_results",
    [
        (
            "Pool 0",
            {"percent_full": (70.0, 90.0)},
            [
                ["[[[storage_pools]]]"],
                ["Pool Name", "  Pool 0"],
                ["Pool ID", "  0"],
                ["Raid Type", "  r_5"],
                ["Percent Full Threshold", "  70"],
                ["Description", "  "],
                ["Disk Type", "  SAS"],
                ["State", "  Ready"],
                ["Status", "  OK(0x0)"],
                ["Current Operation", "  None"],
                ["Current Operation State", "  N/A"],
                ["Current Operation Status", "  N/A"],
                ["Current Operation Percent Completed", "  0"],
                ["Raw Capacity (Blocks)", "  40527668736"],
                ["Raw Capacity (GBs)", "  19325.098"],
                ["User Capacity (Blocks)", "  35990175744"],
                ["User Capacity (GBs)", "  17161.453"],
                ["Consumed Capacity (Blocks)", "  20201398272"],
                ["Consumed Capacity (GBs)", "  9632.777"],
                ["Available Capacity (Blocks)", "  15788777472"],
                ["Available Capacity (GBs)", "  7528.676"],
                ["Percent Full", "  56.130"],
                ["LUN Allocation (Blocks)", "  19501416448"],
                ["LUN Allocation (GBs)", "  9299.000"],
                ["Snapshot Allocation (Blocks)", "  0"],
                ["Snapshot Allocation (GBs)", "  0.000"],
                ["Metadata Allocation (Blocks)", "  699981824"],
                ["Metadata Allocation (GBs)", "  333.777"],
                ["Total Subscribed Capacity (Blocks)", "  20201398272"],
                ["Total Subscribed Capacity (GBs)", "  9632.777"],
                ["Percent Subscribed", "  56.130"],
                ["Oversubscribed by (Blocks)", "  0"],
                ["Oversubscribed by (GBs)", "  0.000"],
                ["LUN Subscribed Capacity (Blocks)", "  19501416448"],
                ["LUN Subscribed Capacity (GBs)", "  9299.000"],
                ["Snapshot Subscribed Capacity (Blocks)", "  0"],
                ["Snapshot Subscribed Capacity (GBs)", "  0.000"],
                ["Metadata Subscribed Capacity (Blocks)", "  699981824"],
                ["Metadata Subscribed Capacity (GBs)", "  333.777"],
                ["Compression Savings (Blocks)", "  N/A"],
                ["Compression Savings (GBs)", "  N/A"],
                [""],
                ["Tier Name", "  Performance"],
                ["Raid Type", "  r_5"],
                ["Raid Drive Count", "  9"],
                ["User Capacity (GBs)", "  17161.45"],
                ["Consumed Capacity (GBs)", "  9632.78"],
                ["Available Capacity (GBs)", "  7528.68"],
                ["Percent Subscribed", "  56.13%"],
                ["Disks (Type)", ""],
                ["Bus 1 Enclosure 0 Disk 1 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 8 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 13 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 10 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 7 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 9 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 10 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 12 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 14 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 1 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 3 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 5 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 7 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 9 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 0 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 10 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 7 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 9 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 12 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 3 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 5 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 6 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 8 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 2 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 0 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 11 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 14 (Unknown)"],
                ["Bus 1 Enclosure 0 Disk 6 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 2 (SAS)"],
                ["Bus 1 Enclosure 0 Disk 4 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 11 (SAS)"],
                ["Bus 0 Enclosure 0 Disk 13 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 4 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 6 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 8 (SAS)"],
                ["Bus 0 Enclosure 1 Disk 11 (SAS)"],
                [""],
                ["Rebalance Percent Complete", "  N/A"],
                ["Disks", ""],
                ["Bus 1 Enclosure 0 Disk 1"],
                ["Bus 1 Enclosure 0 Disk 13"],
                ["Bus 1 Enclosure 0 Disk 8"],
                ["Bus 0 Enclosure 1 Disk 10"],
                ["Bus 0 Enclosure 0 Disk 14"],
                ["Bus 0 Enclosure 0 Disk 12"],
                ["Bus 0 Enclosure 0 Disk 10"],
                ["Bus 0 Enclosure 0 Disk 9"],
                ["Bus 0 Enclosure 0 Disk 7"],
                ["Bus 0 Enclosure 1 Disk 9"],
                ["Bus 0 Enclosure 1 Disk 7"],
                ["Bus 0 Enclosure 1 Disk 5"],
                ["Bus 0 Enclosure 1 Disk 3"],
                ["Bus 0 Enclosure 1 Disk 1"],
                ["Bus 0 Enclosure 1 Disk 0"],
                ["Bus 1 Enclosure 0 Disk 10"],
                ["Bus 1 Enclosure 0 Disk 12"],
                ["Bus 1 Enclosure 0 Disk 9"],
                ["Bus 1 Enclosure 0 Disk 7"],
                ["Bus 1 Enclosure 0 Disk 5"],
                ["Bus 1 Enclosure 0 Disk 3"],
                ["Bus 0 Enclosure 0 Disk 8"],
                ["Bus 0 Enclosure 0 Disk 6"],
                ["Bus 0 Enclosure 1 Disk 2"],
                ["Bus 1 Enclosure 0 Disk 0"],
                ["Bus 1 Enclosure 0 Disk 11"],
                ["Bus 1 Enclosure 0 Disk 14"],
                ["Bus 1 Enclosure 0 Disk 6"],
                ["Bus 1 Enclosure 0 Disk 4"],
                ["Bus 1 Enclosure 0 Disk 2"],
                ["Bus 0 Enclosure 0 Disk 13"],
                ["Bus 0 Enclosure 0 Disk 11"],
                ["Bus 0 Enclosure 1 Disk 11"],
                ["Bus 0 Enclosure 1 Disk 8"],
                ["Bus 0 Enclosure 1 Disk 6"],
                ["Bus 0 Enclosure 1 Disk 4"],
                [
                    "LUNs",
                    "  136, 120, 111, 127, 131, 130, 121, 133, 102, 132, 103, 107, 126, 138, 137, 134, 105, 101, 109, 128, 122, 106, 129, 110, 123, 124, 135, 104, 100, 108, 125",
                ],
                ["FAST Cache", "  N/A"],
                ["Auto-Delete Pool Full Threshold Enabled", "  Off"],
                ["Auto-Delete Pool Full High Watermark", "  95.00"],
                ["Auto-Delete Pool Full Low Watermark", "  85.00"],
                ["Auto-Delete Pool Full State", "  Idle"],
                ["Auto-Delete Snapshot Space Used Threshold Enabled", "  Off"],
                ["Auto-Delete Snapshot Space Used High Watermark", "  25.00"],
                ["Auto-Delete Snapshot Space Used Low Watermark", "  20.00"],
                ["Auto-Delete Snapshot Space Used State", "  Idle"],
                [""],
                ["[[[auto_tiering]]]"],
                ["Auto-tiering is not supported on this system."],
                ["Unrecognized option", " (-info)."],
            ],
            [
                (
                    0,
                    "State: Ready, Status: OK(0x0), [Phys. capacity] User capacity: 16.8 TiB, Consumed capacity: 9.41 TiB, Available capacity: 7.35 TiB",
                ),
                (0, "Percent full: 56.13%"),
                (
                    0,
                    "[Virt. capacity] Percent subscribed: 56.13%, Oversubscribed by: 0 B, Total subscribed capacity: 9.41 TiB",
                    [
                        ("emcvnx_consumed_capacity", 10343115546165.248),
                        ("emcvnx_avail_capacity", 8083854300545.024),
                        ("emcvnx_perc_full", 56.13),
                        ("emcvnx_perc_subscribed", 56.13),
                        ("emcvnx_over_subscribed", 0.0),
                        ("emcvnx_total_subscribed_capacity", 10343115546165.248),
                    ],
                ),
            ],
        ),
    ],
)
def test_check_emcvnx_storage_pools(
    item: str, params: Mapping[str, Any], string_table: StringTable, expected_results: Sequence[Any]
) -> None:
    """Test check function for emcvnx_storage_pools check."""
    parsed = parse_emcvnx_storage_pools(string_table)
    result = list(check_emcvnx_storage_pools(item, params, parsed))
    assert result == expected_results
