#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from collections.abc import Mapping, Sequence
from typing import Any

import pytest

from cmk.agent_based.v1.type_defs import StringTable
from cmk.base.legacy_checks.ibm_svc_enclosure import (
    check_ibm_svc_enclosure,
    discover_ibm_svc_enclosure,
    parse_ibm_svc_enclosure,
)


@pytest.mark.parametrize(
    "string_table, expected_discoveries",
    [
        (
            [
                [
                    "1",
                    "online",
                    "control",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24C",
                    "7804037",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "2",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804306",
                    "2",
                    "0",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "3",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804326",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "4",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804352",
                    "2",
                    "2",
                    "2",
                    "2",
                    "24",
                ],
            ],
            [("1", {}), ("2", {}), ("3", {}), ("4", {})],
        ),
    ],
)
def test_discover_ibm_svc_enclosure(
    string_table: StringTable, expected_discoveries: Sequence[tuple[str, Mapping[str, Any]]]
) -> None:
    """Test discovery function for ibm_svc_enclosure check."""
    parsed = parse_ibm_svc_enclosure(string_table)
    result = list(discover_ibm_svc_enclosure(parsed))
    assert sorted(result) == sorted(expected_discoveries)


@pytest.mark.parametrize(
    "item, params, string_table, expected_results",
    [
        (
            "1",
            {"levels_lower_online_canisters": (2, 0)},
            [
                [
                    "1",
                    "online",
                    "control",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24C",
                    "7804037",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "2",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804306",
                    "2",
                    "0",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "3",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804326",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "4",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804352",
                    "2",
                    "2",
                    "2",
                    "2",
                    "24",
                ],
            ],
            [
                (0, "Status: online"),
                (1, "Online canisters: 1 (warn/crit below 2/0) of 2"),
                (0, "Online PSUs: 2 of 2"),
            ],
        ),
        (
            "2",
            {"levels_lower_online_canisters": (-1, -1)},
            [
                [
                    "1",
                    "online",
                    "control",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24C",
                    "7804037",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "2",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804306",
                    "2",
                    "0",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "3",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804326",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "4",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804352",
                    "2",
                    "2",
                    "2",
                    "2",
                    "24",
                ],
            ],
            [(0, "Status: online"), (0, "Online canisters: 0 of 2"), (0, "Online PSUs: 2 of 2")],
        ),
        (
            "3",
            {},
            [
                [
                    "1",
                    "online",
                    "control",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24C",
                    "7804037",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "2",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804306",
                    "2",
                    "0",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "3",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804326",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "4",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804352",
                    "2",
                    "2",
                    "2",
                    "2",
                    "24",
                ],
            ],
            [
                (0, "Status: online"),
                (2, "Online canisters: 1 (warn/crit below 2/2) of 2"),
                (0, "Online PSUs: 2 of 2"),
            ],
        ),
        (
            "4",
            {},
            [
                [
                    "1",
                    "online",
                    "control",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24C",
                    "7804037",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "2",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804306",
                    "2",
                    "0",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "3",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804326",
                    "2",
                    "1",
                    "2",
                    "2",
                    "24",
                ],
                [
                    "4",
                    "online",
                    "expansion",
                    "yes",
                    "0",
                    "io_grp0",
                    "2072-24E",
                    "7804352",
                    "2",
                    "2",
                    "2",
                    "2",
                    "24",
                ],
            ],
            [(0, "Status: online"), (0, "Online canisters: 2 of 2"), (0, "Online PSUs: 2 of 2")],
        ),
    ],
)
def test_check_ibm_svc_enclosure(
    item: str, params: Mapping[str, Any], string_table: StringTable, expected_results: Sequence[Any]
) -> None:
    """Test check function for ibm_svc_enclosure check."""
    parsed = parse_ibm_svc_enclosure(string_table)
    result = list(check_ibm_svc_enclosure(item, params, parsed))
    assert result == expected_results
