#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# mypy: disable-error-code="no-untyped-call"

from collections.abc import Mapping, Sequence
from typing import Any

import pytest

from cmk.agent_based.v1.type_defs import StringTable
from cmk.base.legacy_checks.ibm_svc_node import (
    check_ibm_svc_node,
    discover_ibm_svc_node,
    parse_ibm_svc_node,
)


@pytest.mark.parametrize(
    "string_table, expected_discoveries",
    [
        (
            [
                [
                    "1",
                    "N1_164191",
                    "10001AA202",
                    "500507680100D7CA",
                    "online",
                    "0",
                    "io_grp0",
                    "no",
                    "2040000051442002",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n1164191",
                    "",
                    "164191",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "2",
                    "N2_164373",
                    "10001AA259",
                    "500507680100D874",
                    "online",
                    "0",
                    "io_grp0",
                    "no",
                    "2040000051442149",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n2164373",
                    "",
                    "164373",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "5",
                    "N3_162711",
                    "100025E317",
                    "500507680100D0A7",
                    "online",
                    "1",
                    "io_grp1",
                    "no",
                    "2040000085543047",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n3162711",
                    "",
                    "162711",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "6",
                    "N4_164312",
                    "100025E315",
                    "500507680100D880",
                    "online",
                    "1",
                    "io_grp1",
                    "yes",
                    "2040000085543045",
                    "CG  8",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n4164312",
                    "",
                    "164312",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            ],
            [("io_grp0", {}), ("io_grp1", {})],
        ),
    ],
)
def test_discover_ibm_svc_node(
    string_table: StringTable, expected_discoveries: Sequence[tuple[str, Mapping[str, Any]]]
) -> None:
    """Test discovery function for ibm_svc_node check."""
    parsed = parse_ibm_svc_node(string_table)
    result = list(discover_ibm_svc_node(parsed))
    assert sorted(result) == sorted(expected_discoveries)


@pytest.mark.parametrize(
    "item, params, string_table, expected_results",
    [
        (
            "io_grp0",
            {},
            [
                [
                    "1",
                    "N1_164191",
                    "10001AA202",
                    "500507680100D7CA",
                    "online",
                    "0",
                    "io_grp0",
                    "no",
                    "2040000051442002",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n1164191",
                    "",
                    "164191",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "2",
                    "N2_164373",
                    "10001AA259",
                    "500507680100D874",
                    "online",
                    "0",
                    "io_grp0",
                    "no",
                    "2040000051442149",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n2164373",
                    "",
                    "164373",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "5",
                    "N3_162711",
                    "100025E317",
                    "500507680100D0A7",
                    "online",
                    "1",
                    "io_grp1",
                    "no",
                    "2040000085543047",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n3162711",
                    "",
                    "162711",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "6",
                    "N4_164312",
                    "100025E315",
                    "500507680100D880",
                    "online",
                    "1",
                    "io_grp1",
                    "yes",
                    "2040000085543045",
                    "CG  8",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n4164312",
                    "",
                    "164312",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            ],
            [(0, "Node N1_164191 is online, Node N2_164373 is online")],
        ),
        (
            "io_grp1",
            {},
            [
                [
                    "1",
                    "N1_164191",
                    "10001AA202",
                    "500507680100D7CA",
                    "online",
                    "0",
                    "io_grp0",
                    "no",
                    "2040000051442002",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n1164191",
                    "",
                    "164191",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "2",
                    "N2_164373",
                    "10001AA259",
                    "500507680100D874",
                    "online",
                    "0",
                    "io_grp0",
                    "no",
                    "2040000051442149",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n2164373",
                    "",
                    "164373",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "5",
                    "N3_162711",
                    "100025E317",
                    "500507680100D0A7",
                    "online",
                    "1",
                    "io_grp1",
                    "no",
                    "2040000085543047",
                    "CG8  ",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n3162711",
                    "",
                    "162711",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
                [
                    "6",
                    "N4_164312",
                    "100025E315",
                    "500507680100D880",
                    "online",
                    "1",
                    "io_grp1",
                    "yes",
                    "2040000085543045",
                    "CG  8",
                    "iqn.1986-03.com.ibm",
                    "2145.svc-cl.n4164312",
                    "",
                    "164312",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            ],
            [(0, "Node N3_162711 is online, Node N4_164312 is online")],
        ),
    ],
)
def test_check_ibm_svc_node(
    item: str, params: Mapping[str, Any], string_table: StringTable, expected_results: Sequence[Any]
) -> None:
    """Test check function for ibm_svc_node check."""
    parsed = parse_ibm_svc_node(string_table)
    result = list(check_ibm_svc_node(item, params, parsed))
    assert result == expected_results
