MK_LIVESTATUS := mk-livestatus
MK_LIVESTATUS_DIR := $(MK_LIVESTATUS)-$(CMK_VERSION)

# Attention: copy-n-paste from check_mk/Makefile below...
MK_LIVESTATUS_BUILD := $(BUILD_HELPER_DIR)/$(MK_LIVESTATUS_DIR)-build
MK_LIVESTATUS_UNPACK := $(BUILD_HELPER_DIR)/$(MK_LIVESTATUS_DIR)-unpack
MK_LIVESTATUS_INSTALL := $(BUILD_HELPER_DIR)/$(MK_LIVESTATUS_DIR)-install
MK_LIVESTATUS_PACKAGE := $(PACKAGE_DIR)/$(MK_LIVESTATUS)/$(MK_LIVESTATUS_DIR).tar.gz

.PHONY: $(MK_LIVESTATUS) $(MK_LIVESTATUS)-build $(MK_LIVESTATUS)-install $(MK_LIVESTATUS)-skel $(MK_LIVESTATUS)-clean

$(MK_LIVESTATUS): $(MK_LIVESTATUS_BUILD)
$(MK_LIVESTATUS)-install: $(MK_LIVESTATUS_INSTALL)
$(MK_LIVESTATUS)-build: $(MK_LIVESTATUS_BUILD)

$(MK_LIVESTATUS_PACKAGE):
	$(MAKE) -C $(REPO_PATH) omd/packages/mk-livestatus/$(MK_LIVESTATUS_DIR).tar.gz

$(MK_LIVESTATUS_UNPACK): $(MK_LIVESTATUS_PACKAGE)
	$(RM) -r $*
	$(MKDIR) $(BUILD_HELPER_DIR)
	$(TAR_GZ) $<
	$(TOUCH) $@

$(MK_LIVESTATUS_BUILD): $(MK_LIVESTATUS_UNPACK) $(RE2_BUILD)
	cd $(MK_LIVESTATUS_DIR) ; \
	    ./configure CXXFLAGS="-g -O3 -Wall -Wextra" --with-re2=$(PACKAGE_RE2_DESTDIR) --prefix=$(OMD_ROOT)
	$(MAKE) -C $(MK_LIVESTATUS_DIR) PACKAGE_GOOGLETEST=$(PACKAGE_DIR)/googletest PACKAGE_ASIO=$(PACKAGE_DIR)/asio all
	$(TOUCH) $@

$(MK_LIVESTATUS_INSTALL): $(MK_LIVESTATUS_BUILD)
	$(MAKE) -j1 DESTDIR=$(DESTDIR) -C $(MK_LIVESTATUS_DIR) PACKAGE_GOOGLETEST=$(PACKAGE_DIR)/googletest PACKAGE_ASIO=$(PACKAGE_DIR)/asio install
	$(MKDIR) $(DESTDIR)$(OMD_ROOT)/bin
	install -m 755 $(PACKAGE_DIR)/$(MK_LIVESTATUS)/lq $(DESTDIR)$(OMD_ROOT)/bin
	$(MKDIR) $(DESTDIR)$(OMD_ROOT)/lib/python
	install -m 644 $(MK_LIVESTATUS_DIR)/api/python/livestatus.py $(DESTDIR)$(OMD_ROOT)/lib/python
	install -m 755 $(PACKAGE_DIR)/$(MK_LIVESTATUS)/LIVESTATUS_TCP $(DESTDIR)$(OMD_ROOT)/lib/omd/hooks/
	install -m 755 $(PACKAGE_DIR)/$(MK_LIVESTATUS)/LIVESTATUS_TCP_ONLY_FROM $(DESTDIR)$(OMD_ROOT)/lib/omd/hooks/
	install -m 755 $(PACKAGE_DIR)/$(MK_LIVESTATUS)/LIVESTATUS_TCP_PORT $(DESTDIR)$(OMD_ROOT)/lib/omd/hooks/
	install -m 755 $(PACKAGE_DIR)/$(MK_LIVESTATUS)/LIVESTATUS_TCP_TLS $(DESTDIR)$(OMD_ROOT)/lib/omd/hooks/
	$(TOUCH) $@

$(MK_LIVESTATUS)-skel:

$(MK_LIVESTATUS)-clean:
	$(RM) -r mk-livestatus-*.*.*[0-9] $(BUILD_HELPER_DIR)/$(MK_LIVESTATUS)*
