#!/usr/bin/env python3
# Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from contextlib import suppress
from logging import Logger
from pathlib import Path
from typing import override

from cmk.update_config.lib import ExpiryVersion
from cmk.update_config.registry import update_action_registry, UpdateAction
from cmk.utils.paths import omd_root


def remove_nagios_share(root: Path, logger: Logger) -> None:
    for path in [
        root / "local/share/nagios/htdocs/theme/images",
        root / "local/share/nagios/htdocs/theme/stylesheets",
    ]:
        if path.is_symlink():
            path.unlink()
            logger.info(f"Removed symlink: {path}")
    for path in [
        root / "local/share/nagios/htdocs/theme",
        root / "local/share/nagios/htdocs/",
        root / "local/share/nagios/",
    ]:
        with suppress(OSError):
            path.rmdir()
            logger.info(f"Removed empty directory: {path}")


class RemoveNagiosShare(UpdateAction):
    @override
    def __call__(self, logger: Logger) -> None:
        remove_nagios_share(omd_root, logger)


update_action_registry.register(
    RemoveNagiosShare(
        name="remove_nagios_share",
        title="Remove autogenerated local/share/nagios/",
        sort_index=33,  # Does not matter.
        expiry_version=ExpiryVersion.CMK_260,
    )
)
