#!/usr/bin/env python3
# Copyright (C) 2022 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from typing import Final

AZURE_REGIONS: Final = {
    "eastus": "East US",
    "eastus2": "East US 2",
    "centralus": "Central US",
    "northcentralus": "North Central US",
    "southcentralus": "South Central US",
    "westcentralus": "West Central US",
    "westus": "West US",
    "westus2": "West US 2",
    "westus3": "West US 3",
    "canadaeast": "Canada East",
    "canadacentral": "Canada Central",
    "brazilsouth": "Brazil South",
    "brazilsoutheast": "Brazil Southeast",
    "northeurope": "North Europe",
    "westeurope": "West Europe",
    "francecentral": "France Central",
    "francesouth": "France South",
    "ukwest": "UK West",
    "uksouth": "UK South",
    "switzerlandnorth": "Switzerland North",
    "switzerlandwest": "Switzerland West",
    "norwayeast": "Norway East",
    "norwaywest": "Norway West",
    "germanynorth": "Germany North",
    "germanywestcentral": "Germany West Central",
    "swedencentral": "Sweden Central",
    "swedensouth": "Sweden South",
    "southeastasia": "Southeast Asia",
    "eastasia": "East Asia",
    "australiaeast": "Australia East",
    "australiasoutheast": "Australia Southeast",
    "australiacentral": "Australia Central",
    "australiacentral2": "Australia Central 2",
    "centralindia": "Central India",
    "westindia": "West India",
    "southindia": "South India",
    "japaneast": "Japan East",
    "japanwest": "Japan West",
    "koreacentral": "Korea Central",
    "koreasouth": "Korea South",
    "southafricawest": "South Africa West",
    "southafricanorth": "South Africa North",
    "uaecentral": "UAE Central",
    "uaenorth": "UAE North",
    "qatarcentral": "Qatar Central",
    "usgovvirginia": "US Gov Virginia",
    "usgovarizona": "US Gov Arizona",
    "usgovtexas": "US Gov Texas",
    "usdodeast": "US DoD East",
    "usdodcentral": "US DoD Central",
    "chinaeast": "China East",
    "chinaeast2": "China East 2",
    "chinanorth": "China North",
    "chinanorth2": "China North 2",
    "chinanorth3": "China North 3",
    "jioindiawest": "Jio India West",
    "jioindiacentral": "Jio India Central",
}
