type = "Component"
display_name = "Plugins: H3C"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["mohamed.saleh@checkmk.com"]
description = """
Plugins for H3C/HPE FlexNetwork LAN switches.
"""
