type = "Component"
display_name = "Plugins: Libelle Business Shadow"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["andrea.vaccaro@checkmk.com"]
description = """
Plugin for Libelle Business Shadow disaster-recovery replication.
"""
