#!/usr/bin/env python3
# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

import pytest

from cmk.ccc.version import Edition
from cmk.gui import main_modules
from cmk.gui.views.inventory._display_hints import inv_display_hints


@pytest.fixture(scope="module", autouse=True)
def _load_gui_plugins() -> None:
    """Run the gui edition's full plug-in registration chain so the inv-UI
    registry is populated with the production set the snapshots assert on.
    """
    main_modules.register(Edition.COMMUNITY)


_KNOWN_ATTRIBUTES_KEY_ORDERS = {
    ("networking", "interfaces"): [
        "is_show_more",
    ],
    ("hardware", "cpu"): [
        "arch",
        "max_speed",
        "model",
        "type",
        "threads",
        "smt_threads",
        "cpu_max_capa",
        "cpus",
        "logical_cpus",
        "cores",
        "cores_per_cpu",
        "threads_per_cpu",
        "cache_size",
        "bus_speed",
        "voltage",
        "sharing_mode",
        "implementation_mode",
        "entitlement",
    ],
    ("hardware", "memory"): ["total_ram_usable", "total_swap", "total_vmalloc"],
    ("hardware", "system"): [
        "manufacturer",
        "product",
        "serial",
        "model",
        "node_name",
        "partition_name",
        "expresscode",
        "pki_appliance_version",
        "device_number",
        "description",
        "mac_address",
        "type",
        "software_version",
        "license_key_list",
        "model_name",
        "serial_number",
    ],
    ("hardware", "uploaded_files"): ["call_progress_tones"],
    ("hardware", "storage", "controller"): ["version"],
    ("software", "applications", "check_mk"): ["num_hosts", "num_services"],
    ("software", "applications", "check_mk", "cluster"): ["is_cluster"],
    ("software", "applications", "checkmk-agent"): [
        "version",
        "agentdirectory",
        "datadirectory",
        "spooldirectory",
        "pluginsdirectory",
        "localdirectory",
        "agentcontroller",
    ],
    ("software", "applications", "docker"): [
        "version",
        "registry",
        "swarm_state",
        "swarm_node_id",
        "num_containers_total",
        "num_containers_running",
        "num_containers_stopped",
        "num_containers_paused",
        "num_images",
    ],
    ("software", "applications", "docker", "container"): ["node_name"],
    ("software", "applications", "fritz"): [
        "link_type",
        "wan_access_type",
        "auto_disconnect_time",
        "dns_server_1",
        "dns_server_2",
        "voip_dns_server_1",
        "voip_dns_server_2",
        "upnp_config_enabled",
    ],
    ("software", "applications", "kube", "metadata"): ["object", "name", "namespace"],
    ("software", "applications", "kube", "cluster"): ["version"],
    ("software", "applications", "kube", "deployment"): [
        "strategy",
        "match_labels",
        "match_expressions",
    ],
    ("software", "applications", "kube", "daemonset"): [
        "strategy",
        "match_labels",
        "match_expressions",
    ],
    ("software", "applications", "kube", "statefulset"): [
        "strategy",
        "match_labels",
        "match_expressions",
    ],
    ("software", "applications", "kube", "node"): [
        "operating_system",
        "os_image",
        "kernel_version",
        "architecture",
        "container_runtime_version",
        "kubelet_version",
    ],
    ("software", "applications", "kube", "pod"): [
        "dns_policy",
        "host_ip",
        "host_network",
        "node",
        "pod_ip",
        "qos_class",
    ],
    ("software", "applications", "podman"): [
        "mode",
        "version",
        "registry",
        "containers_running",
        "containers_paused",
        "containers_stopped",
        "containers_exited",
        "images_num",
    ],
    ("software", "applications", "podman", "container"): [
        "hostname",
        "pod",
        "labels",
    ],
    ("software", "applications", "podman", "network"): [
        "ip_address",
        "gateway",
        "mac_address",
    ],
    ("software", "applications", "proxmox_ve", "metadata"): ["object", "provider", "name", "node"],
    ("software", "applications", "proxmox_ve", "cluster"): ["cluster"],
    ("software", "applications", "mobileiron"): ["partition_name", "registration_state"],
    ("software", "applications", "citrix", "controller"): ["controller_version"],
    ("software", "applications", "citrix", "vm"): [
        "desktop_group_name",
        "catalog",
        "agent_version",
    ],
    ("software", "applications", "ibm_mq"): ["managers", "channels", "queues"],
    ("software", "bios"): ["vendor", "version", "date"],
    ("software", "configuration", "snmp_info"): ["contact", "location", "name"],
    ("software", "configuration", "organisation"): [
        "organisation_id",
        "organisation_name",
        "network_id",
        "network_name",
        "address",
    ],
    ("software", "firmware"): ["vendor", "version", "platform_level"],
    ("software", "os"): [
        "name",
        "version",
        "vendor",
        "type",
        "install_date",
        "kernel_version",
        "arch",
        "service_pack",
        "build",
    ],
    ("networking",): [
        "hostname",
        "total_interfaces",
        "total_ethernet_ports",
        "available_ethernet_ports",
    ],
    ("hardware", "storage", "disks"): ["size"],
    ("software", "applications", "azure", "metadata"): [
        "object",
        "name",
        "entity",
        "resource_group",
        "subscription_id",
        "subscription_name",
        "region",
        "tenant_id",
        "tenant_name",
    ],
}

_KNOWN_COLUMNS_KEY_ORDERS = {
    ("hardware", "cpu", "nodes"): ["node_name", "cores", "model"],
    ("hardware", "firmware", "redfish"): [
        "component",
        "version",
        "location",
        "description",
        "updateable",
    ],
    ("hardware", "memory", "arrays"): ["maximum_capacity"],
    ("hardware", "memory", "arrays", "devices"): [
        "index",
        "locator",
        "bank_locator",
        "type",
        "form_factor",
        "speed",
        "data_width",
        "total_width",
        "manufacturer",
        "serial",
        "size",
    ],
    ("hardware", "system", "nodes"): ["node_name", "id", "model", "product", "serial"],
    ("hardware", "components", "others"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "components", "unknowns"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "components", "chassis"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "components", "backplanes"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "components", "containers"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "components", "psus"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "components", "fans"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "components", "sensors"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "components", "modules"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "model",
        "manufacturer",
        "bootloader",
        "firmware",
        "type",
        "location",
        "ha_status",
        "software_version",
        "license_key_list",
    ],
    ("hardware", "components", "stacks"): [
        "index",
        "name",
        "description",
        "software",
        "serial",
        "manufacturer",
        "model",
        "location",
    ],
    ("hardware", "storage", "disks"): [
        "fsnode",
        "controller",
        "signature",
        "bus",
        "drive_index",
        "local",
        "product",
        "serial",
        "size",
        "type",
        "vendor",
    ],
    ("hardware", "volumes", "physical_volumes"): [
        "volume_group_name",
        "physical_volume_name",
        "physical_volume_status",
        "physical_volume_total_partitions",
        "physical_volume_free_partitions",
    ],
    ("hardware", "video"): [
        "slot",
        "name",
        "subsystem",
        "driver",
        "driver_version",
        "driver_date",
        "graphic_memory",
    ],
    ("hardware", "nwadapter"): [
        "name",
        "type",
        "macaddress",
        "speed",
        "gateway",
        "ipv4_address",
        "ipv6_address",
        "ipv4_subnet",
        "ipv6_subnet",
    ],
    ("software", "applications", "check_mk", "versions"): [
        "version",
        "number",
        "edition",
        "demo",
        "num_sites",
    ],
    ("software", "applications", "check_mk", "sites"): [
        "site",
        "used_version",
        "num_hosts",
        "num_services",
        "check_mk_helper_usage",
        "fetcher_helper_usage",
        "checker_helper_usage",
        "livestatus_usage",
        "check_helper_usage",
        "autostart",
        "apache",
        "cmc",
        "crontab",
        "dcd",
        "liveproxyd",
        "mkeventd",
        "mknotifyd",
        "rrdcached",
        "stunnel",
        "xinetd",
        "nagios",
        "npcd",
    ],
    ("software", "applications", "check_mk", "cluster", "nodes"): ["name"],
    ("software", "applications", "checkmk-agent", "plugins"): ["name", "version", "cache_interval"],
    ("software", "applications", "checkmk-agent", "local_checks"): [
        "name",
        "version",
        "cache_interval",
    ],
    ("software", "applications", "docker", "node_labels"): ["label"],
    ("software", "applications", "docker", "swarm_manager"): ["NodeID", "Addr"],
    ("software", "applications", "docker", "images"): [
        "id",
        "creation",
        "size",
        "labels",
        "amount_containers",
        "repotags",
        "repodigests",
    ],
    ("software", "applications", "docker", "containers"): [
        "id",
        "creation",
        "name",
        "labels",
        "status",
        "image",
    ],
    ("software", "applications", "docker", "networks"): [
        "network_id",
        "short_id",
        "name",
        "scope",
        "labels",
    ],
    ("software", "applications", "docker", "container", "ports"): [
        "port",
        "protocol",
        "host_addresses",
    ],
    ("software", "applications", "docker", "container", "networks"): [
        "name",
        "ip_address",
        "ip_prefixlen",
        "gateway",
        "mac_address",
        "network_id",
    ],
    ("software", "applications", "docker", "networks", "containers"): [
        "network_id",
        "id",
        "name",
        "ipv4_address",
        "ipv6_address",
        "mac_address",
    ],
    ("software", "applications", "fortinet", "fortisandbox"): ["name", "version"],
    ("software", "applications", "kube", "labels"): ["label_name", "label_value"],
    ("networking", "kube"): ["ip", "address_type"],
    ("software", "applications", "kube", "containers"): [
        "name",
        "ready",
        "restart_count",
        "image",
        "image_pull_policy",
        "image_id",
        "container_id",
    ],
    ("software", "applications", "synthetic_monitoring", "plans"): [
        "application",
        "suite_name",
        "variant",
        "plan_id",
    ],
    ("software", "applications", "synthetic_monitoring", "scheduler", "config"): [
        "scheduler_interval",
        "env_creation",
        "n_attempts_max",
        "robot_type",
        "assigned_to_host",
        "plan_id",
    ],
    ("software", "applications", "synthetic_monitoring", "tests"): [
        "application",
        "suite_name",
        "variant",
        "top_level_suite_name",
        "bottom_level_suite_name",
        "test_name",
        "plan_id",
        "test_item",
    ],
    ("software", "applications", "oracle", "systemparameter"): [
        "sid",
        "name",
        "value",
        "isdefault",
    ],
    ("software", "applications", "oracle", "instance"): [
        "sid",
        "pname",
        "version",
        "openmode",
        "logmode",
        "logins",
        "db_uptime",
        "db_creation_time",
    ],
    ("software", "applications", "oracle", "dataguard_stats"): [
        "sid",
        "db_unique",
        "role",
        "switchover",
    ],
    ("software", "applications", "oracle", "recovery_area"): ["sid", "flashback"],
    ("software", "applications", "oracle", "sga"): [
        "sid",
        "fixed_size",
        "redo_buffer",
        "buf_cache_size",
        "in_mem_area_size",
        "shared_pool_size",
        "large_pool_size",
        "java_pool_size",
        "streams_pool_size",
        "shared_io_pool_size",
        "data_trans_cache_size",
        "granule_size",
        "max_size",
        "start_oh_shared_pool",
        "free_mem_avail",
    ],
    ("software", "applications", "oracle", "pga"): [
        "sid",
        "aggregate_pga_auto_target",
        "aggregate_pga_target_parameter",
        "bytes_processed",
        "extra_bytes_read_written",
        "global_memory_bound",
        "maximum_pga_allocated",
        "maximum_pga_used_for_auto_workareas",
        "maximum_pga_used_for_manual_workareas",
        "total_pga_allocated",
        "total_pga_inuse",
        "total_pga_used_for_auto_workareas",
        "total_pga_used_for_manual_workareas",
        "total_freeable_pga_memory",
    ],
    ("software", "applications", "oracle", "tablespaces"): [
        "sid",
        "name",
        "version",
        "type",
        "autoextensible",
        "current_size",
        "max_size",
        "used_size",
        "num_increments",
        "increment_size",
        "free_space",
    ],
    ("software", "applications", "mssql", "instances"): [
        "name",
        "product",
        "edition",
        "version",
        "clustered",
        "cluster_name",
        "active_node",
        "node_names",
    ],
    ("software", "applications", "ibm_mq", "managers"): [
        "name",
        "instver",
        "instname",
        "status",
        "standby",
        "ha",
    ],
    ("software", "applications", "ibm_mq", "channels"): [
        "qmgr",
        "name",
        "type",
        "status",
        "monchl",
    ],
    ("software", "applications", "ibm_mq", "queues"): [
        "qmgr",
        "name",
        "maxdepth",
        "maxmsgl",
        "created",
        "altered",
        "monq",
    ],
    ("software", "applications", "azure", "application_gateways", "rules", "listeners"): [
        "application_gateway",
        "rule",
        "listener",
        "protocol",
        "port",
        "host_names",
    ],
    (
        "software",
        "applications",
        "azure",
        "application_gateways",
        "rules",
        "listeners",
        "private_ips",
    ): ["application_gateway", "rule", "listener", "ip_address", "allocation_method"],
    (
        "software",
        "applications",
        "azure",
        "application_gateways",
        "rules",
        "listeners",
        "public_ips",
    ): [
        "application_gateway",
        "rule",
        "listener",
        "name",
        "location",
        "ip_address",
        "allocation_method",
        "dns_fqdn",
    ],
    ("software", "applications", "azure", "application_gateways", "rules", "backends"): [
        "application_gateway",
        "rule",
        "address_pool_name",
        "protocol",
        "port",
    ],
    ("software", "applications", "azure", "load_balancers", "inbound_nat_rules"): [
        "load_balancer",
        "inbound_nat_rule",
        "frontend_port",
        "backend_port",
    ],
    ("software", "applications", "azure", "load_balancers", "inbound_nat_rules", "public_ips"): [
        "load_balancer",
        "inbound_nat_rule",
        "location",
        "public_ip_name",
        "ip_address",
        "ip_allocation_method",
        "dns_fqdn",
    ],
    ("software", "applications", "azure", "load_balancers", "inbound_nat_rules", "private_ips"): [
        "load_balancer",
        "inbound_nat_rule",
        "ip_address",
        "ip_allocation_method",
    ],
    (
        "software",
        "applications",
        "azure",
        "load_balancers",
        "inbound_nat_rules",
        "backend_ip_configs",
    ): [
        "load_balancer",
        "inbound_nat_rule",
        "backend_ip_config",
        "ip_address",
        "ip_allocation_method",
    ],
    ("software", "applications", "azure", "load_balancers", "outbound_rules"): [
        "load_balancer",
        "outbound_rule",
        "protocol",
        "idle_timeout",
    ],
    ("software", "applications", "azure", "load_balancers", "outbound_rules", "backend_pools"): [
        "load_balancer",
        "outbound_rule",
        "backend_pool",
    ],
    (
        "software",
        "applications",
        "azure",
        "load_balancers",
        "outbound_rules",
        "backend_pools",
        "addresses",
    ): [
        "load_balancer",
        "outbound_rule",
        "backend_pool",
        "address_name",
        "ip_address",
        "ip_allocation_method",
        "primary",
    ],
    ("software", "kernel_config"): ["name", "value"],
    ("software", "os", "service_packs"): ["name"],
    ("software", "packages"): [
        "name",
        "arch",
        "package_type",
        "summary",
        "version",
        "vendor",
        "package_version",
        "install_date",
        "size",
        "path",
    ],
    ("networking", "addresses"): [
        "address",
        "device",
        "type",
        "network",
        "netmask",
        "prefixlength",
        "broadcast",
        "scope_id",
    ],
    ("networking", "cdp_cache", "neighbors"): [
        "neighbor_name",
        "neighbor_port",
        "local_port",
        "neighbor_address",
        "neighbor_id",
        "platform",
        "platform_details",
        "capabilities",
        "duplex",
        "native_vlan",
        "vtp_mgmt_domain",
        "power_consumption",
    ],
    ("networking", "interfaces"): [
        "index",
        "name",
        "description",
        "alias",
        "oper_status",
        "admin_status",
        "available",
        "speed",
        "last_change",
        "port_type",
        "phys_address",
        "vlantype",
        "vlans",
    ],
    ("networking", "lldp_cache"): [
        "local_cap_supported",
        "local_cap_enabled",
    ],
    ("networking", "lldp_cache", "neighbors"): [
        "neighbor_name",
        "neighbor_port",
        "local_port",
        "neighbor_address",
        "neighbor_id",
        "system_description",
        "port_description",
        "capabilities",
        "capabilities_map_supported",
    ],
    ("networking", "routes"): ["target", "device", "type", "gateway"],
    ("networking", "uplinks"): [
        "interface",
        "protocol",
        "address",
        "gateway",
        "public_address",
        "assignment_mode",
    ],
    ("networking", "wlan", "controller", "accesspoints"): [
        "name",
        "group",
        "ip_addr",
        "model",
        "serial",
        "sys_location",
    ],
    ("networking", "tunnels"): [
        "peername",
        "index",
        "peerip",
        "sourceip",
        "tunnelinterface",
        "linkpriority",
    ],
    ("networking", "sip_interfaces"): [
        "index",
        "name",
        "application_type",
        "sys_interface",
        "device",
        "tcp_port",
        "gateway",
    ],
    ("software", "applications", "vmwareesx"): ["clusters"],
    ("software", "applications", "podman", "containers"): [
        "id",
        "creation",
        "name",
        "labels",
        "status",
        "image",
    ],
    ("software", "applications", "podman", "images"): [
        "id",
        "creation",
        "size",
        "container_num",
        "repository",
        "tag",
    ],
    ("software", "applications", "cisco_meraki", "licenses"): [
        "org_id",
        "org_name",
        "summary",
        "gateway_mg_count",
        "wireless_mr_count",
        "switch_ms_count",
        "sensor_mt_count",
        "video_mv_count",
        "security_mx_count",
        "systems_manager_sm_count",
        "other_count",
    ],
    ("software", "applications", "cisco_meraki", "networks"): [
        "org_id",
        "org_name",
        "network_id",
        "network_name",
        "time_zone",
        "product_types",
        "tags",
        "notes",
        "enrollment_string",
        "is_bound_to_template",
        "url",
    ],
    ("software", "applications", "cisco_meraki", "organisations"): [
        "org_id",
        "org_name",
        "api_status",
        "licensing_model",
        "cloud_region",
        "url",
    ],
}


def test_related_display_hints() -> None:
    all_paths = [h.path for h in inv_display_hints]
    for hint in inv_display_hints:
        assert all(hint.path[:idx] in all_paths for idx in range(1, len(hint.path)))
        assert _KNOWN_ATTRIBUTES_KEY_ORDERS.get(hint.path, []) == list(hint.attributes), hint.path
        assert _KNOWN_COLUMNS_KEY_ORDERS.get(hint.path, []) == list(hint.table.columns), hint.path
