#!/usr/bin/env python3
# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

import pytest

from cmk.gui.watolib.config_domain_name import (
    config_variable_group_registry,
    config_variable_registry,
)


@pytest.mark.usefixtures("load_gui_plugins")
def test_registered_configvars() -> None:
    expected_vars = [
        "actions",
        "adhoc_downtime",
        "apache_process_tuning",
        "archive_orphans",
        "auth_by_http_header",
        "automatic_crash_report_upload",
        "builtin_icon_visibility",
        "bulk_discovery_default_settings",
        "check_mk_perfdata_with_times",
        "cluster_max_cachefile_age",
        "crash_report_target",
        "crash_report_url",
        "custom_service_attributes",
        "debug",
        "debug_livestatus_queries",
        "debug_rules",
        "default_user_profile",
        "default_bi_layout",
        "default_dynamic_visual_permission",
        "delay_precompile",
        "diskspace_cleanup",
        "enable_sounds",
        "escape_plugin_output",
        "event_limit",
        "eventsocket_queue_len",
        "exp_ai_assistant",
        "exp_relay_active_checks",
        "exp_trial_mode_selection",
        "failed_notification_horizon",
        "hard_query_limit",
        "history_lifetime",
        "history_rotation",
        "hostname_translation",
        "housekeeping_interval",
        "sqlite_housekeeping_interval",
        "sqlite_freelist_size",
        "user_security_notification_duration",
        "http_proxies",
        "inventory_check_autotrigger",
        "inventory_check_interval",
        "inventory_check_severity",
        "inventory_cleanup",
        "log_logon_failures",
        "lock_on_logon_failures",
        "ldap_quarantine_period",
        "log_level",
        "log_levels",
        "log_messages",
        "log_rulehits",
        "login_screen",
        "maps_connections",
        "maps_log_level",
        "maps_map_defaults",
        "maps_object_defaults",
        "maps_state_refresh_interval",
        "mkeventd_connect_timeout",
        "mkeventd_notify_contactgroup",
        "mkeventd_notify_facility",
        "mkeventd_notify_remotehost",
        "mkeventd_pprint_rules",
        "mkeventd_service_levels",
        "multisite_draw_ruleicon",
        "notification_backlog",
        "notification_bulk_interval",
        "notification_fallback_email",
        "notification_fallback_format",
        "notification_logging",
        "notification_plugin_timeout",
        "page_heading",
        "pagetitle_date_format",
        "password_policy",
        "piggyback_max_cachefile_age",
        "profile",
        "profiling_options",
        "quicksearch_dropdown_limit",
        "quicksearch_search_order",
        "remote_status",
        "replication",
        "require_two_factor_all_users",
        "reschedule_timeout",
        "snmp_walk_download_timeout",
        "restart_locking",
        "retention_interval",
        "rrdcached_tuning",
        "rule_optimizer",
        "selection_livetime",
        "service_view_grouping",
        "session_mgmt",
        "show_livestatus_errors",
        "show_mode",
        "sidebar_notify_interval",
        "sidebar_update_interval",
        "simulation_mode",
        "single_user_session",
        "site_autostart",
        "site_core",
        "site_livestatus_tcp",
        "site_mkeventd",
        "site_piggyback_hub",
        "site_subject_alternative_names",
        "slow_views_duration_threshold",
        "snmp_credentials",
        "socket_queue_len",
        "soft_query_limit",
        "staleness_threshold",
        "start_url",
        "statistics_interval",
        "table_row_limit",
        "tcp_connect_timeout",
        "translate_snmptraps",
        "trusted_certificate_authorities",
        "ui_theme",
        "use_dns_cache",
        "snmp_backend_default",
        "use_new_descriptions_for",
        "user_downtime_timeranges",
        "user_icons_and_actions",
        "user_localizations",
        "acknowledge_problems",
        "virtual_host_trees",
        "wato_activation_method",
        "wato_activate_changes_comment_mode",
        "wato_hide_filenames",
        "wato_hide_folders_without_read_permissions",
        "wato_hide_hosttags",
        "wato_hide_varnames",
        "wato_icon_categories",
        "wato_max_snapshots",
        "wato_pprint_config",
        "wato_use_git",
        "graph_timeranges",
        "agent_controller_certificates",
        "rest_api_etag_locking",
        "enable_login_via_get",
        "default_language",
        "default_temperature_unit",
        "vue_experimental_features",
        "inject_js_profiling_code",
        "load_frontend_vue",
        "site_trace_send",
        "site_trace_receive",
        "product_usage_analytics",
    ]

    registered = sorted(config_variable_registry.keys())
    assert registered == sorted(expected_vars)


@pytest.mark.usefixtures("load_gui_plugins")
def test_registered_configvar_groups() -> None:
    expected_groups = [
        "Setup",
        "Event Console: generic",
        "Event Console: logging & diagnose",
        "Event Console: SNMP traps",
        "Execution of checks",
        "Maps: Map and object defaults",
        "Maps: Connections & daemon",
        "Notifications",
        "Service discovery",
        "Site management",
        "User interface",
        "User management",
        "Support",
        "Developer tools",
        "Product usage analytics",
        "Experimental flags (for testing only)",
    ]

    registered = sorted(config_variable_group_registry.keys())
    assert registered == sorted(expected_groups)
