#!/usr/bin/env python3
# Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# Public interface of the package: the discovery and update entry points, the objects they take
# and return, and the objects for constructing a graph. Everything else is an implementation
# detail and must not be imported from outside the package.

from ._evaluate import (
    DiscoveredGraph,
    DiscoveredGraphs,
    EvaluatedCurve,
    EvaluatedFixedRange,
    EvaluatedGraph,
    EvaluatedLine,
    EvaluatedMinimalRange,
    EvaluatedRule,
    EvaluatedStack,
    EvaluatedVerticalRange,
)
from ._fetch import (
    evaluate_graphs,
    fetch_translated_metrics,
    RRDSource,
    update_graph_data,
)
from ._from_api import metric_display_attributes
from ._objects import (
    AutoPrecision,
    Bound,
    Constant,
    Curve,
    CurveAttributes,
    DecimalNotation,
    Difference,
    EngineeringScientificNotation,
    EvaluationContext,
    FixedRange,
    Fraction,
    Graph,
    IECNotation,
    Line,
    MetricName,
    MinimalRange,
    Notation,
    PerformanceData,
    PerformanceValue,
    Precision,
    Product,
    Quantity,
    RRDMetric,
    RRDMetricData,
    Rule,
    ScalarKind,
    ScalarOf,
    ServiceRef,
    SINotation,
    Stack,
    StandardScientificNotation,
    StrictPrecision,
    Sum,
    TimeNotation,
    TimeSeries,
    Unit,
    VerticalRange,
)
from ._options import (
    ConsolidationFunction,
    TimeRange,
)
from ._template import (
    build_graphs,
    discover_graphs,
    TemplateOptions,
)

__all__ = [
    "AutoPrecision",
    "Bound",
    "ConsolidationFunction",
    "Constant",
    "Curve",
    "CurveAttributes",
    "DecimalNotation",
    "Difference",
    "DiscoveredGraph",
    "DiscoveredGraphs",
    "EngineeringScientificNotation",
    "EvaluatedCurve",
    "EvaluatedFixedRange",
    "EvaluatedGraph",
    "EvaluatedLine",
    "EvaluatedMinimalRange",
    "EvaluatedRule",
    "EvaluatedStack",
    "EvaluatedVerticalRange",
    "EvaluationContext",
    "FixedRange",
    "Fraction",
    "Graph",
    "IECNotation",
    "Line",
    "MetricName",
    "MinimalRange",
    "Notation",
    "PerformanceData",
    "PerformanceValue",
    "Precision",
    "Product",
    "Quantity",
    "RRDMetric",
    "RRDMetricData",
    "RRDSource",
    "Rule",
    "SINotation",
    "ScalarKind",
    "ScalarOf",
    "ServiceRef",
    "Stack",
    "StandardScientificNotation",
    "StrictPrecision",
    "Sum",
    "TemplateOptions",
    "TimeNotation",
    "TimeRange",
    "TimeSeries",
    "Unit",
    "VerticalRange",
    "build_graphs",
    "discover_graphs",
    "evaluate_graphs",
    "fetch_translated_metrics",
    "metric_display_attributes",
    "update_graph_data",
]
