DISTRO_CODE       = buster 
BUILD_PACKAGES    =
BUILD_PACKAGES   += build-essential
BUILD_PACKAGES   += dpatch
BUILD_PACKAGES   += fping
BUILD_PACKAGES   += smbclient # otherwise missing path in util.pm
BUILD_PACKAGES   += rpcbind # otherwise missing path in util.pm
BUILD_PACKAGES   += dnsutils # nagios-plugins check_dns
BUILD_PACKAGES   += git-buildpackage
BUILD_PACKAGES   += libboost-all-dev
BUILD_PACKAGES   += libcurl4-openssl-dev # needed by perl modules / thruk
BUILD_PACKAGES   += libcloog-ppl1      # needed by libgearman
BUILD_PACKAGES   += libncurses5-dev    # needed by mod-gearman
BUILD_PACKAGES   += libdbi-dev
BUILD_PACKAGES   += libevent-dev
BUILD_PACKAGES   += libgd-dev
BUILD_PACKAGES   += libglib2.0-dev
BUILD_PACKAGES   += libgnutls28-dev
BUILD_PACKAGES   += libldap2-dev
BUILD_PACKAGES   += libltdl-dev
BUILD_PACKAGES   += libmcrypt-dev
BUILD_PACKAGES   += default-libmysqlclient-dev
BUILD_PACKAGES   += libpq-dev
BUILD_PACKAGES   += libpango1.0-dev
BUILD_PACKAGES   += libperl-dev
BUILD_PACKAGES   += libreadline-dev
BUILD_PACKAGES   += libxml2-dev
BUILD_PACKAGES   += libsqlite3-dev # needed by Python (for sqlite3 module)
BUILD_PACKAGES   += tk-dev # needed by Python (for Tkinter module)
BUILD_PACKAGES   += patch
BUILD_PACKAGES   += uuid-dev
BUILD_PACKAGES   += snmp
BUILD_PACKAGES   += apache2-dev  # compiling mod_python
BUILD_PACKAGES   += apache2      # compiling mod_python
BUILD_PACKAGES   += libfreeradius-dev
#
# Check_MK build specific packages below
#
BUILD_PACKAGES   += dietlibc-dev # is not really needed, but useful for cmk components
BUILD_PACKAGES   += libpcap-dev # needed for CMC
BUILD_PACKAGES   += gettext # needed for german l10n
BUILD_PACKAGES   += libgsf-1-dev # needed for msitools
BUILD_PACKAGES   += librrd-dev # needed for CMC
BUILD_PACKAGES   += libffi-dev # needed for pyOpenSSL (and dependant) compilations
BUILD_PACKAGES   += libkrb5-dev # Needed for pykerberos
BUILD_PACKAGES   += libssl1.1-dev # Needed for net-snmp (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828449)
BUILD_PACKAGES   += flex # needed for heirloom-pkgtools
BUILD_PACKAGES   += openssh-client # needed for check_by_ssh
OS_PACKAGES       =
OS_PACKAGES      += cron # needed for sites cron jobs
OS_PACKAGES      += time # needed for mk-job
OS_PACKAGES      += traceroute # needed for Check_MK parent scan
OS_PACKAGES      += curl
OS_PACKAGES      += dialog
OS_PACKAGES      += dnsutils
OS_PACKAGES      += fping
OS_PACKAGES      += graphviz
OS_PACKAGES      += apache2
OS_PACKAGES      += libdbi1
OS_PACKAGES      += libevent-2.1-6
OS_PACKAGES      += libgd3
OS_PACKAGES      += libltdl7
OS_PACKAGES      += libnet-snmp-perl
OS_PACKAGES      += libpango1.0-0
OS_PACKAGES      += libperl5.28
OS_PACKAGES      += libreadline7
OS_PACKAGES      += libsnmp-perl
OS_PACKAGES      += libuuid1
OS_PACKAGES      += binutils # Needed by Check_MK Agent Bakery
OS_PACKAGES      += rpm
OS_PACKAGES      += php
OS_PACKAGES      += php-cgi
OS_PACKAGES      += php-cli
OS_PACKAGES      += php-gd
OS_PACKAGES      += php-sqlite3
OS_PACKAGES      += php-pear
OS_PACKAGES      += rsync
OS_PACKAGES      += smbclient
OS_PACKAGES      += rpcbind
OS_PACKAGES      += lcab # needed for creating MSI packages
OS_PACKAGES      += snmp
OS_PACKAGES      += unzip
OS_PACKAGES      += xinetd
OS_PACKAGES      += libfreeradius3
OS_PACKAGES      += libpcap0.8 # needed for cmc
OS_PACKAGES      += libgsf-1-114 # needed by msitools/Agent Bakery
OS_PACKAGES      += libglib2.0-0 # needed by msitools/Agent Bakery
OS_PACKAGES      += cpio # needed for Agent bakery (solaris pkgs)
OS_PACKAGES      += poppler-utils # needed for preview of PDF in reporting
OS_PACKAGES       += libffi6 # needed for pyOpenSSL and dependant
OS_PACKAGES      += libssl1.1 # Needed for net-snmp (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828449)
OS_PACKAGES      += libnl-3-200
USERADD_OPTIONS   =
ADD_USER_TO_GROUP = gpasswd -a %(user)s %(group)s
PACKAGE_INSTALL   = aptitude -y update ; aptitude -y install
ACTIVATE_INITSCRIPT = update-rc.d %s defaults
APACHE_CONF_DIR   = /etc/apache2/conf.d
APACHE_INIT_NAME  = apache2
APACHE_USER       = www-data
APACHE_GROUP      = www-data
APACHE_BIN        = /usr/sbin/apache2
APACHE_CTL        = /usr/sbin/apache2ctl
APACHE_MODULE_DIR = /usr/lib/apache2/modules
APACHE_MODULE_DIR_64 = /usr/lib/apache2/modules
HTPASSWD_BIN      = /usr/bin/htpasswd
APACHE_ENMOD      = a2enmod %s
PHP_FCGI_BIN      = /usr/bin/php5-cgi
BECOME_ROOT       = su -c
ARCH              = $(shell dpkg --print-architecture)
MOUNT_OPTIONS     =
INIT_CMD          = /etc/init.d/%(name)s %(action)s
