type = "Component"
display_name = "Plugins: Wiesemann & Theis"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["andrea.vaccaro@checkmk.com"]
description = """
Plugins for Wiesemann & Theis Web-IO and Web-Therm appliances.
"""
