#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

import pytest

from cmk.agent_based.v2 import (
    CheckResult,
    DiscoveryResult,
    Result,
    Service,
    State,
    StringTable,
)
from cmk.plugins.windows.agent_based import w32time_peers

DE_PEERS_EXAMPLE_COM = [
    ["Anzahl", "Peers:", "12"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30983.5517802s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30983.6666162s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30983.7917389s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30983.9172860s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30984.0420428s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30984.1672281s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30984.2920495s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30984.4170905s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30984.5420717s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30984.6669730s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30984.7920216s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
    ["---"],
    ["Peer:", "example.com"],
    ["Status:", "Aktiv"],
    ["Verbleibende", "Zeit:", "30984.9169029s"],
    ["Modus:", "3", "(Client)"],
    ["Stratum:", "0", "(nicht", "angegeben)"],
    ["PeerAbrufintervall:", "0", "(nicht", "angegeben)"],
    ["HostAbrufintervall:", "15", "(32768s)"],
    ["Letzte", "erfolgr.", "Synchronisierungszeit:", "(null)"],
    [
        "Letzter",
        "Synchronisierungsfehler:",
        "0x800705B4",
        "(Dieser",
        "Vorgang",
        "wurde",
        "wegen",
        "Zeit\x81berschreitung",
        "zur\x81ckgegeben.",
        ")",
    ],
    ["Letzte", "Synchronisierungsfehlermeldungs-ID:", "0x00000000", "(Erfolgreich)"],
    ["Auth-Typnachricht-ID:", "0x0000005A", "(NoAuth", ")"],
    ["Aufl\x94sungsversuche:", "0"],
    ["G\x81ltiger", "Datenz\x84hler:", "1"],
    ["Erreichbarkeit:", "2"],
]

EN_PEERS = [
    ["#Peers:", "5"],
    ["---"],
    ["Peer:", "time.facebook.com"],
    ["State:", "Active"],
    ["Time", "Remaining:", "1754.9964697s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "1", "(primary", "reference", "-", "syncd", "by", "radio", "clock)"],
    ["PeerPoll", "Interval:", "12", "(4096s)"],
    ["HostPoll", "Interval:", "12", "(4096s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "7:00:50", "PM"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "8"],
    ["Reachability:", "255"],
    ["---"],
    ["Peer:", "time.google.com"],
    ["State:", "Active"],
    ["Time", "Remaining:", "1755.0132055s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "1", "(primary", "reference", "-", "syncd", "by", "radio", "clock)"],
    ["PeerPoll", "Interval:", "12", "(4096s)"],
    ["HostPoll", "Interval:", "12", "(4096s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "7:00:50", "PM"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "8"],
    ["Reachability:", "255"],
    ["---"],
    ["Peer:", "de.pool.ntp.org"],
    ["State:", "Active"],
    ["Time", "Remaining:", "612.9102195s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "2", "(secondary", "reference", "-", "syncd", "by", "(S)NTP)"],
    ["PeerPoll", "Interval:", "12", "(4096s)"],
    ["HostPoll", "Interval:", "12", "(4096s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "6:41:48", "PM"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "8"],
    ["Reachability:", "255"],
    ["---"],
    ["Peer:", "time.cloudflare.com"],
    ["State:", "Active"],
    ["Time", "Remaining:", "618.9722708s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "3", "(secondary", "reference", "-", "syncd", "by", "(S)NTP)"],
    ["PeerPoll", "Interval:", "12", "(4096s)"],
    ["HostPoll", "Interval:", "12", "(4096s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "6:41:54", "PM"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "8"],
    ["Reachability:", "255"],
    ["---"],
    ["Peer:", "example.com"],
    ["State:", "Pending"],
    ["Time", "Remaining:", "5817.0042395s"],
    ["Mode:", "0", "(reserved)"],
    ["Stratum:", "0", "(unspecified)"],
    ["PeerPoll", "Interval:", "0", "(unspecified)"],
    ["HostPoll", "Interval:", "0", "(unspecified)"],
    ["Last", "Successful", "Sync", "Time:", "(null)"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "4"],
    ["ValidDataCounter:", "0"],
    ["Reachability:", "0"],
]

EN_WITH_EXTRA_LINE = [
    ["#Peers:", "2"],
    ["---"],
    ["Peer:", "time.google.com"],
    ["State:", "Active"],
    ["Time", "Remaining:", "1755.0132055s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "1", "(primary", "reference", "-", "syncd", "by", "radio", "clock)"],
    ["PeerPoll", "Interval:", "12", "(4096s)"],
    ["HostPoll", "Interval:", "12", "(4096s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "7:00:50", "PM"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "8"],
    ["Reachability:", "255"],
    ["---"],
    ["Peer:", "de.pool.ntp.org"],
    ["State:", "Active"],
    ["Time", "Remaining:", "612.9102195s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "2", "(secondary", "reference", "-", "syncd", "by", "(S)NTP)"],
    ["PeerPoll", "Interval:", "12", "(4096s)"],
    ["HostPoll", "Interval:", "12", "(4096s)"],
    ["OH", "NO:", "AN", "EXTRA", "LINE", "NOW", "WHAT?"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "6:41:48", "PM"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "8"],
    ["Reachability:", "255"],
]

EN_WITH_REMOVED_LINE = [
    ["#Peers:", "2"],
    ["---"],
    ["Peer:", "time.google.com"],
    ["State:", "Active"],
    ["Time", "Remaining:", "1755.0132055s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "1", "(primary", "reference", "-", "syncd", "by", "radio", "clock)"],
    ["PeerPoll", "Interval:", "12", "(4096s)"],
    ["HostPoll", "Interval:", "12", "(4096s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "7:00:50", "PM"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "8"],
    ["Reachability:", "255"],
    ["---"],
    ["Peer:", "de.pool.ntp.org"],
    ["State:", "Active"],
    ["Time", "Remaining:", "612.9102195s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "2", "(secondary", "reference", "-", "syncd", "by", "(S)NTP)"],
    ["PeerPoll", "Interval:", "12", "(4096s)"],
    # ["HostPoll", "Interval:", "12", "(4096s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "6:41:48", "PM"],
    ["LastSyncError:", "0x00000000", "(Succeeded)"],
    ["LastSyncErrorMsgId:", "0x00000000", "(Succeeded)"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "8"],
    ["Reachability:", "255"],
]

EN_WITH_ERROR = [
    ["#Peers:", "16"],
    ["---"],
    ["Peer:", "de.pool.ntp.org"],
    ["State:", "Active"],
    ["Time", "Remaining:", "12.3386152s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "1", "(primary", "reference", "-", "syncd", "by", "radio", "clock)"],
    ["PeerPoll", "Interval:", "10", "(1024s)"],
    ["HostPoll", "Interval:", "5", "(32s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "10:08:35", "AM"],
    [
        "LastSyncError:",
        "0x800705B4",
        "(This",
        "operation",
        "returned",
        "because",
        "the",
        "timeout",
        "period",
        "expired.",
        ")",
    ],
    ["LastSyncErrorMsgId:", "0x0000005C", "(The", "peer", "is", "unreachable.", ")"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "0"],
    ["ValidDataCounter:", "0"],
    ["Reachability:", "168"],
]


EN_WITH_0_REACHABILITY_AND_HIGH_RESOLVE_ATTEMPTS = [
    ["#Peers:", "16"],
    ["---"],
    ["Peer:", "de.pool.ntp.org"],
    ["State:", "Active"],
    ["Time", "Remaining:", "12.3386152s"],
    ["Mode:", "3", "(Client)"],
    ["Stratum:", "1", "(primary", "reference", "-", "syncd", "by", "radio", "clock)"],
    ["PeerPoll", "Interval:", "10", "(1024s)"],
    ["HostPoll", "Interval:", "5", "(32s)"],
    ["Last", "Successful", "Sync", "Time:", "9/18/2025", "10:08:35", "AM"],
    [
        "LastSyncError:",
        "0x800705B4",
        "(This",
        "operation",
        "returned",
        "because",
        "the",
        "timeout",
        "period",
        "expired.",
        ")",
    ],
    ["LastSyncErrorMsgId:", "0x0000005C", "(The", "peer", "is", "unreachable.", ")"],
    ["AuthTypeMsgId:", "0x0000005A", "(NoAuth", ")"],
    ["Resolve", "Attempts:", "3"],
    ["ValidDataCounter:", "0"],
    ["Reachability:", "0"],
]


NO_PEERS = [["#Peers:", "0"]]


@pytest.mark.parametrize(
    "string_table, expected",
    [
        (
            DE_PEERS_EXAMPLE_COM,
            {
                "example.com": w32time_peers.QueryPeers(
                    time_remaining=30984.9169029,
                    stratum=0,
                    last_successful_sync_time="(null)",
                    last_sync_error_str="Dieser Vorgang wurde wegen Zeit\x81berschreitung zur\x81ckgegeben.",
                    last_sync_error_msg=None,
                    raw_reachability=2,
                    reachability=w32time_peers.Reachability(
                        total_failures=1, consecutive_failures=1, total_attempts=2
                    ),
                )
            },
        ),
        (
            EN_PEERS,
            {
                "de.pool.ntp.org": w32time_peers.QueryPeers(
                    time_remaining=612.9102195,
                    stratum=2,
                    last_successful_sync_time="9/18/2025 6:41:48 PM",
                    last_sync_error_str="Succeeded",
                    last_sync_error_msg=None,
                    raw_reachability=255,
                    reachability=w32time_peers.Reachability(
                        total_failures=0, consecutive_failures=0, total_attempts=8
                    ),
                ),
                "example.com": w32time_peers.QueryPeers(
                    time_remaining=5817.0042395,
                    stratum=0,
                    last_successful_sync_time="(null)",
                    last_sync_error_str="Succeeded",
                    last_sync_error_msg=None,
                    raw_reachability=0,
                    reachability=w32time_peers.Reachability(
                        total_failures=4, consecutive_failures=4, total_attempts=4
                    ),
                ),
                "time.cloudflare.com": w32time_peers.QueryPeers(
                    time_remaining=618.9722708,
                    stratum=3,
                    last_successful_sync_time="9/18/2025 6:41:54 PM",
                    last_sync_error_str="Succeeded",
                    last_sync_error_msg=None,
                    raw_reachability=255,
                    reachability=w32time_peers.Reachability(
                        total_failures=0, consecutive_failures=0, total_attempts=8
                    ),
                ),
                "time.facebook.com": w32time_peers.QueryPeers(
                    time_remaining=1754.9964697,
                    stratum=1,
                    last_successful_sync_time="9/18/2025 7:00:50 PM",
                    last_sync_error_str="Succeeded",
                    last_sync_error_msg=None,
                    raw_reachability=255,
                    reachability=w32time_peers.Reachability(
                        total_failures=0, consecutive_failures=0, total_attempts=8
                    ),
                ),
                "time.google.com": w32time_peers.QueryPeers(
                    time_remaining=1755.0132055,
                    stratum=1,
                    last_successful_sync_time="9/18/2025 7:00:50 PM",
                    last_sync_error_str="Succeeded",
                    last_sync_error_msg=None,
                    raw_reachability=255,
                    reachability=w32time_peers.Reachability(
                        total_failures=0, consecutive_failures=0, total_attempts=8
                    ),
                ),
            },
        ),
        (
            NO_PEERS,
            {},
        ),
    ],
)
def test_parse_w32time_peers(
    string_table: StringTable, expected: dict[str, w32time_peers.QueryPeers]
) -> None:
    assert w32time_peers.parse_w32time_peers(string_table) == expected


@pytest.mark.parametrize(
    "string_table,substr",
    [
        (EN_WITH_EXTRA_LINE, "Peer parsed to more than"),
        (EN_WITH_REMOVED_LINE, "Peer parsed to less than"),
    ],
)
def test_parse_w32time_peers_parse_fail(string_table: StringTable, substr: str) -> None:
    with pytest.raises(ValueError, match=substr):
        w32time_peers.parse_w32time_peers(string_table)


@pytest.mark.parametrize(
    "string_table, item, params, expected",
    [
        pytest.param(
            EN_PEERS,
            "time.google.com",
            w32time_peers.DEFAULT_PARAMS,
            [
                Result(state=State.OK, summary="Last successful sync time: 9/18/2025 7:00:50 PM"),
                Result(state=State.OK, notice="Total failures (last 8 attempts): 0"),
                Result(state=State.OK, notice="Consecutive failures (last 8 attempts): 0"),
                Result(state=State.OK, summary="Stratum: 1"),
                Result(state=State.OK, summary="Next poll in: 29 minutes 15 seconds"),
            ],
            id="green path",
        ),
        pytest.param(
            EN_WITH_ERROR,
            "de.pool.ntp.org",
            w32time_peers.DEFAULT_PARAMS,
            [
                Result(state=State.OK, summary="Last successful sync time: 9/18/2025 10:08:35 AM"),
                Result(state=State.OK, notice="Total failures (last 8 attempts): 5"),
                Result(
                    state=State.WARN,
                    notice="Consecutive failures (last 8 attempts): 3 (warn/crit at 2/5)",
                ),
                Result(state=State.OK, summary="Last sync error: The peer is unreachable."),
                Result(
                    state=State.OK,
                    notice="Details from w32tm: This operation returned because the timeout period expired.",
                ),
                Result(state=State.OK, summary="Stratum: 1"),
                Result(state=State.OK, summary="Next poll in: 12 seconds"),
            ],
            id="error, default params (no alert)",
        ),
        pytest.param(
            EN_WITH_ERROR,
            "de.pool.ntp.org",
            {
                **w32time_peers.DEFAULT_PARAMS,
                "reachability_consecutive_failures": ("fixed", (2, 3)),
                "reachability_total_failures": ("fixed", (5, 6)),
            },
            [
                Result(state=State.OK, summary="Last successful sync time: 9/18/2025 10:08:35 AM"),
                Result(
                    state=State.WARN,
                    summary="Total failures (last 8 attempts): 5 (warn/crit at 5/6)",
                ),
                Result(
                    state=State.CRIT,
                    summary="Consecutive failures (last 8 attempts): 3 (warn/crit at 2/3)",
                ),
                Result(state=State.OK, summary="Last sync error: The peer is unreachable."),
                Result(
                    state=State.OK,
                    notice="Details from w32tm: This operation returned because the timeout period expired.",
                ),
                Result(state=State.OK, summary="Stratum: 1"),
                Result(state=State.OK, summary="Next poll in: 12 seconds"),
            ],
            id="error, with alerts",
        ),
        pytest.param(
            EN_PEERS,
            "time.cloudflare.com",
            {
                **w32time_peers.DEFAULT_PARAMS,
                "stratum": ("fixed", (2, 3)),
            },
            [
                Result(state=State.OK, summary="Last successful sync time: 9/18/2025 6:41:54 PM"),
                Result(state=State.OK, notice="Total failures (last 8 attempts): 0"),
                Result(state=State.OK, notice="Consecutive failures (last 8 attempts): 0"),
                Result(state=State.CRIT, summary="Stratum: 3 (warn/crit at 2/3)"),
                Result(state=State.OK, summary="Next poll in: 10 minutes 19 seconds"),
            ],
            id="high stratum, with alerts",
        ),
        pytest.param(
            EN_WITH_0_REACHABILITY_AND_HIGH_RESOLVE_ATTEMPTS,
            "de.pool.ntp.org",
            {
                **w32time_peers.DEFAULT_PARAMS,
                "reachability_total_failures": ("fixed", (2, 3)),
            },
            [
                Result(state=State.OK, summary="Last successful sync time: 9/18/2025 10:08:35 AM"),
                Result(
                    state=State.CRIT,
                    summary="Total failures (3 attempts): 3 (warn/crit at 2/3)",
                ),
                Result(
                    state=State.WARN,
                    notice="Consecutive failures (3 attempts): 3 (warn/crit at 2/5)",
                ),
                Result(state=State.OK, summary="Last sync error: The peer is unreachable."),
                Result(
                    state=State.OK,
                    notice="Details from w32tm: This operation returned because the timeout period expired.",
                ),
                Result(state=State.OK, summary="Stratum: 1"),
                Result(state=State.OK, summary="Next poll in: 12 seconds"),
            ],
            id="0 reachability, use resolve attempts instead",
        ),
    ],
)
def test_check_w32time_peers(
    string_table: StringTable, item: str, params: w32time_peers.Params, expected: CheckResult
) -> None:
    parsed = w32time_peers.parse_w32time_peers(string_table)
    result = list(w32time_peers.check_w32time_peers(item, params, parsed))
    assert result == expected


@pytest.mark.parametrize(
    "string_table, expected",
    [
        (
            EN_PEERS,
            [
                Service(item="time.facebook.com"),
                Service(item="time.google.com"),
                Service(item="de.pool.ntp.org"),
                Service(item="time.cloudflare.com"),
            ],
        ),
        (DE_PEERS_EXAMPLE_COM, []),
    ],
)
def test_discover_w32time_peers(string_table: StringTable, expected: DiscoveryResult) -> None:
    parsed = w32time_peers.parse_w32time_peers(string_table)
    result = list(w32time_peers.discover_w32time_peers(parsed))
    assert result == expected


@pytest.mark.parametrize(
    "binary, exp_total, exp_consecutive, exp_attempts",
    [
        (0b101, 1, 0, 3),
        (0b101000, 4, 3, 6),
        (0b11111111, 0, 0, 8),
        (0b111, 0, 0, 3),
        (0b000, 1, 1, 1),
    ],
)
def test_compute_failures(
    binary: int, exp_total: int, exp_consecutive: int, exp_attempts: int
) -> None:
    reachability = w32time_peers.Reachability.from_raw(binary, 1)
    assert reachability.total_failures == exp_total
    assert reachability.consecutive_failures == exp_consecutive
    assert reachability.total_attempts == exp_attempts
