type = "Component"
display_name = "Plugins: Orion Telecom"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["mohamed.saleh@checkmk.com"]
description = """
Plugins for Orion Telecom power-distribution and battery shelves.
"""
