#!/usr/bin/env python3
# Copyright (C) 2020 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from cmk.gui.plugins.openapi.restful_objects.endpoint_registry import ENDPOINT_REGISTRY
from cmk.gui.plugins.openapi.restful_objects.params import path_parameters


def test_endpoint_registry() -> None:
    assert sorted(
        [
            (e.func.__module__, e.link_relation, tuple(sorted(path_parameters(e.path))))
            for e in ENDPOINT_REGISTRY
        ]
    ) == sorted(
        [
            ("cmk.gui.plugins.openapi.endpoints.acknowledgement", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.acknowledgement", "cmk/create_service", ()),
            ("cmk.gui.plugins.openapi.endpoints.activate_changes", "cmk/activate", ()),
            (
                "cmk.gui.plugins.openapi.endpoints.activate_changes",
                "cmk/wait-for-completion",
                ("activation_id",),
            ),
            ("cmk.gui.plugins.openapi.endpoints.activate_changes", "cmk/show", ("activation_id",)),
            ("cmk.gui.plugins.openapi.endpoints.activate_changes", "cmk/run", ()),
            (
                "cmk.gui.plugins.openapi.endpoints.activate_changes",
                "cmk/pending-activation-changes",
                (),
            ),
            ("cmk.gui.plugins.openapi.endpoints.agent", "cmk/download", ()),
            ("cmk.gui.plugins.openapi.endpoints.audit_log", ".../delete", ()),
            ("cmk.gui.plugins.openapi.endpoints.audit_log", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.aux_tags", "cmk/show", ("aux_tag_id",)),
            ("cmk.gui.plugins.openapi.endpoints.aux_tags", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.aux_tags", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.aux_tags", "cmk/update", ("aux_tag_id",)),
            ("cmk.gui.plugins.openapi.endpoints.aux_tags", ".../delete", ("aux_tag_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/get_bi_rule", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/put_bi_rule", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/post_bi_rule", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/delete_bi_rule", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/get_bi_aggregation_state", ()),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/get_bi_aggregation", ("aggregation_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/put_bi_aggregation", ("aggregation_id",)),
            (
                "cmk.gui.plugins.openapi.endpoints.bi",
                "cmk/post_bi_aggregation",
                ("aggregation_id",),
            ),
            (
                "cmk.gui.plugins.openapi.endpoints.bi",
                "cmk/delete_bi_aggregation",
                ("aggregation_id",),
            ),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/get_bi_packs", ()),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/get_bi_pack", ("pack_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/delete_bi_pack", ("pack_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/put_bi_pack", ("pack_id",)),
            ("cmk.gui.plugins.openapi.endpoints.bi", "cmk/post_bi_pack", ("pack_id",)),
            ("cmk.gui.plugins.openapi.endpoints.cert", "cmk/show", ()),
            ("cmk.gui.plugins.openapi.endpoints.cert", "cmk/sign", ()),
            ("cmk.gui.plugins.openapi.endpoints.cert", "cmk/global_config", ()),
            ("cmk.gui.plugins.openapi.endpoints.comment", "cmk/show", ("comment_id",)),
            ("cmk.gui.plugins.openapi.endpoints.comment", ".../collection", ("collection_name",)),
            ("cmk.gui.plugins.openapi.endpoints.comment", "cmk/create_for_host", ()),
            ("cmk.gui.plugins.openapi.endpoints.comment", "cmk/create_for_service", ()),
            ("cmk.gui.plugins.openapi.endpoints.comment", ".../delete", ()),
            ("cmk.gui.plugins.openapi.endpoints.contact_group_config", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.contact_group_config", "cmk/bulk_create", ()),
            ("cmk.gui.plugins.openapi.endpoints.contact_group_config", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.contact_group_config", "cmk/show", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.contact_group_config", ".../delete", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.contact_group_config", ".../delete", ()),
            ("cmk.gui.plugins.openapi.endpoints.contact_group_config", ".../update", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.contact_group_config", "cmk/bulk_update", ()),
            ("cmk.gui.plugins.openapi.endpoints.downtime", "cmk/create_host", ()),
            ("cmk.gui.plugins.openapi.endpoints.downtime", "cmk/create_service", ()),
            ("cmk.gui.plugins.openapi.endpoints.downtime", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.downtime", "cmk/show", ("downtime_id",)),
            ("cmk.gui.plugins.openapi.endpoints.downtime", ".../delete", ()),
            ("cmk.gui.plugins.openapi.endpoints.event_console", "cmk/show", ("event_id",)),
            ("cmk.gui.plugins.openapi.endpoints.event_console", ".../collection", ()),
            (
                "cmk.gui.plugins.openapi.endpoints.event_console",
                "cmk/update_and_acknowledge",
                ("event_id",),
            ),
            ("cmk.gui.plugins.openapi.endpoints.event_console", "cmk/change_state", ("event_id",)),
            (
                "cmk.gui.plugins.openapi.endpoints.event_console",
                ".../collection_update_and_acknowledge",
                (),
            ),
            ("cmk.gui.plugins.openapi.endpoints.event_console", ".../collection_change_state", ()),
            ("cmk.gui.plugins.openapi.endpoints.event_console", ".../delete", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_config", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_config", "cmk/create_cluster", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_config", "cmk/bulk_create", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_config", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_config", ".../property", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_config", ".../update", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_config", "cmk/bulk_update", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_config", "cmk/rename", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_config", "cmk/wait-for-completion", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_config", "cmk/move", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_config", ".../delete", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_config", ".../delete", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_config", "cmk/show", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.folder_config", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.folder_config", ".../collection", ("folder",)),
            ("cmk.gui.plugins.openapi.endpoints.folder_config", ".../persist", ("folder",)),
            ("cmk.gui.plugins.openapi.endpoints.folder_config", "cmk/bulk_update", ()),
            ("cmk.gui.plugins.openapi.endpoints.folder_config", ".../delete", ("folder",)),
            ("cmk.gui.plugins.openapi.endpoints.folder_config", "cmk/move", ("folder",)),
            ("cmk.gui.plugins.openapi.endpoints.folder_config", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.folder_config", "cmk/show", ("folder",)),
            ("cmk.gui.plugins.openapi.endpoints.host", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.host", "cmk/show", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_group_config", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_group_config", "cmk/bulk_create", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_group_config", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_group_config", ".../delete", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_group_config", ".../delete", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_group_config", ".../update", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_group_config", "cmk/bulk_update", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_group_config", "cmk/show", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_internal", "cmk/register", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_internal", "cmk/link_uuid", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_internal", "cmk/show", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_tag_group", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_tag_group", "cmk/show", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_tag_group", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.host_tag_group", ".../update", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.host_tag_group", ".../delete", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.metric", "cmk/get_graph", ()),
            ("cmk.gui.plugins.openapi.endpoints.notification_rules", "cmk/show", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.notification_rules", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.notification_rules", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.notification_rules", "cmk/update", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.notification_rules", ".../delete", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.password", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.password", ".../update", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.password", ".../delete", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.password", "cmk/show", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.password", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.rule", "cmk/move", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.rule", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.rule", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.rule", "cmk/show", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.rule", ".../delete", ("rule_id",)),
            ("cmk.gui.plugins.openapi.endpoints.ruleset", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.ruleset", "cmk/show", ("ruleset_name",)),
            ("cmk.gui.plugins.openapi.endpoints.service", "cmk/show", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.service", ".../collection", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.service", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.service_discovery", "cmk/list", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.service_discovery", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.service_discovery", ".../modify", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.service_discovery", "cmk/show", ("host_name",)),
            (
                "cmk.gui.plugins.openapi.endpoints.service_discovery",
                "cmk/wait-for-completion",
                ("host_name",),
            ),
            ("cmk.gui.plugins.openapi.endpoints.service_discovery", ".../update", ()),
            ("cmk.gui.plugins.openapi.endpoints.service_discovery", ".../update", ("host_name",)),
            ("cmk.gui.plugins.openapi.endpoints.service_discovery", "cmk/activate", ()),
            ("cmk.gui.plugins.openapi.endpoints.service_discovery", "cmk/show", ("job_id",)),
            ("cmk.gui.plugins.openapi.endpoints.service_group_config", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.service_group_config", "cmk/bulk_create", ()),
            ("cmk.gui.plugins.openapi.endpoints.service_group_config", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.service_group_config", "cmk/show", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.service_group_config", ".../delete", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.service_group_config", ".../delete", ()),
            ("cmk.gui.plugins.openapi.endpoints.service_group_config", ".../update", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.service_group_config", "cmk/bulk_update", ()),
            ("cmk.gui.plugins.openapi.endpoints.site_management", "cmk/show", ("site_id",)),
            ("cmk.gui.plugins.openapi.endpoints.site_management", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.site_management", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.site_management", "cmk/update", ("site_id",)),
            ("cmk.gui.plugins.openapi.endpoints.site_management", ".../delete", ("site_id",)),
            ("cmk.gui.plugins.openapi.endpoints.site_management", "cmk/site_login", ("site_id",)),
            ("cmk.gui.plugins.openapi.endpoints.site_management", "cmk/site_logout", ("site_id",)),
            ("cmk.gui.plugins.openapi.endpoints.time_periods", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.time_periods", ".../update", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.time_periods", ".../delete", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.time_periods", "cmk/show", ("name",)),
            ("cmk.gui.plugins.openapi.endpoints.time_periods", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.user_config", "cmk/show", ("username",)),
            ("cmk.gui.plugins.openapi.endpoints.user_config", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.user_config", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.user_config", ".../delete", ("username",)),
            ("cmk.gui.plugins.openapi.endpoints.user_config", ".../update", ("username",)),
            ("cmk.gui.plugins.openapi.endpoints.user_role", "cmk/show", ("role_id",)),
            ("cmk.gui.plugins.openapi.endpoints.user_role", ".../collection", ()),
            ("cmk.gui.plugins.openapi.endpoints.user_role", "cmk/create", ()),
            ("cmk.gui.plugins.openapi.endpoints.user_role", ".../delete", ("role_id",)),
            ("cmk.gui.plugins.openapi.endpoints.user_role", ".../update", ("role_id",)),
            ("cmk.gui.plugins.openapi.endpoints.version", "cmk/show", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", "cmk/sign", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", ".../collection", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", "cmk/bake", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", "cmk/bake_and_sign", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", "cmk/bakery-status", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", "cmk/baking-status", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", "cmk/show", ("agent_hash",)),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", "cmk/download_by_host", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.agent", "cmk/download_by_hash", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.dcd", "cmk/fetch_phase_one", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.dcd", "cmk/create", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.dcd", "cmk/show", ("dcd_id",)),
            ("cmk.gui.cee.plugins.openapi.endpoints.dcd", ".../delete", ("dcd_id",)),
            ("cmk.gui.cee.plugins.openapi.endpoints.licensing", "cmk/download", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.licensing", "cmk/verify", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.licensing", "cmk/configure", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.metric", "cmk/get_custom_graph", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.sla", "cmk/compute", ()),
            ("cmk.gui.cee.plugins.openapi.endpoints.metric.internal", "cmk/filter_graph", ()),
        ]
    )
