# Stubs for kubernetes.config (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .config_exception import ConfigException as ConfigException
from .incluster_config import load_incluster_config as load_incluster_config
from .kube_config import list_kube_config_contexts, load_kube_config, new_client_from_config
