# Stubs for kubernetes.config.dateutil_test (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest
from .dateutil import TimezoneInfo, UTC, format_rfc3339, parse_rfc3339

class DateUtilTest(unittest.TestCase):
    def test_parse_rfc3339(self) -> None: ...
    def test_format_rfc3339(self) -> None: ...
