PERL_MODULES := perl-modules

PERL_MODULES_INSTALL := $(BUILD_HELPER_DIR)/$(PERL_MODULES)-install

PERL_MODULES_INSTALL_DIR := $(INTERMEDIATE_INSTALL_BASE)/$(PERL_MODULES)
PERL_MODULES_BUILD_DIR := $(BAZEL_BIN)/omd/packages/$(PERL_MODULES)/$(PERL_MODULES)
PERL_MODULES_WORK_DIR := $(PACKAGE_WORK_DIR)/$(PERL_MODULES)

PERL_MODULES_BUILD_SRCDIR := $(PERL_MODULES_BUILD_DIR)/src
PERL_MODULES_BUILD_PERL5LIB := $(PERL_MODULES_BUILD_DIR)/lib/perl5

# Used by other packages
PACKAGE_PERL_MODULES_PERL5LIB := $(PERL_MODULES_INSTALL_DIR)/lib/perl5

$(PERL_MODULES_INSTALL): $(INTERMEDIATE_INSTALL_BAZEL)
	$(RSYNC) $(PERL_MODULES_INSTALL_DIR)/ $(DESTDIR)$(OMD_ROOT)/
	echo "install  --install_base  ###ROOT###/local/lib/perl5" > $(SKEL)/.modulebuildrc
	$(TOUCH) $@
