# Example configuration for Windows agent

# Almost every section can have flag enabled
# You may use anchors to parametrize your config
# Windows file names better to close in ''
# Use online yaml validator to check your config http://yaml-online-parser.appspot.com/?url=http%3A%2F%2F
# all root section may have key enabled. Default is yes. If set to no, then this section is ignored

global:
    # use name to have mor clear logs
    name: Descriptive name of the configuration file
    # if file defined then used other file
    #file: 'c:\systemconfigs\my perfect  config in yaml.yml'
    enabled: no
    # Restrict access to certain IP addresses
    # If ipv6 is enabled, all listed ipv4 adresses are also accepted as
    # source adresses in their ipv6-mapped form. I.e. if
    # 192.168.56.0/24 is listed, connections from ::ffff:c0a8:3800/120
    # are also possible
    only_from:
        - 127.0.0.1
        - 192.168.56.0/24
        - ::1

    # Change port where the agent is listening ( default 6556 )
    port: 6556

    # Disable ipv6 support. By default, ipv4 is always supported
    # and ipv6 is enabled additionally if supported by the system.
    ipv6: no

    # Do only execute programs and scripts with
    # the following suffixes (in local and plugins).
    # Per default all extensions except txt and dir
    # are being executed.
    execute: exe bat vbs cmd ps1

    # Run async scripts in parallel (to each other). Default is "sequential",
    # which means the scripts are run asynchronously to the agent itself but
    # one after the other. Setting this to parallel may improve the delay before
    # new data is reported but may also lead to the agent having more noticable
    # impact on the system performance
    async: yes

    # Restrict the following configuration variables
    # in [global] to the following hosts
    # ?????????
    host:
        - winsrv*
        - zab???ad

    # Just output certain sections (e.g. for upper hosts)
    sections:
        enabled:
            - check_mk
            - winperf
            #- ps
        # forced to not use
        disabled:
            - logfiles
        # output sections in realtime updates. Please note that not all
        # sections can be used in realtime updates, the following is the
        # complete list
        realtime:
            # specifies how long (in seconds) realtime updates are sent to
            # the last monitoring system that requested an update.
            # this should be longer than the request frequency (usually
            # one minute).
            # Please note that any new request cancels previous realtime
            # update schedules, so no more than one update is sent per second,
            # no matter if this timeout is "too high" or how many monitoring
            # systems are querying the agent.
            timeout: 90
            # enable/disable encryption of regular agent output (default: disabled)
            # yes or no
            encrypted: default
            # passphrase for encrypted communication.
            passphrase: this is my password
            # which sections are realtime
            run:
                - mem
                - df
                - winperf_processor

    # Write a logfile for tackling down crashes of the agent
    debug:
        crash: yes
        # you may specify name of log file
        file:
    trace:
        # you may trace agent in realtime using DbgView or WinDbg
        debugger: no
        file: 'c:\windows\logs\win_agent.log'

    # by default the agent flushes the socket for each agent section.
    # this is mostly for debugging purposes in case the agent is slow
    # to respond.
    # Disabling this may (very) slightly reduce network traffic.
    section_flush: no
