[{'elapsed_time': 2.0569918155670166,
  'filename': 'wato',
  'output': {'context_button': [('No Changes',
                                 'wato.py?mode=changelog&folder=',
                                 'wato_nochanges'),
                                ('Main Menu',
                                 'wato.py?mode=main&folder=',
                                 'home'),
                                ('Rulesets',
                                 'wato.py?mode=ruleeditor&folder=',
                                 'rulesets'),
                                ('Manual Checks',
                                 'wato.py?mode=static_checks&folder=',
                                 'static_checks'),
                                ('Folder Properties',
                                 'wato.py?mode=editfolder&folder=',
                                 'edit'),
                                ('New folder',
                                 'wato.py?mode=newfolder&folder=',
                                 'newfolder'),
                                ('New host',
                                 'wato.py?mode=newhost&folder=',
                                 'new'),
                                ('New cluster',
                                 'wato.py?mode=newcluster&folder=',
                                 'new_cluster'),
                                ('Bulk Import',
                                 'wato.py?mode=bulk_import&folder=',
                                 'bulk_import'),
                                ('Bulk Discovery',
                                 'wato.py?mode=bulkinventory&all=1&folder=',
                                 'inventory'),
                                ('Bulk Renaming',
                                 'wato.py?mode=bulk_rename_host&folder=',
                                 'rename_host'),
                                ('Parent scan',
                                 'wato.py?mode=parentscan&all=1&folder=',
                                 'parentscan'),
                                ('Search',
                                 'wato.py?mode=search&folder=',
                                 'search'),
                                ('Status',
                                 'view.py?view_name=allhosts&wato_folder=',
                                 'status')],
             'data_tables': [{'collect_headers': False,
                              'empty_text': 'No entries.',
                              'headers': [('Actions', None, False),
                                          ('Hostname', None, True),
                                          ('Alias', None, True),
                                          ('IPv4 Address', None, True),
                                          ('IPv6 Address', None, True),
                                          ('Parents', None, True),
                                          ('Monitored on site',
                                           None,
                                           True),
                                          ('Auth', None, False),
                                          ('Permissions', None, True),
                                          ('Contact Groups', None, True),
                                          ('Tags',
                                           'cmk-agent|prod|lan|tcp',
                                           True),
                                          ('Move To', None, False)],
                              'id': 'hosts',
                              'limit': 100,
                              'next_header': None,
                              'omit_headers': False,
                              'omit_if_empty': False,
                              'output_format': 'html',
                              'rows': [([('<a onfocus="if (this.blur) this.blur();" href="wato.py?mode=edithost&host=heute&folder="><img align=absmiddle class=iconbutton title="Edit the properties of this host" src="images/button_edit.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=object_parameters&host=heute&folder="><img align=absmiddle class=iconbutton title="View the rule based parameters of this host" src="images/button_rulesets.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=inventory&host=heute&folder="><img align=absmiddle class=iconbutton title="Edit the services of this host, do a service discovery" src="images/button_services.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=newhost&clone=heute&folder="><img align=absmiddle class=iconbutton title="Create a clone of this host" src="images/button_insert.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=folder&_delete_host=heute&_transid=1449577230/3675548061&folder="><img align=absmiddle class=iconbutton title="Delete this host" src="images/button_delete.png"></a>',
                                          'buttons',
                                          None),
                                         ('<a href="wato.py?mode=edithost&host=heute&folder=">heute</a>\n',
                                          None,
                                          None),
                                         ('', ' inherited', None),
                                         ('127.0.0.1', '', None),
                                         ('', ' inherited', None),
                                         ('', ' inherited', None),
                                         ('heute - Local site heute',
                                          ' inherited',
                                          None),
                                         ('<img class=icon src="images/icon_authok.png" title="You have permission to this host.">',
                                          None,
                                          None),
                                         ('', None, None),
                                         ('', None, None),
                                         ("<nobr>cmk-agent</nobr><b style='color: #888;'>|</b>&#8203;<nobr>prod</nobr><b style='color: #888;'>|</b>&#8203;<nobr>lan</nobr><b style='color: #888;'>|</b>&#8203;<nobr>tcp</nobr>",
                                          'tag-ellipsis',
                                          None),
                                         ('', 'right', None)],
                                        None,
                                        0,
                                        False),
                                       ([('<div id="checkbox_on" title="Show Checkboxes and bulk actions" class="togglebutton checkbox up" onclick="location.href=\'wato.py?folder=&mode=folder&show_checkboxes=1&selection=a46b006e-3a97-455d-902a-31ed1d3d14df\'"><img src="images/icon_checkbox.png"></div><input type="text" class="text" value="" name="search"  />\n<label for="_search" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_search" id="_search" value="Search" class="" />\n</label>',
                                          'bulksearch',
                                          3),
                                         (' Selected hosts:\n<label for="_bulk_delete" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_delete" id="_bulk_delete" value="Delete" class="" />\n</label><label for="_bulk_edit" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_edit" id="_bulk_edit" value="Edit" class="" />\n</label><label for="_bulk_cleanup" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_cleanup" id="_bulk_cleanup" value="Cleanup" class="" />\n</label><label for="_bulk_inventory" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_inventory" id="_bulk_inventory" value="Discovery" class="" />\n</label><label for="_parentscan" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_parentscan" id="_parentscan" value="Parentscan" class="" />\n</label>',
                                          'bulkactions',
                                          9)],
                                        None,
                                        0,
                                        True)],
                              'searchable': False,
                              'sortable': True,
                              'title': None}],
             'page_title': ['Main directory']},
  'user': u'omdadmin',
  'variables': {'mode': 'folder'}},
 {'elapsed_time': 0.007086992263793945,
  'filename': 'wato',
  'output': {'context_button': [('Folder',
                                 'wato.py?mode=folder&folder=',
                                 'back')],
             'page_title': ['Create new host']},
  'user': u'omdadmin',
  'variables': {'folder': '', 'mode': 'newhost'}},
 {'elapsed_time': 0.013139009475708008,
  'filename': 'wato',
  'output': {'context_button': [('1 Changes',
                                 'wato.py?mode=changelog&folder=',
                                 'wato_changes'),
                                ('Main Menu',
                                 'wato.py?mode=main&folder=',
                                 'home'),
                                ('Rulesets',
                                 'wato.py?mode=ruleeditor&folder=',
                                 'rulesets'),
                                ('Manual Checks',
                                 'wato.py?mode=static_checks&folder=',
                                 'static_checks'),
                                ('Folder Properties',
                                 'wato.py?mode=editfolder&folder=',
                                 'edit'),
                                ('New folder',
                                 'wato.py?mode=newfolder&folder=',
                                 'newfolder'),
                                ('New host',
                                 'wato.py?mode=newhost&folder=',
                                 'new'),
                                ('New cluster',
                                 'wato.py?mode=newcluster&folder=',
                                 'new_cluster'),
                                ('Bulk Import',
                                 'wato.py?mode=bulk_import&folder=',
                                 'bulk_import'),
                                ('Bulk Discovery',
                                 'wato.py?mode=bulkinventory&all=1&folder=',
                                 'inventory'),
                                ('Bulk Renaming',
                                 'wato.py?mode=bulk_rename_host&folder=',
                                 'rename_host'),
                                ('Parent scan',
                                 'wato.py?mode=parentscan&all=1&folder=',
                                 'parentscan'),
                                ('Search',
                                 'wato.py?mode=search&folder=',
                                 'search'),
                                ('Status',
                                 'view.py?view_name=allhosts&wato_folder=',
                                 'status')],
             'data_tables': [{'collect_headers': False,
                              'empty_text': 'No entries.',
                              'headers': [('Actions', None, False),
                                          ('Hostname', None, True),
                                          ('Alias', None, True),
                                          ('IPv4 Address', None, True),
                                          ('IPv6 Address', None, True),
                                          ('Parents', None, True),
                                          ('Monitored on site',
                                           None,
                                           True),
                                          ('Auth', None, False),
                                          ('Permissions', None, True),
                                          ('Contact Groups', None, True),
                                          ('Tags',
                                           'lan|ip-v4|cmk-agent|tcp|site:heute|ip-v4-only|prod',
                                           True),
                                          ('Move To', None, False)],
                              'id': 'hosts',
                              'limit': 100,
                              'next_header': None,
                              'omit_headers': False,
                              'omit_if_empty': False,
                              'output_format': 'html',
                              'rows': [([('<a onfocus="if (this.blur) this.blur();" href="wato.py?mode=edithost&host=heute&folder="><img align=absmiddle class=iconbutton title="Edit the properties of this host" src="images/button_edit.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=object_parameters&host=heute&folder="><img align=absmiddle class=iconbutton title="View the rule based parameters of this host" src="images/button_rulesets.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=inventory&host=heute&folder="><img align=absmiddle class=iconbutton title="Edit the services of this host, do a service discovery" src="images/button_services.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=newhost&clone=heute&folder="><img align=absmiddle class=iconbutton title="Create a clone of this host" src="images/button_insert.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=folder&_delete_host=heute&_transid=1449577256/3923633717&folder="><img align=absmiddle class=iconbutton title="Delete this host" src="images/button_delete.png"></a>',
                                          'buttons',
                                          None),
                                         ('<a href="wato.py?mode=edithost&host=heute&folder=">heute</a>\n',
                                          None,
                                          None),
                                         ('', ' inherited', None),
                                         ('127.0.0.1', '', None),
                                         ('', ' inherited', None),
                                         ('', ' inherited', None),
                                         ('heute - Local site heute',
                                          ' inherited',
                                          None),
                                         ('<img class=icon src="images/icon_authok.png" title="You have permission to this host.">',
                                          None,
                                          None),
                                         ('', None, None),
                                         ('', None, None),
                                         ("<nobr>lan</nobr><b style='color: #888;'>|</b>&#8203;<nobr>ip-v4</nobr><b style='color: #888;'>|</b>&#8203;<nobr>cmk-agent</nobr><b style='color: #888;'>|</b>&#8203;<nobr>tcp</nobr><b style='color: #888;'>|</b>&#8203;<nobr>site:heute</nobr><b style='color: #888;'>|</b>&#8203;<nobr>ip-v4-only</nobr><b style='color: #888;'>|</b>&#8203;<nobr>prod</nobr>",
                                          'tag-ellipsis',
                                          None),
                                         ('', 'right', None)],
                                        None,
                                        0,
                                        False),
                                       ([('<a onfocus="if (this.blur) this.blur();" href="wato.py?mode=edithost&host=localhost&folder="><img align=absmiddle class=iconbutton title="Edit the properties of this host" src="images/button_edit.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=object_parameters&host=localhost&folder="><img align=absmiddle class=iconbutton title="View the rule based parameters of this host" src="images/button_rulesets.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=inventory&host=localhost&folder="><img align=absmiddle class=iconbutton title="Edit the services of this host, do a service discovery" src="images/button_services.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=newhost&clone=localhost&folder="><img align=absmiddle class=iconbutton title="Create a clone of this host" src="images/button_insert.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?mode=folder&_delete_host=localhost&_transid=1449577256/3923633717&folder="><img align=absmiddle class=iconbutton title="Delete this host" src="images/button_delete.png"></a>',
                                          'buttons',
                                          None),
                                         ('<a href="wato.py?mode=edithost&host=localhost&folder=">localhost</a>\n',
                                          None,
                                          None),
                                         (u'Der L\xf6k\xe4le R\xf6chner',
                                          '',
                                          None),
                                         (u'127.0.0.1', '', None),
                                         ('', ' inherited', None),
                                         ('', ' inherited', None),
                                         ('heute - Local site heute',
                                          ' inherited',
                                          None),
                                         ('<img class=icon src="images/icon_authok.png" title="You have permission to this host.">',
                                          None,
                                          None),
                                         ('', None, None),
                                         ('', None, None),
                                         ("<nobr>lan</nobr><b style='color: #888;'>|</b>&#8203;<nobr>ip-v4</nobr><b style='color: #888;'>|</b>&#8203;<nobr>cmk-agent</nobr><b style='color: #888;'>|</b>&#8203;<nobr>tcp</nobr><b style='color: #888;'>|</b>&#8203;<nobr>site:heute</nobr><b style='color: #888;'>|</b>&#8203;<nobr>ip-v4-only</nobr><b style='color: #888;'>|</b>&#8203;<nobr>prod</nobr>",
                                          'tag-ellipsis',
                                          None),
                                         ('', 'right', None)],
                                        None,
                                        0,
                                        False),
                                       ([('<div id="checkbox_on" title="Show Checkboxes and bulk actions" class="togglebutton checkbox up" onclick="location.href=\'wato.py?attr_alias=Der%20L%C3%B6k%C3%A4le%20R%C3%B6chner&site=heute&attr_ipaddress=127.0.0.1&filled_in=edithost&contactgroups_use=on&attr_ipv6address=&parents_0=&attr_tag_agent=cmk-agent%7Ctcp&folder=&save=Save%20%26%20Finish&attr_display_ipaddress=1&attr_snmp_community=&attr_tag_networking=lan&attr_display_snmp_community=0&host=localhost&attr_tag_criticality=prod&attr_tag_address_family=ip-v4-only%7Cip-v4&mode=folder&attr_display_ipv6address=0&show_checkboxes=1&selection=40847308-22df-4ccd-8d8a-3b009cf352cb\'"><img src="images/icon_checkbox.png"></div><input type="text" class="text" value="" name="search"  />\n<label for="_search" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_search" id="_search" value="Search" class="" />\n</label>',
                                          'bulksearch',
                                          3),
                                         (' Selected hosts:\n<label for="_bulk_delete" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_delete" id="_bulk_delete" value="Delete" class="" />\n</label><label for="_bulk_edit" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_edit" id="_bulk_edit" value="Edit" class="" />\n</label><label for="_bulk_cleanup" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_cleanup" id="_bulk_cleanup" value="Cleanup" class="" />\n</label><label for="_bulk_inventory" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_inventory" id="_bulk_inventory" value="Discovery" class="" />\n</label><label for="_parentscan" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_parentscan" id="_parentscan" value="Parentscan" class="" />\n</label>',
                                          'bulkactions',
                                          9)],
                                        None,
                                        0,
                                        True)],
                              'searchable': False,
                              'sortable': True,
                              'title': None}],
             'page_title': ['Main directory']},
  'user': u'omdadmin',
  'variables': {'_change_alias': 'on',
                '_change_ipaddress': 'on',
                '_transid': 'valid',
                'attr_alias': 'Der L\xc3\xb6k\xc3\xa4le R\xc3\xb6chner',
                'attr_display_ipaddress': '1',
                'attr_display_ipv6address': '0',
                'attr_display_snmp_community': '0',
                'attr_ipaddress': '127.0.0.1',
                'attr_ipv6address': '',
                'attr_snmp_community': '',
                'attr_tag_address_family': 'ip-v4-only|ip-v4',
                'attr_tag_agent': 'cmk-agent|tcp',
                'attr_tag_criticality': 'prod',
                'attr_tag_networking': 'lan',
                'contactgroups_use': 'on',
                'filled_in': 'edithost',
                'folder': '',
                'host': 'localhost',
                'mode': 'newhost',
                'parents_0': '',
                'save': 'Save & Finish',
                'site': 'heute'}}]
