[{'elapsed_time': 2.430838108062744,
  'filename': 'wato',
  'output': {'context_button': [('No Changes',
                                 'wato.py?folder=&mode=changelog',
                                 'wato_nochanges'),
                                ('Main Menu',
                                 'wato.py?folder=&mode=main',
                                 'home'),
                                ('Rulesets',
                                 'wato.py?folder=&mode=ruleeditor',
                                 'rulesets'),
                                ('Manual Checks',
                                 'wato.py?folder=&mode=static_checks',
                                 'static_checks'),
                                ('Folder Properties',
                                 'wato.py?folder=&mode=editfolder',
                                 'edit'),
                                ('New folder',
                                 'wato.py?folder=&mode=newfolder',
                                 'newfolder'),
                                ('New host',
                                 'wato.py?folder=&mode=newhost',
                                 'new'),
                                ('New cluster',
                                 'wato.py?folder=&mode=newcluster',
                                 'new_cluster'),
                                ('Bulk Import',
                                 'wato.py?folder=&mode=bulk_import',
                                 'bulk_import'),
                                ('Bulk Discovery',
                                 'wato.py?all=1&folder=&mode=bulkinventory',
                                 'inventory'),
                                ('Bulk Renaming',
                                 'wato.py?folder=&mode=bulk_rename_host',
                                 'rename_host'),
                                ('Parent scan',
                                 'wato.py?all=1&folder=&mode=parentscan',
                                 'parentscan'),
                                ('Search',
                                 'wato.py?folder=&mode=search',
                                 'search'),
                                ('Status',
                                 'view.py?view_name=allhosts&wato_folder=',
                                 'status')],
             'data_tables': [{'collect_headers': False,
                              'empty_text': 'No entries.',
                              'headers': [('Actions', None, False),
                                          ('Hostname', None, True),
                                          ('Alias', None, True),
                                          ('IPv4 Address', None, True),
                                          ('IPv6 Address', None, True),
                                          ('Parents', None, True),
                                          ('Monitored on site',
                                           None,
                                           True),
                                          ('Auth', None, False),
                                          ('Permissions', None, True),
                                          ('Contact Groups', None, True),
                                          ('Tags',
                                           'cmk-agent|prod|lan|tcp',
                                           True),
                                          ('Move To', None, False)],
                              'id': 'hosts',
                              'limit': 100,
                              'next_header': None,
                              'omit_headers': False,
                              'omit_if_empty': False,
                              'output_format': 'html',
                              'rows': [([('<a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=heute&mode=edithost"><img align=absmiddle class=iconbutton title="Edit the properties of this host" src="images/button_edit.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=heute&mode=object_parameters"><img align=absmiddle class=iconbutton title="View the rule based parameters of this host" src="images/button_rulesets.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=heute&mode=inventory"><img align=absmiddle class=iconbutton title="Edit the services of this host, do a service discovery" src="images/button_services.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?clone=heute&folder=&mode=newhost"><img align=absmiddle class=iconbutton title="Create a clone of this host" src="images/button_insert.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?_delete_host=heute&_transid=1449587913/1096495580&folder=&mode=folder"><img align=absmiddle class=iconbutton title="Delete this host" src="images/button_delete.png"></a>',
                                          'buttons',
                                          None),
                                         ('<a href="wato.py?folder=&host=heute&mode=edithost">heute</a>\n',
                                          None,
                                          None),
                                         ('', ' inherited', None),
                                         ('127.0.0.1', '', None),
                                         ('', ' inherited', None),
                                         ('', ' inherited', None),
                                         ('heute - Local site heute',
                                          ' inherited',
                                          None),
                                         ('<img class=icon src="images/icon_authok.png" title="You have permission to this host.">',
                                          None,
                                          None),
                                         ('', None, None),
                                         ('', None, None),
                                         ("<nobr>cmk-agent</nobr><b style='color: #888;'>|</b>&#8203;<nobr>prod</nobr><b style='color: #888;'>|</b>&#8203;<nobr>lan</nobr><b style='color: #888;'>|</b>&#8203;<nobr>tcp</nobr>",
                                          'tag-ellipsis',
                                          None),
                                         ('', 'right', None)],
                                        None,
                                        0,
                                        False),
                                       ([('<div id="checkbox_on" title="Show Checkboxes and bulk actions" class="togglebutton checkbox up" onclick="location.href=\'wato.py?folder=&mode=folder&selection=527ca0a9-aefe-4f52-b885-ff236dab57e9&show_checkboxes=1\'"><img src="images/icon_checkbox.png"></div><input type="text" class="text" value="" name="search"  />\n<label for="_search" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_search" id="_search" value="Search" class="" />\n</label>',
                                          'bulksearch',
                                          3),
                                         (' Selected hosts:\n<label for="_bulk_delete" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_delete" id="_bulk_delete" value="Delete" class="" />\n</label><label for="_bulk_edit" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_edit" id="_bulk_edit" value="Edit" class="" />\n</label><label for="_bulk_cleanup" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_cleanup" id="_bulk_cleanup" value="Cleanup" class="" />\n</label><label for="_bulk_inventory" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_inventory" id="_bulk_inventory" value="Discovery" class="" />\n</label><label for="_parentscan" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_parentscan" id="_parentscan" value="Parentscan" class="" />\n</label>',
                                          'bulkactions',
                                          9)],
                                        None,
                                        0,
                                        True)],
                              'searchable': False,
                              'sortable': True,
                              'title': None}],
             'page_title': ['Main directory']},
  'user': u'omdadmin',
  'variables': {'mode': 'folder'}},
 {'elapsed_time': 0.2498798370361328,
  'filename': 'wato',
  'output': {'context_button': [('Folder',
                                 'wato.py?folder=&mode=folder',
                                 'back')],
             'page_title': ['Create new host']},
  'user': u'omdadmin',
  'variables': {'folder': '', 'mode': 'newhost'}},
 {'elapsed_time': 0.25353312492370605,
  'filename': 'wato',
  'output': {'context_button': [('1 Changes',
                                 'wato.py?folder=&mode=changelog',
                                 'wato_changes'),
                                ('Main Menu',
                                 'wato.py?folder=&mode=main',
                                 'home'),
                                ('Rulesets',
                                 'wato.py?folder=&mode=ruleeditor',
                                 'rulesets'),
                                ('Manual Checks',
                                 'wato.py?folder=&mode=static_checks',
                                 'static_checks'),
                                ('Folder Properties',
                                 'wato.py?folder=&mode=editfolder',
                                 'edit'),
                                ('New folder',
                                 'wato.py?folder=&mode=newfolder',
                                 'newfolder'),
                                ('New host',
                                 'wato.py?folder=&mode=newhost',
                                 'new'),
                                ('New cluster',
                                 'wato.py?folder=&mode=newcluster',
                                 'new_cluster'),
                                ('Bulk Import',
                                 'wato.py?folder=&mode=bulk_import',
                                 'bulk_import'),
                                ('Bulk Discovery',
                                 'wato.py?all=1&folder=&mode=bulkinventory',
                                 'inventory'),
                                ('Bulk Renaming',
                                 'wato.py?folder=&mode=bulk_rename_host',
                                 'rename_host'),
                                ('Parent scan',
                                 'wato.py?all=1&folder=&mode=parentscan',
                                 'parentscan'),
                                ('Search',
                                 'wato.py?folder=&mode=search',
                                 'search'),
                                ('Status',
                                 'view.py?view_name=allhosts&wato_folder=',
                                 'status')],
             'data_tables': [{'collect_headers': False,
                              'empty_text': 'No entries.',
                              'headers': [('Actions', None, False),
                                          ('Hostname', None, True),
                                          ('Alias', None, True),
                                          ('IPv4 Address', None, True),
                                          ('IPv6 Address', None, True),
                                          ('Parents', None, True),
                                          ('Monitored on site',
                                           None,
                                           True),
                                          ('Auth', None, False),
                                          ('Permissions', None, True),
                                          ('Contact Groups', None, True),
                                          ('Tags',
                                           'lan|ip-v4|cmk-agent|tcp|site:heute|ip-v4-only|prod',
                                           True),
                                          ('Move To', None, False)],
                              'id': 'hosts',
                              'limit': 100,
                              'next_header': None,
                              'omit_headers': False,
                              'omit_if_empty': False,
                              'output_format': 'html',
                              'rows': [([('<a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=heute&mode=edithost"><img align=absmiddle class=iconbutton title="Edit the properties of this host" src="images/button_edit.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=heute&mode=object_parameters"><img align=absmiddle class=iconbutton title="View the rule based parameters of this host" src="images/button_rulesets.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=heute&mode=inventory"><img align=absmiddle class=iconbutton title="Edit the services of this host, do a service discovery" src="images/button_services.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?clone=heute&folder=&mode=newhost"><img align=absmiddle class=iconbutton title="Create a clone of this host" src="images/button_insert.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?_delete_host=heute&_transid=1449587935/923451947&folder=&mode=folder"><img align=absmiddle class=iconbutton title="Delete this host" src="images/button_delete.png"></a>',
                                          'buttons',
                                          None),
                                         ('<a href="wato.py?folder=&host=heute&mode=edithost">heute</a>\n',
                                          None,
                                          None),
                                         ('', ' inherited', None),
                                         ('127.0.0.1', '', None),
                                         ('', ' inherited', None),
                                         ('', ' inherited', None),
                                         ('heute - Local site heute',
                                          ' inherited',
                                          None),
                                         ('<img class=icon src="images/icon_authok.png" title="You have permission to this host.">',
                                          None,
                                          None),
                                         ('', None, None),
                                         ('', None, None),
                                         ("<nobr>lan</nobr><b style='color: #888;'>|</b>&#8203;<nobr>ip-v4</nobr><b style='color: #888;'>|</b>&#8203;<nobr>cmk-agent</nobr><b style='color: #888;'>|</b>&#8203;<nobr>tcp</nobr><b style='color: #888;'>|</b>&#8203;<nobr>site:heute</nobr><b style='color: #888;'>|</b>&#8203;<nobr>ip-v4-only</nobr><b style='color: #888;'>|</b>&#8203;<nobr>prod</nobr>",
                                          'tag-ellipsis',
                                          None),
                                         ('', 'right', None)],
                                        None,
                                        0,
                                        False),
                                       ([('<a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=localhost&mode=edithost"><img align=absmiddle class=iconbutton title="Edit the properties of this host" src="images/button_edit.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=localhost&mode=object_parameters"><img align=absmiddle class=iconbutton title="View the rule based parameters of this host" src="images/button_rulesets.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?folder=&host=localhost&mode=inventory"><img align=absmiddle class=iconbutton title="Edit the services of this host, do a service discovery" src="images/button_services.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?clone=localhost&folder=&mode=newhost"><img align=absmiddle class=iconbutton title="Create a clone of this host" src="images/button_insert.png"></a><a onfocus="if (this.blur) this.blur();" href="wato.py?_delete_host=localhost&_transid=1449587935/923451947&folder=&mode=folder"><img align=absmiddle class=iconbutton title="Delete this host" src="images/button_delete.png"></a>',
                                          'buttons',
                                          None),
                                         ('<a href="wato.py?folder=&host=localhost&mode=edithost">localhost</a>\n',
                                          None,
                                          None),
                                         (u'Der L\xf6k\xe4le R\xf6chner',
                                          '',
                                          None),
                                         (u'127.0.0.2', '', None),
                                         ('', ' inherited', None),
                                         ('<a href="wato.py?host=heute&mode=edithost">heute</a>',
                                          '',
                                          None),
                                         ('heute - Local site heute',
                                          ' inherited',
                                          None),
                                         ('<img class=icon src="images/icon_authok.png" title="You have permission to this host.">',
                                          None,
                                          None),
                                         ('', None, None),
                                         ('', None, None),
                                         ("<nobr>lan</nobr><b style='color: #888;'>|</b>&#8203;<nobr>ip-v4</nobr><b style='color: #888;'>|</b>&#8203;<nobr>cmk-agent</nobr><b style='color: #888;'>|</b>&#8203;<nobr>tcp</nobr><b style='color: #888;'>|</b>&#8203;<nobr>site:heute</nobr><b style='color: #888;'>|</b>&#8203;<nobr>ip-v4-only</nobr><b style='color: #888;'>|</b>&#8203;<nobr>prod</nobr>",
                                          'tag-ellipsis',
                                          None),
                                         ('', 'right', None)],
                                        None,
                                        0,
                                        False),
                                       ([('<div id="checkbox_on" title="Show Checkboxes and bulk actions" class="togglebutton checkbox up" onclick="location.href=\'wato.py?attr_alias=Der%20L%C3%B6k%C3%A4le%20R%C3%B6chner&attr_display_ipaddress=1&attr_display_ipv6address=0&attr_display_snmp_community=0&attr_ipaddress=127.0.0.2&attr_ipv6address=&attr_snmp_community=&attr_tag_address_family=ip-v4-only%7Cip-v4&attr_tag_agent=cmk-agent%7Ctcp&attr_tag_criticality=prod&attr_tag_networking=lan&contactgroups_use=on&filled_in=edithost&folder=&host=localhost&mode=folder&parents_0=heute&parents_1=&save=Save%20%26%20Finish&selection=776dabcb-786b-4c86-aada-ce1b19b1e983&show_checkboxes=1&site=heute\'"><img src="images/icon_checkbox.png"></div><input type="text" class="text" value="" name="search"  />\n<label for="_search" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_search" id="_search" value="Search" class="" />\n</label>',
                                          'bulksearch',
                                          3),
                                         (' Selected hosts:\n<label for="_bulk_delete" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_delete" id="_bulk_delete" value="Delete" class="" />\n</label><label for="_bulk_edit" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_edit" id="_bulk_edit" value="Edit" class="" />\n</label><label for="_bulk_cleanup" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_cleanup" id="_bulk_cleanup" value="Cleanup" class="" />\n</label><label for="_bulk_inventory" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_bulk_inventory" id="_bulk_inventory" value="Discovery" class="" />\n</label><label for="_parentscan" class="image_button"><input onfocus="if (this.blur) this.blur();" type="submit" name="_parentscan" id="_parentscan" value="Parentscan" class="" />\n</label>',
                                          'bulkactions',
                                          9)],
                                        None,
                                        0,
                                        True)],
                              'searchable': False,
                              'sortable': True,
                              'title': None}],
             'page_title': ['Main directory']},
  'user': u'omdadmin',
  'variables': {'_change_alias': 'on',
                '_change_ipaddress': 'on',
                '_change_parents': 'on',
                '_transid': 'invalid',
                'attr_alias': 'Der L\xc3\xb6k\xc3\xa4le R\xc3\xb6chner',
                'attr_display_ipaddress': '1',
                'attr_display_ipv6address': '0',
                'attr_display_snmp_community': '0',
                'attr_ipaddress': '127.0.0.2',
                'attr_ipv6address': '',
                'attr_snmp_community': '',
                'attr_tag_address_family': 'ip-v4-only|ip-v4',
                'attr_tag_agent': 'cmk-agent|tcp',
                'attr_tag_criticality': 'prod',
                'attr_tag_networking': 'lan',
                'contactgroups_use': 'on',
                'filled_in': 'edithost',
                'folder': '',
                'host': 'localhost',
                'mode': 'newhost',
                'parents_0': 'heute',
                'parents_1': '',
                'save': 'Save & Finish',
                'site': 'heute'}},
 {'elapsed_time': 0.24730205535888672,
  'filename': 'wato',
  'output': {'context_button': [('Main Menu',
                                 'wato.py?folder=&mode=main',
                                 'home'),
                                ('Activate Changes!',
                                 'wato.py?_action=activate&_transid=1449587944/1539833280&folder=&mode=changelog',
                                 'apply'),
                                ('Site Configuration',
                                 'wato.py?folder=&mode=sites',
                                 'sites'),
                                ('Audit Log',
                                 'wato.py?folder=&mode=auditlog',
                                 'auditlog')],
             'data_tables': [{'collect_headers': True,
                              'empty_text': 'No entries.',
                              'headers': [('Actions', None, False),
                                          ('ID', None, True),
                                          ('Alias', None, True),
                                          ('Status', None, True),
                                          ('Version', None, True),
                                          ('Core', None, True),
                                          ('Hosts', None, True),
                                          ('Services', None, True),
                                          ('', None, False),
                                          ('Activate', None, False),
                                          ('Last Result', None, True)],
                              'id': 'site-status',
                              'limit': 100,
                              'next_header': None,
                              'omit_headers': False,
                              'omit_if_empty': False,
                              'output_format': 'html',
                              'rows': [([('<a onfocus="if (this.blur) this.blur();" href="wato.py?edit=heute&folder=&mode=edit_site"><img align=absmiddle class=iconbutton title="Edit the properties of this site" src="images/button_edit.png"></a>',
                                          'buttons',
                                          None),
                                         ('heute', None, None),
                                         ('Local site heute',
                                          None,
                                          None),
                                         ('<img src="images/button_sitestatus_online.png">',
                                          None,
                                          None),
                                         (u'2015.12.08', None, None),
                                         (u'Check_MK 2015.12.08',
                                          None,
                                          None),
                                         ('<a href="view.py?view_name=sitehosts&site=heute">1</a>',
                                          'number',
                                          None),
                                         ('<a href="view.py?view_name=sitesvcs&site=heute">27</a>',
                                          'number',
                                          None),
                                         ('<img class=icon title="This site needs a restart for activating the changes." src="images/icon_need_restart.png">',
                                          'buttons',
                                          None),
                                         ('<label for=" id=id_1" class="image_button"><input id=id_1 value="Restart" class="buttonlink" type="button" onclick="location.href=\'wato.py?_site=heute&_siteaction=restart&_transid=1449587944/1539833280&folder=&mode=changelog\'" />\n</label>',
                                          'buttons',
                                          None),
                                         ('', None, None)],
                                        None,
                                        0,
                                        False)],
                              'searchable': False,
                              'sortable': True,
                              'title': None}],
             'page_title': ['Pending changes to activate']},
  'user': u'omdadmin',
  'variables': {'folder': '', 'mode': 'changelog'}},
 {'elapsed_time': 0.35854291915893555,
  'filename': 'wato',
  'output': {'context_button': [('Main Menu',
                                 'wato.py?folder=&mode=main',
                                 'home'),
                                ('Activate Changes!',
                                 'wato.py?_action=activate&_transid=1449587946/2342378723&folder=&mode=changelog',
                                 'apply'),
                                ('Site Configuration',
                                 'wato.py?folder=&mode=sites',
                                 'sites'),
                                ('Audit Log',
                                 'wato.py?folder=&mode=auditlog',
                                 'auditlog')],
             'data_tables': [{'collect_headers': True,
                              'empty_text': 'No entries.',
                              'headers': [('Actions', None, False),
                                          ('ID', None, True),
                                          ('Alias', None, True),
                                          ('Status', None, True),
                                          ('Version', None, True),
                                          ('Core', None, True),
                                          ('Hosts', None, True),
                                          ('Services', None, True),
                                          ('Activation', None, True)],
                              'id': 'site-status',
                              'limit': 100,
                              'next_header': None,
                              'omit_headers': False,
                              'omit_if_empty': False,
                              'output_format': 'html',
                              'rows': [([('<a onfocus="if (this.blur) this.blur();" href="wato.py?edit=heute&folder=&mode=edit_site"><img align=absmiddle class=iconbutton title="Edit the properties of this site" src="images/button_edit.png"></a>',
                                          'buttons',
                                          None),
                                         ('heute', None, None),
                                         ('Local site heute',
                                          None,
                                          None),
                                         ('<img src="images/button_sitestatus_online.png">',
                                          None,
                                          None),
                                         (u'2015.12.08', None, None),
                                         (u'Check_MK 2015.12.08',
                                          None,
                                          None),
                                         ('<a href="view.py?view_name=sitehosts&site=heute">1</a>',
                                          'number',
                                          None),
                                         ('<a href="view.py?view_name=sitesvcs&site=heute">27</a>',
                                          'number',
                                          None),
                                         ('<div id="repstate_heute"></div><script language="javascript">\nwato_do_replication(\'heute\', 2000);\n</script>\n',
                                          'repprogress',
                                          None)],
                                        None,
                                        0,
                                        False)],
                              'searchable': False,
                              'sortable': True,
                              'title': None}],
             'page_title': ['Pending changes to activate']},
  'user': u'omdadmin',
  'variables': {'_action': 'activate',
                '_transid': 'valid',
                'folder': '',
                'mode': 'changelog'}},
 {'elapsed_time': 0.43735504150390625,
  'filename': 'wato_ajax_replication',
  'output': {},
  'user': u'omdadmin',
  'variables': {'site': 'heute'}},
 {'elapsed_time': 0.022950172424316406,
  'filename': 'view',
  'output': {'context_button': [('Export as PDF',
                                 'report_instant.py?is_summary_host=0&selection=03678b7a-76f0-4bbf-938c-4fe5c7a213b5&view_name=allhosts',
                                 'report'),
                                (u'BI Availability',
                                 'report.py?is_summary_host=0&name=bi_availability&selection=03678b7a-76f0-4bbf-938c-4fe5c7a213b5&view_name=allhosts',
                                 'report'),
                                (u'Service Availability',
                                 'report.py?is_summary_host=0&name=service_availability&selection=03678b7a-76f0-4bbf-938c-4fe5c7a213b5&view_name=allhosts',
                                 'pdf'),
                                ('Edit View',
                                 'edit_view.py?load_user=&load_name=allhosts&back=view.py?is_summary_host%3d0%26selection%3d03678b7a-76f0-4bbf-938c-4fe5c7a213b5%26view_name%3dallhosts',
                                 'edit'),
                                ('Availability',
                                 'view.py?is_summary_host=0&mode=availability&selection=03678b7a-76f0-4bbf-938c-4fe5c7a213b5&view_name=allhosts',
                                 'availability')],
             'page_title': ['All hosts']},
  'user': u'omdadmin',
  'variables': {'view_name': 'allhosts'}}]
