#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from cmk.base.configlib.loaded_config import LoadedConfigFragment
from cmk.base.core.nagios._create_config import NagiosCoreConfig
from cmk.utils.labels import ABCLabelConfig, LabelManager, Labels
from cmk.utils.rulesets.ruleset_matcher import RulesetMatcher

EMPTY_CONFIG = LoadedConfigFragment(
    experimental={},
    discovery_rules={},
    checkgroup_parameters={},
    logwatch_rules=(),
    static_checks={},
    service_rule_groups=set(),
    service_descriptions={},
    service_description_translation=(),
    use_new_descriptions_for={},
    monitoring_core="nagios",
    nagios_illegal_chars="",
    cmc_illegal_chars="",
    all_hosts=(),
    clusters={},
    shadow_hosts={},
    service_dependencies=(),
    fallback_agent_output_encoding="latin-1",
    folder_attributes={},
    agent_config={},
    agent_port=6556,
    agent_ports=(),
    tcp_connect_timeout=5.0,
    tcp_connect_timeouts=(),
    encryption_handling=(),
    piggyback_translation=(),
    piggybacked_host_files=(),
    piggyback_max_cachefile_age=3600,
    agent_encryption=(),
    agent_exclude_sections=(),
    cmc_real_time_checks=None,
    snmp_check_interval=[],
    agent_bakery_logging=None,
    apply_bake_revision=False,
    bake_agents_on_restart=False,
    is_distributed_setup_remote_site=False,
    simulation_mode=False,
    use_dns_cache=True,
    ipaddresses={},
    ipv6addresses={},
    inventory_check_interval=None,
    fake_dns=None,
    tag_config={
        "tag_groups": [],
        "aux_tags": [],
    },
    host_tags={},
    cmc_log_rrdcreation=None,
    cmc_host_rrd_config=[],
    cmc_statehist_cache={"horizon": 63072000, "max_core_downtime": 30},
    cmc_timeperiod_horizon=2 * 365,
    host_recurring_downtimes=[],
    cmc_flap_settings=(3.0, 5.0, 0.1),
    cmc_host_flap_settings=[],
    cmc_host_long_output_in_monitoring_history=[],
    host_state_translation=[],
    cmc_smartping_settings=[],
    cmc_service_rrd_config=[],
    service_recurring_downtimes=[],
    cmc_service_flap_settings=[],
    cmc_service_long_output_in_monitoring_history=[],
    service_state_translation=[],
    cmc_check_timeout=60,
    cmc_service_check_timeout=[],
    cmc_graphite_host_metrics=[],
    cmc_graphite_service_metrics=[],
    cmc_influxdb_service_metrics=[],
    cmc_log_levels={
        "cmk.alert": 5,
        "cmk.carbon": 5,
        "cmk.core": 5,
        "cmk.downtime": 5,
        "cmk.helper": 5,
        "cmk.livestatus": 5,
        "cmk.notification": 5,
        "cmk.rrd": 5,
        "cmk.influxdb": 5,
        "cmk.smartping": 5,
    },
    cluster_max_cachefile_age=90,
    http_proxies={},
    oauth2_connections={},
    extra_service_conf={},
    extra_host_conf={},
    host_attributes={},
    timeperiods={},
    check_periods=(),
    relays={},
    cmc_config_multiprocessing={"use_multiprocessing": True},
    cmc_check_helpers=5,
    cmc_fetcher_helpers=13,
    cmc_checker_helpers=4,
    cmc_real_time_helpers=1,
    cmc_initial_scheduling={"burst": 10, "spread_cmk": 1200, "spread_generic": 150},
    cmc_housekeeping_interval=1000,
    cmc_state_retention_interval=600,
    cmc_debug_notifications=False,
    cmc_dump_core=False,
    cmc_log_microtime=False,
    cmc_log_rotation_method=3,
    cmc_log_limit=50 * 1024 * 1024,
    cmc_log_cmk_helpers={"log_level": 0, "debug": False},
    cmc_livestatus_threads=20,
    cmc_max_response_size=100,
    cmc_livestatus_logcache_size=500000,
    cmc_livestatus_lines_per_file=1000000,
    cmc_authorization={"host": 0, "group": 0},
    cmc_smartping_check_interval=500,
    cmc_smartping_tuning={"omit_payload": False, "num_sockets": 8, "ignore_rst": False},
    mkeventd_enabled=False,
    pnp4nagios_enabled=True,
    cmc_pnp_update_delay=3600,
    cmc_pnp_update_on_restart=False,
    max_long_output_size=2000,
    influxdb_connections={},
    cmc_graphite=[],
    alert_handler_event_types=["statechange"],
    alert_handler_rules=[],
    alert_handler_timeout=60,
    alert_logging=20,
    host_template="check_mk_host",
    cluster_template="check_mk_cluster",
    pingonly_template="check_mk_pingonly",
    active_service_template="check_mk_active",
    passive_service_template_perf="check_mk_passive_perf",
    inventory_check_template="check_mk_inventory",
    service_dependency_template="check_mk",
    generate_hostconf=True,
    generate_dummy_commands=True,
    dummy_check_commandline=(
        'echo "ERROR - you did an active check on this service - please disable active checks" '
        "&& exit 1"
    ),
    delay_precompile=False,
    default_host_group="check_mk",
    extra_nagios_conf="",
    contacts={},
    define_contactgroups={},
    define_hostgroups={},
    define_servicegroups={},
    contactgroup_members={},
    cmc_import_nagios_state=True,
    restart_locking="abort",
    check_submission="file",
    check_max_cachefile_age=0,
    check_mk_perfdata_with_times=True,
    perfdata_format="pnp",
    host_notification_periods=[],
    service_notification_periods=[],
    inventory_check_autotrigger=True,
    monitoring_host=None,
    explicit_snmp_communities={},
    cmc_host_limit=None,
    cmc_service_limit=None,
    cmc_store_params_in_config=False,
    notification_rules=[],
    notification_parameter={},
    notification_backlog=10,
    notification_bulk_interval=10,
    notification_fallback_email="",
    notification_fallback_format=("asciimail", {}),
    notification_plugin_timeout=60,
    notification_logging=15,
    notification_spooling=None,
    notification_spool_to=None,
)


EMPTY_NAGIOS_CORE_CONFIG = NagiosCoreConfig(
    delay_precompile=False,
    host_template="check_mk_host",
    cluster_template="check_mk_cluster",
    pingonly_template="check_mk_pingonly",
    active_service_template="check_mk_active",
    passive_service_template_perf="check_mk_passive_perf",
    inventory_check_template="check_mk_inventory",
    service_dependency_template="check_mk",
    generate_hostconf=True,
    generate_dummy_commands=True,
    dummy_check_commandline=(
        'echo "ERROR - you did an active check on this service - please disable active checks" '
        "&& exit 1"
    ),
    default_host_group="check_mk",
    extra_nagios_conf="",
    contacts={},
    define_contactgroups={},
    define_hostgroups={},
    define_servicegroups={},
    contactgroup_members={},
    simulation_mode=False,
)


class EmptyLabelConfig(ABCLabelConfig):
    def host_labels(self, hn: object) -> Labels:
        return {}

    def service_labels(self, hn: object, sd: object, sn: object) -> Labels:
        return {}


def make_trivial_label_manager() -> LabelManager:
    return LabelManager(EmptyLabelConfig(), {}, {}, {})


def make_trivial_ruleset_matcher() -> RulesetMatcher:
    return RulesetMatcher({}, {}, frozenset(), {}, {})
