CHECK_CERT := check-cert
CHECK_CERT_DIR := $(CHECK_CERT)

CHECK_CERT_BUILD := $(BUILD_HELPER_DIR)/$(CHECK_CERT_DIR)-build
CHECK_CERT_INSTALL := $(BUILD_HELPER_DIR)/$(CHECK_CERT_DIR)-install

.PHONY: $(CHECK_CERT_BUILD)
$(CHECK_CERT_BUILD):
	$(BAZEL_BUILD) //packages/$(CHECK_CERT):$(CHECK_CERT)

.PHONY: $(CHECK_CERT_INSTALL)
$(CHECK_CERT_INSTALL): $(CHECK_CERT_BUILD)
	install -m 755 $(BAZEL_BIN)/packages/$(CHECK_CERT_DIR)/$(CHECK_CERT) $(DESTDIR)$(OMD_ROOT)/lib/nagios/plugins/
	patchelf --set-rpath "\$$ORIGIN/../../../lib" $(DESTDIR)$(OMD_ROOT)/lib/nagios/plugins/$(CHECK_CERT)
