/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VueValidators1 = IsNumber | NumberInRange | LengthInRange

export interface VueValidators {
  all_schemas?: VueValidators1[]
}
export interface IsNumber {
  vue_type?: 'is_number'
  error_message?: string
}
export interface NumberInRange {
  vue_type?: 'number_in_range'
  min_value?: number
  max_value?: number
  error_message?: string
}
export interface LengthInRange {
  vue_type?: 'length_in_range'
  min_value?: number
  max_value?: number
  error_message?: string
}
