#!/usr/bin/env python3
# Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.
import re
from collections.abc import Sequence
from typing import Annotated, Self

from annotated_types import MinLen
from pydantic import AfterValidator, model_validator, WithJsonSchema

from cmk.ccc.regex import WATO_FOLDER_PATH_NAME_REGEX
from cmk.gui.openapi.api_endpoints.models.folder_attribute_models import FolderAttributeRequestModel
from cmk.gui.openapi.framework.model import api_field, api_model
from cmk.gui.openapi.framework.model.common_fields import AnnotatedFolder


def _validate_folder_name(value: str) -> str:
    # ``WATO_FOLDER_PATH_NAME_REGEX`` uses Python-only regex syntax (``\Z``), so it is validated
    # here with the ``re`` module rather than via a pydantic ``pattern``.
    # The pattern is documented in the schema via ``WithJsonSchema`` on the field.
    if not value:
        raise ValueError("The name must not be empty.")
    if not re.match(WATO_FOLDER_PATH_NAME_REGEX, value):
        raise ValueError(f"{value!r} does not match pattern {WATO_FOLDER_PATH_NAME_REGEX!r}.")
    return value


_FOLDER_NAME_JSON_SCHEMA = WithJsonSchema(
    {"type": "string", "pattern": WATO_FOLDER_PATH_NAME_REGEX, "minLength": 1}
)


@api_model
class CreateFolderModel:
    title: Annotated[str, MinLen(1)] = api_field(
        description="The folder title as displayed in the user interface.",
        example="Production Hosts",
    )
    parent: AnnotatedFolder = api_field(
        description=(
            "The folder in which the new folder shall be placed in. The root-folder is "
            "specified by '/'."
        ),
        example="/",
    )
    name: Annotated[str, AfterValidator(_validate_folder_name), _FOLDER_NAME_JSON_SCHEMA] | None = (
        api_field(
            default=None,
            description=(
                "The filesystem directory name (not path!) of the folder. No slashes are allowed. "
                "This will be autogenerated from the title, if not given."
            ),
            example="production",
        )
    )
    attributes: FolderAttributeRequestModel = api_field(
        default_factory=lambda: FolderAttributeRequestModel(dynamic_fields={}),
        description=(
            "Specific attributes to apply for all hosts in this folder (among other things). "
            "Built-in and custom attributes and tag groups can be set here."
        ),
        example={"tag_criticality": "prod"},
    )


@api_model
class UpdateFolderModel:
    title: Annotated[str, MinLen(1)] | None = api_field(
        default=None,
        description="The title of the folder. Used in the GUI.",
        example="Virtual Servers",
    )
    attributes: FolderAttributeRequestModel | None = api_field(
        default=None,
        description=(
            "Replace all attributes with the ones given in this field. Already set attributes, "
            "not given here, will be removed. Can't be used together with update_attributes or "
            "remove_attributes fields."
        ),
        example={"tag_networking": "wan"},
    )
    update_attributes: FolderAttributeRequestModel | None = api_field(
        default=None,
        description=(
            "Just update the folder attributes with these attributes. The previously set "
            "attributes will be overwritten. Can't be used together with attributes or "
            "remove_attributes fields."
        ),
        example={"tag_criticality": "prod"},
    )
    remove_attributes: list[str] | None = api_field(
        default=None,
        description=(
            "A list of attributes which should be removed. Can't be used together with "
            "attributes or update_attributes fields."
        ),
        example=["tag_foobar"],
    )

    @model_validator(mode="after")
    def _validate_one_action(self) -> Self:
        """Only one of the attributes fields is allowed at a time."""
        provided = [
            name
            for name in ("attributes", "update_attributes", "remove_attributes")
            if getattr(self, name) is not None
        ]
        if len(provided) > 1:
            raise ValueError(
                f"This endpoint only allows 1 action (set/update/remove) per call, you specified "
                f"{len(provided)} actions: {', '.join(provided)}."
            )
        return self


@api_model
class UpdateFolderEntry(UpdateFolderModel):
    folder: AnnotatedFolder = api_field(
        description="The path of the folder to be updated.",
        example="/",
    )


@api_model
class BulkUpdateFolderModel:
    entries: Sequence[UpdateFolderEntry] = api_field(description="A list of folder entries.")


@api_model
class MoveFolderModel:
    destination: AnnotatedFolder = api_field(
        description="Where the folder has to be moved to.",
        example="/my/fine/folder",
    )
