type = "Component"
display_name = "Plugins: Blue Coat"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["mohamed.saleh@checkmk.com"]
description = """
Plugins for Blue Coat (Symantec) ProxySG appliances.
"""
