[project]
name = "cmk-livestatus-client"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools]
# cmk.livestatus_client was exposed as livestatus from the beginning of Checkmk.
# We keep deploying it with the old name for compatibility for now.
packages = ["cmk", "cmk.livestatus_client", "livestatus"]

[tool.setuptools.package-data]
"cmk.livestatus_client" = ["py.typed"]
"livestatus" = ["py.typed"]

[tool.bandit]
