---
mssql:
    defaults: # mandatory, to be used if no specific config
        authentication: # mandatory
            username: "foo" # mandatory, default: system
            password: "bar" # optional, no default
            access_token: "baz" # optional, no default
        connection: # optional
            hostname: "localhost" # optional, default: "localhost"
            failoverpartner: "localhost2" # optional, no default
            port: 1433 # optional, default: 1433
            socket: "C:\\path\\to\\file" # optional, no default
            tls: # optional
                ca: "C:\\path\\to\\file" # mandatory
                client_certificate: "C:\\path\\to\\file" # mandatory
            timeout: 5 # optional, default: 5
        sections: # optional
            always: # optional, default
                - "instance"
                - "databases"
                - "counters"
                - "blocked_sessions"
                - "transactionlogs"
                - "clusters"
                - "mirroring"
                - "availability_groups"
                - "connections"
            cached: # optional, default
                - "tablespaces"
                - "datafiles"
                - "backup"
                - "jobs"
            disabled: # optional, no default
                - "someOtherSQL"
            cache_age: 600 # optional, default: 600
        instances: # optional
            detect: yes # optional, default
            include: ["foo", "bar"] # optional, no default /prio 2; use instance even if excluded
            exclude: ["baz"] # optional, no default / prio 3
        mode: "port" # optional, default: "port" / can be "socket", "port" or "special"
    instances: # optional
        - instance: "INST1" # mandatory
          authentication: # optional, no default / same as above
          connection: # optional, no default / same as above
          alias: "someApplicationName" # optional , no default
          piggyback: # optional, no default
              hostname: "myPiggybackHost" # mandatory
              sections: # optional, no default / same as above
