Document: check-mk
Title: Debian check-mk Manual
Author: <insert document author here>
Abstract: This manual describes what check-mk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/check-mk/check-mk.sgml.gz

Format: postscript
Files: /usr/share/doc/check-mk/check-mk.ps.gz

Format: text
Files: /usr/share/doc/check-mk/check-mk.text.gz

Format: HTML
Index: /usr/share/doc/check-mk/html/index.html
Files: /usr/share/doc/check-mk/html/*.html


