multisite_builtin_views = {
'allhosts': {'column_headers': 'pergroup',
              'datasource': 'hosts',
              'description': 'Overall state of allhosts, with counts of services in the various states.',
              'group_painters': [('sitealias', None)],
              'hard_filters': [],
              'hard_filtervars': [],
              'hidden': False,
              'hide_filters': [],
              'layout': 'table_3c',
              'mustsearch': False,
              'name': 'allhosts',
              'owner': '',
              'painters': [('host_state', None),
                           ('host', 'host'),
                           ('num_services_ok', None),
                           ('num_services_warn', None),
                           ('num_services_unknown', None),
                           ('num_services_crit', None),
                           ('num_services_pending', None)],
              'public': True,
              'show_filters': ['siteopt', 'hostregex', 'opthostgroup'],
              'sorters': [('site', False), ('site_host', False)],
              'title': 'All hosts'},
 'host': {'column_headers': 'perpage',
          'datasource': 'services',
          'description': 'All services of a given host. The host and site must be set via HTML variables.',
          'group_painters': [],
          'hard_filters': [],
          'hard_filtervars': [('st0', 'on'),
                              ('st1', 'on'),
                              ('st2', 'on'),
                              ('st3', 'on'),
                              ('stp', 'on')],
          'hidden': True,
          'hide_filters': ['site', 'host'],
          'layout': 'boxed_2',
          'mustsearch': False,
          'name': 'host',
          'owner': '',
          'painters': [('service_state', None),
                       ('service_description', None),
                       ('svc_plugin_output', None),
                       ('svc_state_age', None),
                       ('svc_check_age', None)],
          'public': True,
          'show_filters': ['svcstate'],
          'sorters': [('svcdescr', False)],
          'title': 'Services of Host'},
 'hostgroup': {'datasource': 'hosts',
               'group_painters': [('site_icon', None),
                                  ('sitealias', 'sitehosts')],
               'hard_filters': [],
               'hard_filtervars': [],
               'hidden': True,
               'hide_filters': ['hostgroup'],
               'layout': 'boxed_2',
               'mustsearch': False,
               'name': 'hostgroup',
               'owner': '',
               'painters': [('host_state', None),
                            ('host', 'host'),
                            ('alias', None),
                            ('num_services_ok', None),
                            ('num_services_warn', None),
                            ('num_services_unknown', None),
                            ('num_services_crit', None),
                            ('num_services_pending', None)],
               'public': True,
               'show_filters': [],
               'sorters': [('site', False), ('site_host', False)],
               'title': 'Hostgroup'},
 'hostgroups': {'column_headers': 'pergroup',
                'datasource': 'hostgroups',
                'description': 'A short overview over all host groups, without an explicity listing of the actual hosts',
                'group_painters': [('sitealias', 'sitehosts')],
                'hard_filters': [],
                'hard_filtervars': [],
                'hidden': False,
                'hide_filters': [],
                'layout': 'boxed_3',
                'mustsearch': False,
                'name': 'hostgroups',
                'owner': '',
                'painters': [('hg_name', 'hostgroup'),
                             ('hg_alias', None),
                             ('hg_num_hosts_up', None),
                             ('hg_num_hosts_down', None),
                             ('hg_num_hosts_unreach', None),
                             ('hg_num_hosts_pending', None),
                             ('hg_num_services_ok', None),
                             ('hg_num_services_warn', None),
                             ('hg_num_services_crit', None),
                             ('hg_num_services_unknown', None),
                             ('hg_num_services_pending', None)],
                'public': True,
                'show_filters': [],
                'sorters': [],
                'title': 'Hostgroups'},
 'hostproblems': {'column_headers': 'off',
                  'datasource': 'hosts',
                  'description': 'A complete list of all host problems with a search form for selecting handled and unhandled',
                  'group_painters': [('host_state', None)],
                  'hard_filters': ['host_scheduled_downtime_depth'],
                  'hard_filtervars': [('is_host_scheduled_downtime_depth',
                                       '0'),
                                      ('is_host_in_notification_period',
                                       '-1'),
                                      ('st0', ''),
                                      ('st1', 'on'),
                                      ('st2', 'on'),
                                      ('stp', ''),
                                      ('opthostgroup', '')],
                  'hidden': False,
                  'hide_filters': [],
                  'layout': 'boxed_3',
                  'mustsearch': False,
                  'name': 'hostproblems',
                  'owner': '',
                  'painters': [('host', 'host'),
                               ('host_plugin_output', None),
                               ('num_services', None)],
                  'public': True,
                  'show_filters': ['host_in_notification_period',
                                   'hoststate',
                                   'opthostgroup'],
                  'sorters': [],
                  'title': 'Host problems'},
 'hoststatus': {'datasource': 'hosts',
                'group_painters': [],
                'hard_filters': [],
                'hard_filtervars': [],
                'hidden': True,
                'hide_filters': ['site', 'host'],
                'layout': 'dataset',
                'mustsearch': False,
                'name': 'hoststatus',
                'owner': '',
                'painters': [('host_black', None),
                             ('num_services', 'host'),
                             ('host_state', None),
                             ('site_icon', 'sitehosts'),
                             ('alias', None),
                             ('host', None),
                             ('sitename_plain', None),
                             ('sitealias', None)],
                'public': True,
                'show_filters': [],
                'sorters': [],
                'title': 'Status of Host'},
 'searchhost': {'column_headers': 'pergroup',
                'datasource': 'hosts',
                'description': 'A form for search hosts after a couple of criteria.',
                'group_painters': [('sitealias', None)],
                'hard_filters': [],
                'hard_filtervars': [('is_host_scheduled_downtime_depth',
                                     '-1'),
                                    ('is_host_in_notification_period', '-1'),
                                    ('st0', ''),
                                    ('st1', ''),
                                    ('st2', ''),
                                    ('stp', ''),
                                    ('site', ''),
                                    ('host', ''),
                                    ('is_summary_host', '-1'),
                                    ('opthostgroup', ''),
                                    ('host_check_command', ''),
                                    ('limit', '0')],
                'hidden': False,
                'hide_filters': [],
                'layout': 'table_3c',
                'mustsearch': True,
                'name': 'searchhost',
                'owner': '',
                'painters': [('host_state', None),
                             ('host', 'host'),
                             ('num_services_ok', None),
                             ('num_services_warn', None),
                             ('num_services_crit', None),
                             ('num_services_unknown', None),
                             ('num_services_pending', None),
                             ('host_plugin_output', None)],
                'public': True,
                'show_filters': ['host_scheduled_downtime_depth',
                                 'host_in_notification_period',
                                 'hoststate',
                                 'siteopt',
                                 'hostregex',
                                 'summary_host',
                                 'opthostgroup',
                                 'host_check_command',
                                 'limit'],
                'sorters': [],
                'title': 'Host search'},
 'searchsvc': {'column_headers': 'off',
               'datasource': 'services',
               'description': 'Almost all available filters, used for searching services and maybe doing actions',
               'group_painters': [('sitealias', 'sitehosts'),
                                  ('host', 'host')],
               'hard_filters': [],
               'hard_filtervars': [('is_service_in_notification_period',
                                    '-1'),
                                   ('optservicegroup', ''),
                                   ('is_service_notifications_enabled',
                                    '-1'),
                                   ('is_host_in_notification_period', '-1'),
                                   ('is_in_downtime', '-1'),
                                   ('is_service_scheduled_downtime_depth',
                                    '-1'),
                                   ('is_service_acknowledged', '-1'),
                                   ('host', ''),
                                   ('is_service_active_checks_enabled',
                                    '-1'),
                                   ('service', ''),
                                   ('check_command', ''),
                                   ('is_show_summary_hosts', '-1'),
                                   ('st0', 'on'),
                                   ('st1', 'on'),
                                   ('st2', 'on'),
                                   ('st3', 'on'),
                                   ('stp', 'on'),
                                   ('opthostgroup', ''),
                                   ('service_output', ''),
                                   ('is_service_is_flapping', '-1')],
               'hidden': False,
               'hide_filters': [],
               'layout': 'boxed_2',
               'mustsearch': True,
               'name': 'searchsvc',
               'owner': '',
               'painters': [('service_state', None),
                            ('service_description', None),
                            ('svc_state_age', None),
                            ('svc_plugin_output', None)],
               'public': True,
               'show_filters': ['service_in_notification_period',
                                'optservicegroup',
                                'service_notifications_enabled',
                                'host_in_notification_period',
                                'in_downtime',
                                'service_scheduled_downtime_depth',
                                'service_acknowledged',
                                'hostregex',
                                'service_active_checks_enabled',
                                'serviceregex',
                                'check_command',
                                'show_summary_hosts',
                                'svcstate',
                                'opthostgroup',
                                'output',
                                'service_is_flapping'],
               'sorters': [('site', False),
                           ('site_host', False),
                           ('svcdescr', False)],
               'title': 'Service search'},
 'servicedesc': {'datasource': 'services',
                 'group_painters': [('service_state', None)],
                 'hard_filters': [],
                 'hard_filtervars': [],
                 'hidden': True,
                 'hide_filters': ['service'],
                 'layout': 'table_3c',
                 'mustsearch': False,
                 'name': 'servicedesc',
                 'owner': '',
                 'painters': [('service_state', None),
                              ('host', 'host'),
                              ('svc_plugin_output', None)],
                 'public': True,
                 'show_filters': [],
                 'sorters': [('svcstate', False),
                             ('site', False),
                             ('site_host', False)],
                 'title': 'All Services with this description:'},
 'servicegroup': {'column_headers': 'pergroup',
                  'datasource': 'services',
                  'description': '',
                  'group_painters': [('sitealias', 'sitehosts'),
                                     ('host', 'host')],
                  'hard_filters': [],
                  'hard_filtervars': [],
                  'hidden': True,
                  'hide_filters': ['servicegroup'],
                  'layout': 'table',
                  'mustsearch': False,
                  'name': 'servicegroup',
                  'owner': '',
                  'painters': [('service_state', None),
                               ('svc_state_age', None),
                               ('service_description', None),
                               ('svc_plugin_output', None)],
                  'public': True,
                  'show_filters': [],
                  'sorters': [('site', False),
                              ('site_host', False),
                              ('svcdescr', False)],
                  'title': 'Servicegroup'},
 'sitehosts': {'column_headers': 'off',
               'datasource': 'hosts',
               'description': 'Link view showing all\r\nhosts of one site',
               'group_painters': [('site_icon', None), ('sitealias', None)],
               'hard_filters': [],
               'hard_filtervars': [],
               'hidden': True,
               'hide_filters': ['site'],
               'layout': 'boxed_2',
               'mustsearch': False,
               'name': 'sitehosts',
               'owner': '',
               'painters': [('host_state', None),
                            ('host', 'host'),
                            ('alias', 'hoststatus'),
                            ('num_services_ok', None),
                            ('num_services_warn', None),
                            ('num_services_unknown', None),
                            ('num_services_crit', None),
                            ('num_services_pending', None)],
               'public': True,
               'show_filters': [],
               'sorters': [('site', False), ('site_host', False)],
               'title': 'All hosts of Site'},
 'svcbygroups': {'column_headers': 'pergroup',
                 'datasource': 'servicesbygroup',
                 'description': 'Service grouped by service groups. Services not member of a group are not displayed. Services being in more groups, are displayed once for each group',
                 'group_painters': [('sg_alias', 'servicegroup')],
                 'hard_filters': [],
                 'hard_filtervars': [],
                 'hidden': False,
                 'hide_filters': [],
                 'layout': 'boxed_2',
                 'mustsearch': False,
                 'name': 'svcbygroups',
                 'owner': '',
                 'painters': [('host', None),
                              ('service_state', None),
                              ('svc_state_age', None),
                              ('service_description', None),
                              ('svc_plugin_output', None)],
                 'public': True,
                 'show_filters': [],
                 'sorters': [('servicegroup', False),
                             ('site_host', False),
                             ('svcdescr', False)],
                 'title': 'Services by group'},
 'svcbyhgroups': {'column_headers': 'pergroup',
                 'datasource': 'servicesbyhostgroup',
                 'description': 'Service grouped by host groups. Services not member of a host group are not displayed. Services being in more groups, are displayed once for each group',
                 'group_painters': [('hg_alias', 'hostgroup')],
                 'hard_filters': [],
                 'hard_filtervars': [],
                 'hidden': False,
                 'hide_filters': [],
                 'layout': 'boxed_2',
                 'mustsearch': False,
                 'name': 'svcbygroups',
                 'owner': '',
                 'painters': [('host', None),
                              ('service_state', None),
                              ('svc_state_age', None),
                              ('service_description', None),
                              ('svc_plugin_output', None)],
                 'public': True,
                 'show_filters': [],
                 'sorters': [('hostgroup', False),
                             ('site_host', False),
                             ('svcdescr', False)],
                 'title': 'Serv. by host groups'},
 'svcgroups': {'column_headers': 'pergroup',
               'datasource': 'servicegroups',
               'description': 'A short overview over all servicegroups, without explicity listing of the actual hosts and services',
               'group_painters': [('sitealias', 'sitehosts')],
               'hard_filters': [],
               'hard_filtervars': [],
               'hidden': False,
               'hide_filters': [],
               'layout': 'boxed_3',
               'mustsearch': False,
               'name': 'svcgroups',
               'owner': '',
               'painters': [('sg_name', 'servicegroup'),
                            ('sg_alias', None),
                            ('sg_num_services_ok', None),
                            ('sg_num_services_warn', None),
                            ('sg_num_services_crit', None),
                            ('sg_num_services_unknown', None),
                            ('sg_num_services_pending', None)],
               'public': True,
               'show_filters': [],
               'sorters': [],
               'title': 'Servicegroups'},
 'svcproblems': {'column_headers': 'pergroup',
                 'datasource': 'services',
                 'description': 'All problems of services not currently in a downtime.\r\n\r\n',
                 'group_painters': [('service_state', None)],
                 'hard_filters': ['in_downtime'],
                 'hard_filtervars': [('is_in_downtime', '0'),
                                     ('is_service_acknowledged', '-1'),
                                     ('st0', ''),
                                     ('st1', 'on'),
                                     ('st2', 'on'),
                                     ('st3', 'on'),
                                     ('stp', '')],
                 'hidden': False,
                 'hide_filters': [],
                 'layout': 'table',
                 'mustsearch': False,
                 'name': 'svcproblems',
                 'owner': '',
                 'painters': [('host', 'host'),
                              ('service_description', None),
                              ('svc_state_age', None),
                              ('svc_plugin_output', None),
                              ('link_to_pnp_service', None)],
                 'public': True,
                 'show_filters': ['service_acknowledged', 'svcstate'],
                 'sorters': [('svcstate', True),
                             ('stateage', False),
                             ('svcdescr', False)],
                 'title': 'Service problems'},


'hostsbygroup': {'column_headers': 'pergroup',
                  'datasource': 'hostsbygroup',
                  'description': 'A complete listing of\r\nall host groups and each of their hosts',
                  'group_painters': [('sitealias', 'sitehosts'),
                                     ('hg_alias', 'hostgroup')],
                  'hard_filters': [],
                  'hard_filtervars': [('is_host_scheduled_downtime_depth',
                                       '-1'),
                                      ('is_host_in_notification_period',
                                       '-1'),
                                      ('site', ''),
                                      ('is_summary_host', '-1'),
                                      ('limit', '0')],
                  'hidden': False,
                  'hide_filters': [],
                  'layout': 'boxed_2',
                  'mustsearch': False,
                  'name': 'hostsbygroup',
                  'owner': '',
                  'painters': [('host_state', None),
                            ('host', 'host'),
                            ('alias', 'hoststatus'),
                            ('num_services_ok', None),
                            ('num_services_warn', None),
                            ('num_services_unknown', None),
                            ('num_services_crit', None),
                            ('num_services_pending', None)],
                  'public': True,
                  'show_filters': ['host_scheduled_downtime_depth',
                                   'host_in_notification_period',
                                   'siteopt',
                                   'summary_host',
                                   'limit'],
                  'sorters': [('site', False),
                              ('hostgroup', False),
                              ('site_host', False)],
                  'title': 'Hosts by group'}

}
