#!/usr/bin/python

# When copying stuff from /var/lib/check_mk/web/$USER/views.mk, 
# be sure to set
# - owner to ''
# - public to True
# - set users in linked views to ''

multisite_builtin_views = {
 ('allhosts'): {'datasource': 'hosts',
              'group_painters': [('sitealias', None)],
              'hard_filters': [],
              'hard_filtervars': [],
              'hidden': False,
              'hide_filters': [],
              'layout': 'table_3c',
              'mustsearch': False,
              'name': 'allhosts',
              'owner': '',
              'painters': [('host_state', None),
                           ('host', None),
                           ('alias', ( 'hoststatus')),
                           ('num_services_ok', None),
                           ('num_services_warn', None),
                           ('num_services_unknown', None),
                           ('num_services_crit', None),
                           ('num_services_pending', None)],
              'public': True,
              'show_filters': ['site', 'hostregex', 'opthostgroup'],
              'sorters': [('site', False), ('site_host', False)],
              'title': 'All hosts'},
 ( 'host'): {'datasource': 'services',
          'group_painters': [('host_black', ( 'hoststatus'))],
          'hard_filters': [],
          'hard_filtervars': [],
          'hidden': True,
          'hide_filters': ['site', 'host'],
          'layout': 'boxed_2',
          'mustsearch': False,
          'name': 'host',
          'owner': '',
          'painters': [('service_state', None),
                       ('svc_state_age', None),
                       ('service_description', None),
                       ('svc_plugin_output', None)],
          'public': True,
          'show_filters': [],
          'sorters': [('svcdescr', False)],
          'title': 'Services of Host'},
( 'hoststatus'): {'datasource': 'hosts',
                'group_painters': [],
                'hard_filters': [],
                'hard_filtervars': [],
                'hidden': True,
                'hide_filters': ['host'],
                'layout': 'dataset',
                'mustsearch': False,
                'name': 'hoststatus',
                'owner': '',
                'painters': [('host_black', None),
                             ('num_services', ( 'host')),
                             ('host_state', None),
                             ('site_icon', ( 'sitehosts')),
                             ('alias', None),
                             ('host', None),
                             ('sitename_plain', None),
                             ('sitealias', None)],
                'public': True,
                'show_filters': [],
                'sorters': [],
                'title': 'Status of Host'},
( 'searchsvc'): {'datasource': 'services',
               'group_painters': [('sitealias', ( 'sitehosts')),
                                  ('host', None)],
               'hard_filters': [],
               'hard_filtervars': [],
               'hidden': False,
               'hide_filters': [],
               'layout': 'boxed_4',
               'mustsearch': True,
               'name': 'searchsvc',
               'owner': '',
               'painters': [('service_state', None),
                            ('service_description', None),
                            ('svc_state_age', None),
                            ('svc_plugin_output', None)],
               'public': True,
               'show_filters': ['service_in_notification_period',
                                'optservicegroup',
                                'service_notifications_enabled',
                                'service',
                                'host_in_notification_period',
                                'in_downtime',
                                'service_scheduled_downtime_depth',
                                'service_acknowledged',
                                'hostregex',
                                'service_active_checks_enabled',
                                'check_command',
                                'show_summary_hosts',
                                'svcstate',
                                'opthostgroup',
                                'output',
                                'service_is_flapping'],
               'sorters': [('site', False),
                           ('site_host', False),
                           ('svcdescr', False)],
               'title': 'Search service'},
'servicedesc': {'datasource': 'services',
                 'group_painters': [('service_state', None)],
                 'hard_filters': [],
                 'hard_filtervars': [],
                 'hidden': True,
                 'hide_filters': ['service'],
                 'layout': 'table_3c',
                 'mustsearch': False,
                 'name': 'servicedesc',
                 'owner': '',
                 'painters': [('service_state', None),
                              ('host', ( 'host')),
                              ('svc_plugin_output', None)],
                 'public': True,
                 'show_filters': [],
                 'sorters': [('svcstate', False),
                             ('site', False),
                             ('site_host', False)],
                 'title': 'All Services with this description:'},
'servicegroup': {'datasource': 'services',
                  'group_painters': [('sitealias', ( 'sitehosts')),
                                     ('host', ( 'host'))],
                  'hard_filters': [],
                  'hard_filtervars': [],
                  'hidden': True,
                  'hide_filters': ['servicegroup'],
                  'layout': 'table',
                  'mustsearch': False,
                  'name': 'servicegroup',
                  'owner': '',
                  'painters': [('host', None),
                               ('service_state', None),
                               ('svc_state_age', None),
                               ('service_description', None),
                               ('svc_plugin_output', None)],
                  'public': True,
                  'show_filters': [],
                  'sorters': [('site', False),
                              ('site_host', False),
                              ('svcdescr', False)],
                  'title': 'Servicegroup'},
'services': {'datasource': 'services',
              'group_painters': [('service_description',
                                  'servicedesc')],
              'hard_filters': [],
              'hard_filtervars': [],
              'hidden': False,
              'hide_filters': [],
              'layout': 'boxed_4',
              'mustsearch': False,
              'name': 'services',
              'owner': '',
              'painters': [('host', 'host'),
                           ('svc_state_age', None),
                           ('service_state', None)],
              'public': True,
              'show_filters': ['hostgroup'],
              'sorters': [('svcdescr', False)],
              'title': 'Services'},

'services': {'datasource': 'services',
              'group_painters': [('service_description', None)],
              'hard_filters': [],
              'hard_filtervars': [],
              'hidden': False,
		     'mustsearch' : False,
              'hide_filters': [],
              'layout': 'boxed_4',
              'name': 'services',
              'owner': '',
              'painters': [('host',None), ('svc_state_age',None), ('service_state',None)],
              'public': True,
              'show_filters': ['hostgroup'],
              'sorters': [('svcdescr', False)],
              'title': 'Services'},
'hostgroup': {'datasource': 'hosts',
               'group_painters': [('site_icon', None),
                                  ('sitealias',
                                   'sitehosts')],
               'hard_filters': [],
               'hard_filtervars': [],
               'hidden': True,
		     'mustsearch' : False,
               'hide_filters': ['hostgroup'],
               'layout': 'boxed_2',
               'name': 'hostgroup',
               'owner': '',
               'painters': [('host_state', None),
                            ('host', 'host'),
                            ('alias', None),
                            ('num_services_ok', None),
                            ('num_services_warn', None),
                            ('num_services_unknown', None),
                            ('num_services_crit', None),
                            ('num_services_pending', None)],
               'public': True,
               'show_filters': [],
               'sorters': [('site', False), ('site_host', False)],
               'title': 'Hostgroup'},

'sitehosts': {'datasource': 'hosts',
               'group_painters': [('site_icon', None), ('sitealias', None)],
               'hard_filters': [],
               'hard_filtervars': [],
               'hidden': True,
		     'mustsearch' : False,
               'hide_filters': ['site'],
               'layout': 'boxed_2',
               'name': 'sitehosts',
               'owner': '',
               'painters': [('host_state', None),
                            ('host', 'host'),
                            ('alias', None),
                            ('num_services_ok', None),
                            ('num_services_warn', None),
                            ('num_services_unknown', None),
                            ('num_services_crit', None),
                            ('num_services_pending', None)],
               'public': True,
               'show_filters': [],
               'sorters': [('site', False), ('site_host', False)],
               'title': 'Hosts of Site'}

}
