#!/usr/bin/env python3
# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# mypy: disable-error-code="explicit-any"

"""Shared helpers for host attributes tests across editions."""

from typing import Any

BASE_EXPECTED_ATTRIBUTES: dict[str, dict[str, Any]] = {
    "additional_ipv4addresses": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": ["ip-v4"],
        "editable": True,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Network address",
    },
    "additional_ipv6addresses": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": ["ip-v6"],
        "editable": True,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Network address",
    },
    "alias": {
        "class_name": "NagiosTextAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": True,
        "show_inherited_value": True,
        "topic": "Basic settings",
    },
    "contactgroups": {
        "class_name": "ContactGroupsAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Basic settings",
    },
    "ipaddress": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": ["ip-v4"],
        "editable": True,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": True,
        "show_inherited_value": True,
        "topic": "Network address",
    },
    "ipv6address": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": ["ip-v6"],
        "editable": True,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": True,
        "show_inherited_value": True,
        "topic": "Network address",
    },
    "locked_attributes": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": False,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": True,
        "show_in_host_search": False,
        "show_in_table": False,
        "show_inherited_value": False,
        "topic": "Creation / Locking",
    },
    "locked_by": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": False,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": False,
        "topic": "Creation / Locking",
    },
    "management_address": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Management board",
    },
    "management_ipmi_credentials": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Management board",
    },
    "management_protocol": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Management board",
    },
    "management_snmp_community": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Management board",
    },
    "meta_data": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": False,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": False,
        "show_in_table": False,
        "show_inherited_value": False,
        "topic": "Creation / Locking",
    },
    "network_scan": {
        "class_name": "HostAttributeNetworkScan",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": False,
        "show_in_host_search": False,
        "show_in_table": False,
        "show_inherited_value": False,
        "topic": "Network scan",
    },
    "network_scan_result": {
        "class_name": "NetworkScanResultAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": False,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": False,
        "show_in_host_search": False,
        "show_in_table": False,
        "show_inherited_value": False,
        "topic": "Network scan",
    },
    "parents": {
        "class_name": "ParentsAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": True,
        "show_inherited_value": True,
        "topic": "Basic settings",
    },
    "site": {
        "class_name": "SiteAttribute",
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": True,
        "show_inherited_value": True,
        "topic": "Basic settings",
    },
    "snmp_community": {
        "class_name": "ValueSpecAttribute",
        "depends_on_roles": [],
        "depends_on_tags": ["snmp"],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Monitoring agents",
    },
    "tag_address_family": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": True,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Network address",
    },
    "tag_agent": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": True,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Monitoring agents",
    },
    "tag_snmp_ds": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": True,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Monitoring agents",
    },
    "tag_piggyback": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": True,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Monitoring agents",
    },
    "labels": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Custom attributes",
    },
    "inventory_failed": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": False,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": False,
        "show_in_host_search": False,
        "show_in_table": False,
        "show_inherited_value": False,
        "topic": "Creation / Locking",
    },
    "waiting_for_discovery": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": False,
        "from_config": False,
        "show_in_folder": False,
        "show_in_form": False,
        "show_in_host_search": False,
        "show_in_table": False,
        "show_inherited_value": False,
        "topic": "Custom attributes",
    },
}

CMK_AGENT_CONNECTION_ATTR: dict[str, dict[str, Any]] = {
    "cmk_agent_connection": {
        "depends_on_roles": [],
        "depends_on_tags": ["checkmk-agent"],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Monitoring agents",
    },
}

METRICS_ASSOCIATION_ATTR: dict[str, dict[str, Any]] = {
    "metrics_association": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": False,
        "show_inherited_value": True,
        "topic": "Monitoring agents",
    },
}

BAKE_AGENT_PACKAGE_ATTR: dict[str, dict[str, Any]] = {
    "bake_agent_package": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": False,
        "show_in_host_search": False,
        "show_in_table": False,
        "show_inherited_value": False,
        "topic": "Monitoring agents",
    },
}

RELAY_ATTR: dict[str, dict[str, Any]] = {
    "relay": {
        "depends_on_roles": [],
        "depends_on_tags": [],
        "editable": True,
        "from_config": False,
        "show_in_folder": True,
        "show_in_form": True,
        "show_in_host_search": True,
        "show_in_table": True,
        "show_inherited_value": True,
        "topic": "Basic settings",
    },
}
