LCAB := lcab

LCAB_BUILD := $(BUILD_HELPER_DIR)/$(LCAB)-build
LCAB_INSTALL := $(BUILD_HELPER_DIR)/$(LCAB)-install

.PHONY: $(LCAB_BUILD)
$(LCAB_BUILD):
	bazel build @$(LCAB)//:$(LCAB)

.PHONY: $(LCAB_INSTALL)
$(LCAB_INSTALL): $(LCAB_BUILD)
	$(RSYNC) --chmod=u+w $(BAZEL_BIN_EXT)/$(LCAB)/$(LCAB)/bin $(DESTDIR)$(OMD_ROOT)/
