LCAB := lcab

LCAB_BUILD := $(BUILD_HELPER_DIR)/$(LCAB)-build
LCAB_INSTALL := $(BUILD_HELPER_DIR)/$(LCAB)-install

$(LCAB_BUILD):
	$(BAZEL_BUILD) @$(LCAB)//:$(LCAB)

$(LCAB_INSTALL): $(LCAB_BUILD)
	$(RSYNC) --chmod=u+w $(BAZEL_BIN)/$(LCAB)/$(LCAB)/bin $(DESTDIR)$(OMD_ROOT)/
