"""link_shared_typing: link the Bazel-generated cmk-shared-typing into a package.

cmk-shared-typing's TypeScript definitions are generated by Bazel, so they
cannot come through the pnpm lockfile like an ordinary workspace dependency.
Every package which needs them links the generated `js_library` directly
instead, and resolves it via the `*` fallback path in its `tsconfig.json`.

That link is the same four lines in each package, and rules_js has already
changed their spelling once: `npm_link_package` lost its `root_package`
argument in rules_js 3.0.0, which had to be deleted in every copy by hand.
Keep it in one place so the next such change is a one-line fix:

    load("//bazel/rules:link_shared_typing.bzl", "link_shared_typing")

    link_shared_typing()

and depend on `:node_modules/cmk-shared-typing-bzl` as usual.
"""

load("@aspect_rules_js//npm:defs.bzl", "npm_link_package")

# The link target name, also the directory the package appears under in the
# package's node_modules tree. Callers spell it out in their deps.
LINK_NAME = "node_modules/cmk-shared-typing-bzl"

def link_shared_typing(name = LINK_NAME, visibility = ["//visibility:private"]):
    """Links cmk-shared-typing into the calling package's node_modules.

    Args:
      name: name of the link target to create.
      visibility: visibility of the link target. The default is private
        because each package creates its own package store; linking against
        another package's store does not give you a usable node_modules tree.
    """
    npm_link_package(
        name = name,
        package = "cmk-shared-typing",
        src = "//packages/cmk-shared-typing:cmk_shared_typing_ts",
        visibility = visibility,
    )
