[project]
name = "cmk-server-side-calls"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-data]
"cmk.server_side_calls" = ["py.typed"]

[tool.bandit]
