# Cargo.toml file used to lock the deps for bazel.
#
# See Also:
#    https://earthly.dev/blog/rust-monorepo/

[workspace]
members = [
    "cmk-agent-ctl",
    "mk-sql",
]
package.edition = "2021"
resolver = "2"

[profile.release.package.cmk-agent-ctl]
opt-level = "z" # Optimize for size.
