# generated by datamodel-codegen:
#   filename:  vue_validators.json
#   timestamp: 2024-05-23T12:11:54+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Union


@dataclass
class IsNumber:
    vue_type: str = "is_number"
    error_message: Optional[str] = None


@dataclass
class LengthInRange:
    vue_type: str = "length_in_range"
    min_value: Optional[int] = None
    max_value: Optional[int] = None
    error_message: Optional[str] = None


@dataclass
class NumberInRange:
    vue_type: str = "number_in_range"
    min_value: Optional[int] = None
    max_value: Optional[int] = None
    error_message: Optional[str] = None


VueValidators = Union[IsNumber, NumberInRange, LengthInRange]


@dataclass
class Model:
    all_schemas: Optional[List[VueValidators]] = None
