#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from collections.abc import Sequence

import pytest

from cmk.agent_based.v2 import Result, Service, State, StringTable
from cmk.plugins.ibm.agent_based.ibm_svc_portsas import (
    check_ibm_svc_portsas,
    discover_ibm_svc_portsas,
    IbmSvcPortsasParams,
    parse_ibm_svc_portsas,
)

STRING_TABLE: StringTable = [
    [
        "0",
        "1",
        "6Gb",
        "1",
        "node1",
        "500507680305D3C0",
        "online",
        "",
        "host",
        "host_controller",
        "0",
        "1",
    ],
    [
        "1",
        "2",
        "6Gb",
        "1",
        "node1",
        "500507680309D3C0",
        "online",
        "",
        "host",
        "host_controller",
        "0",
        "2",
    ],
    [
        "2",
        "3",
        "6Gb",
        "1",
        "node1",
        "50050768030DD3C0",
        "online",
        "",
        "host",
        "host_controller",
        "0",
        "3",
    ],
    [
        "3",
        "4",
        "6Gb",
        "1",
        "node1",
        "500507680311D3C0",
        "offline",
        "500507680474F03F",
        "none",
        "enclosure",
        "0",
        "4",
    ],
    [
        "4",
        "5",
        "N/A",
        "1",
        "node1",
        "500507680315D3C0",
        "offline_unconfigured",
        "",
        "none",
        "host_controller",
        "1",
        "1",
    ],
    [
        "5",
        "6",
        "N/A",
        "1",
        "node1",
        "500507680319D3C0",
        "offline_unconfigured",
        "",
        "none",
        "host_controller",
        "1",
        "2",
    ],
    [
        "6",
        "7",
        "N/A",
        "1",
        "node1",
        "50050768031DD3C0",
        "offline_unconfigured",
        "",
        "none",
        "host_controller",
        "1",
        "3",
    ],
    [
        "7",
        "8",
        "N/A",
        "1",
        "node1",
        "500507680321D3C0",
        "offline_unconfigured",
        "",
        "none",
        "host_controller",
        "1",
        "4",
    ],
    [
        "8",
        "1",
        "6Gb",
        "2",
        "node2",
        "500507680305D3C1",
        "online",
        "",
        "host",
        "host_controller",
        "0",
        "1",
    ],
    [
        "9",
        "2",
        "6Gb",
        "2",
        "node2",
        "500507680309D3C1",
        "online",
        "",
        "host",
        "host_controller",
        "0",
        "2",
    ],
    [
        "10",
        "3",
        "6Gb",
        "2",
        "node2",
        "50050768030DD3C1",
        "online",
        "",
        "host",
        "host_controller",
        "0",
        "3",
    ],
    [
        "11",
        "4",
        "6Gb",
        "2",
        "node2",
        "500507680311D3C1",
        "offline",
        "500507680474F07F",
        "none",
        "enclosure",
        "0",
        "4",
    ],
    [
        "12",
        "5",
        "N/A",
        "2",
        "node2",
        "500507680315D3C1",
        "offline_unconfigured",
        "",
        "none",
        "host_controller",
        "1",
        "1",
    ],
    [
        "13",
        "6",
        "N/A",
        "2",
        "node2",
        "500507680319D3C1",
        "offline_unconfigured",
        "",
        "none",
        "host_controller",
        "1",
        "2",
    ],
    [
        "14",
        "7",
        "N/A",
        "2",
        "node2",
        "50050768031DD3C1",
        "offline_unconfigured",
        "",
        "none",
        "host_controller",
        "1",
        "3",
    ],
    [
        "15",
        "8",
        "N/A",
        "2",
        "node2",
        "500507680321D3C1",
        "offline_unconfigured",
        "",
        "none",
        "host_controller",
        "1",
        "4",
    ],
]


@pytest.mark.parametrize(
    "string_table, expected_discoveries",
    [
        (
            STRING_TABLE,
            [
                Service(item="Node 1 Slot 0 Port 1", parameters={"current_state": "online"}),
                Service(item="Node 1 Slot 0 Port 2", parameters={"current_state": "online"}),
                Service(item="Node 1 Slot 0 Port 3", parameters={"current_state": "online"}),
                Service(item="Node 1 Slot 0 Port 4", parameters={"current_state": "offline"}),
                Service(item="Node 2 Slot 0 Port 1", parameters={"current_state": "online"}),
                Service(item="Node 2 Slot 0 Port 2", parameters={"current_state": "online"}),
                Service(item="Node 2 Slot 0 Port 3", parameters={"current_state": "online"}),
                Service(item="Node 2 Slot 0 Port 4", parameters={"current_state": "offline"}),
            ],
        ),
    ],
)
def test_discover_ibm_svc_portsas(
    string_table: StringTable, expected_discoveries: Sequence[Service]
) -> None:
    """Test discovery function for ibm_svc_portsas check."""
    parsed = parse_ibm_svc_portsas(string_table)
    result = list(discover_ibm_svc_portsas(parsed))
    assert sorted(result, key=lambda s: s.item or "") == sorted(
        expected_discoveries, key=lambda s: s.item or ""
    )


@pytest.mark.parametrize(
    "item, params, string_table, expected_results",
    [
        (
            "Node 1 Slot 0 Port 1",
            {"current_state": "online"},
            STRING_TABLE,
            [Result(state=State.OK, summary="Status: online, Speed: 6Gb, Type: host_controller")],
        ),
        (
            "Node 1 Slot 0 Port 2",
            {"current_state": "online"},
            STRING_TABLE,
            [Result(state=State.OK, summary="Status: online, Speed: 6Gb, Type: host_controller")],
        ),
        (
            "Node 1 Slot 0 Port 3",
            {"current_state": "online"},
            STRING_TABLE,
            [Result(state=State.OK, summary="Status: online, Speed: 6Gb, Type: host_controller")],
        ),
        (
            "Node 1 Slot 0 Port 4",
            {"current_state": "offline"},
            STRING_TABLE,
            [Result(state=State.OK, summary="Status: offline, Speed: 6Gb, Type: enclosure")],
        ),
        (
            "Node 2 Slot 0 Port 1",
            {"current_state": "online"},
            STRING_TABLE,
            [Result(state=State.OK, summary="Status: online, Speed: 6Gb, Type: host_controller")],
        ),
        (
            "Node 2 Slot 0 Port 2",
            {"current_state": "online"},
            STRING_TABLE,
            [Result(state=State.OK, summary="Status: online, Speed: 6Gb, Type: host_controller")],
        ),
        (
            "Node 2 Slot 0 Port 3",
            {"current_state": "online"},
            STRING_TABLE,
            [Result(state=State.OK, summary="Status: online, Speed: 6Gb, Type: host_controller")],
        ),
        (
            "Node 2 Slot 0 Port 4",
            {"current_state": "offline"},
            STRING_TABLE,
            [Result(state=State.OK, summary="Status: offline, Speed: 6Gb, Type: enclosure")],
        ),
    ],
)
def test_check_ibm_svc_portsas(
    item: str,
    params: IbmSvcPortsasParams,
    string_table: StringTable,
    expected_results: Sequence[Result],
) -> None:
    """Test check function for ibm_svc_portsas check."""
    parsed = parse_ibm_svc_portsas(string_table)
    result = list(check_ibm_svc_portsas(item, params, parsed))
    assert result == expected_results
