type = "Component"
display_name = "Plugins: Symantec Endpoint Protection"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["mohamed.saleh@checkmk.com"]
description = """
Plugins for Symantec Endpoint Protection client state.
"""
