type = "Component"
display_name = "Plugins: Symantec Endpoint Protection"
has_support_component = true
members_required = 0
description = """
Plugins for Symantec Endpoint Protection client state.
"""
