#!/bin/bash
#
# This checks ALL tests, but on a second run only those
# which need to be run because the code they test has been
# changed or because they previously have failed.
if [ "$1" != "127" ]; then
    set -e -o pipefail
fi

REPO_PATH="$(git rev-parse --show-toplevel)"
PIPENV=pipenv

pushd "$REPO_PATH"/tests >/dev/null
PIPENV_VENV_IN_PROJECT=true \
    PIPENV_NOSPIN=true \
    PIPENV_HIDE_EMOJIS=true \
    PIPENV_NO_INHERIT=true \
    PIPENV_PIPFILE="$REPO_PATH/Pipfile" \
    PIPENV_IGNORE_VIRTUALENVS=1 \
    PYTEST_ARGS=--testmon \
    $PIPENV run make test-unit
popd >/dev/null
