#!/bin/bash
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# This file is for execution by the pre-commit framework.
#
source "$(dirname $0)/lib-precommit"

# Filter out all tests/* and tests-py3/* files.
declare -a FILES

for param in "$@"; do
    if [[ "$param" == tests* ]]; then
        continue
    fi
    FILES+=($param)
done

NUM_PARAM=${#FILES[@]}

if [ "$NUM_PARAM" == "0" ]; then
    echo No files to check. >&2
    exit 0
fi

REPO_PATH="$(git rev-parse --show-toplevel)"
PIPENV="$REPO_PATH/scripts/run-pipenv"

printf -v files " %s" ${FILES[@]}
PYTHON2_FILES=$(python_files 2 "$files")
PYTHON3_FILES=$(python_files 3 "$files")

if [ ! -z "$PYTHON2_FILES" ]; then
    $PIPENV 2 run python -m doctest $PYTHON2_FILES
fi

if [ ! -z "$PYTHON3_FILES" ]; then
    $PIPENV 3 run python -m doctest $PYTHON3_FILES
fi

exit 0
