#!/bin/bash
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

set -e

REPO_PATH=$(dirname $(dirname $(realpath "$0")))
PYTHON_VERSION=$("$REPO_PATH/scripts/detect-python-version" "$@")
exec "$REPO_PATH/scripts/run-pipenv" ${PYTHON_VERSION%.?} run pylint "$@"
