#!/bin/bash
# mypy_path in mypy.ini doesn't support relative paths, so use this wrapper to
# tell mypy about the relevant paths using the MYPYPATH environment variable
set -e

REPO_PATH=$(dirname $(dirname $(realpath "$0")))
PYTHON_VERSION=3.7

# Detect whether or not mypy is available and print out an error that is in the
# same format as mypy issues. This message is understood by e.g. vims ALE and
# displays and error that mypy could not be executed.
VENV_MYPY_PATH="$REPO_PATH/virtual-envs/$PYTHON_VERSION/.venv/bin/mypy"
if [ ! -f "$VENV_MYPY_PATH" ]; then
    # Try to fix this first
    rm -rf "$REPO_PATH/virtual-envs/$PYTHON_VERSION/.venv"
    make --silent -C "$REPO_PATH/virtual-envs/$PYTHON_VERSION" .venv 1>&2

    if [ ! -f "$VENV_MYPY_PATH" ]; then
        for LAST_ARG; do :; done
        echo "$LAST_ARG:1: error: Could not find $VENV_MYPY_PATH"
        exit 1
    fi
fi

# NOTE: We should NOT run this in "$REPO_PATH", otherwise mypy will make paths
# in messages relative, which will confuse e.g. Emacs' flycheck mode.
MYPYPATH="$REPO_PATH:$REPO_PATH/livestatus/api/python:$REPO_PATH/omd/packages/omd:$REPO_PATH/tests-py3:$REPO_PATH/tests-py3/typeshed" \
    exec "$REPO_PATH/scripts/run-pipenv" 3 run mypy \
    --python-version $("$REPO_PATH/scripts/detect-python-version" "$@") \
    --scripts-are-modules \
    "$@"
