/**
 * Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
 * This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
 * conditions defined in the file COPYING, which is part of this source code package.
 */

// TODO: replace these placeholders with imports from the autogenerated schema
// once the `/api/internal/monitoring/hosts` endpoint lands. The pattern follows
// packages/cmk-frontend-vue/src/dashboard/types/api.ts — a central re-export
// derived from cmk-shared-typing. Long-term interface: CMK-34681.

export type HostState = 'UP' | 'DOWN' | 'UNREACHABLE'

export interface HostEntry {
  name: string
  state: HostState
  ip: string
  alias: string
  num_services_ok: number
  num_services_warn: number
  num_services_crit: number
  num_services_unknown: number
  num_services_pending: number
}
