POSTGRESQL := postgresql
POSTGRESQL_VERS := 10.20
POSTGRESQL_DIR := $(POSTGRESQL)-$(POSTGRESQL_VERS)

POSTGRESQL_UNPACK := $(BUILD_HELPER_DIR)/$(POSTGRESQL_DIR)-unpack
POSTGRESQL_BUILD := $(BUILD_HELPER_DIR)/$(POSTGRESQL_DIR)-build
POSTGRESQL_INTERMEDIATE_INSTALL := $(BUILD_HELPER_DIR)/$(POSTGRESQL_DIR)-install-intermediate
POSTGRESQL_INSTALL := $(BUILD_HELPER_DIR)/$(POSTGRESQL_DIR)-install

POSTGRESQL_INSTALL_DIR := $(INTERMEDIATE_INSTALL_BASE)/$(POSTGRESQL_DIR)
POSTGRESQL_BUILD_DIR := $(PACKAGE_BUILD_DIR)/$(POSTGRESQL_DIR)
#POSTGRESQL_WORK_DIR := $(PACKAGE_WORK_DIR)/$(POSTGRESQL_DIR)

# Used by python3-modules (pymssql)
PACKAGE_POSTGRESQL_DESTDIR := $(POSTGRESQL_INSTALL_DIR)
PACKAGE_POSTGRESQL_BIN := $(PACKAGE_POSTGRESQL_DESTDIR)/bin
PACKAGE_POSTGRESQL_LD_LIBRARY_PATH := $(PACKAGE_POSTGRESQL_DESTDIR)/lib
PACKAGE_POSTGRESQL_INCLUDE_PATH := $(PACKAGE_POSTGRESQL_DESTDIR)/include

ifneq ($(filter $(DISTRO_CODE),el6),)
$(POSTGRESQL_BUILD): $(POSTGRESQL_UNPACK)
	cd $(POSTGRESQL_BUILD_DIR) && ./configure \
	    --prefix=""

	$(MAKE) -C $(POSTGRESQL_BUILD_DIR)
	$(TOUCH) $@
else
$(POSTGRESQL_BUILD):
	$(MKDIR) $(BUILD_HELPER_DIR)
	$(TOUCH) $@
endif

$(POSTGRESQL_INTERMEDIATE_INSTALL): $(POSTGRESQL_BUILD)
ifneq ($(filter $(DISTRO_CODE),el6),)
	$(MAKE) DESTDIR=$(POSTGRESQL_INSTALL_DIR) -C $(POSTGRESQL_BUILD_DIR)/src/bin install
	$(MAKE) DESTDIR=$(POSTGRESQL_INSTALL_DIR) -C $(POSTGRESQL_BUILD_DIR)/src/include install
	$(MAKE) DESTDIR=$(POSTGRESQL_INSTALL_DIR) -C $(POSTGRESQL_BUILD_DIR)/src/interfaces install
endif
	$(TOUCH) $@

$(POSTGRESQL_INSTALL): $(POSTGRESQL_INTERMEDIATE_INSTALL)
ifneq ($(filter $(DISTRO_CODE),el6),)
	$(RSYNC) $(POSTGRESQL_INSTALL_DIR)/ $(DESTDIR)$(OMD_ROOT)/
endif
	$(TOUCH) $@
