#!/usr/bin/env python3
# Copyright (C) 2025 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.
from cmk.gui.openapi.restful_objects.endpoint_family import EndpointFamily

HISTORICAL_EVENTS_FAMILY = EndpointFamily(
    name="Historical events",
    description=(
        """

Historical Event Console Events

This endpoint family allows you to retrieve historical events from the Event Console. The Event Console is a powerful tool within Checkmk that helps you manage and analyze events generated by your monitoring setup. With this API, you can access detailed information about past events, including their history, state changes, and associated metadata.

The endpoints available are the following:
- List historical events: Retrieve a list of historical events with filtering options.
- Show historical event: Get detailed information about a specific historical event by its event ID.


"""
    ),
    doc_group="Monitoring",
)
