@startuml

component "[[../arch-comp-metric-backend.html Metric backend]]" as metric_backend
interface "HTTP" as http_metric_backend
component "[[../arch-comp-dcdd.html DCD]]" as dcd
component "hosts" as hosts
component "agent_otel" as agent_otel

metric_backend -down- http_metric_backend
dcd -up-> http_metric_backend: query
agent_otel -up-> http_metric_backend: query
dcd -down-> hosts: create hosts and discover services
agent_otel -down-> hosts: monitoring data

@enduml
