@startuml

component "[[../arch-comp-data-backend.html Data backend]]" as data_backend
interface "HTTP" as http_data_backend

component "[[../arch-comp-gui.html GUI]]" as gui {
    component "Custom graph editor" as custom_graph_editor
    component "agent_custom_query rules" as agent_custom_query_rules
}

component "agent_custom_query" as agent_custom_query

data_backend - http_data_backend
custom_graph_editor -left-> http_data_backend: query
custom_graph_editor --> agent_custom_query_rules: create via slide-in
agent_custom_query -up-> http_data_backend: query

@enduml
