@startuml

package "Site" {
    component "Agent Receiver"
}

package "Relay Engine" {
    component Scheduler
    component "Polling Client" as Poller

    package "Fetcher Pool" as fetcher_pool {
        interface "Queue" as fetcher_queue
        component "Fetcher"
        "Fetcher" -u- fetcher_queue

    }

    package "Ad-hoc Fetcher Pool" as adhoc_pool {
        interface "Queue" as ad_hoc_queue
        component "Ad-hoc Fetcher"
        "Ad-hoc Fetcher" -u- ad_hoc_queue
    }

    Scheduler -d-> fetcher_queue
    Poller -d-> ad_hoc_queue: Fetch tasks

    component "Result Submitter"
    interface "Queue" as result_queue
    "Result Submitter" -u- result_queue

    "Fetcher" -d-> result_queue
    "Ad-hoc Fetcher" -d-> result_queue
}

    Poller -> "Agent Receiver": Query for tasks
    "Result Submitter" -u---> "Agent Receiver": Send task result
@enduml
