@startuml

component "[[../arch-comp-data-backend.html Data backend]]" as data_backend
interface "HTTP" as http_data_backend
component "[[../arch-comp-dcdd.html DCD]]" as dcd
component "hosts" as hosts
component "Telemetry metrics fetcher" as telemetry_metrics_fetcher

data_backend -down- http_data_backend
dcd -up-> http_data_backend: query
telemetry_metrics_fetcher -up-> http_data_backend: query
dcd -down-> hosts: create hosts and discover services
telemetry_metrics_fetcher -down-> hosts: monitoring data

@enduml
