@startuml
class Manager
class Site
class Channel
abstract class ABCClient
abstract class ABCInternalClient extends ABCClient
class InventoryUpdateClient extends ABCInternalClient

Manager "1" o-- "many" Site : administrates >
Process <|-- Site
Site "1" o-- "many" Channel : manage &\nassign clients >
Site "1" o-- "many" ABCClient : accept & assign\nto channel >
Site *-- InventoryUpdater
InventoryUpdater o-- Site
InventoryUpdater ..> InventoryUpdateClient : instantiate
InventoryUpdateClient o-- Site
Channel "1" o-- "1" ABCClient: process requests >
Thread <|-- Channel
ABCClient o-- Site
ABCClient o-- Channel
ABCClient <|--- Client
ABCClient <|--- HeartbeatClient

note bottom of Client
  Processes standard
  livestatus queries.
end note
note bottom of HeartbeatClient
  Keeps channels open.
  Check if remote is still there.
end note
note bottom of InventoryUpdateClient
  Fetches HW/SW Inventory information
  from remote site and stores it centrally
  for the UI.
end note
@enduml
