@startuml
skinparam componentStyle uml2
skinparam monochrome true
' Remove shadows
skinparam shadowing false
scale 0.6

package users {
    actor "Operator" as operator
    actor "Admin" as admin
}

package "API clients" as api_clients {
    component "[[../arch-comp-grafana-connector.html Grafana Connector]]" as grafana_connector
    component "REST client" as rest_api_client
    component "[[../arch-comp-livestatus-client.html Livestatus client]]" as external_livestatus_client
}

package "[[../arch-comp-omd.html OMD: Checkmk run-time environment]]" as omd {
    interface HTTP as http_gui
    interface HTTP as http_rest_api
    interface HTTP as http_agent_receiver_rest_api

    component "[[../arch-comp-apache.html Apache]]" as apache {
        component "mod_wsgi" as mod_wsgi {
            package "[[../arch-comp-gui.html GUI]]" {
                component GUI
                component "REST API" as rest_api
                component "[[../arch-comp-livestatus-client.html Livestatus client]]" as apache_livestatus_client
            }
        }
        component mod_fcgid {
            component "[[../arch-comp-nagvis.html NagVis]]" as nagvis
        }
    }
    interface Livestatus as apache_livestatus

    component "[[../arch-comp-agent-receiver.html agent-receiver]]" as agent_receiver

    component "[[../arch-comp-core.html Monitoring Core]]" as cmc {
        component "RRD integration" as rrd_integration
        component "[[../arch-comp-livestatus.html Livestatus]]" as cmc_livestatus_server
        component "[[../arch-comp-checkengine.html Check engine]]" as check_engine {
            component checker
            component Fetcher
        }
        component "[[../arch-comp-smartping.html Smart ping]]" as smart_ping {
            component ICMPReceiver
            component ICMPSender
        }
        component "Notification engine" as cmc_notify {
            component "Notify helper" as notify_helper
        }
    }
    interface "call" as call_notification_plugins

    component "[[../arch-comp-crontab.html crontab]]" as crontab
    component "[[../arch-comp-backup.html backup]]" as backup

    component "[[../arch-comp-liveproxyd.html liveproxyd]]" as liveproxyd
    interface "[[../arch-comp-livestatus-client.html Livestatus client]]" as liveproxyd_livestatus_client

    component "[[../arch-comp-dcd.html dcd]]" as dcd
    interface "HTTP" as dcd_web_api_client
    interface Piggyback as dcd_piggyback

    component mkeventd
    interface Livestatus as mkeventd_livestatus

    component "[[../arch-comp-mknotifyd.html mknotifyd]]" as mknotifyd
    interface Notification as mknotifyd_notification

    component "[[../arch-comp-rrd-backend.html RRD backend]]" as rrd_backend
    interface "IO" as rrd_io

    package "Notification plugins" as notification_plugins

    component "[[../arch-comp-metric-backend.html Metric backend]]" as metric_backend
    interface "HTTP" as http_metric_backend
    interface "TCP" as tcp_metric_backend

    component "[[../arch-comp-otel-collector.html OTel collector]]" as otel_collector
}

package "[[../arch-comp-distributed.html Other site]]" as other_site {
    component "[[../arch-comp-core.html Monitoring Core]]" as cmc_other_site
    component "[[../arch-comp-gui.html GUI]]" as gui_other_site
    component "[[../arch-comp-mknotifyd.html mknotifyd]]" as mknotifyd_other_site
}
interface "mknotifyd protocol" as mknotifyd_protocol

package "[[../arch-comp-hosts.html hosts]]" as hosts {
    component "[[../arch-comp-hosts.html Agent host]]" as agent_based_host
    component "[[../arch-comp-hosts.html SNMP host]]" as snmp_host
    component "Ping host"
    component "API host" as api_hosts
}

interface TCP
interface Syslog
interface SNMP
interface "SNMP trap" as trap
interface HTTP as api_hosts_http
interface HTTPS as https_agent_receiver

users -- http_gui
rest_api_client -- http_rest_api
grafana_connector -- http_rest_api

http_gui -- GUI
http_gui -- nagvis
http_rest_api -- rest_api

http_agent_receiver_rest_api -- rest_api
http_agent_receiver_rest_api -- agent_receiver
agent_receiver -- https_agent_receiver

GUI -- apache_livestatus_client
GUI -- http_metric_backend
rest_api -- apache_livestatus_client
apache_livestatus_client -- apache_livestatus
nagvis -- apache_livestatus
apache_livestatus -- liveproxyd

liveproxyd -- liveproxyd_livestatus_client
liveproxyd_livestatus_client -- cmc_livestatus_server

dcd_web_api_client -- dcd
dcd -- dcd_piggyback
dcd_web_api_client - rest_api
dcd_piggyback -- check_engine
dcd -- http_metric_backend

metric_backend - http_metric_backend
metric_backend -- tcp_metric_backend
otel_collector -- tcp_metric_backend

' Help visualization
notify_helper -[hidden]r-> rrd_integration
rrd_integration - cmc_livestatus_server
checker - Fetcher

external_livestatus_client -- cmc_livestatus_server
Fetcher ------ TCP
Fetcher ------ SNMP
Fetcher ------ api_hosts_http
Fetcher ---up--- http_metric_backend
TCP -- agent_based_host
SNMP -- snmp_host
api_hosts_http -- api_hosts
ICMPSender ----- hosts
ICMPReceiver ----- hosts

rrd_integration -- rrd_io
rrd_io -- rrd_backend

notify_helper -- call_notification_plugins
call_notification_plugins ----- notification_plugins
notify_helper -- mknotifyd_notification
mknotifyd_notification -- mknotifyd
mknotifyd ------- mknotifyd_protocol
mknotifyd_protocol -- mknotifyd_other_site

cmc_livestatus_server -- mkeventd_livestatus
mkeventd_livestatus -- mkeventd
mkeventd --- Syslog
Syslog -- agent_based_host
agent_based_host -- https_agent_receiver
mkeventd ------ trap
trap -- snmp_host

@enduml
