MAINTENANCE := maintenance
MAINTENANCE_VERS := $(OMD_VERSION)

MAINTENANCE_BUILD := $(BUILD_HELPER_DIR)/$(MAINTENANCE)-build
MAINTENANCE_INSTALL := $(BUILD_HELPER_DIR)/$(MAINTENANCE)-install
MAINTENANCE_SKEL := $(BUILD_HELPER_DIR)/$(MAINTENANCE)-skel

.PHONY: $(MAINTENANCE) $(MAINTENANCE)-skel $(MAINTENANCE)-clean build-helper/maintenance

$(MAINTENANCE)-install: $(MAINTENANCE_INSTALL)

$(MAINTENANCE):

$(MAINTENANCE_BUILD):
	$(TOUCH) $@

$(MAINTENANCE_INSTALL):
	install -v -m 755 $(PACKAGE_DIR)/$(MAINTENANCE)/merge-crontabs $(DESTDIR)$(OMD_ROOT)/bin
	install -v -m 755 $(PACKAGE_DIR)/$(MAINTENANCE)/diskspace $(DESTDIR)$(OMD_ROOT)/bin
	install -v -m 755 $(PACKAGE_DIR)/$(MAINTENANCE)/logrotate $(DESTDIR)$(OMD_ROOT)/bin
	$(TOUCH) $@

$(MAINTENANCE_SKEL):
	$(TOUCH) $@

maintenance-skel:

maintenance-clean:
