<!--
Copyright (C) 2024 Checkmk GmbH - License: GNU General Public License v2
This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
conditions defined in the file COPYING, which is part of this source code package.
-->
<script setup lang="ts">
import { computed } from 'vue'

import { cmkIconVariants } from './icons.constants.ts'
import type { CmkIconProps, SimpleIcons } from './types.ts'
import { iconSizeNametoNumber } from './utils'

function getIconName(iconName: SimpleIcons): string {
  if (!iconName) {
    return 'none'
  }

  const errors: string[] = []
  if (iconName.includes('_')) {
    errors.push(
      `Icon name "${iconName}" contains an underscore (_). Use kebab-case (dashes) instead.`
    )
  }
  if (iconName.startsWith('icon-')) {
    errors.push(
      `Icon name "${iconName}" contains "icon". Pass only the base name, e.g. "main-help".`
    )
  }
  if (iconName.includes('.svg')) {
    errors.push(`Icon name "${iconName}" contains ".svg". Do not include file extensions.`)
  }

  if (errors.length > 0) {
    throw new Error(errors.join(' '))
  }

  return iconName
}

const props = defineProps<CmkIconProps>()

const iconSize = computed(() => iconSizeNametoNumber(props.size))

const getTransformRotate = () => {
  return `rotate(${props.rotate || 0}deg)`
}
</script>

<template>
  <img
    class="cmk-icon"
    :class="[
      cmkIconVariants({ variant: props.variant, colored: props.colored }),
      `cmk-icon__icon--${getIconName(props.name)}`
    ]"
    :title="title || ''"
    :alt="title || ''"
    :width="iconSize"
    :height="iconSize"
  />
</template>

<style scoped>
.cmk-icon {
  margin: 0;
  padding: 0;
  vertical-align: baseline;
  transform: v-bind('getTransformRotate()');

  &.cmk-icon--inline {
    display: inline-block;
    margin-right: var(--spacing-half);
    vertical-align: middle;
  }

  &.cmk-icon--colorless {
    filter: grayscale(100%);
  }
}
</style>

<style lang="scss">
body[data-theme='modern-dark'] {
  .cmk-icon__icon--search {
    content: url('~cmk-frontend/themes/modern-dark/images/icon_search.svg');
  }
}

body[data-theme='facelift'] {
  .cmk-icon__icon--search {
    content: url('~cmk-frontend/themes/facelift/images/icon_search.png');
  }
}

$unthemed-icons: (
  '2fa-backup-codes': 'icon_2fa_backup_codes.svg',
  '2fa': 'icon_2fa.svg',
  'abort': 'icon_abort.png',
  'about-checkmk': 'icon_about_checkmk.svg',
  'accept-all': 'icon_accept_all.svg',
  'accept': 'icon_accept.svg',
  'ack': 'icon_ack.png',
  'acknowledge-test': 'icon_acknowledge_test.png',
  'action': 'icon_action.png',
  'activate': 'icon_activate.png',
  'add-dashlet': 'icon_add_dashlet.png',
  'add': 'icon_add.png',
  'agent-output': 'icon_agent_output.png',
  'agents': 'icon_agents.svg',
  'aggrcomp': 'icon_aggrcomp.png',
  'aggr': 'icon_aggr.svg',
  'aggr-single': 'icon_aggr_single.svg',
  'aggr-single-problem': 'icon_aggr_single_problem.svg',
  'aix-tgz': 'icon_aix_tgz.svg',
  'alert-ack': 'icon_alert_ack.png',
  'alert-ackstop': 'icon_alert_ackstop.png',
  'alert-alert-handler-failed': 'icon_alert_alert_handler_failed.png',
  'alert-alert-handler-started': 'icon_alert_alert_handler_started.png',
  'alert-alert-handler-stopped': 'icon_alert_alert_handler_stopped.png',
  'alert-cmk-notify': 'icon_alert_cmk_notify.png',
  'alert-command': 'icon_alert_command.png',
  'alert-crit': 'icon_alert_crit.svg',
  'alert-down': 'icon_alert_down.png',
  'alert-downtime': 'icon_alert_downtime.png',
  'alert-downtimestop': 'icon_alert_downtimestop.png',
  'alert-flapping': 'icon_alert_flapping.png',
  'alert-handlers': 'icon_alert_handlers.svg',
  'alert': 'icon_alert.png',
  'alert-notify': 'icon_alert_notify.png',
  'alert-notify-progress': 'icon_alert_notify_progress.png',
  'alert-notify-result': 'icon_alert_notify_result.png',
  'alert-ok': 'icon_alert_ok.png',
  'alert-overview': 'icon_alert-overview.svg',
  'alert-reload': 'icon_alert_reload.png',
  'alert-restart': 'icon_alert_restart.png',
  'alerts': 'icon_alerts.svg',
  'alert-start': 'icon_alert_start.png',
  'alert-stop': 'icon_alert_stop.png',
  'alert-timeline': 'icon_alert_timeline.svg',
  'alert-unknown': 'icon_alert_unknown.png',
  'alert-unreach': 'icon_alert_unreach.png',
  'alert-up': 'icon_alert_up.png',
  'alert-warn': 'icon_alert_warn.png',
  'all-states': 'icon_all_states.png',
  'analysis': 'icon_analysis.svg',
  'analyze-config': 'icon_analyze_config.svg',
  'annotation': 'icon_annotation.png',
  'api': 'icon_api.svg',
  'apply': 'icon_apply.png',
  'app-monitoring-topic': 'icon_app_monitoring_topic.svg',
  'archive-event': 'icon_archive_event.png',
  'ar-simulate': 'icon_ar_simulate.png',
  'assume-0': 'icon_assume_0.png',
  'assume-1': 'icon_assume_1.png',
  'assume-2': 'icon_assume_2.png',
  'assume-3': 'icon_assume_3.png',
  'assume-bg': 'assume_bg.png',
  'assume-none': 'icon_assume_none.png',
  'auditlog': 'icon_auditlog.svg',
  'autherr': 'icon_autherr.png',
  'authok': 'icon_authok.png',
  'availability': 'icon_availability.svg',
  'av-computation': 'icon_av_computation.png',
  'aws-logo': 'icon_aws_logo.svg',
  'azure-storage': 'icon_azure_storage.svg',
  'azure-vms': 'icon_azure_vms.svg',
  'background-job-details': 'icon_background_job_details.png',
  'background-jobs': 'icon_background_jobs.svg',
  'back': 'icon_back.png',
  'back-off': 'icon_back_off.png',
  'backup': 'icon_backup.svg',
  'backup-restore-stop': 'icon_backup_restore_stop.png',
  'backup-start': 'icon_backup_start.png',
  'backup-state': 'icon_backup_state.png',
  'backup-stop': 'icon_backup_stop.png',
  'backup-target-edit': 'icon_backup_target_edit.png',
  'backup-targets': 'icon_backup_targets.svg',
  'bake': 'icon_bake.svg',
  'bake-result': 'icon_bake_result.png',
  'barplot': 'icon_barplot.svg',
  'bi-freeze': 'icon_bi_freeze.svg',
  'bilist': 'icon_bilist.png',
  'bitree': 'icon_bitree.png',
  'bookmark-list': 'icon_bookmark_list.svg',
  'bottom': 'icon_bottom.png',
  'bulk': 'icon_bulk.svg',
  'bulk-import': 'icon_bulk_import.png',
  'cached': 'icon_cached.png',
  'cancel': 'icon_cancel.svg',
  'cannot-reschedule': 'icon_cannot_reschedule.png',
  'certificate': 'icon_certificate.svg',
  'checkbox-hover-bg': 'checkbox_hover_bg.png',
  'checkbox': 'icon_checkbox.svg',
  'check': 'icon_check.svg',
  'checkmark-bare': 'icon_checkmark_bare.svg',
  'checkmark': 'icon_checkmark.svg',
  'checkmk': 'icon_checkmk.svg',
  'checkmk-logo': 'icon_checkmk_logo.svg',
  'checkmk-logo-min': 'icon_checkmk_logo_min.svg',
  'check-parameters': 'icon_check_parameters.svg',
  'check-plugins': 'icon_check_plugins.svg',
  'cleanup': 'icon_cleanup.png',
  'clear': 'icon_clear.png',
  'clipboard': 'icon_clipboard.svg',
  'clone': 'icon_clone.svg',
  'closetimewarp': 'icon_closetimewarp.png',
  'cloud': 'icon_cloud.svg',
  'cluster': 'icon_cluster.png',
  'collapse-arrow': 'icon_collapse_arrow.png',
  'collapse': 'icon_collapse.png',
  'color-mode': 'icon_color_mode.svg',
  'commands': 'icon_commands.svg',
  'condition': 'icon_condition.png',
  'connection-tests': 'icon_connection_tests.svg',
  'contactgroups': 'icon_contactgroups.svg',
  'continue': 'icon_continue.png',
  'copied': 'icon_copied.svg',
  'counting': 'icon_counting.png',
  'crash-glow': 'icon_crash_glow.png',
  'crash': 'icon_crash.svg',
  'critical': 'icon_critical.png',
  'crit-problem': 'icon_crit_problem.svg',
  'cross-grey': 'icon_cross_grey.svg',
  'cross': 'icon_cross.svg',
  'custom-attr': 'icon_custom_attr.svg',
  'customer-management': 'icon_customer_management.png',
  'custom-graph': 'icon_custom_graph.png',
  'custom-snapin': 'icon_custom_snapin.svg',
  'd146n0571c5': 'icon_d146n0571c5.png',
  'dashboard-controls': 'icon_dashboard_controls.png',
  'dashboard-edit': 'icon_dashboard_edit.svg',
  'dashboard-grid': 'icon_dashboard_grid.svg',
  'dashboard': 'icon_dashboard.svg',
  'dashboard-main': 'icon_dashboard_main.svg',
  'dashboard-problems': 'icon_dashboard_problems.svg',
  'dashboard-system': 'icon_dashboard_system.svg',
  'dash': 'icon_dash.svg',
  'dashlet-anchor': 'dashlet_anchor.svg',
  'dashlet-network-topology': 'icon_dashlet_network_topology.png',
  'dashlet-nodata': 'icon_dashlet_nodata.png',
  'dashlet-notifications-bar-chart': 'icon_dashlet_notifications_bar_chart.png',
  'dashlet-resize': 'dashlet_resize.svg',
  'dashlet-url': 'icon_dashlet_url.png',
  'dcd-connections': 'icon_dcd_connections.svg',
  'dcd-execute': 'icon_dcd_execute.png',
  'dcd-history': 'icon_dcd_history.png',
  'delayed': 'icon_delayed.png',
  'delete': 'icon_delete.svg',
  'deploy-agents': 'icon_deploy_agents.png',
  'deployment-error': 'icon_deployment_error.png',
  'deployment-status': 'icon_deployment_status.png',
  'derived-downtime': 'icon_derived_downtime.png',
  'detail': 'icon_detail.png',
  'developer-resources': 'icon_developer_resources.svg',
  'diagnose': 'icon_diagnose.png',
  'diagnostics-dump-file': 'icon_diagnostics_dump_file.png',
  'diagnostics': 'icon_diagnostics.svg',
  'disabled': 'icon_disabled.svg',
  'disabled-service': 'icon_disabled_service.svg',
  'disable-test': 'icon_disable_test.png',
  'dissolve-operation': 'icon_dissolve_operation.png',
  'docker': 'icon_docker.svg',
  'down': 'icon_down.png',
  'download-agents': 'icon_download_agents.svg',
  'download-csv': 'icon_download_csv.png',
  'download': 'icon_download.png',
  'download-json': 'icon_download_json.png',
  'downtime-for-report': 'icon_downtime_for_report.png',
  'downtime': 'icon_downtime.svg',
  'edit-custom-graph': 'icon_edit_custom_graph.png',
  'edit-forecast-model': 'icon_edit_forecast_model.png',
  'edit': 'icon_edit.svg',
  'email': 'icon_email.png',
  'emblem-downtime': 'emblem_downtime.svg',
  'emblem-edit': 'emblem_edit.svg',
  'emblem-remove': 'emblem_remove.png',
  'emblem-sign': 'emblem_sign.svg',
  'emblem-trans': 'emblem_trans.svg',
  'empty': 'icon_empty.png',
  'enabled': 'icon_enabled.png',
  'enable-test': 'icon_enable_test.png',
  'encrypted': 'icon_encrypted.png',
  'end': 'icon_end.png',
  'error': 'icon_error.png',
  'event-console': 'icon_event_console.svg',
  'event console-status': 'icon_event console_status.svg',
  'event': 'icon_event.svg',
  'expand': 'icon_expand.png',
  'export': 'icon_export.png',
  'export-rule': 'icon_export_rule.svg',
  'external': 'icon_external.svg',
  'factoryreset': 'icon_factoryreset.png',
  'fake-check-result': 'icon_fake_check_result.svg',
  'favicon': 'favicon.ico',
  'filter': 'icon_filter.svg',
  'filters-set': 'icon_filters_set.png',
  'flapping': 'icon_flapping.png',
  'folder-closed': 'folder_closed.png',
  'folder-hi': 'folder_hi.png',
  'folder': 'icon_folder.svg',
  'folder-open': 'folder_open.png',
  'folderproperties': 'icon_folderproperties.png',
  'forecast-graph': 'icon_forecast_graph.png',
  'foreign-changes': 'icon_foreign_changes.png',
  'forth': 'icon_forth.png',
  'forth-off': 'icon_forth_off.png',
  'frameurl': 'icon_frameurl.svg',
  'gauge': 'icon_gauge.svg',
  'gcp': 'icon_gcp.svg',
  'global-settings': 'icon_global_settings.svg',
  'globe': 'globe.png',
  'graph-collection': 'icon_graph_collection.png',
  'graph': 'icon_graph.svg',
  'graph-tuning': 'icon_graph_tuning.png',
  'gui-design': 'icon_gui_design.png',
  'guitest': 'icon_guitest.png',
  'hard-states': 'icon_hard_states.png',
  'hardware': 'icon_hardware.svg',
  'help-activated': 'icon_help_activated.svg',
  'hierarchy': 'icon_hierarchy.svg',
  'history': 'icon_history.png',
  'host-graph': 'icon_host_graph.svg',
  'hostgroups': 'icon_hostgroups.svg',
  'host': 'icon_host.png',
  'host-problems': 'icon_host_problems.svg',
  'host-state': 'icon_host_state.svg',
  'host-svc-problems-dark': 'icon_host_svc_problems_dark.svg',
  'ical': 'icon_ical.png',
  'icons': 'icon_icons.svg',
  'ignore': 'icon_ignore.png',
  'inactive': 'icon_inactive.png',
  'influxdb-connections': 'icon_influxdb_connections.svg',
  'info': 'icon_info.svg',
  'inline-error': 'icon_inline_error.svg',
  'insertdate': 'icon_insertdate.svg',
  'insert': 'icon_insert.svg',
  'install': 'icon_install.png',
  'integrations-custom': 'icon_integrations_custom.svg',
  'integrations-other': 'icon_integrations_other.svg',
  'inventory-failed': 'icon_inventory_failed.png',
  'inventory': 'icon_inventory.svg',
  'inverted': 'icon_inverted.png',
  'inv': 'icon_inv.png',
  'kubernetes': 'icon_kubernetes.svg',
  'laptop-50': 'icon_laptop_50.png',
  'ldap': 'icon_ldap.svg',
  'learning-beginner': 'icon_learning_beginner.svg',
  'learning-checkmk': 'icon_learning_checkmk.svg',
  'learning-forum': 'icon_learning_forum.svg',
  'learning-guide': 'icon_learning_guide.svg',
  'learning-video-tutorials': 'icon_learning_video_tutorials.svg',
  'license-failed': 'icon_license_failed.png',
  'license-successful': 'icon_license_successful.png',
  'license-unknown-state': 'icon_license_unknown_state.png',
  'licensing': 'icon_licensing.svg',
  'lightbulb': 'icon_lightbulb.svg',
  'lightbulb-idea': 'icon_lightbulb_idea.svg',
  'link': 'icon_link.png',
  'linux-deb': 'icon_linux_deb.svg',
  'linux': 'icon_linux.svg',
  'linux-rpm': 'icon_linux_rpm.svg',
  'linux-tgz': 'icon_linux_tgz.svg',
  'load-graph': 'load_graph.png',
  'localrule': 'icon_localrule.png',
  'log': 'icon_log.svg',
  'login': 'icon_login.png',
  'logo-cmk-small': 'logo_cmk_small.png',
  'logwatch': 'icon_logwatch.png',
  'magic-move': 'icon_magic_move.png',
  'main-changes-active': 'icon_main_changes_active.svg',
  'main-customize-active': 'icon_main_customize_active.svg',
  'main-help-active': 'icon_main_help_active.svg',
  'main-monitoring-active': 'icon_main_monitoring_active.svg',
  'main-search-active': 'icon_main_search_active.svg',
  'main-setup-active': 'icon_main_setup_active.svg',
  'main-user-active': 'icon_main_user_active.svg',
  'manual-active': 'icon_manual_active.svg',
  'matrix': 'icon_matrix.png',
  'menu': 'icon_menu.png',
  'menu-item-checked': 'icon_menu_item_checked.png',
  'menu-item-unchecked': 'icon_menu_item_unchecked.png',
  'message': 'icon_message.svg',
  'migrate-users': 'icon_migrate_users.svg',
  'missing': 'icon_missing.svg',
  'mkeventd-rules': 'icon_mkeventd_rules.png',
  'mkps': 'icon_mkps.svg',
  'monitored-service': 'icon_monitored_service.svg',
  'movedown': 'icon_movedown.png',
  'move': 'icon_move.png',
  'moveup': 'icon_moveup.png',
  'nagvis': 'icon_nagvis.png',
  'need-replicate': 'icon_need_replicate.png',
  'need-restart': 'icon_need_restart.png',
  'networking': 'icon_networking.svg',
  'network-services': 'icon_network_services.svg',
  'network-topology': 'icon_network_topology.svg',
  'new-cluster': 'icon_new_cluster.png',
  'newfolder': 'icon_newfolder.png',
  'new': 'icon_new.svg',
  'new-mkp': 'icon_new_mkp.png',
  'nodowntime': 'icon_nodowntime.png',
  'no-entry': 'icon_no_entry.svg',
  'no-pending-changes': 'icon_no_pending_changes.svg',
  'no-revert': 'icon_no_revert.svg',
  'notes': 'icon_notes.png',
  'notif-disabled': 'icon_notif_disabled.png',
  'notif-enabled': 'icon_notif_enabled.png',
  'notification-enabled': 'icon_notification_enabled.png',
  'notifications': 'icon_notifications.svg',
  'notification-timeline': 'icon_notification_timeline.svg',
  'notif-man-disabled': 'icon_notif_man_disabled.png',
  'npassive': 'icon_npassive.png',
  'ntop': 'icon_ntop.svg',
  'ooservice': 'ooservice.png',
  'open-telemetry': 'icon_open_telemetry.svg',
  'opentelemetry': 'icon_opentelemetry.svg',
  'os-other': 'icon_os_other.svg',
  'otel-collector': 'icon_otel_collector.svg',
  'outofnot': 'icon_outofnot.png',
  'outof-serviceperiod': 'icon_outof_serviceperiod.png',
  'packages': 'icon_packages.svg',
  'pagetype-topic': 'icon_pagetype_topic.svg',
  'pageurl': 'icon_pageurl.svg',
  'painteroptions-down-hi': 'icon_painteroptions_down_hi.png',
  'painteroptions-down-lo': 'icon_painteroptions_down_lo.png',
  'painteroptions': 'icon_painteroptions.svg',
  'painteroptions-off': 'icon_painteroptions_off.png',
  'parentscan': 'icon_parentscan.png',
  'passwords': 'icon_passwords.svg',
  'pause': 'icon_pause.png',
  'pending-changes': 'icon_pending_changes.svg',
  'pending-task': 'icon_pending_task.svg',
  'percentage-of-service-problems': 'icon_percentage-of-service-problems.svg',
  'persist': 'icon_persist.png',
  'pie-chart': 'icon_pie_chart.png',
  'plugins-agentless': 'icon_plugins_agentless.svg',
  'plugins-app': 'icon_plugins_app.png',
  'plugins-cloud': 'icon_plugins_cloud.svg',
  'plugins-containerization': 'icon_plugins_containerization.svg',
  'plugins-generic': 'icon_plugins_generic.svg',
  'plugins-hw': 'icon_plugins_hw.png',
  'plugins-os': 'icon_plugins_os.svg',
  'plugins-virtual': 'icon_plugins_virtual.svg',
  'pluginurl': 'pluginurl.png',
  'plus': 'icon_plus.svg',
  'pnp': 'icon_pnp.png',
  'predefined-conditions': 'icon_predefined_conditions.svg',
  'prediction': 'icon_prediction.png',
  'problem': 'icon_problem.svg',
  'qs-aws': 'icon_qs_aws.svg',
  'qs-azure': 'icon_qs_azure.svg',
  'qs-gcp': 'icon_qs_gcp.svg',
  'qs-otel': 'icon_qs_otel.svg',
  'qs-relay': 'icon_qs_relay.svg',
  'quicksearch-field-bg': 'quicksearch_field_bg.png',
  'quicksearch': 'icon_quicksearch.png',
  'quick-setup-aws': 'icon_quick_setup_aws.svg',
  'random': 'icon_random.png',
  'rank': 'icon_rank.svg',
  'read-only': 'icon_read_only.svg',
  'recreate-broker-certificate': 'icon_recreate_broker_certificate.svg',
  'redo': 'icon_redo.svg',
  'relay-menu': 'icon_relay_menu.svg',
  'release-deploy': 'release_deploy.svg',
  'release-mkp': 'icon_release_mkp.png',
  'release-mkp-yellow': 'icon_release_mkp_yellow.png',
  'release-scale': 'release_scale.svg',
  'reload': 'icon_reload.svg',
  'reloadsnapin': 'icon_reloadsnapin.png',
  'reloadsnapin-lo-alt': 'icon_reloadsnapin_lo_alt.png',
  'rename-host': 'icon_rename_host.svg',
  'repl-25': 'icon_repl_25.png',
  'repl-50': 'icon_repl_50.png',
  'repl-75': 'icon_repl_75.png',
  'replay': 'icon_replay.png',
  'repl-failed': 'icon_repl_failed.png',
  'replicate': 'icon_replicate.png',
  'repl-locked': 'icon_repl_locked.png',
  'repl-pending': 'icon_repl_pending.png',
  'repl-success': 'icon_repl_success.png',
  'report-element': 'icon_report_element.png',
  'report-fixed': 'icon_report_fixed.png',
  'report': 'icon_report.svg',
  'reportscheduler': 'icon_reportscheduler.png',
  'report-store': 'icon_report_store.png',
  'resetcounters': 'icon_resetcounters.png',
  'reset': 'icon_reset.png',
  'resize-graph': 'resize_graph.png',
  'resize': 'icon_resize.png',
  'restart': 'icon_restart.png',
  'restore': 'icon_restore.png',
  'revert': 'icon_revert.svg',
  'rj45-50': 'icon_rj45_50.png',
  'roles': 'icon_roles.svg',
  'rotate-left': 'icon_rotate_left.png',
  'rule': 'icon_rule.svg',
  'rule-no': 'icon_rule_no.png',
  'rule-no-off': 'icon_rule_no_off.png',
  'rulesets-deprecated': 'icon_rulesets_deprecated.png',
  'rulesets-ineffective': 'icon_rulesets_ineffective.png',
  'rules': 'icon_rules.svg',
  'rule-yes': 'icon_rule_yes.png',
  'rule-yes-off': 'icon_rule_yes_off.png',
  'saml': 'icon_saml.svg',
  'save-dashboard': 'icon_save_dashboard.svg',
  'save-graph': 'icon_save_graph.svg',
  'save': 'icon_save.svg',
  'save-to-folder': 'icon_save_to_folder.svg',
  'save-to-services': 'icon_save_to_services.svg',
  'save-view': 'icon_save_view.svg',
  'scatterplot': 'icon_scatterplot.svg',
  'service-discovery': 'icon_service_discovery.svg',
  'service-duration': 'icon_service_duration.svg',
  'service-graph': 'icon_service_graph.svg',
  'servicegroups': 'icon_servicegroups.svg',
  'service-label-add': 'icon_service_label_add.svg',
  'service-label-remove': 'icon_service_label_remove.svg',
  'service-label-update': 'icon_service_label_update.svg',
  'services-fix-all': 'icon_services_fix_all.svg',
  'services-green': 'icon_services_green.svg',
  'services': 'icon_services.svg',
  'services-refresh': 'icon_services_refresh.svg',
  'services-stop': 'icon_services_stop.png',
  'services-tabula-rasa': 'icon_services_tabula_rasa.svg',
  'service-state': 'icon_service_state.svg',
  'service-to-disabled': 'icon_service_to_disabled.svg',
  'service-to-ignored': 'icon_service_to_ignored.svg',
  'service-to-monitored': 'icon_service_to_monitored.svg',
  'service-to-new': 'icon_service_to_new.svg',
  'service-to-removed': 'icon_service_to_removed.svg',
  'service-to-unchanged': 'icon_service_to_unchanged.svg',
  'service-to-undecided': 'icon_service_to_undecided.svg',
  'showbi': 'icon_showbi.png',
  'showhide': 'icon_showhide.png',
  'show-less-green': 'icon_show_less_green.svg',
  'show-more-green': 'icon_show_more_green.svg',
  'sidebar': 'icon_sidebar.svg',
  'sidebar-logout': 'icon_sidebar_logout.svg',
  'sidebar-position': 'icon_sidebar_position.svg',
  'sidebar-top': 'sidebar_top.png',
  'signature-key': 'icon_signature_key.svg',
  'signature-key-partial': 'icon_signature_key_partial.png',
  'sign': 'icon_sign.svg',
  'single-metric': 'icon_single_metric.svg',
  'site-globals': 'icon_site_globals.png',
  'site-globals-modified': 'icon_site_globals_modified.png',
  'site-overview': 'icon_site_overview.svg',
  'sites': 'icon_sites.svg',
  'sla-configuration': 'icon_sla_configuration.png',
  'sla': 'icon_sla.svg',
  'snapin-greyswitch-off': 'icon_snapin_greyswitch_off.png',
  'snapin-greyswitch-on': 'icon_snapin_greyswitch_on.png',
  'snapshot-checksum': 'icon_snapshot_checksum.png',
  'snapshot': 'icon_snapshot.png',
  'snapshot-nchecksum': 'icon_snapshot_nchecksum.png',
  'snapshot-pchecksum': 'icon_snapshot_pchecksum.png',
  'snmp': 'icon_snmp.svg',
  'software': 'icon_software.svg',
  'solaris-pkg': 'icon_solaris_pkg.svg',
  'solaris-tgz': 'icon_solaris_tgz.svg',
  'someproblem': 'someproblem.png',
  'starred': 'icon_starred.png',
  'start': 'icon_start.png',
  'static-checks': 'icon_static_checks.svg',
  'static-text': 'icon_static_text.svg',
  'status': 'icon_status.svg',
  'status-report': 'status_report.png',
  'svc-problems': 'icon_svc_problems.svg',
  'sync-graphs': 'icon_sync_graphs.png',
  'sync-mkp': 'icon_sync_mkp.png',
  'synthetic-monitoring-purple': 'icon_synthetic_monitoring_purple.svg',
  'synthetic-monitoring-topic': 'icon_synthetic_monitoring_topic.svg',
  'synthetic-monitoring-yellow': 'icon_synthetic_monitoring_yellow.svg',
  'tag': 'icon_tag.svg',
  'timeline': 'icon_timeline.png',
  'timeperiods': 'icon_timeperiods.svg',
  'timewarp': 'icon_timewarp.png',
  'timewarp-off': 'icon_timewarp_off.png',
  'tls': 'icon_tls.svg',
  'toggle-context': 'icon_toggle_context.png',
  'toggle-details': 'icon_toggle_details.png',
  'toggle-on': 'icon_toggle_on.svg',
  'topic-2fa': 'icon_topic_2fa.svg',
  'topic-administration': 'icon_topic_administration.png',
  'topic-agents': 'icon_topic_agents.png',
  'topic-analyze': 'icon_topic_analyze.png',
  'topic-applications': 'icon_topic_applications.png',
  'topic-bi': 'icon_topic_bi.png',
  'topic-change-password': 'icon_topic_change_password.png',
  'topic-checkmk': 'icon_topic_checkmk.svg',
  'topic-events': 'icon_topic_events.png',
  'topic-exporter': 'icon_topic_exporter.svg',
  'topic-general': 'icon_topic_general.png',
  'topic-graphs': 'icon_topic_graphs.png',
  'topic-history': 'icon_topic_history.png',
  'topic-hosts': 'icon_topic_hosts.png',
  'topic-inventory': 'icon_topic_inventory.png',
  'topic-maintenance': 'icon_topic_maintenance.png',
  'topic-monitoring': 'icon_topic_monitoring.svg',
  'topic-my-workplace': 'icon_topic_my_workplace.svg',
  'topic-network': 'icon_topic_network.svg',
  'top': 'icon_top.png',
  'topic-other': 'icon_topic_other.png',
  'topic-overview': 'icon_topic_overview.png',
  'topic-problems': 'icon_topic_problems.png',
  'topic-profile': 'icon_topic_profile.png',
  'topic-quick-setups': 'icon_topic_quick_setups.svg',
  'topic-reporting': 'icon_topic_reporting.svg',
  'topic-services': 'icon_topic_services.png',
  'topic-site': 'icon_topic_site.png',
  'topic-system': 'icon_topic_system.svg',
  'topic-user-interface': 'icon_topic_user_interface.svg',
  'topic-users': 'icon_topic_users.png',
  'topic-visualization': 'icon_topic_visualization.png',
  'top-list': 'icon_top-list.svg',
  'trans': 'icon_trans.svg',
  'trust': 'icon_trust.png',
  'unacknowledge-test': 'icon_unacknowledge_test.png',
  'undecided-service': 'icon_undecided_service.svg',
  'undo': 'icon_undo.svg',
  'unpackaged-files': 'icon_unpackaged_files.png',
  'unusedbirules': 'icon_unusedbirules.png',
  'update-discovery-parameters': 'icon_update_discovery_parameters.svg',
  'update-host-labels': 'icon_update_host_labels.svg',
  'update': 'icon_update.png',
  'update-service-labels': 'icon_update_service_labels.svg',
  'upgrade': 'icon_upgrade.svg',
  'up': 'icon_up.png',
  'upload': 'icon_upload.png',
  'url': 'icon_url.png',
  'usedrulesets': 'icon_usedrulesets.png',
  'user-locked': 'icon_user_locked.png',
  'users': 'icon_users.svg',
  'validation-error': 'icon_validation_error.png',
  'video': 'icon_video.png',
  'view-columns': 'icon_view_columns.png',
  'view-copy': 'icon_view_copy.svg',
  'view': 'icon_view.svg',
  'view-link': 'icon_view_link.svg',
  'view-refresh': 'icon_view_refresh.png',
  'vsphere': 'icon_vsphere.svg',
  'warning': 'icon_warning.png',
  'wato-changes': 'icon_wato_changes.png',
  'wato': 'icon_wato.png',
  'wato-nochanges': 'icon_wato_nochanges.png',
  'werk-ack': 'icon_werk_ack.png',
  'widget-clone': 'icon_widget_clone.svg',
  'widget-delete': 'icon_widget_delete.svg',
  'widget-edit': 'icon_widget_edit.svg',
  'wikisearch': 'icon_wikisearch.png',
  'windows-msi': 'icon_windows_msi.svg',
  'wrong-agent': 'icon_wrong_agent.png',
  'www': 'icon_www.png',
  'zoom': 'icon_zoom.png'
);
$themed-icons: (
  'agent-registration': 'icon_agent_registration.svg',
  'analyze': 'icon_analyze.svg',
  'assign': 'icon_assign.svg',
  'aws': 'icon_aws.svg',
  'cancel-notifications': 'icon_cancel_notifications.svg',
  'checkmark-bg-white': 'icon_checkmark_bg_white.svg',
  'checkmark-orange': 'icon_checkmark_orange.svg',
  'checkmark-plus': 'icon_checkmark_plus.svg',
  'close': 'icon_close.svg',
  'comment': 'icon_comment.svg',
  'configuration': 'icon_configuration.svg',
  'cross-bg-white': 'icon_cross_bg_white.svg',
  'dashboard-grid': 'icon_dashboard_grid.svg',
  'dashboard-menuarrow': 'icon_dashboard_menuarrow.svg',
  'dashlet-clone': 'dashlet_clone.svg',
  'dashlet-delete': 'dashlet_delete.svg',
  'dashlet-edit': 'dashlet_edit.svg',
  'drag': 'icon_drag.svg',
  'emblem-add': 'emblem_add.svg',
  'emblem-api': 'emblem_api.svg',
  'emblem-disable': 'emblem_disable.svg',
  'emblem-download': 'emblem_download.svg',
  'emblem-enable': 'emblem_enable.svg',
  'emblem-more': 'emblem_more.svg',
  'emblem-pending': 'emblem_pending.svg',
  'emblem-refresh': 'emblem_refresh.svg',
  'emblem-rulesets': 'emblem_rulesets.svg',
  'emblem-search': 'emblem_search.svg',
  'emblem-settings': 'emblem_settings.svg',
  'emblem-statistic': 'emblem_statistic.svg',
  'emblem-time': 'emblem_time.svg',
  'emblem-warning': 'emblem_warning.svg',
  'export-link': 'icon_export_link.svg',
  'favorite': 'icon_favorite.svg',
  'filter-line': 'icon_filter_line.svg',
  'fixall': 'icon_fixall.svg',
  'folder-blue': 'icon_folder_blue.svg',
  'help': 'icon_help.svg',
  'home': 'icon_home.svg',
  'host-svc-problems': 'icon_host_svc_problems.svg',
  'hyphen': 'icon_hyphen.svg',
  'info-circle': 'icon_info_circle.svg',
  'main-changes': 'icon_main_changes.svg',
  'main-customize': 'icon_main_customize.svg',
  'main-help': 'icon_main_help.svg',
  'main-monitoring': 'icon_main_monitoring.svg',
  'main-search': 'icon_main_search.svg',
  'main-setup': 'icon_main_setup.svg',
  'main-user': 'icon_main_user.svg',
  'manual': 'icon_manual.svg',
  'nagios': 'icon_nagios.svg',
  'network': 'icon_network.svg',
  'performance-data': 'icon_performance_data.svg',
  'release-automated': 'release_automated.svg',
  'reload-cmk': 'icon_reload_cmk.svg',
  'rulesets': 'icon_rulesets.svg',
  'saas': 'icon_saas.svg',
  'search-action-button': 'icon_search_action_button.svg',
  'search-action': 'icon_search_action.svg',
  'search': 'icon_search.svg',
  'select-arrow': 'icon_select_arrow.svg',
  'services-blue': 'icon_services_blue.svg',
  'show-less': 'icon_show_less.svg',
  'show-more': 'icon_show_more.svg',
  'sidebar-folded': 'icon_sidebar_folded.svg',
  'site-dead': 'icon_site_dead.svg',
  'site-disabled': 'icon_site_disabled.svg',
  'site-down': 'icon_site_down.svg',
  'site-missing': 'icon_site_missing.svg',
  'site-unreach': 'icon_site_unreach.svg',
  'site-waiting': 'icon_site_waiting.svg',
  'snmpmib': 'icon_snmpmib.svg',
  'sparkle': 'icon_sparkle.svg',
  'speedometer': 'speedometer.svg',
  'stale': 'icon_stale.svg',
  'suggestion': 'icon_suggestion.svg',
  'table-actions-off': 'icon_table_actions_off.svg',
  'table-actions-on': 'icon_table_actions_on.svg',
  'tick': 'icon_tick.svg',
  'toggle-off': 'icon_toggle_off.svg',
  'tree-closed': 'tree_closed.svg'
);

@each $name, $filename in $themed-icons {
  body[data-theme='modern-dark'] {
    .cmk-icon__icon--#{$name} {
      content: url('~cmk-frontend/themes/modern-dark/images/#{$filename}');
    }
  }

  body[data-theme='facelift'] {
    .cmk-icon__icon--#{$name} {
      content: url('~cmk-frontend/themes/facelift/images/#{$filename}');
    }
  }
}
@each $name, $filename in $unthemed-icons {
  .cmk-icon__icon--#{$name} {
    content: url('~cmk-frontend/themes/facelift/images/#{$filename}');
  }
}
</style>
