#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# <<<agent_msg>>>
# CRIT This is the Message

def inventory_agent_msg(info):
    if len(info) > 0:
        return [(None,{})]

def check_agent_msg(_no_item, _no_params, info):
    if info[0][0] == "CRIT":
        state = 2
    elif info[0][0] == "WARN":
        state = 1
    elif info[0][0] == "OK":
        state = 0
    else:
        state = 3

    return(state, nagios_state_names[state] + " - " + " ".join(info[0][1:]))


check_info['agent_msg'] = {
    "check_function"          : check_agent_msg,
    "inventory_function"      : inventory_agent_msg,
    "service_description"     : "Message from Agent",
}

