#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from typing import Any, Mapping, Optional

# TODO: Cleanup this separation violation. This should be accessed through the check API
from cmk.base.config import SpecialAgentConfiguration


def agent_prometheus_arguments(
    params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> SpecialAgentConfiguration:
    prometheus_params = {**params, "host_address": ipaddress, "host_name": hostname}
    return SpecialAgentConfiguration([], repr(prometheus_params))


special_agent_info["prometheus"] = agent_prometheus_arguments
