#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2021 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

import copy

# TODO: Cleanup this separation violation. This should be accessed through the check API
import cmk.base.config


def agent_alertmanager_arguments(params, hostname, ipaddress):
    alertmanager_params = copy.copy(params)
    alertmanager_params.update({"host_address": ipaddress, "host_name": hostname})
    return cmk.base.config.SpecialAgentConfiguration([], repr(alertmanager_params))


special_agent_info['alertmanager'] = agent_alertmanager_arguments
