#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables from the check-context which are necessary for
# resolving legacy discovery results such as [("SUMMARY", "diskstat_default_levels")]. Furthermore,
# it might also remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.akcp_sensor import *  # pylint: disable=wildcard-import,unused-wildcard-import

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables from the check-context which are necessary for
# resolving legacy discovery results such as [("SUMMARY", "diskstat_default_levels")]. Furthermore,
# it might also remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.humidity import *  # pylint: disable=wildcard-import,unused-wildcard-import

# Example for contents of info
#      description       percent  status  online
# ["Humdity1 Description", "0",    "0",    "2"]

check_info["akcp_sensor_humidity"] = {
    "check_function": check_akcp_humidity,
    "inventory_function": inventory_akcp_humidity,
    "service_description": "Humidity %s",
    "has_perfdata": True,
    "snmp_scan_function": snmp_scan_akcp_sensor,
    "snmp_info": (
        ".1.3.6.1.4.1.3854.1.2.2.1.17.1",
        [
            1,  # SPAGENT-MIB::sensorProbeHumidityDescription
            3,  # SPAGENT-MIB::sensorProbeHumidityPercent
            4,  # SPAGENT-MIB::sensorProbeHumidityStatus
            5,  # SPAGENT-MIB::sensorProbeHumidityOnline
        ],
    ),
    "group": "humidity",
}
