#!/usr/bin/env python3
# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


from cmk.base.check_api import all_of, not_exists, startswith
from cmk.base.check_legacy_includes.akcp_sensor import (
    check_akcp_sensor_drycontact,
    inventory_akcp_sensor_no_params,
)
from cmk.base.config import check_info

check_info["akcp_sensor_drycontact"] = {
    "detect": all_of(
        startswith(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.3854.1"), not_exists(".1.3.6.1.4.1.3854.2.*")
    ),
    "check_function": check_akcp_sensor_drycontact,
    "inventory_function": inventory_akcp_sensor_no_params,
    "service_description": "Dry Contact %s",
    "snmp_info": (
        ".1.3.6.1.4.1.3854.1.2.2.1.18.1",
        [
            1,  # Sensor Name
            3,  # Sensor Status (2 = OK, 4 = Not ok)
            5,  # Sensor Online
        ],
    ),
}
