#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_akcp_sensor_drycontact(info):
    return [ ( x[0], None ) for x in info if x[2] == "1" ]

def check_akcp_sensor_drycontact(item, _no_params, info):
    for line in info:
        if item == line[0]:
            state = saveint(line[1])
            if state == 2:
                return 0, "Drycontact OK"
            return 2, "Drycontact on Error"
    return 3, "Drycontact not found anymore"

check_info["akcp_sensor_drycontact"] = {
    "check_function"        : check_akcp_sensor_drycontact,
    "inventory_function"    : inventory_akcp_sensor_drycontact,
    "service_description"   : "Device %s",
    "has_perfdata"          : False,
    'snmp_scan_function'    :  lambda oid: oid(".1.3.6.1.2.1.1.2.0") in\
                         [ ".1.3.6.1.4.1.3854.1.2.2.1.1", ".1.3.6.1.4.1.3854.1" ],
    'snmp_info'             : ( ".1.3.6.1.4.1.3854.1.2.2.1.18.1" , [
                                                            1, #Sensor Name
                                                            3, #Sensor Status (2 = OK, 4 = Not ok)
                                                            5, #Sensor Online
                                                            ] ),
}

