#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from cmk.base.check_legacy_includes.alcatel import *  # pylint: disable=wildcard-import,unused-wildcard-import
factory_settings['alcatel_temp'] = ALCATEL_TEMP_CHECK_DEFAULT_PARAMETERS

check_info["alcatel_cpu_aos7"] = {
    "check_function": check_alcatel_cpu,
    "inventory_function": inventory_alcatel_cpu,
    "service_description": "CPU utilization",
    "has_perfdata": True,
    "snmp_scan_function": alcatel_new_networking_products_scan_function,
    "snmp_info": (
        ".1.3.6.1.4.1.6486.801.1.2.1.16.1.1.1.1.1",  # MIB object "healthModuleTable"
        [15]  # MIB object "healthModuleCpuLatest"
    ),
}
