#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.arris_cmts import *  # pylint: disable=wildcard-import,unused-wildcard-import

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.temperature import *  # pylint: disable=wildcard-import,unused-wildcard-import

factory_settings["arris_cmts_temp_default_levels"] = {"levels": (40, 46)}


def inventory_arris_cmts_temp(info):
    for line in info:
        # only devices with not default temperature
        if line[1] != "999":
            yield line[0], {}


def check_arris_cmts_temp(item, params, info):
    for name, temp in info:
        if name == item:
            return check_temperature(int(temp), params, "arris_cmts_temp_%s" % item)

    return 3, "Sensor not found in SNMP data"


check_info["arris_cmts_temp"] = {
    "check_function": check_arris_cmts_temp,
    "inventory_function": inventory_arris_cmts_temp,
    "service_description": "Temperature Module %s",
    "has_perfdata": True,
    "snmp_scan_function": arris_cmts_scan_function,
    "snmp_info": (
        ".1.3.6.1.4.1.4998.1.1.10.1.4.2.1",
        [
            3,  # cardName
            29,  # Card Temperature
        ],
    ),
    "group": "temperature",
    "default_levels_variable": "arris_cmts_temp_default_levels",
}
