#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2017             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def inventory_bdt_tape_status(info):
    return [(None, None)]


def check_bdt_tape_status(_no_item, _no_params, info):
    status_id = info[0][0]

    status = {
        '1': 'other',
        '2': 'unknown',
        '3': 'ok',
        '4': 'non-critical',
        '5': 'critical',
        '6': 'non-recoverable',
    }.get(status_id, 'unknown')

    state = {
        'other': 3,
        'unknown': 3,
        'ok': 0,
        'non-critical': 1,
        'critical': 2,
        'non-recoverable': 2,
    }.get(status, 3)

    return state, status


check_info['bdt_tape_status'] = {
    'inventory_function': inventory_bdt_tape_status,
    'check_function': check_bdt_tape_status,
    'service_description': "Tape Library Status",
    'snmp_scan_function': lambda oid:
                          ('.1.3.6.1.4.1.20884.10893.2.101' in oid('.1.3.6.1.2.1.1.2.0')),
    'snmp_info': (
        '.1.3.6.1.4.1.20884.10893.2.101.2',
        '1',  # bDTGlobalStatus
    ),
}
