#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
#[['1', '24', 'SLOT #0: TEMP #1'],
#['2', '12', 'SLOT #0: TEMP #2'],
#['3', '12', 'SLOT #0: TEMP #3'],
#['4', '4687', 'power #1'],
#['5', '4560', 'power #2'],
#['6', '4821', 'power #3'],
#['7', '1', 'Power Supply #1'],
#['8', '1', 'Power Supply #2']]


def inventory_brocade_power(info):
    info = brocade_sensor_convert(info, "Power")
    return [ (x[0], None) for x in info ]

def check_brocade_power(item, _no_params, info):
    info = brocade_sensor_convert(info, "Power")
    for snmp_item, name, value in info:
        if item == snmp_item:
            value = saveint(value)
            if value != 1:
                return 2, "Error on supply %s" % name
            return 0, "No problems found"

    return 3, "Supply not found"

check_info["brocade_power"] = {
    "check_function"        : check_brocade_power,
    "inventory_function"    : inventory_brocade_power,
    "service_description"   : "Power supply %s",
    "has_perfdata"          : False,
    "includes"              : [ "brocade.include"], 
    "snmp_info"             : ('.1.3.6.1.4.1.1588.2.1.1.1.1.22.1', [ 4, 5 ] ),
    'snmp_scan_function':      \
     lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.1588.2.1.1") or \
                 oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.24.1.1588.2.1.1"),
}

