#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def brocade_mlx_power_combine_item(id, descr):
    if descr == "":
        return id
    else:
        return "%s %s" % (id, descr)

def inventory_brocade_mlx_power(info):
    inventory = []
    for power_id, power_descr, power_state in info:
        inventory.append( (brocade_mlx_power_combine_item(power_id, power_descr), None) )
    return inventory

def check_brocade_mlx_power(item, _no_params, info):
    for power_id, power_descr, power_state in info:
        if brocade_mlx_power_combine_item(power_id, power_descr) == item:
            if power_state == "2":
                return 0, "Power supply reports state: normal"
            elif power_state == "3":
                return 2, "Power supply reports state: failure"
            elif power_state == "1":
                return 3, "Power supply reports state: other"
            else:
                return 3, "Power supply reports an unhandled state (%s)" % power_state
    return 3, "Power supply not found"

check_info["brocade_mlx_power"] = {
    "check_function"        : check_brocade_mlx_power,
    "inventory_function"    : inventory_brocade_mlx_power,
    "service_description"   : "Power supply %s",
    "snmp_info"             : ('.1.3.6.1.4.1.1991.1.1.1.2.1.1', [ 1, 2, 3 ]), # power supplies (id, descr, state)
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.1991.1."),
    "has_perfdata"          : False,
}
