#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def check_dns_arguments(params):
    description, settings = params
    args = ["-H", description]

    if "server" in settings:
        if settings["server"] is not None:
            args += ["-s", settings["server"]]
    else:
        args += ["-s", "$HOSTADDRESS$"]

    if "expected_address" in settings:
        # Convert from old (str) to new (list of strings)
        exp = settings["expected_address"]
        # TODO: Use six.string_types when this is a module.
        if isinstance(exp, basestring):
            exp = [exp]
        for entry in exp:
            args += ["-a", entry]

    if settings.get("expected_authority"):
        args.append("-A")

    if "response_time" in settings:
        warn, crit = settings["response_time"]
        args += ["-w", "%f" % float(warn)]
        args += ["-c", "%f" % float(crit)]

    if "timeout" in settings:
        args += ["-t", settings["timeout"]]

    return args


def check_dns_desc(params):
    if "name" in params[1]:
        return params[1]["name"]
    return "DNS %s" % params[0]


active_check_info["dns"] = {
    "command_line": "$USER1$/check_dns $ARG1$",
    "argument_function": check_dns_arguments,
    "service_description": check_dns_desc,
    "has_perfdata": True,
}
