#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def check_cmk_inv(params):
    if params is None:
        params = {}  # convert from legacy rule syntax

    args = []
    args += ["--inv-fail-status=%d" % params.get("fail_status", 1)]
    args += ["--hw-changes=%d" % params.get("hw_changes", 0)]
    args += ["--sw-changes=%d" % params.get("sw_changes", 0)]
    args += ["--sw-missing=%d" % params.get("sw_missing", 0)]

    return args


active_check_info["cmk_inv"] = {
    "command_line": "cmk $ARG1$ --cache --inventory-as-check $HOSTNAME$",
    "argument_function": check_cmk_inv,
    "service_description": lambda x: "Check_MK HW/SW Inventory",
}
