#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def check_mail_arguments(params):
    args = []

    fetch_proto, fetch_params = params["fetch"]
    args.append("--protocol=%s" % fetch_proto)

    if "server" in fetch_params:
        args.append("--server=%s" % fetch_params["server"])
    else:
        args.append("--server=$HOSTADDRESS$")

    fetch_use_ssl, fetch_port = fetch_params["ssl"]
    if fetch_use_ssl:
        args.append("--ssl")
    if fetch_port is not None:
        args.append("--port=%d" % fetch_port)

    username, password = fetch_params["auth"]
    args.append("--username=%s" % username)
    args.append(passwordstore_get_cmdline("--password=%s", password))

    if "connect_timeout" in params:
        args.append("--connect-timeout=%d" % params["connect_timeout"])

    if "forward" in params:
        forward = params["forward"]
        args += ["--forward-ec"]
        if "method" in forward:
            args.append("--forward-method=%s" % forward["method"])

        if "match_subject" in forward:
            args.append("--match-subject=%s" % forward["match_subject"])

        if "facility" in forward:
            args.append("--forward-facility=%d" % forward["facility"])

        if "host" in forward:
            args.append("--forward-host=%s" % forward["host"])

        if "application" in forward:
            args.append("--forward-app=%s" % forward["application"])

        if "body_limit" in forward:
            args.append("--body-limit=%d" % forward["body_limit"])

        if "cleanup" in forward:
            if forward["cleanup"] is True:
                args.append("--cleanup=delete")
            else:
                args.append("--cleanup=%s" % forward["cleanup"])

    return args


active_check_info["mail"] = {
    "command_line": "$USER1$/check_mail $ARG1$",
    "argument_function": check_mail_arguments,
    "service_description": lambda params: params["service_description"],
    "has_perfdata": True,
}
