#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2015             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# Copyright by Mathias Kettner and Mathias Kettner GmbH.  All rights reserved.
#
# Check_MK is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.
#
# Check_MK is  distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY;  without even the implied warranty of
# MERCHANTABILITY  or  FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have  received  a copy of the  GNU  General Public
# License along with Check_MK.  If  not, email to mk@mathias-kettner.de
# or write to the postal address provided at www.mathias-kettner.de

def check_ftp_arguments(params):
    if type(params) == tuple:
        host, settings = params
    else:
        host = "$HOSTADDRESS$"
        settings = params

    args = ' -H %s' % quote_shell_string(host)

    if "port" in settings:
        args += ' -p %d' % settings['port']

    if "response_time" in settings:
        args += ' -w %f -c %f' % (
            settings["response_time"][0]/1000.0,
            settings["response_time"][1]/1000.0)

    if "timeout" in settings:
        args += ' -t %d' % settings["timeout"]

    if "refuse_state" in settings:
        args += ' -r %s' % settings["refuse_state"]

    if settings.get("escape_send_string"):
        args += ' --escape'

    if "send_string" in settings:
        args += ' -s %s' % quote_shell_string(settings["send_string"])

    if "expect" in settings:
        for s in settings["expect"]:
            args += ' -e %s' % quote_shell_string(s)

    if settings.get("ssl"):
        args += ' --ssl'

    if "cert_days" in settings:
        args += ' -D %d' % settings["cert_days"]

    return args


def check_ftp_get_item(params):
    if type(params) == tuple:
        return "FTP " + args[0]
    else:
        if "port" in params and params["port"] != 21:
            return "FTP Port " + str(params["port"])
        return "FTP"

active_check_info['ftp'] = {
    "command_line"        : '$USER1$/check_ftp $ARG1$',
    "argument_function"   : check_ftp_arguments,
    "service_description" : check_ftp_get_item,
    "has_perfdata"        : True,
}

