#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from cmk.base.check_legacy_includes.cisco_cpu_scan_functions import *  # pylint: disable=wildcard-import,unused-wildcard-import
factory_settings['cisco_cpu_multiitem_default_levels'] = {
    'levels': (80.0, 90.0),
}


def parse_cisco_cpu_multiitem(info):
    ph_idx_to_desc = {}
    for idx, desc in info[1]:
        if desc.lower().startswith("cpu "):
            desc = desc[4:]
        ph_idx_to_desc[idx] = desc

    parsed = {}
    for idx, util in info[0]:
        name = ph_idx_to_desc.get(idx, idx)
        try:
            parsed[name] = {'util': float(util)}
        except ValueError:
            pass
    return parsed


@get_parsed_item_data
def check_cisco_cpu_multiitem(_no_item, params, data):
    warn, crit = params['levels']
    value = data['util']
    yield check_levels(value,
                       "util", (warn, crit),
                       human_readable_func=get_percent_human_readable,
                       boundaries=(0, 100),
                       infoname="Utilization in the last 5 minutes")


check_info["cisco_cpu_multiitem"] = {
    'parse_function': parse_cisco_cpu_multiitem,
    'check_function': check_cisco_cpu_multiitem,
    'inventory_function': discover(),
    "group": "cpu_utilization_multiitem",
    "default_levels_variable": "cisco_cpu_multiitem_default_levels",
    'service_description': 'CPU utilization %s',
    'has_perfdata': True,
    'snmp_info': [
        (
            '.1.3.6.1.4.1.9.9.109.1.1.1',
            [
                '1.2',  # cpmCPUTotalPhysicalIndex
                '1.8',  # cpmCPUTotal5minRev
            ]),
        (
            '.1.3.6.1.2.1.47.1.1.1',
            [
                OID_END,  #OID index
                '1.7',  # entPhysicalName
            ])
    ],
    'snmp_scan_function': snmp_scan_cisco_cpu_multiitem,
}
