#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2015             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# Copyright by Mathias Kettner and Mathias Kettner GmbH.  All rights reserved.
#
# Check_MK is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.
#
# Check_MK is  distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY;  without even the implied warranty of
# MERCHANTABILITY  or  FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have  received  a copy of the  GNU  General Public
# License along with Check_MK.  If  not, email to mk@mathias-kettner.de
# or write to the postal address provided at www.mathias-kettner.de

check_includes['df_netapp32'] = [ "df.include", "df_netapp.include" ]




check_info["df_netapp32"] = {
    'check_function':          check_df_netapp,
    'inventory_function':      inventory_df_netapp,
    'service_description':     'Filesystem %s',
    'has_perfdata':            True,
    'snmp_info':               ('.1.3.6.1.4.1.789.1.5.4.1', [2, 3, 4]),
    'snmp_scan_function':      \
         lambda oid: is_netapp_filer(oid) and not oid(".1.3.6.1.4.1.789.1.5.4.1.29.*"),
    'group':                   'filesystem',
    'default_levels_variable': 'filesystem_default_levels',
}
