#!/usr/bin/env python3
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


from cmk.base.check_api import any_of, check_levels, discover, get_parsed_item_data, startswith
from cmk.base.config import check_info, factory_settings

factory_settings["domino_mailqueues_defaults"] = {"queue_length": (300, 350)}

MAILQUEUES_LABEL = (
    ("lnDeadMail", "Dead mails"),
    ("lnWaitingMail", "Waiting mails"),
    ("lnMailHold", "Mails on hold"),
    ("lnMailTotalPending", "Total pending mails"),
    ("InMailWaitingforDNS", "Mails waiting for DNS"),
)


def parse_domino_mailqueues(info):
    if not info:
        return {}

    return {
        item: (label, int(raw_value)) for (item, label), raw_value in zip(MAILQUEUES_LABEL, info[0])
    }


@get_parsed_item_data
def check_domino_mailqueues(_item, params, data):
    label, value = data
    yield check_levels(
        value,
        "mails",
        params.get("queue_length"),
        infoname=label,
        human_readable_func=lambda d: "%d" % int(d),
    )


check_info["domino_mailqueues"] = {
    "detect": any_of(
        startswith(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.311.1.1.3.1.2"),
        startswith(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.8072.3.1.10"),
        startswith(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.8072.3.2.10"),
    ),
    "parse_function": parse_domino_mailqueues,
    "inventory_function": discover(),
    "check_function": check_domino_mailqueues,
    "service_description": "Domino Queue %s",
    "default_levels_variable": "domino_mailqueues_defaults",
    "snmp_info": (
        ".1.3.6.1.4.1.334.72.1.1.4",
        [
            "1",  # lnDeadMail
            "6",  # lnWaitingMail
            "21",  # lnMailHold
            "31",  # lnMailTotalPending
            "34",  # InMailWaitingforDNS
        ],
    ),
    "group": "domino_mailqueues",
}
