#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_emc_datadomain_fs(info):
    mplist = []
    for line in info:
        if line[1] in inventory_df_exclude_mountpoints:
            continue
        mplist.append((line[1], None))
    return mplist

def check_emc_datadomain_fs(item, params, info):
    fslist = []
    for line in info:
        if item == line[1] or "patterns" in params:
            size_mb = float(line[2])*1024.0
            avail_mb = float(line[4])*1024.0
            fslist.append((item, size_mb, avail_mb, 0))
    return df_check_filesystem_list(item, params, fslist)

check_info["emc_datadomain_fs"] = {
    "check_function"          : check_emc_datadomain_fs,
    "inventory_function"      : inventory_emc_datadomain_fs,
    "service_description"     : "DD-Filesystem %s",
    "includes"                : [ "df.include" ],
    "group"                   : "filesystem",
    "default_levels_variable" : "filesystem_default_levels",
    "has_perfdata"            : True,
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.1.0").startswith("Data Domain OS"),
    "snmp_info"               : (".1.3.6.1.4.1.19746.1.3.2.1.1",
                                       [
                                            1, # fileSystemResourceIndex
                                            3, # fileSystemResourceName
                                            4, # fileSystemSpaceSize
                                            5, # fileSystemSpaceUsed
                                            6, # fileSystemSpaceAvail
                                            7, # fileSystemPercentUsed
                                            8, # fileSystemSpaceCleanable
                                       ],
                            ),
}

