#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_enviromux_sems_digital(parsed):
    for item, sensor_data in parsed.items():
        yield item, {}


def check_enviromux_sems_digital(item, params, parsed):
    sensor_value = parsed[item]['sensor_value']
    sensor_normal_value = parsed[item]['sensor_normal_value']
    if sensor_value == "Unknown":
        return 3, "Sensor value is unknown"
    elif sensor_value == sensor_normal_value:
        return 0, "Sensor Value is normal: %s" % sensor_value
    else:
        return 2, "Sensor Value is not normal: %s . It should be: %s" % (sensor_value, sensor_normal_value)


check_info['enviromux_sems_digital'] = {
    'parse_function'        : parse_enviromux_sems_digital,
    'inventory_function'    : inventory_enviromux_sems_digital,
    'check_function'        : check_enviromux_sems_digital,
    'service_description'   : 'Digital Sensor: %s',
    'snmp_info'             : ('.1.3.6.1.4.1.3699.1.1.2.1.6.1.1', [
                                                 "1",  # digIntputIndex
                                                 "2",  # digIntputDescription
                                                 "3",  # digIntputGroupNB
                                                 "4",  # digIntputGroup
                                                 "5",  # digIntputValue
                                                 "6",  # digIntputNormalValue
                                                 "7",  # digIntputStatus
                               ]),
    'includes'              : ["enviromux.include"],
    'has_perfdata'          : True,
    'snmp_scan_function'    : enviromux_sems_scan_function,
    'group'                 : "temperature",
}
