#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


# Agent / MIB output
# see: .1.3.6.1.4.1.3375.2.1.14.1.1.0
#      .1.3.6.1.4.1.3375.2.1.14.1.2.0
# F5-BIGIP-SYSTEM-MIB::sysCmSyncStatusId
# F5-BIGIP-SYSTEM-MIB::sysCmSyncStatusStatus

# F5 nodes need to be ntp synced otherwise status reports might be wrong.


f5_bigip_cluster_v11_states = {
    '0': ( "Unknown", 		        3),
    '1': ( "Syncing", 		        0),
    '2': ( "Need Manual Sync",          1),
    '3': ( "In Sync", 		        0),
    '4': ( "Sync Failed", 	        2),
    '5': ( "Sync Disconnected",	        2),
    '6': ( "Standalone", 	        2),
    '7': ( "Awaiting Initial Sync", 	1),
    '8': ( "Incompatible Version", 	2),
    '9': ( "Partial Sync", 	        2),
}


def inventory_f5_bigip_cluster_v11(info):
    if len(info) == 1:
        return [(None, None)]


def check_f5_bigip_cluster_v11(_no_item, _no_params, info):
    statusid, statustxt = info[0]
    statename, state = f5_bigip_cluster_v11_states[statusid]
    infotext = statename
    if statename != statustxt:
        infotext += ' - ' + statustxt
    return state, infotext


check_info["f5_bigip_cluster_v11"] = {
    'check_function':          check_f5_bigip_cluster_v11,
    'inventory_function':      inventory_f5_bigip_cluster_v11,
    'service_description':     'Config Sync Status',
    'snmp_info':               ('.1.3.6.1.4.1.3375.2.1.14.1', [
        "1.0", # sysCmSyncStatusId
        "2.0" # sysCmSyncStatusStatus
    ]),

    'snmp_scan_function':      \
     lambda oid: '.1.3.6.1.4.1.3375.2' in oid(".1.3.6.1.2.1.1.2.0") \
        and "big-ip" in oid(".1.3.6.1.4.1.3375.2.1.4.1.0").lower() \
	and int(oid(".1.3.6.1.4.1.3375.2.1.4.2.0").split('.')[0]) >= 11,
}
