#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

f5_bigip_cpu_temp_default_params = (60, 80)


def inventory_f5_bigip_cpu_temp(info):
    for line in info:
        yield line[0], "f5_bigip_cpu_temp_default_params"


def check_f5_bigip_cpu_temp(item, params, info):
    for name, temp in info:
        if name == item:
            return check_temperature(int(temp), params, "f5_bigip_cpu_temp_%s" % item)


check_info["f5_bigip_cpu_temp"] = {
    'check_function': check_f5_bigip_cpu_temp,
    'inventory_function': inventory_f5_bigip_cpu_temp,
    'service_description': 'Temperature CPU %s',
    'group': 'temperature',
    'has_perfdata': True,
    'includes': ['temperature.include'],
    'snmp_info': ('.1.3.6.1.4.1.3375.2.1.3.1.2.1', [1, 2]),
    'snmp_scan_function': lambda oid: '.1.3.6.1.4.1.3375.2' in oid(".1.3.6.1.2.1.1.2.0") and
                          "big-ip" in oid(".1.3.6.1.4.1.3375.2.1.4.1.0").lower(),
}
