#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2016             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# .1.3.6.1.4.1.25597.13.1.40.0 1

factory_settings['quarantine_levels'] = {'usage': (70, 80)}


def check_fireeye_quarantine(no_item, params, info):
    usage = int(info[0][0])
    warn, crit = params.get('usage')
    infotext = 'Usage: %d%%' % usage
    perf_counter = 'quarantine'
    return fireeye_check_generic(infotext, perf_counter, usage, warn, crit)


check_info['fireeye_quarantine'] = {
    'inventory_function': lambda info: inventory_fireeye_generic(info, False, True),
    'check_function': check_fireeye_quarantine,
    'service_description': 'Quarantine Usage',
    'default_levels_variable': 'quarantine_levels',
    'group': 'fireeye_quarantine',
    'snmp_info': (
        '.1.3.6.1.4.1.25597.13.1.40',
        [
            '0',  # FE-FIREEYE-MIB::feeQuarantineUsage
        ]),
    'snmp_scan_function': scan_fireeye,
    'has_perfdata': True,
    'includes': ['fireeye.include']
}
