#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# check_mk plugin to monitor storage systems like Fujitsu ETERNUS DX80 S2 supporting FJDARY-E100.MIB
# Copyright (c) 2012 FuH Entwicklungsgesellschaft mbH, Umkirch, Germany. All rights reserved.
# Author: Philipp Hoefflin, 2012, hoefflin+cmk@fuh-e.de

# example snmpwalk output:
# snmpwalk -c public -v 1 dx80 .1.3.6.1.4.1.211.1.21.1.100.2.1.2.1.1
# FJDARY-E100::fjdaryCmIndex.0 = INTEGER: 0
# FJDARY-E100::fjdaryCmIndex.1 = INTEGER: 1
# snmpwalk -c public -v 1 dx80 .1.3.6.1.4.1.211.1.21.1.100.2.1.2.1.3
# FJDARY-E100::fjdaryCmStatus.0 = INTEGER: normal(1)
# FJDARY-E100::fjdaryCmStatus.1 = INTEGER: normal(1)

check_info['fjdarye100_cmods'] = (check_fjdarye_item, "Channel Module %s", 0,  inventory_fjdarye_item)
check_includes['fjdarye100_cmods'] = ["fjdarye.include"]
# 1: fjdaryCmIndex, 3: fjdaryCmStatus
snmp_info['fjdarye100_cmods'] = (".1.3.6.1.4.1.211.1.21.1.100.2.1.2.1", [ 1, 3 ])

snmp_scan_functions['fjdarye100_cmods'] \
        = lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.211.1.21.1.100"
