#!/usr/bin/env python3
# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


from cmk.base.check_api import all_of, contains, exists
from cmk.base.check_legacy_includes.fortigate_cpu import (
    check_fortigate_cpu,
    inventory_fortigate_cpu,
)
from cmk.base.config import check_info, factory_settings

factory_settings["fortigate_cpu_base_default_levels"] = {"util": (80.0, 90.0)}


check_info["fortigate_cpu_base"] = {
    "detect": all_of(
        contains(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.12356.101.1"),
        exists(".1.3.6.1.4.1.12356.101.4.1.3.0"),
    ),
    "inventory_function": inventory_fortigate_cpu,
    "check_function": check_fortigate_cpu,
    "service_description": "CPU utilization",
    "group": "cpu_utilization",
    # uses mib FORTINET-FORTIGATE-MIB
    "snmp_info": (".1.3.6.1.4.1.12356.101.4.1", [3]),
    "default_levels_variable": "fortigate_cpu_base_default_levels",
}
