#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2017             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.4.1.3.1 "CPU1 Power"
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.4.1.3.2 "CPU2 Power"
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.4.1.4.1 "HDD Power"
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.4.1.7.1 "System Power"
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.4.1.10.1 "PSU1 Power"
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.4.1.10.2 "PSU2 Power"
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.4.1.224.1 "Total Power"
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.4.1.224.2 "Total Power Out"
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.5.1.3.1 5
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.5.1.3.2 0
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.5.1.4.1 8
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.5.1.7.1 50
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.5.1.10.1 52
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.5.1.10.2 40
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.5.1.224.1 92
#.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1.5.1.224.2 68


def parse_fsc_sc2_power_consumption(info):
    parsed = {}
    for designation, value in info:
        parsed.setdefault(designation, {"power": int(value)})
    return parsed


check_info['fsc_sc2_power_consumption'] = {
    'parse_function'            : parse_fsc_sc2_power_consumption,
    'inventory_function'        : inventory_elphase,
    'check_function'            : check_elphase,
    'service_description'       : 'Power Comsumption %s',
    'snmp_info'                 : ('.1.3.6.1.4.1.231.2.10.2.2.10.6.7.1', [
                                    '4',    #sc2cpcDesignation
                                    '5',    #sc2cpcCurrentValue
                                  ]),
    'snmp_scan_function'        : lambda oid: oid('.1.3.6.1.4.1.231.2.10.2.2.10.1.1.0'),
    'has_perfdata'              : True,
    'group'                     : 'el_inphase',
    'includes'                  : ['elphase.include'],
}
