#!/usr/bin/env python3
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


from cmk.base.check_legacy_includes.temperature import check_temperature

# 19:1100, 38:822X
# .1.3.6.1.4.1.28507.**.1.6.1.1.2.1 225 --> GUDEADS-EPC****-MIB::epc****TempSensor.1

# Similar default levels in other checks
factory_settings["gude_temp_default_levels"] = {
    "levels": (35.0, 40.0),
}


def inventory_gude_temp(info):
    for oid_index, reading_str in info:
        _oid, index = oid_index.split(".")
        if reading_str != "-9999":
            yield "Sensor %s" % index, {}


def check_gude_temp(item, params, info):
    for oid_index, reading_str in info:
        _oid, index = oid_index.split(".")
        if "Sensor %s" % index == item:
            return check_temperature(float(reading_str) / 10, params, "gude_temp.%s" % item)
    return None


check_info["gude_temp"] = {
    "detect": any_of(
        startswith(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.28507.19"),
        startswith(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.28507.38"),
        startswith(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.28507.66"),
        startswith(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.28507.67"),
    ),
    "inventory_function": inventory_gude_temp,
    "check_function": check_gude_temp,
    "service_description": "Temperature %s",
    "snmp_info": (
        ".1.3.6.1.4.1.28507",
        ["19", "38", "66", "67"],
        [
            OID_END,
            "1.6.1.1.2",  # GUDEADS-EPC****-MIB::epc****TempSensor
        ],
    ),
    "group": "temperature",
    "default_levels_variable": "gude_temp_default_levels",
}
