#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


def parse_hr_mem(info):
    # This should never happen:
    raise RuntimeError("section already migrated")


memused_default_levels = (150.0, 200.0)


def inventory_hr_mem(section):
    if section:
        return [(None, "memused_default_levels")]


def check_hr_mem(_no_item, params, section):
    if not section:
        return

    for subresult in check_memory(params, section):
        yield subresult


# This check plugin uses the migrated section from cmk/base/plugins/agent_based/hr_mem.py!
check_info["hr_mem"] = {
    'parse_function': parse_hr_mem,
    'inventory_function': inventory_hr_mem,
    'check_function': check_hr_mem,
    'service_description': 'Memory',
    'has_perfdata': True,
    'snmp_info': (
        '.1.3.6.1.2.1.25.2.3.1',
        [
            2,  # hrStorageType
            3,  # hrStorageDescr
            4,  # hrStorageAllocationUnits
            5,  # hrStorageSize
            6,  # hrStorageUsed
        ]),
    # Some devices are reporting wrong data on
    # HOST-RESOURCES-MIB. Use UCD-MIB in these
    # cases instead
    'snmp_scan_function': is_hr_mem,
    'group': 'memory',
    'includes': ["mem.include", "ucd_hr.include"]
}
