#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables from the check-context which are necessary for
# resolving legacy discovery results such as [("SUMMARY", "diskstat_default_levels")]. Furthermore,
# it might also remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.huawei_osn import *  # pylint: disable=wildcard-import,unused-wildcard-import

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables from the check-context which are necessary for
# resolving legacy discovery results such as [("SUMMARY", "diskstat_default_levels")]. Furthermore,
# it might also remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.temperature import *  # pylint: disable=wildcard-import,unused-wildcard-import

# The laser should not get hotter than 70°C
factory_settings["huawei_osn_temp_default_levels"] = {
    "levels": (70, 80),
}


def inventory_huawei_osn_temp(info):
    for line in info:
        yield (line[1], {})


def check_huawei_osn_temp(item, params, info):
    for line in info:
        if item == line[1]:
            temp = float(line[0]) / 10.0
            yield check_temperature(temp, params, "huawei_osn_temp_%s" % item)


check_info["huawei_osn_temp"] = {
    "inventory_function": inventory_huawei_osn_temp,
    "check_function": check_huawei_osn_temp,
    "service_description": "Temperature %s",
    "snmp_info": (
        ".1.3.6.1.4.1.2011.2.25.3.40.50.76.10.1",
        [
            "2.190",  # OPTIX-GLOBAL-NGWDM-MIB::new_boardPer15mCurMonValue.boardTemperatureCurrent
            "6.190",  # OPTIX-GLOBAL-NGWDM-MIB::new_boardPer15mCurPara.boardTemperatureCurrent
        ],
    ),
    "snmp_scan_function": huawei_osn_scan_function,
    "group": "temperature",
    "has_perfdata": True,
    "default_levels_variable": "huawei_osn_temp_default_levels",
}
