#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2016             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# .1.3.6.1.4.1.19011.1.3.2.1.3.1.3.1.2.1 "Water Sensor-R" --> ISPRO-MIB::isDeviceMonitorDigitalInName
# .1.3.6.1.4.1.19011.1.3.2.1.3.1.3.1.4.1 1 --> ISPRO-MIB::isDeviceMonitorDigitalInAlarm
# .1.3.6.1.4.1.19011.1.3.2.1.3.2.4.1.3.1 2 --> ISPRO-MIB::isDeviceConfigDigitalInState


def inventory_ispro_sensors_digital(info):
    return [(line[0], None) for line in info if line[0] and line[2] != "1"]


def check_ispro_sensors_digital(item, params, info):
    map_states = {
        "state": {
            "1": "disabled",
            "2": "normal open",
            "3": "normal close",
        },
        "alarm": {
            "1": (0, "normal", "active"),
            "2": (2, "alarm", "inactive"),
        }
    }

    for name, alarm, state in info:
        if item == name:
            # more readable, avoiding confusion
            alarm_state, alarm_state_readable, alarm_device_state_readable = \
                map_states["alarm"].get(alarm, (3, "unknown", "unexpected(%s)" % alarm))
            return alarm_state, 'Status: %s, Alarm status: %s (device: %s)' % \
                   (map_states["state"].get(state, "unexpected(%s)" % state),
                    alarm_state_readable, alarm_device_state_readable )


check_info['ispro_sensors_digital'] = {
    'inventory_function': inventory_ispro_sensors_digital,
    'check_function': check_ispro_sensors_digital,
    'service_description': 'Digital in %s',
    'snmp_info': (
        '.1.3.6.1.4.1.19011.1.3.2.1.3',
        [
            "1.3.1.2",  # ISPRO-MIB::isDeviceMonitorDigitalInName
            "1.3.1.4",  # ISPRO-MIB::isDeviceMonitorDigitalInAlarm
            "2.4.1.3",  # ISPRO-MIB::isDeviceConfigDigitalInState
        ]),
    'snmp_scan_function': ispro_scan_function,
    'includes': ['ispro.include'],
}
