#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

###########################################################################
# NOTE: This check (and associated special agent) is deprecated and will be
#       removed in Checkmk version 2.2.
###########################################################################


def inventory_k8s_roles(parsed):
    if parsed:
        return [(None, {})]
    return []


def check_k8s_roles(item, params, parsed):
    cluster_roles = len(parsed["cluster_roles"])
    roles = len(parsed["roles"])

    yield check_levels(
        cluster_roles + roles,
        "k8s_total_roles",
        params.get("total"),
        infoname="Total",
        human_readable_func=int,
        boundaries=(0, None),
    )
    yield check_levels(
        cluster_roles,
        "k8s_cluster_roles",
        params.get("cluster_roles"),
        infoname="Cluster roles",
        human_readable_func=int,
        boundaries=(0, None),
    )
    yield check_levels(
        roles,
        "k8s_roles",
        params.get("roles"),
        infoname="Roles",
        human_readable_func=int,
        boundaries=(0, None),
    )


check_info["k8s_roles"] = {
    # section is already migrated!
    "inventory_function": inventory_k8s_roles,
    "check_function": check_k8s_roles,
    "service_description": "Roles",
    "group": "k8s_roles",
    "has_perfdata": True,
}
