#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
#<<<kaspersky_quarantine:sep(58)>>>
#Quarantine/backup statistics:
#        Objects: 0
#        Size: 0
#        Last added: unknown

def inventory_kaspersky_av_quarantine(info):
    return [( None, None )]

def check_kaspersky_av_quarantine(item, _no_params, info):
    info = dict(info)
    objects = int(info['Objects'])
    perf = [ ( 'objects', objects ) ]
    if objects > 0:
        return 2, " %d Objects in Quarantine. Last added: %s" % ( objects, info['Last added'].strip() ), perf
    return 0, "No objects in Quarantine", perf

check_info["kaspersky_av_quarantine"] = {
    "check_function"        : check_kaspersky_av_quarantine,
    "inventory_function"    : inventory_kaspersky_av_quarantine,
    "service_description"   : "AV Quarantine",
    "has_perfdata"          : True,
}

