#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.temperature import *  # pylint: disable=wildcard-import,unused-wildcard-import

liebert_bat_temp_default = (40, 50)  # warning / critical


def parse_liebert_bat_temp(info):
    try:
        return {"Battery": int(info[0][0])}
    except (ValueError, IndexError):
        return {}


@discover(default_params="liebert_bat_temp_default")
def discover_liebert_bat_temp(key, _value):
    return key


@get_parsed_item_data
def check_liebert_bat_temp(item, params, data):
    return check_temperature(data, params, "liebert_bat_temp_%s" % item)


check_info["liebert_bat_temp"] = {
    "parse_function": parse_liebert_bat_temp,
    "inventory_function": discover_liebert_bat_temp,
    "check_function": check_liebert_bat_temp,
    "service_description": "Temperature %s",
    "has_perfdata": True,
    "group": "temperature",
    "snmp_info": (".1.3.6.1.4.1.476.1.42.3.4.1.3.3.1.3", "1"),
    "snmp_scan_function": lambda oid: oid(".1.3.6.1.2.1.1.2.0") in [".1.3.6.1.4.1.476.1.42"],
}
