#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2017             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# example output
# .1.3.6.1.4.1.476.1.42.3.9.20.1.10.1.2.1.5027 Supply Humidity
# .1.3.6.1.4.1.476.1.42.3.9.20.1.20.1.2.1.5027 Unavailable
# .1.3.6.1.4.1.476.1.42.3.9.20.1.30.1.2.1.5027 % RH
# .1.3.6.1.4.1.476.1.42.3.9.20.1.10.1.2.1.5028 Return Humidity
# .1.3.6.1.4.1.476.1.42.3.9.20.1.20.1.2.1.5028 21.0
# .1.3.6.1.4.1.476.1.42.3.9.20.1.30.1.2.1.5028 % RH

factory_settings['liebert_humidity_air_default_levels'] = {
    'levels': (50, 55),
    'levels_lower': (10, 15),
}


def _item_from_key(key):
    return key.replace(" Humidity", "")


def discover_liebert_humidity_air(parsed):
    parsed, _extra_section = parsed
    for key, (value, _unit) in parsed.iteritems():
        if "Unavailable" not in value:
            yield _item_from_key(key), {}


def _get_item_data(item, parsed):
    for key, data in parsed.iteritems():
        if _item_from_key(key) == item:
            return data
    return (None, None)


def check_liebert_humidity_air(item, params, parsed):
    parsed, liebert_system_section = parsed
    value, unit = _get_item_data(item, parsed)
    if value is None:
        return

    device_state = liebert_system_section.get('Unit Operating State')
    if "Unavailable" in value and device_state == "standby":
        yield 0, "Unit is in standby (unavailable)"
        return

    try:
        value = float(value)
    except ValueError:
        return

    levels = params['levels'] + params['levels_lower']
    yield check_levels(value, 'humidity', levels, unit=unit)


check_info['liebert_humidity_air'] = {
    'parse_function': lambda info: parse_liebert(info, str),
    'inventory_function': discover_liebert_humidity_air,
    'check_function': check_liebert_humidity_air,
    'service_description': '%s Humidity',
    'snmp_info': (
        '.1.3.6.1.4.1.476.1.42.3.9.20.1',
        [
            '10.1.2.1.5027',  #LIEBERT-GP-FLExible-MIB: lgpFlexibleEntryDataLabel
            '20.1.2.1.5027',  #LIEBERT-GP-FLExible-MIB: lgpFlexibleEntryValue
            '30.1.2.1.5027',  #LIEBERT-GP-FLExible-MIB: lgpFlexibleEntryUnitsOfMeasure
            '10.1.2.1.5028',  #LIEBERT-GP-FLExible-MIB: lgpFlexibleEntryDataLabel
            '20.1.2.1.5028',  #LIEBERT-GP-FLExible-MIB: lgpFlexibleEntryValue
            '30.1.2.1.5028',  #LIEBERT-GP-FLExible-MIB: lgpFlexibleEntryUnitsOfMeasure
        ]),
    'snmp_scan_function': scan_liebert,
    'includes': ['liebert.include'],
    'group': 'humidity',
    'default_levels_variable': 'liebert_humidity_air_default_levels',
    'has_perfdata': True,
    'extra_sections': ["liebert_system"],
}
