#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.df import *  # pylint: disable=wildcard-import,unused-wildcard-import
from cmk.base.check_legacy_includes.size_trend import *  # pylint: disable=wildcard-import,unused-wildcard-import

factory_settings["filesystem_default_levels"] = FILESYSTEM_DEFAULT_LEVELS


def inventory_lvm_vgs(info):
    for line in info:
        yield line[0], {}


def check_lvm_vgs(item, params, info):
    vglist = []
    for vg, _pvs, _lvs, _sns, _attr, size, free in info:
        size_mb = int(size) // 1024**2
        avail_mb = int(free) // 1024**2
        vglist.append((vg, size_mb, avail_mb, 0))
    return df_check_filesystem_list(item, params, vglist)


check_info["lvm_vgs"] = {
    "check_function": check_lvm_vgs,
    "inventory_function": inventory_lvm_vgs,
    "service_description": "LVM VG %s",
    "has_perfdata": True,
    "group": "volume_groups",
    "default_levels_variable": "filesystem_default_levels",
}
