#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_mbg_lantime_ng_state(info):
    if info:
        return[ (None, {}) ]

def check_mbg_lantime_ng_state(_no_item, params, info):
    states = {
        '0': (2, 'not available'),
        '1': (2, 'not synchronized'),
        '2': (0, 'synchronized'),
    }
    ntp_state, stratum, refclock_name = info[0][:-1]
    # Convert to microseconds
    refclock_offset = float(info[0][-1]) * 1000
    newinfo = [[ntp_state, stratum, refclock_name, refclock_offset]]
    return check_mbg_lantime_state_common(states, _no_item, params, newinfo)


check_info["mbg_lantime_ng_state"] = {
    'check_function'            : check_mbg_lantime_ng_state,
    'inventory_function'        : inventory_mbg_lantime_ng_state,
    'service_description'       : 'LANTIME State',
    'has_perfdata'              : True,
    'default_levels_variable'   : "mbg_lantime_state_default_levels",
    'group'                     : 'mbg_lantime_state',
    'snmp_info'                 : ('.1.3.6.1.4.1.5597.30.0.2', [
                                    1, # MBG-SNMP-LTNG-MIB::mbgLtNgNtpCurrentState
                                    2, # MBG-SNMP-LTNG-MIB::mbgLtNgNtpStratum
                                    3, # MBG-SNMP-LTNG-MIB::mbgLtNgNtpRefclockName
                                    4, # MBG-SNMP-LTNG-MIB::mbgLtNgNtpRefclockOffset
                                  ]),
    'snmp_scan_function'        : snmp_scan_mbg_lantime_ng_hw,
    'includes'                  : ["mbg_lantime.include"],
}
