#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# Copyright by Mathias Kettner and Mathias Kettner GmbH.  All rights reserved.
#
# Check_MK is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.
#
# Check_MK is  distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY;  without even the implied warranty of
# MERCHANTABILITY  or  FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have  received  a copy of the  GNU  General Public
# License along with Check_MK.  If  not, email to mk@mathias-kettner.de
# or write to the postal address provided at www.mathias-kettner.de


def inventory_mbg_lantime_ng_power(info):
    for line in info:
        yield line[0], None

def check_mbg_lantime_ng_power(item, _no_params, info):
    power_states = {
        "0" : ( 2, "not available" ),
        "1" : ( 2, "down"          ),
        "2" : ( 0, "up"            ),
    }
    for index, power_status in info:
        if item == index:
            power_state, power_state_name = power_states[power_status]
            infotext = "Status: %s" % power_state_name
            return power_state, infotext


check_info["mbg_lantime_ng_power"] = {
    "check_function"        : check_mbg_lantime_ng_power,
    "inventory_function"    : inventory_mbg_lantime_ng_power,
    "service_description"   : "Power Supply %s",
    "snmp_info"             : (".1.3.6.1.4.1.5597.30.0.5.0.2.1", [
                                    1, # MBG-SNMP-LTNG-MIB::mbgLtNgSysPsIndex
                                    2, # MBG-SNMP-LTNG-MIB::mbgLtNgSysPsStatus
                                  ]),
    "snmp_scan_function"    : snmp_scan_mbg_lantime_ng_hw,
    "includes"              : [ "mbg_lantime.include" ],
}
