#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from cmk.base.check_legacy_includes.cpu_load import *  # pylint: disable=wildcard-import,unused-wildcard-import
from cmk.base.check_legacy_includes.mcafee_gateway import *  # pylint: disable=wildcard-import,unused-wildcard-import
mcafee_emailgateway_cpuload_default_levels = (5.0, 10.0)


def inventory_mcafee_emailgateway_cpuload(info):
    return [(None, "mcafee_emailgateway_cpuload_default_levels")]


def check_mcafee_emailgateway_cpuload(item, params, info):
    load = float(info[0][0])
    return check_cpu_load_generic(params, [load, load, load])


check_info['mcafee_emailgateway_cpuload'] = {
    'inventory_function': inventory_mcafee_emailgateway_cpuload,
    'check_function': check_mcafee_emailgateway_cpuload,
    'service_description': 'CPU load',
    'snmp_info': (
        '.1.3.6.1.4.1.1230.2.4.1.2.3.1',
        [
            '2',  # loadaverage
        ]),
    'snmp_scan_function': scan_mcafee_emailgateway,
    'group': 'cpu_load',
}
