#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def inventory_orion_backup(info):
    return [(None, {})]


def check_orion_backup(item, params, info):
    map_states = {
        '1': (1, 'inactive'),
        '2': (0, 'OK'),
        '3': (1, 'occured'),
        '4': (2, 'fail'),
    }

    backup_time_status, backup_time = info[0]
    state, state_readable = map_states[backup_time_status]
    return state, 'Status: %s, Expected time: %s minutes' % (state_readable, backup_time)


check_info['orion_backup'] = {
    'inventory_function': inventory_orion_backup,
    'check_function': check_orion_backup,
    'service_description': 'Backup',
    'snmp_info': (
        '.1.3.6.1.4.1.20246.2.3.1.1.1.2.5.3.3',
        [
            '2',  # ORION-BASE-MIB::dcLossOfBackupTimeStatus
            '3',  # ORION-BASE-MIB::dcExpectedBackupTime
        ]),
    'snmp_scan_function': lambda oid: oid('.1.3.6.1.2.1.1.2.0').startswith('.1.3.6.1.4.1.20246'),
}
