#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Voltage 28507.27.1.5.1.2.1.6
# Ampere m28507.27.1.5.1.2.1.5
# Power 28507.27.1.5.1.2.1.4
# Track power 28507.27.1.5.1.2.1.10
# Consumption 28507.27.1.5.1.2.1.3


check_info['pdu_gude_8310'] = {
    'check_function' : check_pdu_gude,
    'inventory_function' : inventory_pdu_gude,
    'snmp_scan_function' : lambda oid: oid(".1.3.6.1.2.1.1.2.0") in [".1.3.6.1.4.1.28507.27"],
    'service_description' : 'Phase %s',
    'has_perfdata' : True,
    'group' : 'pdu_gude', 
    'snmp_info' : ( '.1.3.6.1.4.1.28507.27.1.5.1.2.1', [3, 4, 5, 6,10] ), 
    'includes' : ["pdu_gude.include"],
}
