#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2016             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

check_info['perle_modules_cm1000'] = {
    'inventory_function': inventory_perle_cm_modules,
    'check_function': check_perle_cm_modules,
    'service_description': 'Chassis slot %s CM1000',
    'snmp_info': (
        '.1.3.6.1.4.1.1966.21.1.1.1.1.4.1',
        [
            "1.1.3",  # PERLE-MCR-MGT-MIB::cm1000Modelname
            "3.1.3",  # PERLE-MCR-MGT-MIB::cm1000LedPWR
            "1.1.2",  # PERLE-MCR-MGT-MIB::cm1000ConfigSlotIndex
            "1.1.18",  # PERLE-MCR-MGT-MIB::cm1000FiberLPRFStatus
            "1.1.12",  # PERLE-MCR-MGT-MIB::cm1000FiberLinkStatus
            "1.1.13",  # PERLE-MCR-MGT-MIB::cm1000FiberConnType
            "1.1.15",  # PERLE-MCR-MGT-MIB::cm1000FiberSpeed
            "1.1.28",  # PERLE-MCR-MGT-MIB::cm1000CopperLPRFStatus
            "1.1.21",  # PERLE-MCR-MGT-MIB::cm1000CopperLinkStatus
            "1.1.22",  # PERLE-MCR-MGT-MIB::cm1000CopperConnType
            "1.1.24",  # PERLE-MCR-MGT-MIB::cm1000CopperSpeed
        ]),
    'snmp_scan_function': perle_scan_function,
    'includes': ['perle.include'],
}
