#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


# 1.3.6.1.4.1.367.3.2.1.2.19.5.1.5.1 Counter: Machine Total
# 1.3.6.1.4.1.367.3.2.1.2.19.5.1.9.1 98040
# 1.3.6.1.4.1.367.3.2.1.2.19.5.1.5.21 Total Prints: Color
# 1.3.6.1.4.1.367.3.2.1.2.19.5.1.9.21 46226
# 1.3.6.1.4.1.367.3.2.1.2.19.5.1.5.22 Total Prints: Black & White
# 1.3.6.1.4.1.367.3.2.1.2.19.5.1.9.22 51814


def parse_printer_pages_ricoh(info):
    parsed = {}
    for name, pages_text in info:
        if name == 'Counter: Machine Total':
            parsed['pages_total'] = int(pages_text)

        elif name == 'Total Prints: Color':
            parsed['pages_color'] = int(pages_text)

        elif name == 'Total Prints: Black & White':
            parsed['pages_bw'] = int(pages_text)
    return parsed


check_info["printer_pages_ricoh"] = {
    'parse_function'        : parse_printer_pages_ricoh,
    'inventory_function'    : inventory_printer_pages_types,
    'check_function'        : check_printer_pages_types,
    'service_description'   : 'Pages',
    'has_perfdata'          : True,
    'snmp_info'             : (".1.3.6.1.4.1.367.3.2.1.2.19.5.1", [ 5, 9 ]),
    'snmp_scan_function'    : scan_ricoh_printer,
    'includes'              : [ 'printer_pages.include' ],
}
