#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2017             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def parse_sap_hana_version(info):
    parsed = {}
    # First one is header
    for line in info[1:]:
        if line[0] in ["git merge time", "compile date", ]:
            line_data = ":".join(line[1:]).strip()
        else:
            line_data = " ".join(line[1:]).strip()
        parsed.setdefault(line[0], line_data)
    return parsed


def inventory_sap_hana_version(parsed):
    return [(None, None)]


def check_sap_hana_version(item, params, parsed):
    for k, v in parsed.iteritems():
        if k in ["version", ]:
            yield 0, "%s: %s" % (k.title(), v)


check_info['sap_hana_version'] = {
    'parse_function'        : parse_sap_hana_version,
    'inventory_function'    : inventory_sap_hana_version,
    'check_function'        : check_sap_hana_version,
    'service_description'   : 'SAP HANA Version',
}
