#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


def inventory_sap_hana_filesystem(parsed):
    return


def check_sap_hana_filesystem(item, params, parsed):
    return 1, "This check is deprecated. Please have a look at werk #7100."


check_info["sap_hana_filesystem"] = {
    "inventory_function": inventory_sap_hana_filesystem,
    "check_function": check_sap_hana_filesystem,
    "service_description": "SAP HANA Filesystem %s",
}
