#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_snmp_info(info):
    if len(info[0]) >= 4:
        return [ (None, None) ]

def check_snmp_info(checktype, params, info):
    if len(info[0]) >= 4:
        return (0, "OK - %s, %s, %s, %s" % (info[0][0], info[0][2], info[0][3], info[0][1]))
    else:
        return (3, "UNKNOWN - No data retrieved")

check_info['snmp_info'] = (check_snmp_info, "SNMP Info", 0, inventory_snmp_info)
snmp_info['snmp_info']  = ( ".1.3.6.1.2.1.1", [ '1.0', '4.0', '5.0', '6.0', ] )

# This check works on all SNMP hosts
snmp_scan_functions['snmp_info'] = lambda oid: oid(".1.3.6.1.2.1.1.1.0") != None
