#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

factory_settings['stormshield_updates'] = {
    'Not Available' : 1,
    'Broken'        : 2,
    'Uptodate'      : 0,
    'Disabled'      : 1,
    'Never started' : 0,
    'Running'       : 0,
    'Failed'        : 2,
}

def inventory_stormshield_updates(info):
    for index, subsystem, state, lastrun in info:
        if state == 'Failed' and lastrun == '':
            pass
        elif not state in ['Not Available', 'Never started']:
            yield subsystem, {}


def check_stormshield_updates(item, params, info):
    for index, subsystem, state, lastrun in info:
        if item == subsystem:
            if lastrun == '':
                lastrun = 'Never'
            infotext = 'Subsystem %s is %s, last update: %s' % ( subsystem, state, lastrun)
            monitoringstate = params.get(state, 3)
            yield monitoringstate, infotext


check_info['stormshield_updates'] = {
    'inventory_function'        : inventory_stormshield_updates,
    'check_function'            : check_stormshield_updates,
    'default_levels_variable'   : 'stormshield_updates',
    'service_description'       : 'Autoupdate %s',
    'has_perfdata'              : False,
    'snmp_info'                 : ('.1.3.6.1.4.1.11256.1.9.1.1', [
                                  '1',    # ID
                                  '2',    # SubSystem
                                  '3',    # State
                                  '4'     # LastUpdate
                                  ] ),
    'group'                     : 'stormshield_updates',
    'snmp_scan_function'        : stormshield_scan_function,
    'includes'                  : [ 'stormshield.include' ],
}
