#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:

symantec_av_updates_default_levels = ( 259200, 345600 )

def inventory_symantec_av_updates(info):
    return [( None, 'symantec_av_updates_default_levels' )]

def check_symantec_av_updates( _no_item, params, info):
    warn, crit = params
    last =  info[0][0]
    last =  datetime.datetime.strptime(last, "%m/%d/%y").date()
    age = abs((datetime.datetime.now().date() - last).days)
    age = 60*60*25*age
    rev = info[0][-1]

    message = "%d days since last update" % age
    if age > crit:
        return 2, message
    if age > warn:
        return 1, message
    return 0, message

check_info["symantec_av_updates"] = {
    "check_function"        : check_symantec_av_updates,
    "group"                 : "antivir_update_age",
    "inventory_function"    : inventory_symantec_av_updates,
    "service_description"   : "AV Update Status",
    "has_perfdata"          : False,
}

