#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2015             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# .1.3.6.1.4.1.2021.4.5.0 4003584 --> UCD-SNMP-MIB::memTotalReal.0
# .1.3.6.1.4.1.2021.4.6.0 188296  --> UCD-SNMP-MIB::memAvailReal.0


# suggested by cutomer
factory_settings["ucd_mem_default_levels"] = {
    "levels" : ("perc_used", (80.0, 90.0))
}


def inventory_ucd_mem(info):
    if info and len(info[0]) > 1:
        for line in info[0]:
            if line == "":
                return []
        return [ ("", {}) ]


def check_ucd_mem(_no_item, params, info):
    mem_total_bytes, mem_avail_bytes = \
        map(lambda x: int(x.replace("kB", "").strip()) * 1024, info[0])
    mem_used_bytes = mem_total_bytes - mem_avail_bytes
    return check_memory_simple(mem_used_bytes, mem_total_bytes, params)


check_info['ucd_mem'] = {
    'inventory_function'        : inventory_ucd_mem,
    'check_function'            : check_ucd_mem,
    'service_description'       : 'Memory',
    'has_perfdata'              : True,
    'snmp_info'                 : (".1.3.6.1.4.1.2021.4", [
                                        "5",    # memTotal     -> kB
                                        "6",    # memAvailable -> kB
                                  ]),
    'snmp_scan_function'        : prefer_hr_scan_function,
    'default_levels_variable'   : 'ucd_mem_default_levels',
    'group'                     : 'memory_simple',
    'includes'                  : [ "ucd.include", "memory.include" ],
}
