#!/usr/bin/python

def vbox_guest_make_dict(info):
    return dict([(l[1].split('/',2)[2].rstrip(','), l[3]) for l in info])

def check_vbox_guest(item, _no_params, info):
    if len(info) == 1 and info[0][0] == "ERROR":
        return (3, "UNKNOWN - Error running VBoxControl guestproperty enumerate")
    try:
        d = vbox_guest_make_dict(info)
    except:
        d = {}

    if len(d) == 0:
        return (2, "CRIT - No guest additions installed")

    version = d.get('GuestAdd/Version')
    revision = d.get('GuestAdd/Revision')
    if not version or not version[0].isdigit():
        return (3, "UNKNOWN - No guest addition version available")
    infotext = " - version: %s, revision: %s" % (version, revision)

    host_version = d['HostInfo/VBoxVer']
    host_revision = d['HostInfo/VBoxRev']
    if (host_version, host_revision) != (version, revision):
        return (1, "WARN" + infotext + ", Host has %s/%s" % (host_version, host_revision))
    else:
        return (0, "OK" + infotext)

def inventory_vbox_guest(checktype, info):
    if len(info) > 0:
        return [(None, None)]

check_info["vbox_guest"] = ( check_vbox_guest, "VBox Guest Additions", 0, inventory_vbox_guest)

