#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

check_info["viprinet_mem"] = {
    "check_function": lambda _no_item, _no_params, info: (
        0,
        "Memory used: %s" % get_bytes_human_readable(saveint(info[0][0])),
    ),
    "inventory_function": lambda info: len(info) > 0 and [(None, None)] or [],
    "service_description": "Memory",
    "snmp_info": (".1.3.6.1.4.1.35424.1.2", [2]),
    "snmp_scan_function": lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.35424",
}
