#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

import collections
from typing import Iterable, List, Mapping

import pytest

from testlib import Check

pytestmark = pytest.mark.checks

UnitEntry = collections.namedtuple(
    "UnitEntry", ['name', 'type', 'load', 'active', 'sub', 'description', 'state'])


@pytest.mark.parametrize(
    "string_table, expected_result",
    [
        pytest.param(
            [
                ['[list-unit-files]'],
                ['UNIT', 'FILE', 'STATE'],
                ['proc-sys-fs-binfmt_misc.automount', 'static'],
                ['dev-hugepages.mount', 'static'],
                ['dev-mqueue.mount', 'static'],
                ['proc-fs-nfsd.mount', 'static'],
                ['proc-sys-fs-binfmt_misc.mount', 'static'],
                ['sys-fs-fuse-connections.mount', 'static'],
                ['sys-kernel-config.mount', 'static'],
                ['sys-kernel-debug.mount', 'static'],
                ['tmp.mount', 'disabled'],
                ['var-lib-nfs-rpc_pipefs.mount', 'static'],
                ['brandbot.path', 'enabled'],
                ['systemd-ask-password-console.path', 'static'],
                ['systemd-ask-password-plymouth.path', 'static'],
                ['systemd-ask-password-wall.path', 'static'],
                ['session-22867.scope', 'static'],
                ['session-23765.scope', 'static'],
                ['session-23771.scope', 'static'],
                ['session-7560.scope', 'static'],
                ['session-c3.scope', 'static'],
                ['session-c4.scope', 'static'],
                ['abrt-ccpp.service', 'enabled'],
                ['abrt-oops.service', 'enabled'],
                ['abrt-pstoreoops.service', 'disabled'],
                ['abrt-vmcore.service', 'enabled'],
                ['abrt-xorg.service', 'enabled'],
                ['abrtd.service', 'enabled'],
                ['arp-ethers.service', 'disabled'],
                ['atd.service', 'enabled'],
                ['atop.service', 'enabled'],
                ['atopacct.service', 'disabled'],
                ['auditd.service', 'enabled'],
                ['auth-rpcgss-module.service', 'static'],
                ['autofs.service', 'disabled'],
                ['autovt@.service', 'enabled'],
                ['blk-availability.service', 'disabled'],
                ['brandbot.service', 'static'],
                ['canberra-system-bootup.service', 'disabled'],
                ['canberra-system-shutdown-reboot.service', 'disabled'],
                ['canberra-system-shutdown.service', 'disabled'],
                ['cgconfig.service', 'disabled'],
                ['cgdcbxd.service', 'disabled'],
                ['cgred.service', 'disabled'],
                ['check-mk-agent@.service', 'static'],
                ['chrony-dnssrv@.service', 'static'],
                ['chrony-wait.service', 'disabled'],
                ['chronyd.service', 'disabled'],
                ['console-getty.service', 'disabled'],
                ['console-shell.service', 'disabled'],
                ['container-getty@.service', 'static'],
                ['corosync-notifyd.service', 'disabled'],
                ['corosync-qdevice.service', 'disabled'],
                ['corosync.service', 'disabled'],
                ['cpupower.service', 'disabled'],
                ['crm_mon.service', 'disabled'],
                ['crond.service', 'enabled'],
                ['dbus-org.freedesktop.hostname1.service', 'static'],
                ['dbus-org.freedesktop.import1.service', 'static'],
                ['dbus-org.freedesktop.locale1.service', 'static'],
                ['dbus-org.freedesktop.login1.service', 'static'],
                ['dbus-org.freedesktop.machine1.service', 'static'],
                ['dbus-org.freedesktop.NetworkManager.service', 'enabled'],
                ['dbus-org.freedesktop.nm-dispatcher.service', 'enabled'],
                ['dbus-org.freedesktop.timedate1.service', 'static'],
                ['dbus.service', 'static'],
                ['debug-shell.service', 'disabled'],
                ['dm-event.service', 'static'],
                ['dmraid-activation.service', 'enabled'],
                ['dnsmasq.service', 'disabled'],
                ['dracut-cmdline.service', 'static'],
                ['dracut-initqueue.service', 'static'],
                ['dracut-mount.service', 'static'],
                ['dracut-pre-mount.service', 'static'],
                ['dracut-pre-pivot.service', 'static'],
                ['dracut-pre-trigger.service', 'static'],
                ['dracut-pre-udev.service', 'static'],
                ['dracut-shutdown.service', 'static'],
                ['dsmcad_SCHED_PHT_BACKUP_DC2.service', 'enabled'],
                ['ebtables.service', 'disabled'],
                ['emergency.service', 'static'],
                ['fancontrol.service', 'disabled'],
                ['fcoe.service', 'disabled'],
                ['firewalld.service', 'disabled'],
                ['fprintd.service', 'static'],
                ['fstrim.service', 'static'],
                ['getty@.service', 'enabled'],
                ['goferd.service', 'enabled'],
                ['gssproxy.service', 'disabled'],
                ['halt-local.service', 'static'],
                ['hwloc-dump-hwdata.service', 'disabled'],
                ['initrd-cleanup.service', 'static'],
                ['initrd-parse-etc.service', 'static'],
                ['initrd-switch-root.service', 'static'],
                ['initrd-udevadm-cleanup-db.service', 'static'],
                ['ipmi.service', 'disabled'],
                ['ipmievd.service', 'disabled'],
                ['iprdump.service', 'disabled'],
                ['iprinit.service', 'disabled'],
                ['iprupdate.service', 'disabled'],
                ['irqbalance.service', 'enabled'],
                ['iscsi-shutdown.service', 'static'],
                ['iscsi.service', 'enabled'],
                ['iscsid.service', 'disabled'],
                ['iscsiuio.service', 'disabled'],
                ['kdump.service', 'enabled'],
                ['kmod-static-nodes.service', 'static'],
                ['kpatch.service', 'disabled'],
                ['libstoragemgmt.service', 'enabled'],
                ['lldpad.service', 'disabled'],
                ['lm_sensors.service', 'enabled'],
                ['lvm2-lvmetad.service', 'static'],
                ['lvm2-lvmpolld.service', 'static'],
                ['lvm2-monitor.service', 'enabled'],
                ['lvm2-pvscan@.service', 'static'],
                ['lwsmd.service', 'enabled'],
                ['mdadm-grow-continue@.service', 'static'],
                ['mdadm-last-resort@.service', 'static'],
                ['mdmon@.service', 'static'],
                ['mdmonitor.service', 'enabled'],
                ['messagebus.service', 'static'],
                ['microcode.service', 'enabled'],
                ['multipathd.service', 'enabled'],
                ['NetworkManager-dispatcher.service', 'enabled'],
                ['NetworkManager-wait-online.service', 'enabled'],
                ['NetworkManager.service', 'enabled'],
                ['nfs-blkmap.service', 'disabled'],
                ['nfs-config.service', 'static'],
                ['nfs-idmap.service', 'static'],
                ['nfs-idmapd.service', 'static'],
                ['nfs-lock.service', 'static'],
                ['nfs-mountd.service', 'static'],
                ['nfs-rquotad.service', 'disabled'],
                ['nfs-secure.service', 'static'],
                ['nfs-server.service', 'disabled'],
                ['nfs-utils.service', 'static'],
                ['nfs.service', 'disabled'],
                ['nfslock.service', 'static'],
                ['ntpd.service', 'enabled'],
                ['ntpdate.service', 'disabled'],
                ['numad.service', 'disabled'],
                ['pacemaker.service', 'disabled'],
                ['pcs_snmp_agent.service', 'enabled'],
                ['pcsd.service', 'enabled'],
                ['plymouth-halt.service', 'disabled'],
                ['plymouth-kexec.service', 'disabled'],
                ['plymouth-poweroff.service', 'disabled'],
                ['plymouth-quit-wait.service', 'disabled'],
                ['plymouth-quit.service', 'disabled'],
                ['plymouth-read-write.service', 'disabled'],
                ['plymouth-reboot.service', 'disabled'],
                ['plymouth-start.service', 'disabled'],
                ['plymouth-switch-root.service', 'static'],
                ['pmcd.service', 'disabled'],
                ['pmie.service', 'disabled'],
                ['pmie_check.service', 'static'],
                ['pmie_daily.service', 'disabled'],
                ['pmlogger.service', 'disabled'],
                ['pmlogger_check.service', 'disabled'],
                ['pmlogger_daily-poll.service', 'disabled'],
                ['pmlogger_daily.service', 'disabled'],
                ['pmproxy.service', 'disabled'],
                ['polkit.service', 'static'],
                ['postfix.service', 'disabled'],
                ['powertop.service', 'disabled'],
                ['prole_hana.service', 'enabled'],
                ['psacct.service', 'disabled'],
                ['puppet.service', 'enabled'],
                ['puppetagent.service', 'enabled'],
                ['quotaon.service', 'static'],
                ['rc-local.service', 'static'],
                ['rdisc.service', 'disabled'],
                ['rescue.service', 'static'],
                ['rhel-autorelabel-mark.service', 'enabled'],
                ['rhel-autorelabel.service', 'enabled'],
                ['rhel-configure.service', 'enabled'],
                ['rhel-dmesg.service', 'enabled'],
                ['rhel-domainname.service', 'enabled'],
                ['rhel-import-state.service', 'enabled'],
                ['rhel-loadmodules.service', 'enabled'],
                ['rhel-readonly.service', 'enabled'],
                ['rhsm-facts.service', 'disabled'],
                ['rhsm.service', 'disabled'],
                ['rhsmcertd.service', 'enabled'],
                ['rngd.service', 'enabled'],
                ['rpc-gssd.service', 'static'],
                ['rpc-rquotad.service', 'disabled'],
                ['rpc-statd-notify.service', 'static'],
                ['rpc-statd.service', 'static'],
                ['rpcbind.service', 'enabled'],
                ['rpcgssd.service', 'static'],
                ['rpcidmapd.service', 'static'],
                ['rsyncd.service', 'disabled'],
                ['rsyncd@.service', 'static'],
                ['rsyslog.service', 'enabled'],
                ['selinux-policy-migrate-local-changes@.service', 'static'],
                ['serial-getty@.service', 'disabled'],
                ['smartd.service', 'enabled'],
                ['snmpd.service', 'enabled'],
                ['snmptrapd.service', 'disabled'],
                ['sshd-keygen.service', 'static'],
                ['sshd.service', 'enabled'],
                ['sshd@.service', 'static'],
                ['sysstat.service', 'enabled'],
                ['systemd-ask-password-console.service', 'static'],
                ['systemd-ask-password-plymouth.service', 'static'],
                ['systemd-ask-password-wall.service', 'static'],
                ['systemd-backlight@.service', 'static'],
                ['systemd-binfmt.service', 'static'],
                ['systemd-bootchart.service', 'disabled'],
                ['systemd-firstboot.service', 'static'],
                ['systemd-fsck-root.service', 'static'],
                ['systemd-fsck@.service', 'static'],
                ['systemd-halt.service', 'static'],
                ['systemd-hibernate-resume@.service', 'static'],
                ['systemd-hibernate.service', 'static'],
                ['systemd-hostnamed.service', 'static'],
                ['systemd-hwdb-update.service', 'static'],
                ['systemd-hybrid-sleep.service', 'static'],
                ['systemd-importd.service', 'static'],
                ['systemd-initctl.service', 'static'],
                ['systemd-journal-catalog-update.service', 'static'],
                ['systemd-journal-flush.service', 'static'],
                ['systemd-journald.service', 'static'],
                ['systemd-kexec.service', 'static'],
                ['systemd-localed.service', 'static'],
                ['systemd-logind.service', 'static'],
                ['systemd-machine-id-commit.service', 'static'],
                ['systemd-machined.service', 'static'],
                ['systemd-modules-load.service', 'static'],
                ['systemd-nspawn@.service', 'disabled'],
                ['systemd-poweroff.service', 'static'],
                ['systemd-quotacheck.service', 'static'],
                ['systemd-random-seed.service', 'static'],
                ['systemd-readahead-collect.service', 'enabled'],
                ['systemd-readahead-done.service', 'indirect'],
                ['systemd-readahead-drop.service', 'enabled'],
                ['systemd-readahead-replay.service', 'enabled'],
                ['systemd-reboot.service', 'static'],
                ['systemd-remount-fs.service', 'static'],
                ['systemd-rfkill@.service', 'static'],
                ['systemd-shutdownd.service', 'static'],
                ['systemd-suspend.service', 'static'],
                ['systemd-sysctl.service', 'static'],
                ['systemd-timedated.service', 'static'],
                ['systemd-tmpfiles-clean.service', 'static'],
                ['systemd-tmpfiles-setup-dev.service', 'static'],
                ['systemd-tmpfiles-setup.service', 'static'],
                ['systemd-udev-settle.service', 'static'],
                ['systemd-udev-trigger.service', 'static'],
                ['systemd-udevd.service', 'static'],
                ['systemd-update-done.service', 'static'],
                ['systemd-update-utmp-runlevel.service', 'static'],
                ['systemd-update-utmp.service', 'static'],
                ['systemd-user-sessions.service', 'static'],
                ['systemd-vconsole-setup.service', 'static'],
                ['target.service', 'disabled'],
                ['tcsd.service', 'disabled'],
                ['teamd@.service', 'static'],
                ['tuned.service', 'enabled'],
                ['unbound-anchor.service', 'static'],
                ['usb_modeswitch@.service', 'static'],
                ['uuidd.service', 'indirect'],
                ['vgauthd.service', 'enabled'],
                ['vmtoolsd.service', 'enabled'],
                ['wpa_supplicant.service', 'disabled'],
                ['-.slice', 'static'],
                ['machine.slice', 'static'],
                ['system.slice', 'static'],
                ['user-0.slice', 'static'],
                ['user-1101.slice', 'static'],
                ['user-1104.slice', 'static'],
                ['user.slice', 'static'],
                ['check-mk-agent.socket', 'enabled'],
                ['dbus.socket', 'static'],
                ['dm-event.socket', 'enabled'],
                ['iscsid.socket', 'enabled'],
                ['iscsiuio.socket', 'enabled'],
                ['lldpad.socket', 'disabled'],
                ['lvm2-lvmetad.socket', 'enabled'],
                ['lvm2-lvmpolld.socket', 'enabled'],
                ['rpcbind.socket', 'enabled'],
                ['rsyncd.socket', 'disabled'],
                ['sshd.socket', 'disabled'],
                ['syslog.socket', 'static'],
                ['systemd-initctl.socket', 'static'],
                ['systemd-journald.socket', 'static'],
                ['systemd-shutdownd.socket', 'static'],
                ['systemd-udevd-control.socket', 'static'],
                ['systemd-udevd-kernel.socket', 'static'],
                ['uuidd.socket', 'enabled'],
                ['basic.target', 'static'],
                ['bluetooth.target', 'static'],
                ['cryptsetup-pre.target', 'static'],
                ['cryptsetup.target', 'static'],
                ['ctrl-alt-del.target', 'disabled'],
                ['default.target', 'enabled'],
                ['emergency.target', 'static'],
                ['final.target', 'static'],
                ['getty-pre.target', 'static'],
                ['getty.target', 'static'],
                ['graphical.target', 'static'],
                ['halt.target', 'disabled'],
                ['hibernate.target', 'static'],
                ['hybrid-sleep.target', 'static'],
                ['initrd-fs.target', 'static'],
                ['initrd-root-fs.target', 'static'],
                ['initrd-switch-root.target', 'static'],
                ['initrd.target', 'static'],
                ['iprutils.target', 'disabled'],
                ['kexec.target', 'disabled'],
                ['local-fs-pre.target', 'static'],
                ['local-fs.target', 'static'],
                ['machines.target', 'disabled'],
                ['multi-user.target', 'enabled'],
                ['network-online.target', 'static'],
                ['network-pre.target', 'static'],
                ['network.target', 'static'],
                ['nfs-client.target', 'enabled'],
                ['nss-lookup.target', 'static'],
                ['nss-user-lookup.target', 'static'],
                ['paths.target', 'static'],
                ['poweroff.target', 'disabled'],
                ['printer.target', 'static'],
                ['reboot.target', 'disabled'],
                ['remote-cryptsetup.target', 'disabled'],
                ['remote-fs-pre.target', 'static'],
                ['remote-fs.target', 'enabled'],
                ['rescue.target', 'disabled'],
                ['resource-agents-deps.target', 'static'],
                ['rpc_pipefs.target', 'static'],
                ['rpcbind.target', 'static'],
                ['runlevel0.target', 'disabled'],
                ['runlevel1.target', 'disabled'],
                ['runlevel2.target', 'enabled'],
                ['runlevel3.target', 'enabled'],
                ['runlevel4.target', 'enabled'],
                ['runlevel5.target', 'static'],
                ['runlevel6.target', 'disabled'],
                ['shutdown.target', 'static'],
                ['sigpwr.target', 'static'],
                ['sleep.target', 'static'],
                ['slices.target', 'static'],
                ['smartcard.target', 'static'],
                ['sockets.target', 'static'],
                ['sound.target', 'static'],
                ['suspend.target', 'static'],
                ['swap.target', 'static'],
                ['sysinit.target', 'static'],
                ['system-update.target', 'static'],
                ['time-sync.target', 'static'],
                ['timers.target', 'static'],
                ['umount.target', 'static'],
                ['chrony-dnssrv@.timer', 'disabled'],
                ['fstrim.timer', 'disabled'],
                ['mdadm-last-resort@.timer', 'static'],
                ['pmie_check.timer', 'disabled'],
                ['pmie_daily.timer', 'disabled'],
                ['pmlogger_check.timer', 'disabled'],
                ['pmlogger_daily-poll.timer', 'disabled'],
                ['pmlogger_daily.timer', 'disabled'],
                ['systemd-readahead-done.timer', 'indirect'],
                ['systemd-tmpfiles-clean.timer', 'static'],
                ['unbound-anchor.timer', 'enabled'],
                ['362', 'unit', 'files', 'listed.'],
                ['[all]'],
                ['UNIT', 'LOAD', 'ACTIVE', 'SUB', 'JOB'],
                [
                    'dev-disk-by\\x2duuid-7941a423\\x2de7d7\\x2d4bbd\\x2d9526\\x2dfdb7ba7982a6.device',
                    'loaded', 'active', 'plugged',
                    '/dev/disk/by-uuid/7941a423-e7d7-4bbd-9526-fdb7ba7982a6'
                ],
                ['dev-sr0.device', 'loaded', 'active', 'plugged', 'VMware_Virtual_SATA_CDRW_Drive'],
                [
                    'dev-vg_data-lv_data.device', 'loaded', 'active', 'plugged',
                    '/dev/vg_data/lv_data'
                ],
                ['hana-data.mount', 'loaded', 'active', 'mounted', '/hana/data'],
                ['hana-log.mount', 'loaded', 'active', 'mounted', '/hana/log'],
                ['hana-shared.mount', 'loaded', 'active', 'mounted', '/hana/shared'],
                [
                    'proc-fs-nfsd.mount', 'loaded', 'inactive', 'dead', 'NFSD', 'configuration',
                    'filesystem'
                ],
                [
                    'proc-sys-fs-binfmt_misc.mount', 'loaded', 'active', 'mounted', 'Arbitrary',
                    'Executable', 'File', 'Formats', 'File', 'System'
                ],
                ['run-user-0.mount', 'loaded', 'active', 'mounted', '/run/user/0'],
                ['run-user-1101.mount', 'loaded', 'active', 'mounted', '/run/user/1101'],
                ['run-user-1104.mount', 'loaded', 'active', 'mounted', '/run/user/1104'],
                ['sapTEMP.mount', 'loaded', 'active', 'mounted', '/sapTEMP'],
                ['sapWORK.mount', 'loaded', 'active', 'mounted', '/sapWORK'],
                [
                    'sys-fs-fuse-connections.mount', 'loaded', 'inactive', 'dead', 'FUSE',
                    'Control', 'File', 'System'
                ],
                [
                    'sys-kernel-config.mount', 'loaded', 'active', 'mounted', 'Configuration',
                    'File', 'System'
                ],
                [
                    'sys-kernel-debug.mount', 'loaded', 'active', 'mounted', 'Debug', 'File',
                    'System'
                ],
                ['tmp.mount', 'loaded', 'inactive', 'dead', 'Temporary', 'Directory'],
                ['usr-sap.mount', 'loaded', 'active', 'mounted', '/usr/sap'],
                ['usr.mount', 'loaded', 'active', 'mounted', '/usr'],
                [
                    'var-lib-nfs-rpc_pipefs.mount', 'loaded', 'active', 'mounted', 'RPC', 'Pipe',
                    'File', 'System'
                ],
                ['brandbot.path', 'loaded', 'active', 'waiting', 'Flexible', 'branding'],
                [
                    'systemd-ask-password-console.path', 'loaded', 'inactive', 'dead', 'Dispatch',
                    'Password', 'Requests', 'to', 'Console', 'Directory', 'Watch'
                ],
                [
                    'systemd-ask-password-plymouth.path', 'loaded', 'active', 'waiting', 'Forward',
                    'Password', 'Requests', 'to', 'Plymouth', 'Directory', 'Watch'
                ],
                [
                    'systemd-ask-password-wall.path', 'loaded', 'active', 'waiting', 'Forward',
                    'Password', 'Requests', 'to', 'Wall', 'Directory', 'Watch'
                ],
                [
                    'abrtd.service', 'loaded', 'active', 'running', 'ABRT', 'Automated', 'Bug',
                    'Reporting', 'Tool'
                ],
                ['atd.service', 'loaded', 'active', 'running', 'Job', 'spooling', 'tools'],
                [
                    'atop.service', 'loaded', 'active', 'running', 'Atop', 'advanced',
                    'performance', 'monitor'
                ],
                [
                    'blk-availability.service', 'loaded', 'active', 'exited', 'Availability', 'of',
                    'block', 'devices'
                ],
                [
                    'brandbot.service', 'loaded', 'inactive', 'dead', 'Flexible', 'Branding',
                    'Service'
                ],
                [
                    'check-mk-agent@40273-10.223.16.185:6556-10.20.114.58:57796.service', 'loaded',
                    'activating', 'start', 'start', 'CheckMK', '(10.20.114.58:57796)'
                ],
                [
                    'corosync-qdevice.service', 'loaded', 'active', 'running', 'Corosync',
                    'Qdevice', 'daemon'
                ],
                [
                    'corosync.service', 'loaded', 'active', 'running', 'Corosync', 'Cluster',
                    'Engine'
                ],
                [
                    'cpupower.service', 'loaded', 'inactive', 'dead', 'Configure', 'CPU', 'power',
                    'related', 'settings'
                ],
                ['crond.service', 'loaded', 'active', 'running', 'Command', 'Scheduler'],
                [
                    'dbus.service', 'loaded', 'active', 'running', 'D-Bus', 'System', 'Message',
                    'Bus'
                ],
                [
                    '*', 'display-manager.service', 'not-found', 'inactive', 'dead',
                    'display-manager.service'
                ],
                [
                    'dm-event.service', 'loaded', 'inactive', 'dead', 'Device-mapper', 'event',
                    'daemon'
                ],
                [
                    'dmraid-activation.service', 'loaded', 'inactive', 'dead', 'Activation', 'of',
                    'DM', 'RAID', 'sets'
                ],
                [
                    'dracut-shutdown.service', 'loaded', 'inactive', 'dead', 'Restore',
                    '/run/initramfs'
                ],
                [
                    'dsmcad_SCHED_PHT_BACKUP_DC2.service', 'loaded', 'active', 'running', '"IBM',
                    'Spectrum', 'Protect', 'Client', 'dsmcad', 'systemd-style', 'service."'
                ],
                ['emergency.service', 'loaded', 'inactive', 'dead', 'Emergency', 'Shell'],
                ['fcoe.service', 'loaded', 'inactive', 'dead', 'Open-FCoE', 'Inititator.'],
                [
                    'iscsi.service', 'loaded', 'inactive', 'dead', 'Login', 'and', 'scanning', 'of',
                    'iSCSI', 'devices'
                ],
                ['iscsid.service', 'loaded', 'inactive', 'dead', 'Open-iSCSI'],
                [
                    'iscsiuio.service', 'loaded', 'inactive', 'dead', 'iSCSI', 'UserSpace', 'I/O',
                    'driver'
                ],
                [
                    'kdump.service', 'loaded', 'active', 'exited', 'Crash', 'recovery', 'kernel',
                    'arming'
                ],
                [
                    'kmod-static-nodes.service', 'loaded', 'active', 'exited', 'Create', 'list',
                    'of', 'required', 'static', 'device', 'nodes', 'for', 'the', 'current', 'kernel'
                ],
                [
                    'libstoragemgmt.service', 'loaded', 'active', 'running', 'libstoragemgmt',
                    'plug-in', 'server', 'daemon'
                ],
                ['*', 'livesys.service', 'not-found', 'inactive', 'dead', 'livesys.service'],
                [
                    'lldpad.service', 'loaded', 'inactive', 'dead', 'Link', 'Layer', 'Discovery',
                    'Protocol', 'Agent', 'Daemon.'
                ],
                [
                    '*', 'lm_sensors.service', 'loaded', 'failed', 'failed', 'Initialize',
                    'hardware', 'monitoring', 'sensors'
                ],
                [
                    '*', 'lvm2-activation-early.service', 'not-found', 'inactive', 'dead',
                    'lvm2-activation-early.service'
                ],
                [
                    '*', 'lvm2-activation.service', 'not-found', 'inactive', 'dead',
                    'lvm2-activation.service'
                ],
                [
                    'lvm2-lvmetad.service', 'loaded', 'active', 'running', 'LVM2', 'metadata',
                    'daemon'
                ],
                ['lvm2-lvmpolld.service', 'loaded', 'inactive', 'dead', 'LVM2', 'poll', 'daemon'],
                [
                    'lvm2-monitor.service', 'loaded', 'active', 'exited', 'Monitoring', 'of',
                    'LVM2', 'mirrors,', 'snapshots', 'etc.', 'using', 'dmeventd', 'or', 'progress',
                    'polling'
                ],
                [
                    'network.service', 'loaded', 'active', 'exited', 'LSB:', 'Bring', 'up/down',
                    'networking'
                ],
                [
                    'NetworkManager-wait-online.service', 'loaded', 'active', 'exited', 'Network',
                    'Manager', 'Wait', 'Online'
                ],
                ['NetworkManager.service', 'loaded', 'active', 'running', 'Network', 'Manager'],
                [
                    'nfs-config.service', 'loaded', 'inactive', 'dead', 'Preprocess', 'NFS',
                    'configuration'
                ],
                [
                    'nfs-idmapd.service', 'loaded', 'inactive', 'dead', 'NFSv4', 'ID-name',
                    'mapping', 'service'
                ],
                ['nfs-mountd.service', 'loaded', 'inactive', 'dead', 'NFS', 'Mount', 'Daemon'],
                [
                    '*', 'nfs-secure-server.service', 'not-found', 'inactive', 'dead',
                    'nfs-secure-server.service'
                ],
                [
                    'nfs-server.service', 'loaded', 'inactive', 'dead', 'NFS', 'server', 'and',
                    'services'
                ],
                [
                    'nfs-utils.service', 'loaded', 'inactive', 'dead', 'NFS', 'server', 'and',
                    'client', 'services'
                ],
                ['ntpd.service', 'loaded', 'active', 'running', 'Network', 'Time', 'Service'],
                ['ntpdate.service', 'loaded', 'inactive', 'dead', 'Set', 'time', 'via', 'NTP'],
                ['puppet.service', 'loaded', 'active', 'running', 'Puppet', 'agent'],
                [
                    '*', 'puppetmaster.service', 'not-found', 'inactive', 'dead',
                    'puppetmaster.service'
                ],
                ['*', 'rbdmap.service', 'not-found', 'inactive', 'dead', 'rbdmap.service'],
                [
                    'rc-local.service', 'loaded', 'inactive', 'dead', '/etc/rc.d/rc.local',
                    'Compatibility'
                ],
                ['rescue.service', 'loaded', 'inactive', 'dead', 'Rescue', 'Shell'],
                ['*', 'ypbind.service', 'not-found', 'inactive', 'dead', 'ypbind.service'],
                ['*', 'yppasswdd.service', 'not-found', 'inactive', 'dead', 'yppasswdd.service'],
                ['*', 'ypserv.service', 'not-found', 'inactive', 'dead', 'ypserv.service'],
                ['*', 'ypxfrd.service', 'not-found', 'inactive', 'dead', 'ypxfrd.service'],
                ['-.slice', 'loaded', 'active', 'active', 'Root', 'Slice'],
                ['slices.target', 'loaded', 'active', 'active', 'Slices'],
                ['sockets.target', 'loaded', 'active', 'active', 'Sockets'],
                ['swap.target', 'loaded', 'active', 'active', 'Swap'],
                ['sysinit.target', 'loaded', 'active', 'active', 'System', 'Initialization'],
                ['*', 'syslog.target', 'not-found', 'inactive', 'dead', 'syslog.target'],
            ],
            {
                'device': {
                    'dev-disk-by\\x2duuid-7941a423\\x2de7d7\\x2d4bbd\\x2d9526\\x2dfdb7ba7982a6':
                        UnitEntry(
                            name=
                            'dev-disk-by\\x2duuid-7941a423\\x2de7d7\\x2d4bbd\\x2d9526\\x2dfdb7ba7982a6',
                            type='device',
                            load='loaded',
                            active='active',
                            sub='plugged',
                            description='/dev/disk/by-uuid/7941a423-e7d7-4bbd-9526-fdb7ba7982a6',
                            state='unknown',
                        ),
                    'dev-sr0': UnitEntry(
                        name='dev-sr0',
                        type='device',
                        load='loaded',
                        active='active',
                        sub='plugged',
                        description='VMware_Virtual_SATA_CDRW_Drive',
                        state='unknown',
                    ),
                    'dev-vg_data-lv_data': UnitEntry(
                        name='dev-vg_data-lv_data',
                        type='device',
                        load='loaded',
                        active='active',
                        sub='plugged',
                        description='/dev/vg_data/lv_data',
                        state='unknown',
                    ),
                },
                'mount': {
                    'hana-data': UnitEntry(
                        name='hana-data',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/hana/data',
                        state='unknown',
                    ),
                    'hana-log': UnitEntry(
                        name='hana-log',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/hana/log',
                        state='unknown',
                    ),
                    'hana-shared': UnitEntry(
                        name='hana-shared',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/hana/shared',
                        state='unknown',
                    ),
                    'proc-fs-nfsd': UnitEntry(
                        name='proc-fs-nfsd',
                        type='mount',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='NFSD configuration filesystem',
                        state='static',
                    ),
                    'proc-sys-fs-binfmt_misc': UnitEntry(
                        name='proc-sys-fs-binfmt_misc',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='Arbitrary Executable File Formats File System',
                        state='static',
                    ),
                    'run-user-0': UnitEntry(
                        name='run-user-0',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/run/user/0',
                        state='unknown',
                    ),
                    'run-user-1101': UnitEntry(
                        name='run-user-1101',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/run/user/1101',
                        state='unknown',
                    ),
                    'run-user-1104': UnitEntry(
                        name='run-user-1104',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/run/user/1104',
                        state='unknown',
                    ),
                    'sapTEMP': UnitEntry(
                        name='sapTEMP',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/sapTEMP',
                        state='unknown',
                    ),
                    'sapWORK': UnitEntry(
                        name='sapWORK',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/sapWORK',
                        state='unknown',
                    ),
                    'sys-fs-fuse-connections': UnitEntry(
                        name='sys-fs-fuse-connections',
                        type='mount',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='FUSE Control File System',
                        state='static',
                    ),
                    'sys-kernel-config': UnitEntry(
                        name='sys-kernel-config',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='Configuration File System',
                        state='static',
                    ),
                    'sys-kernel-debug': UnitEntry(
                        name='sys-kernel-debug',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='Debug File System',
                        state='static',
                    ),
                    'tmp': UnitEntry(
                        name='tmp',
                        type='mount',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Temporary Directory',
                        state='disabled',
                    ),
                    'usr': UnitEntry(
                        name='usr',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/usr',
                        state='unknown',
                    ),
                    'usr-sap': UnitEntry(
                        name='usr-sap',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='/usr/sap',
                        state='unknown',
                    ),
                    'var-lib-nfs-rpc_pipefs': UnitEntry(
                        name='var-lib-nfs-rpc_pipefs',
                        type='mount',
                        load='loaded',
                        active='active',
                        sub='mounted',
                        description='RPC Pipe File System',
                        state='static',
                    ),
                },
                'path': {
                    'brandbot': UnitEntry(
                        name='brandbot',
                        type='path',
                        load='loaded',
                        active='active',
                        sub='waiting',
                        description='Flexible branding',
                        state='enabled',
                    ),
                    'systemd-ask-password-console': UnitEntry(
                        name='systemd-ask-password-console',
                        type='path',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Dispatch Password Requests to Console Directory Watch',
                        state='static',
                    ),
                    'systemd-ask-password-plymouth': UnitEntry(
                        name='systemd-ask-password-plymouth',
                        type='path',
                        load='loaded',
                        active='active',
                        sub='waiting',
                        description='Forward Password Requests to Plymouth Directory Watch',
                        state='static',
                    ),
                    'systemd-ask-password-wall': UnitEntry(
                        name='systemd-ask-password-wall',
                        type='path',
                        load='loaded',
                        active='active',
                        sub='waiting',
                        description='Forward Password Requests to Wall Directory Watch',
                        state='static',
                    ),
                },
                'service': {
                    'NetworkManager': UnitEntry(
                        name='NetworkManager',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Network Manager',
                        state='enabled',
                    ),
                    'NetworkManager-wait-online': UnitEntry(
                        name='NetworkManager-wait-online',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='exited',
                        description='Network Manager Wait Online',
                        state='enabled',
                    ),
                    'abrtd': UnitEntry(
                        name='abrtd',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='ABRT Automated Bug Reporting Tool',
                        state='enabled',
                    ),
                    'atd': UnitEntry(
                        name='atd',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Job spooling tools',
                        state='enabled',
                    ),
                    'atop': UnitEntry(
                        name='atop',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Atop advanced performance monitor',
                        state='enabled',
                    ),
                    'blk-availability': UnitEntry(
                        name='blk-availability',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='exited',
                        description='Availability of block devices',
                        state='disabled',
                    ),
                    'brandbot': UnitEntry(
                        name='brandbot',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Flexible Branding Service',
                        state='static',
                    ),
                    'check-mk-agent@40273-10.223.16.185:6556-10.20.114.58:57796': UnitEntry(
                        name='check-mk-agent@40273-10.223.16.185:6556-10.20.114.58:57796',
                        type='service',
                        load='loaded',
                        active='activating',
                        sub='start',
                        description='start CheckMK (10.20.114.58:57796)',
                        state='static',
                    ),
                    'corosync': UnitEntry(
                        name='corosync',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Corosync Cluster Engine',
                        state='disabled',
                    ),
                    'corosync-qdevice': UnitEntry(
                        name='corosync-qdevice',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Corosync Qdevice daemon',
                        state='disabled',
                    ),
                    'cpupower': UnitEntry(
                        name='cpupower',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Configure CPU power related settings',
                        state='disabled',
                    ),
                    'crond': UnitEntry(
                        name='crond',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Command Scheduler',
                        state='enabled',
                    ),
                    'dbus': UnitEntry(
                        name='dbus',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='D-Bus System Message Bus',
                        state='static',
                    ),
                    'display-manager': UnitEntry(
                        name='display-manager',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='display-manager.service',
                        state='unknown',
                    ),
                    'dm-event': UnitEntry(
                        name='dm-event',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Device-mapper event daemon',
                        state='static',
                    ),
                    'dmraid-activation': UnitEntry(
                        name='dmraid-activation',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Activation of DM RAID sets',
                        state='enabled',
                    ),
                    'dracut-shutdown': UnitEntry(
                        name='dracut-shutdown',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Restore /run/initramfs',
                        state='static',
                    ),
                    'dsmcad_SCHED_PHT_BACKUP_DC2': UnitEntry(
                        name='dsmcad_SCHED_PHT_BACKUP_DC2',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='"IBM Spectrum Protect Client dsmcad systemd-style service."',
                        state='enabled',
                    ),
                    'emergency': UnitEntry(
                        name='emergency',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Emergency Shell',
                        state='static',
                    ),
                    'fcoe': UnitEntry(
                        name='fcoe',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Open-FCoE Inititator.',
                        state='disabled',
                    ),
                    'iscsi': UnitEntry(
                        name='iscsi',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Login and scanning of iSCSI devices',
                        state='enabled',
                    ),
                    'iscsid': UnitEntry(
                        name='iscsid',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Open-iSCSI',
                        state='disabled',
                    ),
                    'iscsiuio': UnitEntry(
                        name='iscsiuio',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='iSCSI UserSpace I/O driver',
                        state='disabled',
                    ),
                    'kdump': UnitEntry(
                        name='kdump',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='exited',
                        description='Crash recovery kernel arming',
                        state='enabled',
                    ),
                    'kmod-static-nodes': UnitEntry(
                        name='kmod-static-nodes',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='exited',
                        description=
                        'Create list of required static device nodes for the current kernel',
                        state='static',
                    ),
                    'libstoragemgmt': UnitEntry(
                        name='libstoragemgmt',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='libstoragemgmt plug-in server daemon',
                        state='enabled',
                    ),
                    'livesys': UnitEntry(
                        name='livesys',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='livesys.service',
                        state='unknown',
                    ),
                    'lldpad': UnitEntry(
                        name='lldpad',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Link Layer Discovery Protocol Agent Daemon.',
                        state='disabled',
                    ),
                    'lm_sensors': UnitEntry(
                        name='lm_sensors',
                        type='service',
                        load='loaded',
                        active='failed',
                        sub='failed',
                        description='Initialize hardware monitoring sensors',
                        state='enabled',
                    ),
                    'lvm2-activation': UnitEntry(
                        name='lvm2-activation',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='lvm2-activation.service',
                        state='unknown',
                    ),
                    'lvm2-activation-early': UnitEntry(
                        name='lvm2-activation-early',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='lvm2-activation-early.service',
                        state='unknown',
                    ),
                    'lvm2-lvmetad': UnitEntry(
                        name='lvm2-lvmetad',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='LVM2 metadata daemon',
                        state='static',
                    ),
                    'lvm2-lvmpolld': UnitEntry(
                        name='lvm2-lvmpolld',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='LVM2 poll daemon',
                        state='static',
                    ),
                    'lvm2-monitor': UnitEntry(
                        name='lvm2-monitor',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='exited',
                        description=
                        'Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling',
                        state='enabled',
                    ),
                    'network': UnitEntry(
                        name='network',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='exited',
                        description='LSB: Bring up/down networking',
                        state='unknown',
                    ),
                    'nfs-config': UnitEntry(
                        name='nfs-config',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Preprocess NFS configuration',
                        state='static',
                    ),
                    'nfs-idmapd': UnitEntry(
                        name='nfs-idmapd',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='NFSv4 ID-name mapping service',
                        state='static',
                    ),
                    'nfs-mountd': UnitEntry(
                        name='nfs-mountd',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='NFS Mount Daemon',
                        state='static',
                    ),
                    'nfs-secure-server': UnitEntry(
                        name='nfs-secure-server',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='nfs-secure-server.service',
                        state='unknown',
                    ),
                    'nfs-server': UnitEntry(
                        name='nfs-server',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='NFS server and services',
                        state='disabled',
                    ),
                    'nfs-utils': UnitEntry(
                        name='nfs-utils',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='NFS server and client services',
                        state='static',
                    ),
                    'ntpd': UnitEntry(
                        name='ntpd',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Network Time Service',
                        state='enabled',
                    ),
                    'ntpdate': UnitEntry(
                        name='ntpdate',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Set time via NTP',
                        state='disabled',
                    ),
                    'puppet': UnitEntry(
                        name='puppet',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Puppet agent',
                        state='enabled',
                    ),
                    'puppetmaster': UnitEntry(
                        name='puppetmaster',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='puppetmaster.service',
                        state='unknown',
                    ),
                    'rbdmap': UnitEntry(
                        name='rbdmap',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='rbdmap.service',
                        state='unknown',
                    ),
                    'rc-local': UnitEntry(
                        name='rc-local',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='/etc/rc.d/rc.local Compatibility',
                        state='static',
                    ),
                    'rescue': UnitEntry(
                        name='rescue',
                        type='service',
                        load='loaded',
                        active='inactive',
                        sub='dead',
                        description='Rescue Shell',
                        state='static',
                    ),
                    'ypbind': UnitEntry(
                        name='ypbind',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='ypbind.service',
                        state='unknown',
                    ),
                    'yppasswdd': UnitEntry(
                        name='yppasswdd',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='yppasswdd.service',
                        state='unknown',
                    ),
                    'ypserv': UnitEntry(
                        name='ypserv',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='ypserv.service',
                        state='unknown',
                    ),
                    'ypxfrd': UnitEntry(
                        name='ypxfrd',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='ypxfrd.service',
                        state='unknown',
                    ),
                },
                'slice': {
                    '-': UnitEntry(
                        name='-',
                        type='slice',
                        load='loaded',
                        active='active',
                        sub='active',
                        description='Root Slice',
                        state='static',
                    ),
                },
                'target': {
                    'slices': UnitEntry(
                        name='slices',
                        type='target',
                        load='loaded',
                        active='active',
                        sub='active',
                        description='Slices',
                        state='static',
                    ),
                    'sockets': UnitEntry(
                        name='sockets',
                        type='target',
                        load='loaded',
                        active='active',
                        sub='active',
                        description='Sockets',
                        state='static',
                    ),
                    'swap': UnitEntry(
                        name='swap',
                        type='target',
                        load='loaded',
                        active='active',
                        sub='active',
                        description='Swap',
                        state='static',
                    ),
                    'sysinit': UnitEntry(
                        name='sysinit',
                        type='target',
                        load='loaded',
                        active='active',
                        sub='active',
                        description='System Initialization',
                        state='static',
                    ),
                    'syslog': UnitEntry(
                        name='syslog',
                        type='target',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='syslog.target',
                        state='unknown',
                    ),
                },
            },
            id="* for broken units",
        ),
        pytest.param(
            [
                ['[list-unit-files]'],
                ['UNIT', 'FILE', 'STATE', 'VENDOR', 'PRESET'],
                ['proc-sys-fs-binfmt_misc.automount', 'static', 'enabled'],
                ['-.mount', 'generated', 'enabled'],
                ['boot-efi.mount', 'generated', 'enabled'],
                ['clean-mount-point@.service', 'static', 'enabled'],
                ['ippusbxd@.service', 'static', 'enabled'],
                ['irqbalance.service', 'enabled', 'enabled'],
                ['kerneloops.service', 'enabled', 'enabled'],
                ['snapd.service', 'enabled', 'enabled'],
                ['snapd.snap-repair.service', 'static', 'enabled'],
                ['snapd.system-shutdown.service', 'enabled', 'enabled'],
                ['speech-dispatcher.service', 'disabled', 'enabled'],
                ['408', 'unit', 'files', 'listed.'],
                ['[all]'],
                ['UNIT', 'LOAD', 'ACTIVE', 'SUB', 'JOB', 'DESCRIPTION'],
                [
                    'proc-sys-fs-binfmt_misc.automount', 'loaded', 'active', 'running', 'Arbitrary',
                    'Executable', 'File', 'Formats', 'File', 'System', 'Automount', 'Point'
                ],
                ['●', 'iscsi.service', 'not-found', 'inactive', 'dead', 'iscsi.service'],
                ['●', 'iscsid.service', 'not-found', 'inactive', 'dead', 'iscsid.service'],
                ['●', 'kbd.service', 'not-found', 'inactive', 'dead', 'kbd.service'],
                [
                    'kerneloops.service', 'loaded', 'active', 'running', 'Tool', 'to',
                    'automatically', 'collect', 'and', 'submit', 'kernel', 'crash', 'signatures'
                ],
            ],
            {
                'automount': {
                    'proc-sys-fs-binfmt_misc': UnitEntry(
                        name='proc-sys-fs-binfmt_misc',
                        type='automount',
                        load='loaded',
                        active='active',
                        sub='running',
                        description='Arbitrary Executable File Formats File System Automount Point',
                        state='static',
                    ),
                },
                'service': {
                    'iscsi': UnitEntry(
                        name='iscsi',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='iscsi.service',
                        state='unknown',
                    ),
                    'iscsid': UnitEntry(
                        name='iscsid',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='iscsid.service',
                        state='unknown',
                    ),
                    'kbd': UnitEntry(
                        name='kbd',
                        type='service',
                        load='not-found',
                        active='inactive',
                        sub='dead',
                        description='kbd.service',
                        state='unknown',
                    ),
                    'kerneloops': UnitEntry(
                        name='kerneloops',
                        type='service',
                        load='loaded',
                        active='active',
                        sub='running',
                        description=
                        'Tool to automatically collect and submit kernel crash signatures',
                        state='enabled',
                    ),
                },
            },
            id="C.UTF-8 locale (● instead of * for broken units)",
        ),
    ],
)
def test_parse_systemd_units(
    string_table: Iterable[List[str]],
    expected_result: Mapping[str, UnitEntry],
) -> None:
    assert Check("systemd_units").run_parse(string_table) == expected_result


@pytest.mark.parametrize('services, blacklist, expected', [
    ([
        UnitEntry(name=u'gpu-manager',
                  type='service',
                  load=u'loaded',
                  active=u'inactive',
                  sub=u'dead',
                  description=u'Detect the available GPUs and deal with any system changes',
                  state=u'unknown'),
        UnitEntry(name=u'rsyslog',
                  type='service',
                  load=u'loaded',
                  active=u'active',
                  sub=u'running',
                  description=u'System Logging Service',
                  state=u'enabled'),
        UnitEntry(name=u'alsa-state',
                  type='service',
                  load=u'loaded',
                  active=u'inactive',
                  sub=u'dead',
                  description=u'Manage Sound Card State (restore and store)',
                  state=u'disabled'),
    ], [], {
        "included": [
            UnitEntry(name=u'gpu-manager',
                      type='service',
                      load=u'loaded',
                      active=u'inactive',
                      sub=u'dead',
                      description=u'Detect the available GPUs and deal with any system changes',
                      state=u'unknown'),
            UnitEntry(name=u'rsyslog',
                      type='service',
                      load=u'loaded',
                      active=u'active',
                      sub=u'running',
                      description=u'System Logging Service',
                      state=u'enabled')
        ],
        "excluded": [],
        "disabled": [
            UnitEntry(name=u'alsa-state',
                      type='service',
                      load=u'loaded',
                      active=u'inactive',
                      sub=u'dead',
                      description=u'Manage Sound Card State (restore and store)',
                      state=u'disabled')
        ],
        "static": [],
        "activating": [],
        "reloading": [],
    }),
    (
        [
            UnitEntry(name=u'gpu-manager',
                      type='service',
                      load=u'loaded',
                      active=u'inactive',
                      sub=u'dead',
                      description=u'Detect the available GPUs and deal with any system changes',
                      state=u'unknown'),
            UnitEntry(name=u'rsyslog',
                      type='service',
                      load=u'loaded',
                      active=u'active',
                      sub=u'running',
                      description=u'System Logging Service',
                      state=u'enabled'),
            UnitEntry(name=u'alsa-state',
                      type='service',
                      load=u'loaded',
                      active=u'inactive',
                      sub=u'dead',
                      description=u'Manage Sound Card State (restore and store)',
                      state=u'indirect')
        ],
        [u'gpu'],
        {
            "included": [
                UnitEntry(name=u'rsyslog',
                          type='service',
                          load=u'loaded',
                          active=u'active',
                          sub=u'running',
                          description=u'System Logging Service',
                          state=u'enabled'),
            ],
            "excluded": [
                UnitEntry(name=u'gpu-manager',
                          type='service',
                          load=u'loaded',
                          active=u'inactive',
                          sub=u'dead',
                          description=u'Detect the available GPUs and deal with any system changes',
                          state=u'unknown'),
            ],
            "disabled": [
                UnitEntry(name=u'alsa-state',
                          type='service',
                          load=u'loaded',
                          active=u'inactive',
                          sub=u'dead',
                          description=u'Manage Sound Card State (restore and store)',
                          state=u'indirect')
            ],
            "static": [],
            "activating": [],
            "reloading": [],
        },
    ),
])
def test_services_split(services, blacklist, expected):
    check = Check('systemd_units')
    services_split = check.context['_services_split']
    actual = services_split(services, blacklist)
    assert actual == expected
