# Copyright (C) 2023 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

[package]
name = "check_http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { version = "*", features = ["aes", "std"] }
bytes = { version = "*" }
anyhow = { version = "*" }
clap = { version = "*", features = ["derive"] }
http = { version = "*" }
reqwest = { version = "*", features = ["json"] }
scrypt = { version = "*", default-features = false, features = ["std"] }
tokio = { version = "*", features = ["full"] }
openssl = { version = "*", features = ["vendored"] }
httpdate = { version = "*" }
mime = { version = "*" }
encoding_rs = { version = "*" }
regex = { version = "*" }
