#!/bin/sh
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

INSTANCES=$(ps -ef | grep db2sysc | awk '{print $1}' | sort -u | grep -v root)

if [ "$INSTANCES" ] ; then
    echo "<<<db2_mem>>>"
    for INSTANCE in $INSTANCES; do
        echo "Instance $INSTANCE"
        su - $INSTANCE -c "db2pd -dbptnmem " | egrep '(Memory Limit|HWM usage)'
    done
fi
