#!/bin/bash
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# Developed by Thorsten Bruhns from OPITZ CONSULTING Deutschland GmbH

set -f

ocrcfgfile=/etc/oracle/ocr.loc
olrcfgfile=/etc/oracle/olr.loc
resourcefilter="^NAME=|^TYPE=|^STATE=|^TARGET=|^ENABLED="

#   .--Functions-----------------------------------------------------------.
#   |             _____                 _   _                              |
#   |            |  ___|   _ _ __   ___| |_(_) ___  _ __  ___              |
#   |            | |_ | | | | '_ \ / __| __| |/ _ \| '_ \/ __|             |
#   |            |  _|| |_| | | | | (__| |_| | (_) | | | \__ \             |
#   |            |_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/             |
#   |                                                                      |
#   +----------------------------------------------------------------------+
#   |                                                                      |
#   '----------------------------------------------------------------------'

function set_has_env(){
    test -f ${ocrcfgfile} || exit 0
    local_has_type=$(cat $ocrcfgfile | grep "^local_only=" | cut -d"=" -f2 | tr '[:lower:]' '[:upper:]')
    local_has_type=${local_has_type:-"FALSE"}

    if [ -f ${olrcfgfile} ] ; then
        has_ORACLE_HOME=$(cat $olrcfgfile | grep "^crs_home=" | cut -d"=" -f2)
    else
        # There is no olr.cfg in 10.2 and 11.1
        # we try to get the ORA_CRS_HOME from /etc/init.d/init.cssd
        local_has_type=FALSE
        INITCSSD=/etc/init.d/init.cssd
        if [ ! -f ${INITCSSD} ] ; then
            exit 0
        else
            has_ORACLE_HOME=$(grep "^ORA_CRS_HOME=" ${INITCSSD} | cut -d"=" -f2-)
        fi
    fi

    CRSCTL=${has_ORACLE_HOME}/bin/crsctl
    OLSNODES=${has_ORACLE_HOME}/bin/olsnodes
    CRS_STAT=${has_ORACLE_HOME}/bin/crs_stat
}

function printhasdata() {
    ps -e | grep cssd.bin > /dev/null || exit 0

    echo "<<<oracle_crs_version:sep(124)>>>"
    $CRSCTL query has releaseversion

    echo "<<<oracle_crs_res>>>"
    $CRSCTL stat res -f | grep -E $resourcefilter
}

function printcrsdata() {
    ps -e | grep -e ohasd.bin -e crsd.bin > /dev/null || exit 0

    echo "<<<oracle_crs_version:sep(124)>>>"
    crs_version=$($CRSCTL query crs releaseversion)
    echo $crs_version

    echo "<<<oracle_crs_voting>>>"
    $CRSCTL query css votedisk | grep "^ [0-9]"

    ps -e | grep crsd.bin > /dev/null || exit 0
    echo "<<<oracle_crs_res:sep(124)>>>"
    OLS_NODENAME=$($OLSNODES -l)

    echo "nodename|"$OLS_NODENAME

    crs_version_short=$(echo $crs_version | cut -d"[" -f2- | cut -d"." -f-2 | sed 's/\.//')
    if [ $(($crs_version_short)) -ge 112 ] ; then
        $CRSCTL stat res -v -n $OLS_NODENAME -init | grep -E $resourcefilter | sed "s/^/csslocal\|/"
        for nodelist in $($OLSNODES)
        do
            $CRSCTL stat res -v -n $nodelist | grep -E $resourcefilter | sed "s/^/$nodelist\|/"
        done
    else
        $CRS_STAT -f -c $OLS_NODENAME | grep -E $resourcefilter | sed "s/^/$OLS_NODENAME\|/"
    fi
}

#.
#   .--Main----------------------------------------------------------------.
#   |                        __  __       _                                |
#   |                       |  \/  | __ _(_)_ __                           |
#   |                       | |\/| |/ _` | | '_ \                          |
#   |                       | |  | | (_| | | | | |                         |
#   |                       |_|  |_|\__,_|_|_| |_|                         |
#   |                                                                      |
#   +----------------------------------------------------------------------+
#   |                                                                      |
#   '----------------------------------------------------------------------'

set_has_env
echo "<<<oracle_crs_res>>>"
echo "<<<oracle_crs_version>>>"
echo "<<<oracle_crs_votedisk>>>"
if [ $local_has_type = 'FALSE' ] ; then
    printcrsdata
else
    printhasdata
fi

