HEIRLOOM_PKGTOOLS := heirloom-pkgtools
HEIRLOOM_PKGTOOLS_VERS := 070227
HEIRLOOM_PKGTOOLS_DIR := $(HEIRLOOM_PKGTOOLS)-$(HEIRLOOM_PKGTOOLS_VERS)
# Increase this to enforce a recreation of the build cache
HEIRLOOM_PKGTOOLS_BUILD_ID := 0

HEIRLOOM_PKGTOOLS_PATCHING := $(BUILD_HELPER_DIR)/$(HEIRLOOM_PKGTOOLS_DIR)-patching
HEIRLOOM_PKGTOOLS_BUILD := $(BUILD_HELPER_DIR)/$(HEIRLOOM_PKGTOOLS_DIR)-build
HEIRLOOM_PKGTOOLS_INTERMEDIATE_INSTALL := $(BUILD_HELPER_DIR)/$(HEIRLOOM_PKGTOOLS_DIR)-install-intermediate
HEIRLOOM_PKGTOOLS_CACHE_PKG_PROCESS := $(BUILD_HELPER_DIR)/$(HEIRLOOM_PKGTOOLS_DIR)-cache-pkg-process
HEIRLOOM_PKGTOOLS_INSTALL := $(BUILD_HELPER_DIR)/$(HEIRLOOM_PKGTOOLS_DIR)-install

HEIRLOOM_PKGTOOLS_INSTALL_DIR := $(INTERMEDIATE_INSTALL_BASE)/$(HEIRLOOM_PKGTOOLS_DIR)
HEIRLOOM_PKGTOOLS_BUILD_DIR := $(PACKAGE_BUILD_DIR)/$(HEIRLOOM_PKGTOOLS_DIR)
#HEIRLOOM_PKGTOOLS_WORK_DIR := $(PACKAGE_WORK_DIR)/$(HEIRLOOM_PKGTOOLS_DIR)

$(HEIRLOOM_PKGTOOLS_BUILD): $(HEIRLOOM_PKGTOOLS_PATCHING)
	cd $(HEIRLOOM_PKGTOOLS_BUILD_DIR) ; \
	    find -name Makefile -delete ; \
	    $(MAKE)
	$(TOUCH) $@

HEIRLOOM_PKGTOOLS_CACHE_PKG_PATH := $(call cache_pkg_path,$(HEIRLOOM_PKGTOOLS_DIR),$(HEIRLOOM_PKGTOOLS_BUILD_ID))

$(HEIRLOOM_PKGTOOLS_CACHE_PKG_PATH):
	$(call pack_pkg_archive,$@,$(HEIRLOOM_PKGTOOLS_DIR),$(HEIRLOOM_PKGTOOLS_BUILD_ID),$(HEIRLOOM_PKGTOOLS_INTERMEDIATE_INSTALL))

$(HEIRLOOM_PKGTOOLS_CACHE_PKG_PROCESS): $(HEIRLOOM_PKGTOOLS_CACHE_PKG_PATH)
	$(call unpack_pkg_archive,$(HEIRLOOM_PKGTOOLS_CACHE_PKG_PATH),$(HEIRLOOM_PKGTOOLS_DIR))
	$(call upload_pkg_archive,$(HEIRLOOM_PKGTOOLS_CACHE_PKG_PATH),$(HEIRLOOM_PKGTOOLS_DIR),$(HEIRLOOM_PKGTOOLS_BUILD_ID))
	$(TOUCH) $@

$(HEIRLOOM_PKGTOOLS_INTERMEDIATE_INSTALL): $(HEIRLOOM_PKGTOOLS_BUILD)

$(HEIRLOOM_PKGTOOLS_INTERMEDIATE_INSTALL): $(HEIRLOOM_PKGTOOLS_BUILD)
	$(MKDIR) $(HEIRLOOM_PKGTOOLS_INSTALL_DIR)/bin
	$(MKDIR) $(HEIRLOOM_PKGTOOLS_INSTALL_DIR)/share/man/man1
	for F in pkgmk pkgtrans; do \
	    install -m 755 $(HEIRLOOM_PKGTOOLS_BUILD_DIR)/pkgcmds/$$F/$$F $(HEIRLOOM_PKGTOOLS_INSTALL_DIR)/bin/ ; \
	    install -m 644 $(HEIRLOOM_PKGTOOLS_BUILD_DIR)/man/$$F.1 $(HEIRLOOM_PKGTOOLS_INSTALL_DIR)/share/man/man1/; \
	    gzip -f $(HEIRLOOM_PKGTOOLS_INSTALL_DIR)/share/man/man1/$$F.1 ; \
	done
	$(TOUCH) $@

$(HEIRLOOM_PKGTOOLS_INSTALL): $(HEIRLOOM_PKGTOOLS_CACHE_PKG_PROCESS)
	$(RSYNC) $(HEIRLOOM_PKGTOOLS_INSTALL_DIR)/ $(DESTDIR)$(OMD_ROOT)/
	$(TOUCH) $@
