HEIRLOOM_PKGTOOLS := heirloom-pkgtools

HEIRLOOM_PKGTOOLS_BUILD := $(BUILD_HELPER_DIR)/$(HEIRLOOM_PKGTOOLS)-build
HEIRLOOM_PKGTOOLS_INSTALL := $(BUILD_HELPER_DIR)/$(HEIRLOOM_PKGTOOLS)-install

HEIRLOOM_PKGTOOLS_BUILD_DIR := $(BAZEL_BIN_EXT)/$(HEIRLOOM_PKGTOOLS)/$(HEIRLOOM_PKGTOOLS)

.PHONY: $(HEIRLOOM_PKGTOOLS_BUILD)
$(HEIRLOOM_PKGTOOLS_BUILD):
	$(BAZEL_CMD) build @$(HEIRLOOM_PKGTOOLS)//:$(HEIRLOOM_PKGTOOLS)

.PHONY: $(HEIRLOOM_PKGTOOLS_INSTALL)
$(HEIRLOOM_PKGTOOLS_INSTALL): $(HEIRLOOM_PKGTOOLS_BUILD)
	for F in pkgmk pkgtrans; do \
	    install -m 755 $(HEIRLOOM_PKGTOOLS_BUILD_DIR)/bin/$$F $(DESTDIR)$(OMD_ROOT)/bin/ ; \
	    install -m 644 $(HEIRLOOM_PKGTOOLS_BUILD_DIR)/share/man/man1/$$F.1.gz $(DESTDIR)$(OMD_ROOT)/share/man/man1/; \
	done
