#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# YAPF is disabled in the next section to get simpler overview of the keys
# present in the dictionary as they are packed together much more
# densely. You are responsible of manually formatting this dictionary, or
# at your choice adding temporarily in the style file the option:
# each_dict_entry_on_separate_line=False

import cmk.gui.utils
from cmk.gui.i18n import _l
from cmk.gui.plugins.views.utils import inventory_displayhints
from cmk.gui.plugins.visuals.inventory import (
    FilterInvtableAdminStatus,
    FilterInvtableAvailable,
    FilterInvtableIDRange,
    FilterInvtableInterfaceType,
    FilterInvtableOperStatus,
    FilterInvtableTimestampAsAge,
    FilterInvtableVersion,
)

# yapf: disable

inventory_displayhints.update({
    ".": {"title": _l("Inventory")},
    ".hardware.": {"title": _l("Hardware"), "icon": "hardware"},
    ".hardware.chassis.": {"title": _l("Chassis")},
    ".hardware.cpu.": {
        "title": _l("Processor"),
        "keyorder": [
            "arch",
            "max_speed",
            "model",
            "type",
            "threads",
            "smt_threads",
            "sharing_mode",
            "implementation_mode",
            "entitlement",
            "cpu_max_capa",
            "logical_cpus",
        ],
    },
    ".hardware.cpu.arch": {"title": _l("CPU Architecture"), "short": _l("CPU Arch")},
    ".hardware.cpu.max_speed": {"title": _l("Maximum Speed"), "paint": "hz"},
    ".hardware.cpu.model": {"title": _l("Model"), "short": _l("CPU Model")},
    ".hardware.cpu.threads": {"title": _l("Total Number of Hyperthreads"), "paint": "count"},
    ".hardware.cpu.smt_threads": {"title": _l("SMT Threads"), "paint": "count"},
    ".hardware.cpu.sharing_mode": {"title": _l("Shared Processor Mode")},
    ".hardware.cpu.implementation_mode": {"title": _l("Processor Implementation Mode")},
    ".hardware.cpu.entitlement": {"title": _l("Processor Entitled Capacity")},
    ".hardware.cpu.cpu_max_capa": {"title": _l("Processor Max. Capacity")},
    ".hardware.cpu.cache_size": {"title": _l("Cache Size"), "paint": "bytes"},
    ".hardware.cpu.bus_speed": {"title": _l("Bus Speed"), "paint": "hz"},
    ".hardware.cpu.voltage": {"title": _l("Voltage"), "paint": "volt"},
    ".hardware.cpu.cores_per_cpu": {"title": _l("Cores per CPU"), "paint": "count"},
    ".hardware.cpu.threads_per_cpu": {"title": _l("Hyperthreads per CPU"), "paint": "count"},
    ".hardware.cpu.cpus": {
        "title": _l("Number of physical CPUs"), "short": _l("CPUs"), "paint": "count"
    },
    ".hardware.cpu.logical_cpus": {
        "title": _l("Number of logical CPUs"), "short": _l("Logical CPUs"), "paint": "count"
    },
    ".hardware.cpu.cores": {
        "title": _l("Total Number of Cores"), "short": _l("Cores"), "paint": "count"
    },
    ".hardware.memory.": {"title": _l("Memory (RAM)")},
    ".hardware.memory.total_ram_usable": {"title": _l("Total usable RAM"), "paint": "bytes_rounded"},
    ".hardware.memory.total_swap": {"title": _l("Total swap space"), "paint": "bytes_rounded"},
    ".hardware.memory.total_vmalloc": {
        "title": _l("Virtual addresses for mapping"), "paint": "bytes_rounded"
    },
    # FIXME Cleanup: This path has no table.
    ".hardware.memory.arrays:": {"title": _l("Arrays (Controllers)")},
    ".hardware.memory.arrays:*.": {"title": _l("Controller %d")},
    ".hardware.memory.arrays:*.devices:": {
        "title": _l("Devices"),
        "keyorder": [
            "locator",
            "bank_locator",
            "type",
            "form_factor",
            "speed",
            "data_width",
            "total_width",
            "manufacturer",
            "serial",
        ],
    },
    ".hardware.memory.arrays:*.maximum_capacity": {
        "title": _l("Maximum Capacity"), "paint": "bytes"
    },
    ".hardware.memory.arrays:*.devices:*.": {"title": lambda v: v["locator"]},
    ".hardware.memory.arrays:*.devices:*.size": {"title": _l("Size"), "paint": "bytes"},
    ".hardware.memory.arrays:*.devices:*.speed": {"title": _l("Speed"), "paint": "hz"},
    ".hardware.system.": {
        "title": _l("System"),
        "keyorder": [
            "manufacturer",
            "product",
            "serial",
            "node_name",
            "partition_name",
        ],
    },
    ".hardware.system.product": {"title": _l("Product"), "is_show_more": False},
    ".hardware.system.serial": {"title": _l("Serial Number")},
    ".hardware.system.expresscode": {"title": _l("Express Servicecode")},
    ".hardware.system.model": {"title": _l("Model Name")},
    ".hardware.system.manufacturer": {"title": _l("Manufacturer")},

    # Legacy ones. Kept to not break existing views - DON'T use these values for new plugins
    ".software.applications.kubernetes.roles:": {
        "title": _l("Roles"),
        "keyorder": ["role", "namespace"],
    },
    ".software.applications.kubernetes.nodes:": {
        "title": _l("Nodes"),
        "keyorder": ["name"],
    },
    ".software.applications.kubernetes.pod_container:": {
        "title": _l("Containers"),
        "keyorder": [
            "name",
            "ready",
            "restart_count",
            "image",
            "image_pull_policy",
            "image_id",
            "container_id",
        ],
    },
    ".software.applications.kubernetes.job_container:": {
        "title": _l("Containers"),
        "keyorder": [
            "name",
            "image",
            "image_pull_policy",
        ],
    },
    ".software.applications.kubernetes.roles:*.role" : {"title": _l("Name")},
    ".software.applications.kubernetes.roles:*.namespace" : {"title": _l("Namespace")},
    ".software.applications.kubernetes.nodes:*.name" : {"title": _l("Name")},
    ".software.applications.kubernetes.ingresses:": {
        "title": _l("Ingress"),
        "keyorder": ["path", "service_name", "service_port"],
    },
    ".software.applications.kubernetes.pod_container:*.name": {"title": _l("Name")},
    ".software.applications.kubernetes.pod_container:*.image": {"title": _l("Image")},
    ".software.applications.kubernetes.pod_container:*.image_pull_policy": {"title": _l("Image pull policy")},
    ".software.applications.kubernetes.pod_container:*.image_id": {"title": _l("Image ID")},
    ".software.applications.kubernetes.pod_container:*.ready": {"title": _l("Ready"), "paint": "container_ready"},
    ".software.applications.kubernetes.pod_container:*.restart_count": {"title": _l("Restart count")},
    ".software.applications.kubernetes.pod_container:*.container_id": {"title": _l("Container ID")},
    ".software.applications.kubernetes.job_container:*.name": {"title": _l("Name")},
    ".software.applications.kubernetes.job_container:*.image": {"title": _l("Image")},
    ".software.applications.kubernetes.job_container:*.image_pull_policy": {"title": _l("Image pull policy")},
    ".software.applications.kubernetes.daemon_pod_containers:": {
        "title": _l("Daemon pod containers"),
        "keyorder": ["name", "image", "image_pull_policy"],
    },
    ".software.applications.kubernetes.daemon_pod_containers:*.name": {"title": _l("Name")},
    ".software.applications.kubernetes.daemon_pod_containers:*.image": {"title": _l("Image")},
    ".software.applications.kubernetes.daemon_pod_containers:*.image_pull_policy": {"title": _l("Image pull policy")},
    ".software.applications.kubernetes.pod_info.": {
        "title": _l("Pod"),
    },
    ".software.applications.kubernetes.pod_info.node": {"title": _l("Node")},
    ".software.applications.kubernetes.pod_info.host_network": {"title": _l("Host network")},
    ".software.applications.kubernetes.pod_info.dns_policy": {"title": _l("DNS policy")},
    ".software.applications.kubernetes.pod_info.host_ip": {"title": _l("Host IP")},
    ".software.applications.kubernetes.pod_info.pod_ip": {"title": _l("Pod IP")},
    ".software.applications.kubernetes.pod_info.qos_class": {"title": _l("QOS class")},
    ".software.applications.kubernetes.service_info.": {
        "title": _l("Service"),
    },
    ".software.applications.kubernetes.service_info.type": {"title": _l("Type")},
    ".software.applications.kubernetes.service_info.cluster_ip": {"title": _l("Cluster IP")},
    ".software.applications.kubernetes.service_info.load_balancer_ip": {"title": _l("Load Balancer IP")},
    ".software.applications.kubernetes.selector.": {
        "title": _l("Selectors"),
    },
    ".software.applications.kubernetes.assigned_pods:": {
        "title": _l("Pods"),
        "keyorder": ["id", "name"],
    },
    ".software.applications.kubernetes.assigned_pods:*.name": {"title": _l("Name")},
    ".hardware.system.serial_number": {"title": _l("Serial Number - LEGACY, don't use")},
    ".hardware.system.model_name": {"title": _l("Model Name - LEGACY, don't use")},
    ".hardware.components.": {"title": _l("Physical Components")},
    ".hardware.components.others:": {
        "title": _l("Other entities"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "manufacturer",
            "model",
            "location",
        ],
        "view": "invother_of_host",
    },
    ".hardware.components.others:*.index": {"title": _l("Index")},
    ".hardware.components.others:*.name": {"title": _l("Name")},
    ".hardware.components.others:*.description": {"title": _l("Description")},
    ".hardware.components.others:*.software": {"title": _l("Software")},
    ".hardware.components.others:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.others:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.others:*.model": {"title": _l("Model Name")},
    ".hardware.components.others:*.location": {"title": _l("Location")},
    ".hardware.components.unknowns:": {
        "title": _l("Unknown entities"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "manufacturer",
            "model",
            "location",
        ],
        "view": "invunknown_of_host",
    },
    ".hardware.components.unknowns:*.index": {"title": _l("Index")},
    ".hardware.components.unknowns:*.name": {"title": _l("Name")},
    ".hardware.components.unknowns:*.description": {"title": _l("Description")},
    ".hardware.components.unknowns:*.software": {"title": _l("Software")},
    ".hardware.components.unknowns:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.unknowns:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.unknowns:*.model": {"title": _l("Model Name")},
    ".hardware.components.unknowns:*.location": {"title": _l("Location")},
    ".hardware.components.chassis:": {
        "title": _l("Chassis"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "manufacturer",
            "model",
            "location",
        ],
        "view": "invchassis_of_host",
    },
    ".hardware.components.chassis:*.index": {"title": _l("Index")},
    ".hardware.components.chassis:*.name": {"title": _l("Name")},
    ".hardware.components.chassis:*.description": {"title": _l("Description")},
    ".hardware.components.chassis:*.software": {"title": _l("Software")},
    ".hardware.components.chassis:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.chassis:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.chassis:*.model": {"title": _l("Model Name")},
    ".hardware.components.chassis:*.location": {"title": _l("Location")},
    ".hardware.components.backplanes:": {
        "title": _l("Backplanes"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "manufacturer",
            "model",
            "location",
        ],
        "view": "invbackplane_of_host",
    },
    ".hardware.components.backplanes:*.index": {"title": _l("Index")},
    ".hardware.components.backplanes:*.name": {"title": _l("Name")},
    ".hardware.components.backplanes:*.description": {"title": _l("Description")},
    ".hardware.components.backplanes:*.software": {"title": _l("Software")},
    ".hardware.components.backplanes:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.backplanes:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.backplanes:*.model": {"title": _l("Model Name")},
    ".hardware.components.backplanes:*.location": {"title": _l("Location")},
    ".hardware.components.containers:": {
        "title": _l("Containers"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "manufacturer",
            "model",
            "location",
        ],
        "view": "invcontainer_of_host",
    },
    ".hardware.components.containers:*.index": {"title": _l("Index")},
    ".hardware.components.containers:*.name": {"title": _l("Name")},
    ".hardware.components.containers:*.description": {"title": _l("Description")},
    ".hardware.components.containers:*.software": {"title": _l("Software")},
    ".hardware.components.containers:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.containers:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.containers:*.model": {"title": _l("Model Name")},
    ".hardware.components.containers:*.location": {"title": _l("Location")},
    ".hardware.components.psus:": {
        "title": _l("Power Supplies"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "manufacturer",
            "model",
            "location",
        ],
        "view": "invpsu_of_host",
    },
    ".hardware.components.psus:*.index": {"title": _l("Index")},
    ".hardware.components.psus:*.name": {"title": _l("Name")},
    ".hardware.components.psus:*.description": {"title": _l("Description")},
    ".hardware.components.psus:*.software": {"title": _l("Software")},
    ".hardware.components.psus:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.psus:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.psus:*.model": {"title": _l("Model Name")},
    ".hardware.components.psus:*.location": {"title": _l("Location")},
    ".hardware.components.fans:": {
        "title": _l("Fans"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "manufacturer",
            "model",
            "location",
        ],
        "view": "invfan_of_host",
    },
    ".hardware.components.fans:*.index": {"title": _l("Index")},
    ".hardware.components.fans:*.name": {"title": _l("Name")},
    ".hardware.components.fans:*.description": {"title": _l("Description")},
    ".hardware.components.fans:*.software": {"title": _l("Software")},
    ".hardware.components.fans:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.fans:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.fans:*.model": {"title": _l("Model Name")},
    ".hardware.components.fans:*.location": {"title": _l("Location")},
    ".hardware.components.sensors:": {
        "title": _l("Sensors"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "manufacturer",
            "model",
            "location",
        ],
        "view": "invsensor_of_host",
    },
    ".hardware.components.sensors:*.index": {"title": _l("Index")},
    ".hardware.components.sensors:*.name": {"title": _l("Name")},
    ".hardware.components.sensors:*.description": {"title": _l("Description")},
    ".hardware.components.sensors:*.software": {"title": _l("Software")},
    ".hardware.components.sensors:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.sensors:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.sensors:*.model": {"title": _l("Model Name")},
    ".hardware.components.sensors:*.location": {"title": _l("Location")},
    ".hardware.components.modules:": {
        "title": _l("Modules"),
        "keyorder": [
            "index",
            "name",
            "description",
            "software",
            "serial",
            "model",
            "manufacturer",
            "bootloader",
            "firmware",
            "type",
            "location",
        ],
        "view": "invmodule_of_host",
    },
    ".hardware.components.modules:*.index": {"title": _l("Index")},
    ".hardware.components.modules:*.name": {"title": _l("Name")},
    ".hardware.components.modules:*.description": {"title": _l("Description")},
    ".hardware.components.modules:*.software": {"title": _l("Software")},
    ".hardware.components.modules:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.modules:*.model": {"title": _l("Model Name")},
    ".hardware.components.modules:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.modules:*.bootloader": {"title": _l("Bootloader")},
    ".hardware.components.modules:*.firmware": {"title": _l("Firmware")},
    ".hardware.components.modules:*.type": {"title": _l("Type")},
    ".hardware.components.modules:*.location": {"title": _l("Location")},
    ".hardware.components.stacks:": {
        "title": _l("Stacks"),
        "keyorder": ["index", "name", "description", "software", "serial", "model", "location"],
        "view": "invstack_of_host",
    },
    ".hardware.components.stacks:*.index": {"title": _l("Index")},
    ".hardware.components.stacks:*.name": {"title": _l("Name")},
    ".hardware.components.stacks:*.description": {"title": _l("Description")},
    ".hardware.components.stacks:*.software": {"title": _l("Software")},
    ".hardware.components.stacks:*.serial": {"title": _l("Serial Number")},
    ".hardware.components.stacks:*.manufacturer": {"title": _l("Manufacturer")},
    ".hardware.components.stacks:*.model": {"title": _l("Model Name")},
    ".hardware.components.stacks:*.location": {"title": _l("Location")},
    ".hardware.storage.": {"title": _l("Storage")},
    ".hardware.storage.controller.": {"title": _l("Controller")},
    ".hardware.storage.controller.version": {"title": _l("Version")},
    ".hardware.storage.disks:": {
        "title": _l("Block Devices"),
        # FIXME Only use key columns used in inventory_lnx_block_devices, inventory_win_disks
        # hp_proliant_da_phydrv, netapp_api_disk. Cleanup these different entries.
        "keyorder": ["fsnode", "controller", "signature"],
    },
    ".hardware.storage.disks:*.": {"title": _l("Block Device %d")},
    ".hardware.storage.disks:*.fsnode": {"title": _l("Filesystem Node")},
    ".hardware.storage.disks:*.controller": {"title": _l("Controller")},
    ".hardware.storage.disks:*.signature": {"title": _l("Disk ID")},
    ".hardware.storage.disks:*.vendor": {"title": _l("Vendor")},
    ".hardware.storage.disks:*.local": {"title": _l("Local")},
    ".hardware.storage.disks:*.bus": {"title": _l("Bus")},
    ".hardware.storage.disks:*.product": {"title": _l("Product")},
    ".hardware.storage.disks:*.serial": {"title": _l("Serial Number")},
    ".hardware.storage.disks:*.size": {"title": _l("Size"), "paint": "size"},
    ".hardware.storage.disks:*.type": {"title": _l("Type")},
    ".hardware.volumes.physical_volumes.*:": {
        "title": ("Physical Volumes"),
        "keyorder": [
            "volume_group_name",
            "physical_volume_name",
            "physical_volume_status",
            "physical_volume_total_partitions",
            "physical_volume_free_partitions"],
    },
    ".hardware.volumes.physical_volumes:*.volume_group_name": {"title": _l("Volume Group Name")},
    ".hardware.volumes.physical_volumes:*.physical_volume_name": {"title": _l("Physical Volume Name")},
    ".hardware.volumes.physical_volumes:*.physical_volume_status": {"title": _l("Physical Volume Status")},
    ".hardware.volumes.physical_volumes:*.physical_volume_total_partitions": {"title" : _l("Physical Volume Total Partitions")},
    ".hardware.volumes.physical_volumes:*.physical_volume_free_partitions": {"title" : _l("Physical Volume Free Partitions")},
    ".hardware.video:": {
        "title": _l("Graphic Cards"),
        "keyorder": ["name", "driver_version", "driver_date", "graphic_memory"],
    },
    ".hardware.video:*.": {"title": _l("Graphic Card %d")},
    ".hardware.video:*.name": {"title": _l("Graphic Card Name"), "short": _l("Card Name")},
    ".hardware.video:*.subsystem": {"title": _l("Vendor and Device ID"), "short": _l("Vendor")},
    ".hardware.video:*.driver": {"title": _l("Driver"), "short": _l("Driver")},
    ".hardware.video:*.driver_date": {"title": _l("Driver Date"), "short": _l("Driver Date")},
    ".hardware.video:*.driver_version": {
        "title": _l("Driver Version"), "short": _l("Driver Version")
    },
    ".hardware.video:*.graphic_memory": {"title": _l("Memory"), "paint": "bytes_rounded"},
    ".hardware.nwadapter:": {
        "title": _l("Network Adapters"),
        "keyorder": ["name", "type", "macaddress", "speed", "gateway", "ipv4_address", "ipv6_address", "ipv4_subnet", "ipv6_subnet"],
    },
    ".hardware.nwadapter:*.": {"title": _l("Network Adapter %d")},
    ".hardware.nwadapter:*.name": {"title": _l("Name")},
    ".hardware.nwadapter:*.type": {"title": _l("Type")},
    ".hardware.nwadapter:*.macaddress": {"title": _l("Physical Address (MAC)")},
    ".hardware.nwadapter:*.speed": {"title": _l("Speed"), "paint": "nic_speed"},
    ".hardware.nwadapter:*.ipv4_address": {"title": _l("IPv4 Address")},
    ".hardware.nwadapter:*.ipv4_subnet": {"title": _l("IPv4 Subnet")},
    ".hardware.nwadapter:*.ipv6_address": {"title": _l("IPv6 Address")},
    ".hardware.nwadapter:*.ipv6_subnet": {"title": _l("IPv6 Subnet")},
    ".hardware.nwadapter:*.gateway": {"title": _l("Gateway")},
    ".software.": {"title": _l("Software"), "icon": "software"},
    ".software.applications.": {"title": _l("Applications")},
    ".software.applications.check_mk.": {"title": _l("Checkmk")},
    ".software.applications.check_mk.num_hosts": {"title": _l("# Hosts"), "short": _l("Hosts"),},
    ".software.applications.check_mk.num_services": {"title": _l("# Services"), "short": _l("Services"),},
    ".software.applications.check_mk.versions:": {
        "title": _l("Versions"),
        "keyorder": ["version", "number", "edition", "demo", "num_sites"],
        "view": "invcmkversions_of_host",
    },
    ".software.applications.check_mk.versions:*.demo": {"paint": "bool"},
    ".software.applications.check_mk.sites:": {
        "title": _l("Sites"),
        "keyorder": [
            "site",
            "used_version",
            "num_hosts",
            "num_services",
            "check_mk_helper_usage",
            "fetcher_helper_usage",
            "checker_helper_usage",
            "livestatus_usage",
            "check_helper_usage",
            "autostart",
        ],
        "view": "invcmksites_of_host",
    },
    ".software.applications.check_mk.sites:*.used_version": {"short": _l("Version")},
    ".software.applications.check_mk.sites:*.num_hosts": {"short": _l("Hosts")},
    ".software.applications.check_mk.sites:*.num_services": {"short": _l("Services")},
    ".software.applications.check_mk.sites:*.check_mk_helper_usage": {"short": _l("CMK helper")},
    ".software.applications.check_mk.sites:*.fetcher_helper_usage": {"short": _l("Fetcher helper")},
    ".software.applications.check_mk.sites:*.checker_helper_usage": {"short": _l("Checker helper")},
    ".software.applications.check_mk.sites:*.livestatus_usage": {"short": _l("Live helper")},
    ".software.applications.check_mk.sites:*.check_helper_usage": {"short": _l("Act. helper")},
    ".software.applications.check_mk.sites:*.autostart": {"paint": "bool"},
    ".software.applications.check_mk.sites:*.apache": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.cmc": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.crontab": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.dcd": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.liveproxyd": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.mkeventd": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.mknotifyd": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.rrdcached": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.stunnel": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.xinetd": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.nagios": {"paint": "service_status"},
    ".software.applications.check_mk.sites:*.npcd": {"paint": "service_status"},
    ".software.applications.check_mk.cluster.": {"title": _l("Cluster")},
    ".software.applications.check_mk.cluster.is_cluster": {
        "title": _l("Cluster host"), "short": _l("Cluster"), "paint": "bool"
    },
    ".software.applications.check_mk.cluster.nodes:": {
        "title": _l("Nodes"),
        "keyorder": ["name"],
    },
    ".software.applications.check_mk.host_labels:": {
        "title": _l("Discovered host labels"),
        "keyorder": [
            "label",
            "plugin_name",
        ],
    },
    ".software.applications.check_mk.host_labels:*.label": {
        "title": _l("Label"),
        "paint": "cmk_label",
    },
    ".software.applications.check_mk.host_labels:*.plugin_name": {
        "title": _l("Discovered by plugin"),
    },
    ".software.applications.checkmk-agent.plugins:": {
        "title": _l("Agent plugins"),
        "keyorder": ["name", "version", "cache_interval"],
    },
    ".software.applications.checkmk-agent.local_checks:": {
        "title": _l("Local checks"),
        "keyorder": ["name", "version", "cache_interval"],
    },
    ".software.applications.docker.": {
        "icon": "docker", "title": "Docker", "keyorder": [
            "version",
            "num_containers_total",
            "num_containers_running",
            "num_containers_stopped",
            "num_containers_paused",
            "num_images",
            "registry",
        ]
    },
    ".software.applications.docker.version": {"title": _l("Version")},
    ".software.applications.docker.registry": {"title": _l("Registry")},
    ".software.applications.docker.swarm_state": {"title": _l("Swarm State")},
    ".software.applications.docker.swarm_node_id": {"title": _l("Swarm Node ID")},
    ".software.applications.docker.num_containers_total": {"title": _l("# Containers"), "short": _l("Containers"),},
    ".software.applications.docker.num_containers_running": {"title": _l("# Containers running"), "short": _l("Running"),},
    ".software.applications.docker.num_containers_stopped": {"title": _l("# Containers stopped"), "short": _l("Stopped"),},
    ".software.applications.docker.num_containers_paused": {"title": _l("# Containers paused"), "short": _l("Paused"),},
    ".software.applications.docker.num_images": {"title": _l("# Images")},
    ".software.applications.docker.node_labels:": {
        "title": _l("Node Labels"),
        "keyorder": ["label"],
    },
    ".software.applications.docker.node_labels:*.label": {"title": _l("Label")},
    ".software.applications.docker.swarm_manager:": {
        "title": _l("Swarm Managers"),
        "keyorder": ["NodeID"],
    },
    ".software.applications.docker.swarm_manager:*.NodeID": {"title": _l("Node ID")},
    ".software.applications.docker.swarm_manager:*.Addr": {"title": _l("Address")},
    ".software.applications.docker.images:": {
        "title": _l("Images"),
        "keyorder": ["id", "creation", "size", "labels", "amount_containers", "repotags", "repodigests"],
        "view": "invdockerimages_of_host",
        "is_show_more": False,
    },
    ".software.applications.docker.images:*.id": {"title": _l("ID")},
    ".software.applications.docker.images:*.creation": {"title": _l("Creation")},
    ".software.applications.docker.images:*.size": {"paint": "size"},
    ".software.applications.docker.images:*.labels": {"paint": "csv_labels"},
    ".software.applications.docker.images:*.amount_containers": {"title": _l("# Containers")},
    ".software.applications.docker.images:*.repotags": {"title": _l("Repository/Tag"), "paint": "csv_labels"},
    ".software.applications.docker.images:*.repodigests": {"title": _l("Digests"), "paint": "csv_labels"},

    # Node containers
    ".software.applications.docker.containers:": {
        "title": _l("Containers"),
        "keyorder": ["id", "creation", "name", "labels", "status", "image"],
        "view": "invdockercontainers_of_host",
        "is_show_more": False,
    },
    ".software.applications.docker.containers:*.id": {"title": _l("ID")},
    ".software.applications.docker.containers:*.labels": {"paint": "csv_labels"},
    ".software.applications.docker.networks.*.": {"title": "Network %s"},
    ".software.applications.docker.networks.*.network_id": {"title": "Network ID"},
    ".software.applications.docker.networks.*.name": {"title": "Name"},
    ".software.applications.docker.networks.*.scope": {"title": "Scope"},
    ".software.applications.docker.networks.*.labels": {"title": "Labels", "paint": "csv_labels"},
    ".software.applications.docker.container.": {"title": _l("Container")},
    ".software.applications.docker.container.node_name": {"title": _l("Node name")},
    ".software.applications.docker.container.ports:": {
        "title": _l("Ports"),
        "keyorder": ["port", "protocol", "host_addresses"],
    },
    ".software.applications.docker.container.networks:": {
        "title": _l("Networks"),
        "keyorder": ["name", "ip_address", "ip_prefixlen", "gateway", "mac_address", "network_id"],
    },
    ".software.applications.docker.container.networks:*.ip_address": {"title": _l("IP address")},
    ".software.applications.docker.container.networks:*.ip_prefixlen": {"title": _l("IP Prefix")},
    ".software.applications.docker.container.networks:*.mac_address": {"title": _l("MAC address")},
    ".software.applications.docker.container.networks:*.network_id": {"title": _l("Network ID")},
    ".software.applications.docker.networks.*.containers:": {
        "keyorder": ["name", "id", "ipv4_address", "ipv6_address", "mac_address"],
    },
    ".software.applications.docker.networks.*.containers:*.id": {"title": _l("ID")},
    ".software.applications.docker.networks.*.containers:*.ipv4_address": {
        "title": _l("IPv4 address"),
    },
    ".software.applications.docker.networks.*.containers:*.ipv6_address": {
        "title": _l("IPv6 address"),
    },
    ".software.applications.docker.networks.*.containers:*.mac_address": {
        "title": _l("MAC address"),
    },
    ".software.applications.fortinet.fortisandbox:": {
        "title": _l("FortiSandbox Software"),
        "keyorder": ["name", "version"],
    },
    ".software.applications.fortinet.fortisandbox:*.name": {"title": _l("Name")},
    ".software.applications.fortinet.fortisandbox:*.version": {"title": _l("Version")},
    ".software.applications.fortinet.fortigate_high_availability.": {
        "title": _l("FortiGate HighAvailability"),
    },

    ".software.applications.fritz.link_type": {"title": _l("Link type")},
    ".software.applications.fritz.wan_access_type": {"title": _l("WAN access type")},
    ".software.applications.fritz.auto_disconnect_time": {"title": _l("Auto-disconnect time")},
    ".software.applications.fritz.dns_server_1": {"title": _l("DNS server 1")},
    ".software.applications.fritz.dns_server_2": {"title": _l("DNS server 2")},
    ".software.applications.fritz.voip_dns_server_1": {"title": _l("VoIP DNS server 1")},
    ".software.applications.fritz.voip_dns_server_2": {"title": _l("VoIP DNS server 2")},
    ".software.applications.fritz.statefulset.upnp_config_enabled": {"title": _l("uPnP configuration enabled")},

    ".software.applications.kube.": {"title": _l("Kubernetes")},

    ".software.applications.kube.labels:": {
        "title": _l("Labels"),
        "keyorder": ["label_name", "label_value"],
    },
    ".software.applications.kube.labels:*.label_name": {
        "title": _l("Name"),
    },
    ".software.applications.kube.labels:*.label_value": {
        "title": _l("Value"),
    },

    ".software.applications.kube.network:": {
        "title": _l("Network"),
        "keyorder": ["ip", "address_type"],
    },
    ".software.applications.kube.network:*.ip": {
        "title": _l("IP address"),
    },
    ".software.applications.kube.network:*.address_type": {
        "title": _l("Type"),
    },
    ".software.applications.kube.containers:": {
        "title": _l("Containers"),
        "keyorder": [
            "name",
            "ready",
            "restart_count",
            "image",
            "image_pull_policy",
            "image_id",
            "container_id",
        ],
    },

    ".software.applications.kube.metadata.": {
        "title": _l("General"),
        "keyorder": [
            "object",
            "name",
            "namespace",
        ],
    },
    ".software.applications.kube.metadata.object": {"title": _l("Object")},
    ".software.applications.kube.metadata.name": {"title": _l("Name")},
    ".software.applications.kube.metadata.namespace": {"title": _l("Namespace")},

    ".software.applications.kube.containers:*.name": {"title": _l("Name")},
    ".software.applications.kube.containers:*.image": {"title": _l("Image")},
    ".software.applications.kube.containers:*.image_pull_policy": {"title": _l("Image pull policy")},
    ".software.applications.kube.containers:*.image_id": {"title": _l("Image ID")},
    ".software.applications.kube.containers:*.ready": {"title": _l("Ready"), "paint": "container_ready"},
    ".software.applications.kube.containers:*.restart_count": {"title": _l("Restart count")},
    ".software.applications.kube.containers:*.container_id": {"title": _l("Container ID")},

    ".software.applications.kube.cluster.": {"title": _l("Cluster")},
    ".software.applications.kube.cluster.version": {"title": _l("Version")},

    ".software.applications.kube.deployment.": {"title": _l("Deployment")},
    ".software.applications.kube.deployment.strategy": {"title": _l("StrategyType")},
    ".software.applications.kube.deployment.match_labels": {"title": _l("matchLabels")},
    ".software.applications.kube.deployment.match_expressions": {"title": _l("matchExpressions")},

    ".software.applications.kube.daemonset.": {"title": _l("DaemonSet")},
    ".software.applications.kube.daemonset.strategy": {"title": _l("StrategyType")},
    ".software.applications.kube.daemonset.match_labels": {"title": _l("matchLabels")},
    ".software.applications.kube.daemonset.match_expressions": {"title": _l("matchExpressions")},

    ".software.applications.kube.statefulset.": {"title": _l("StatefulSet")},
    ".software.applications.kube.statefulset.strategy": {"title": _l("StrategyType")},
    ".software.applications.kube.statefulset.match_labels": {"title": _l("matchLabels")},
    ".software.applications.kube.statefulset.match_expressions": {"title": _l("matchExpressions")},

    ".software.applications.kube.node.": { "title": _l("Node") },
    ".software.applications.kube.node.operating_system": {"title": _l("Operating system")},
    ".software.applications.kube.node.os_image": {"title": _l("OS image")},
    ".software.applications.kube.node.kernel_version": {"title": _l("Kernel version")},
    ".software.applications.kube.node.architecture": {"title": _l("Architecture")},
    ".software.applications.kube.node.container_runtime_version": {"title": _l("Container runtime version")},
    ".software.applications.kube.node.kubelet_version": {"title": _l("Kubelet version")},
    ".software.applications.kube.node.kube_proxy_version": {"title": _l("Kube-proxy version")},

    ".software.applications.kube.pod.": {"title": _l("Pod")},
    ".software.applications.kube.pod.name": {"title": _l("Name")},
    ".software.applications.kube.pod.namespace": {"title": _l("Namespace")},
    ".software.applications.kube.pod.dns_policy": {"title": _l("DNS policy")},
    ".software.applications.kube.pod.host_ip": {"title": _l("Host IP")},
    ".software.applications.kube.pod.host_network": {"title": _l("Host network")},
    ".software.applications.kube.pod.node": {"title": _l("Node")},
    ".software.applications.kube.pod.pod_ip": {"title": _l("Pod IP")},
    ".software.applications.kube.pod.qos_class": {"title": _l("QoS class")},

    ".software.applications.citrix.": {"title": _l("Citrix")},
    ".software.applications.citrix.controller.": {"title": _l("Controller")},
    ".software.applications.citrix.controller.controller_version": {
        "title": _l("Controller Version"),
    },
    ".software.applications.citrix.vm.": {"title": _l("Virtual Machine")},
    ".software.applications.citrix.vm.desktop_group_name": {"title": _l("Desktop Group Name")},
    ".software.applications.citrix.vm.catalog": {"title": _l("Catalog")},
    ".software.applications.citrix.vm.agent_version": {"title": _l("Agent Version")},
    ".software.applications.oracle.": {"title": _l("Oracle DB")},
    ".software.applications.oracle.systemparameter:": {
        "title": _l("V$SYSTEM_PARAMETER"),
        "keyorder": [
            "sid",
            "name",
            "value",
            "isdefault",
        ],
        "view": "invorasystemparameter_of_host",
    },
    ".software.applications.oracle.systemparameter:*.sid": {"title": _l("SID")},
    ".software.applications.oracle.systemparameter:*.name": {"title": _l("Name")},
    ".software.applications.oracle.systemparameter:*.value": {"title": _l("Value")},
    ".software.applications.oracle.systemparameter:*.isdefault": {"title": _l("Is default")},
    ".software.applications.oracle.instance:": {
        "title": _l("Instances"),
        "keyorder": [
            "sid",
            "pname",
            "version",
            "openmode",
            "logmode",
            "logins",
            "db_uptime",
            "db_creation_time",
        ],
        "view": "invorainstance_of_host",
    },
    ".software.applications.oracle.instance:*.sid": {"title": _l("SID")},
    ".software.applications.oracle.instance:*.pname": {"title": _l("Process Name")},
    ".software.applications.oracle.instance:*.version": {"title": _l("Version")},
    ".software.applications.oracle.instance:*.openmode": {"title": _l("Open mode")},
    ".software.applications.oracle.instance:*.logmode": {"title": _l("Log mode")},
    ".software.applications.oracle.instance:*.logins": {"title": _l("Logins")},
    ".software.applications.oracle.instance:*.db_uptime": {"title": _l("Uptime"), "paint": "age"},
    ".software.applications.oracle.instance:*.db_creation_time": {
        "title": _l("Creation time"),
    },
    ".software.applications.oracle.dataguard_stats:": {
        "title": _l("Dataguard statistics"),
        "keyorder": ["sid", "db_unique", "role", "switchover"],
        "view": "invoradataguardstats_of_host",
    },
    ".software.applications.oracle.dataguard_stats:*.sid": {"title": _l("SID")},
    ".software.applications.oracle.dataguard_stats:*.db_unique": {"title": _l("Name")},
    ".software.applications.oracle.dataguard_stats:*.role": {"title": _l("Role")},
    ".software.applications.oracle.dataguard_stats:*.switchover": {"title": _l("Switchover")},
    ".software.applications.oracle.recovery_area:": {
        "title": _l("Recovery area"),
        "keyorder": ["sid", "flashback"],
        "view": "invorarecoveryarea_of_host",
    },
    ".software.applications.oracle.recovery_area:*.sid": {"title": _l("SID")},
    ".software.applications.oracle.recovery_area:*.flashback": {"title": _l("Flashback")},
    ".software.applications.oracle.sga:": {
        "title": _l("SGA Info"),
        "keyorder": [
            "sid",
            "fixed_size",
            "redo_buffer",
            "buf_cache_size",
            "in_mem_area_size",
            "shared_pool_size",
            "large_pool_size",
            "java_pool_size",
            "streams_pool_size",
            "shared_io_pool_size",
            "data_trans_cache_size",
            "granule_size",
            "max_size",
            "start_oh_shared_pool",
            "free_mem_avail",
        ],
        "view": "invorasga_of_host",
    },
    ".software.applications.oracle.sga:*.sid": {"title": _l("SID")},
    ".software.applications.oracle.sga:*.fixed_size": {"title": _l("Fixed size"), "paint": "size"},
    ".software.applications.oracle.sga:*.max_size": {"title": _l("Maximum size"), "paint": "size"},
    ".software.applications.oracle.sga:*.redo_buffer": {
        "title": _l("Redo buffers"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.buf_cache_size": {
        "title": _l("Buffer cache size"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.in_mem_area_size": {
        "title": _l("In-memory area"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.shared_pool_size": {
        "title": _l("Shared pool size"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.large_pool_size": {
        "title": _l("Large pool size"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.java_pool_size": {
        "title": _l("Java pool size"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.streams_pool_size": {
        "title": _l("Streams pool size"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.shared_io_pool_size": {
        "title": _l("Shared pool size"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.data_trans_cache_size": {
        "title": _l("Data transfer cache size"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.granule_size": {
        "title": _l("Granule size"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.start_oh_shared_pool": {
        "title": _l("Startup overhead in shared pool"), "paint": "size"
    },
    ".software.applications.oracle.sga:*.free_mem_avail": {
        "title": _l("Free SGA memory available"), "paint": "size"
    },
    ".software.applications.oracle.pga:": {
        "title": _l("PGA Info"),
        "keyorder": [
            "sid",
            "aggregate_pga_auto_target",
            "aggregate_pga_target_parameter",
            "bytes_processed",
            "extra_bytes_read_written",
            "global_memory_bound",
            "maximum_pga_allocated",
            "maximum_pga_used_for_auto_workareas",
            "maximum_pga_used_for_manual_workareas",
            "total_pga_allocated",
            "total_pga_inuse",
            "total_pga_used_for_auto_workareas",
            "total_pga_used_for_manual_workareas",
            "total_freeable_pga_memory",
        ],
        "view": "invorapga_of_host",
    },
    ".software.applications.oracle.pga:*.sid": {"title": _l("SID")},
    ".software.applications.oracle.pga:*.aggregate_pga_auto_target": {"title": _l("Aggregate PGA auto target"), "paint": "size"},
    ".software.applications.oracle.pga:*.aggregate_pga_target_parameter": {"title": _l("Aggregate PGA target parameter"), "paint": "size"},
    ".software.applications.oracle.pga:*.bytes_processed": {"title": _l("Bytes processed"), "paint": "size"},
    ".software.applications.oracle.pga:*.extra_bytes_read_written": {"title": _l("Extra bytes read/written"), "paint": "size"},
    ".software.applications.oracle.pga:*.global_memory_bound": {"title": _l("Global memory bound"), "paint": "size"},
    ".software.applications.oracle.pga:*.maximum_pga_allocated": {"title": _l("Maximum PGA allocated"), "paint": "size"},
    ".software.applications.oracle.pga:*.maximum_pga_used_for_auto_workareas": {"title": _l("Maximum PGA used for auto workareas"), "paint": "size"},
    ".software.applications.oracle.pga:*.maximum_pga_used_for_manual_workareas": {"title": _l("Maximum PGA used for manual workareas"), "paint": "size"},
    ".software.applications.oracle.pga:*.total_pga_allocated": {"title": _l("Total PGA allocated"), "paint": "size"},
    ".software.applications.oracle.pga:*.total_pga_inuse": {"title": _l("Total PGA inuse"), "paint": "size"},
    ".software.applications.oracle.pga:*.total_pga_used_for_auto_workareas": {"title": _l("Total PGA used for auto workareas"), "paint": "size"},
    ".software.applications.oracle.pga:*.total_pga_used_for_manual_workareas": {"title": _l("Total PGA used for manual workareas"), "paint": "size"},
    ".software.applications.oracle.pga:*.total_freeable_pga_memory": {"title": _l("Total freeable PGA memory"), "paint": "size"},
    ".software.applications.oracle.tablespaces:": {
        "title": _l("Tablespaces"),
        "keyorder": [
            "sid",
            "name",
            "version",
            "type",
            "autoextensible",
            "current_size",
            "max_size",
            "used_size",
            "num_increments",
            "increment_size",
            "free_space",
        ],
        "view": "invoratablespace_of_host",
    },
    ".software.applications.oracle.tablespaces:*.sid": {"title": _l("SID")},
    ".software.applications.oracle.tablespaces:*.name": {"title": _l("Name")},
    ".software.applications.oracle.tablespaces:*.version": {"title": _l("Version")},
    ".software.applications.oracle.tablespaces:*.type": {"title": _l("Type")},
    ".software.applications.oracle.tablespaces:*.autoextensible": {"title": _l("Autoextensible")},
    ".software.applications.oracle.tablespaces:*.current_size": {
        "title": _l("Current size"), "paint": "size"
    },
    ".software.applications.oracle.tablespaces:*.max_size": {
        "title": _l("Max. size"), "paint": "size"
    },
    ".software.applications.oracle.tablespaces:*.used_size": {
        "title": _l("Used size"), "paint": "size"
    },
    ".software.applications.oracle.tablespaces:*.num_increments": {
        "title": _l("Number of increments"),
    },
    ".software.applications.oracle.tablespaces:*.increment_size": {
        "title": _l("Increment size"), "paint": "size"
    },
    ".software.applications.oracle.tablespaces:*.free_space": {
        "title": _l("Free space"), "paint": "size"
    },
    ".software.applications.vmwareesx:*.": {"title": _l("Datacenter %d")},
    ".software.applications.vmwareesx:*.clusters:*.": {"title": _l("Cluster %d")},
    ".software.applications.mssql.": {"title": _l("MSSQL")},
    ".software.applications.mssql.instances:": {
        "title": _l("Instances"),
        "keyorder": [
            "name",
            "product",
            "edition",
            "version",
            "clustered",
            "cluster_name",
            "active_node",
            "node_names",
        ],
    },
    ".software.applications.mssql.instances:*.clustered": {
        "title": _l("Clustered"), "paint": "mssql_is_clustered"
    },
    ".software.applications.ibm_mq.": {
        "title": _l("IBM MQ"),
        "keyorder": ["managers", "channels", "queues"],
    },
    ".software.applications.ibm_mq.managers:": {
        "title": _l("Managers"),
        "keyorder": ["name", "instver", "instname", "status", "standby", "ha"],
        "view": "invibmmqmanagers_of_host",
    },
    ".software.applications.ibm_mq.managers:*.name": {"title": _l("Queue Manager Name")},
    ".software.applications.ibm_mq.managers:*.instver": {"title": _l("Version")},
    ".software.applications.ibm_mq.managers:*.instname": {"title": _l("Installation")},
    ".software.applications.ibm_mq.managers:*.status": {"title": _l("Status")},
    ".software.applications.ibm_mq.managers:*.standby": {"title": _l("Standby")},
    ".software.applications.ibm_mq.managers:*.ha": {"title": _l("HA")},
    ".software.applications.ibm_mq.channels:": {
        "title": _l("Channels"),
        "keyorder": ["qmgr", "name", "type", "status", "monchl"],
        "view": "invibmmqchannels_of_host",
    },
    ".software.applications.ibm_mq.channels:*.qmgr": {"title": _l("Queue Manager Name")},
    ".software.applications.ibm_mq.channels:*.name": {"title": _l("Channel")},
    ".software.applications.ibm_mq.channels:*.type": {"title": _l("Type")},
    ".software.applications.ibm_mq.channels:*.status": {"title": _l("Status")},
    ".software.applications.ibm_mq.channels:*.monchl": {"title": _l("Monitoring")},
    ".software.applications.ibm_mq.queues:": {
        "title": _l("Queues"),
        "keyorder": ["qmgr", "name", "maxdepth", "maxmsgl", "created", "altered", "monq"],
        "view": "invibmmqqueues_of_host",
    },
    ".software.applications.ibm_mq.queues:*.qmgr": {"title": _l("Queue Manager Name")},
    ".software.applications.ibm_mq.queues:*.name": {"title": _l("Queue")},
    ".software.applications.ibm_mq.queues:*.maxdepth": {"title": _l("Max Depth")},
    ".software.applications.ibm_mq.queues:*.maxmsgl": {"title": _l("Max Length")},
    ".software.applications.ibm_mq.queues:*.created": {"title": _l("Created")},
    ".software.applications.ibm_mq.queues:*.altered": {"title": _l("Altered")},
    ".software.applications.ibm_mq.queues:*.monq": {"title": _l("Monitoring")},
    ".software.bios.": {"title": _l("BIOS")},
    ".software.bios.vendor": {"title": _l("Vendor")},
    ".software.bios.version": {"title": _l("Version")},
    ".software.bios.date": {"title": _l("Date"), "paint": "date"},
    ".software.configuration.": {"title": _l("Configuration")},
    ".software.configuration.snmp_info.": {"title": _l("SNMP Information")},
    ".software.configuration.snmp_info.contact": {"title": _l("Contact")},
    ".software.configuration.snmp_info.location": {"title": _l("Location"), "is_show_more": False},
    ".software.configuration.snmp_info.name": {"title": _l("System name")},
    ".software.firmware.": {
        "title": _l("Firmware"),
        "keyorder": [
            "vendor",
            "version",
        ],
    },
    ".software.firmware.vendor": {"title": _l("Vendor")},
    ".software.firmware.version": {"title": _l("Version")},
    ".software.firmware.platform_level": {"title": _l("Platform Firmware level")},
    ".software.kernel_config:": {
        "title": _l("Kernel Configuration (sysctl)"),
        "keyorder": ["name", "value"],
        "view": "invkernelconfig_of_host",
    },
    ".software.kernel_config:*.name": {"title": _l("Parameter name")},
    ".software.kernel_config:*.value": {"title": _l("Value")},
    ".software.os.": {"title": _l("Operating System")},
    ".software.os.name": {"title": _l("Name"), "short": _l("Operating System"), "is_show_more": False},
    ".software.os.version": {"title": _l("Version")},
    ".software.os.vendor": {"title": _l("Vendor")},
    ".software.os.type": {"title": _l("Type"), "is_show_more": False},  # e.g. "linux"
    ".software.os.install_date": {"title": _l("Install Date"), "paint": "date"},
    ".software.os.kernel_version": {"title": _l("Kernel Version"), "short": _l("Kernel")},
    ".software.os.arch": {"title": _l("Kernel Architecture"), "short": _l("Architecture")},
    ".software.os.service_pack": {"title": _l("Latest Service Pack"), "short": _l("Service Pack")},
    ".software.os.service_packs:": {"title": _l("Service Packs"), "keyorder": ["name"]},
    ".software.packages:": {
        "title": _l("Packages"),
        "icon": "packages",
        "keyorder": ["name", "version", "arch", "package_type", "summary"],
        "view": "invswpac_of_host",
        "is_show_more": False,
    },
    ".software.packages:*.name": {"title": _l("Name")},
    ".software.packages:*.arch": {"title": _l("Architecture")},
    ".software.packages:*.package_type": {"title": _l("Type")},
    ".software.packages:*.summary": {"title": _l("Description")},
    ".software.packages:*.version": {
        "title": _l("Version"), "sort": cmk.gui.utils.cmp_version, "filter": FilterInvtableVersion
    },
    ".software.packages:*.vendor": {"title": _l("Publisher")},
    ".software.packages:*.package_version": {
        "title": _l("Package Version"), "sort": cmk.gui.utils.cmp_version, "filter": FilterInvtableVersion
    },
    ".software.packages:*.install_date": {"title": _l("Install Date"), "paint": "date"},
    ".software.packages:*.size": {"title": _l("Size"), "paint": "count"},
    ".software.packages:*.path": {"title": _l("Path")},
    ".networking.": {"title": _l("Networking"), "icon": "networking"},
    ".networking.total_interfaces": {"title": _l("Interfaces"), "paint": "count"},
    ".networking.total_ethernet_ports": {"title": _l("Ports"), "paint": "count"},
    ".networking.hostname": {"title": _l("Hostname")},
    ".networking.available_ethernet_ports": {"title": _l("Ports available"), "paint": "count"},
    ".networking.addresses:": {
        "title": _l("IP Addresses"),
        "keyorder": ["address", "device", "type"],
    },
    ".networking.addresses:*.address": {"title": _l("Address")},
    ".networking.addresses:*.device": {"title": _l("Device")},
    ".networking.addresses:*.type": {"title": _l("Address Type"), "paint": "ip_address_type"},
    ".networking.interfaces:": {
        "title": _l("Interfaces"),
        "keyorder": [
            "index",
            "description",
            "alias",
            "oper_status",
            "admin_status",
            "available",
            "speed",
        ],
        "view": "invinterface_of_host",
        "is_show_more": False,
    },
    ".networking.interfaces:*.index": {
        "title": _l("Index"), "paint": "number", "filter": FilterInvtableIDRange
    },
    ".networking.interfaces:*.description": {"title": _l("Description")},
    ".networking.interfaces:*.alias": {"title": _l("Alias")},
    ".networking.interfaces:*.phys_address": {"title": _l("Physical Address (MAC)")},
    ".networking.interfaces:*.oper_status": {
        "title": _l("Operational Status"),
        "short": _l("Status"),
        "paint": "if_oper_status",
        "filter": FilterInvtableOperStatus,
    },
    ".networking.interfaces:*.admin_status": {
        "title": _l("Administrative Status"),
        "short": _l("Admin"),
        "paint": "if_admin_status",
        "filter": FilterInvtableAdminStatus,
    },
    ".networking.interfaces:*.available": {
        "title": _l("Port Usage"),
        "short": _l("Used"),
        "paint": "if_available",
        "filter": FilterInvtableAvailable,
    },
    ".networking.interfaces:*.speed": {"title": _l("Speed"), "paint": "nic_speed"},
    ".networking.interfaces:*.port_type": {
        "title": _l("Type"),
        "paint": "if_port_type",
        "filter": FilterInvtableInterfaceType,
    },
    ".networking.interfaces:*.last_change": {
        "title": _l("Last Change"),
        "paint": "timestamp_as_age_days",
        "filter": FilterInvtableTimestampAsAge,
    },
    ".networking.interfaces:*.vlans": {"title": _l("VLANs")},
    ".networking.interfaces:*.vlantype": {"title": _l("VLAN type")},
    ".networking.routes:": {
        "title": _l("Routes"), "keyorder": ["target", "device", "type", "gateway"]
    },
    ".networking.routes:*.target": {"title": _l("Target"), "paint": "ipv4_network"},
    ".networking.routes:*.device": {"title": _l("Device")},
    ".networking.routes:*.type": {"title": _l("Type of route"), "paint": "route_type"},
    ".networking.routes:*.gateway": {"title": _l("Gateway")},
    ".networking.wlan.": {"title": _l("WLAN")},
    ".networking.wlan.controller.": {"title": _l("Controller")},
    ".networking.wlan.controller.accesspoints:": {
        "title": _l("Access Points"),
        "keyorder": ["name", "group", "ip_addr", "model", "serial", "sys_location"],
    },
    ".networking.wlan.controller.accesspoints:*.name": {"title": _l("Name")},
    ".networking.wlan.controller.accesspoints:*.group": {"title": _l("Group")},
    ".networking.wlan.controller.accesspoints:*.ip_addr": {"title": _l("IP Address")},
    ".networking.wlan.controller.accesspoints:*.model": {"title": _l("Model")},
    ".networking.wlan.controller.accesspoints:*.serial": {"title": _l("Serial Number")},
    ".networking.wlan.controller.accesspoints:*.sys_location": {"title": _l("System Location")},
    ".networking.tunnels:": {
        "title" : _l("Networking Tunnels"),
        "keyorder": ["peername", "index", "peerip", "sourceip", "tunnelinterface", "linkpriority"],
    },
    ".networking.tunnels:*.index": { "title" : _l("Index") },
    ".networking.tunnels:*.linkpriority": { "title" : _l("Link Priority") },
    ".networking.tunnels:*.peerip": { "title" : _l("Peer IP Address") },
    ".networking.tunnels:*.peername": { "title" : _l("Peer Name")  },
    ".networking.tunnels:*.sourceip": { "title" : _l("Source IP Address") },
    ".networking.tunnels:*.tunnelinterface": { "title" : _l("Tunnel Interface") },
}
)

# yapf: enable
