# Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.
"""Fetch-phase repository for the Windows agent's pinned wheel closure.

``python-3.cab`` ships the Pipfile packages (and their transitive dependencies)
as ``win_amd64`` / ``cp3xx`` wheels.  This repository rule downloads that pinned
closure during Bazel's fetch phase — exactly like the ``python_msi_*``
``http_file`` repos and the Python source ``http_archive`` — so the
``python_cab`` build action stays hermetic (no in-action network).

The pins live in ``windows_python_wheels.lock.json`` (url + sha256 per wheel),
regenerated by ``refresh_wheel_pins.py``.  The downloaded wheels are exposed as a
single ``:wheels`` filegroup the rule stages into a ``pip --find-links`` dir, and
the locked ``name==version`` pins as ``REQUIREMENTS`` in ``requirements.bzl`` so
the install request always matches the closure exactly (every package — including
transitive deps — installs as explicitly REQUESTED, like the historic pipenv flow).

Each wheel also gets a ``package_metadata`` target carrying its
``pkg:pypi/<name>@<version>`` PURL (attached to the ``:wheels`` filegroup) so the
SBOM aspect can attribute the closure like every other Checkmk dependency.
"""

_BUILD_FILE = """\
# Generated by windows_python_wheels.bzl — do not edit.
load("@package_metadata//rules:package_metadata.bzl", "package_metadata")

package(default_visibility = ["//visibility:public"])

{metadata}
filegroup(
    name = "wheels",
    srcs = glob(["*.whl"]),
    package_metadata = [{metadata_targets}],
)
"""

_METADATA_RULE = """\
package_metadata(
    name = "{target}",
    purl = "pkg:pypi/{name}@{version}",
)
"""

def _pep503_name(name):
    """PEP 503 normalized project name used in the pypi PURL (and target name)."""
    normalized = ""
    prev_dash = False
    for char in name.lower().elems():
        if char in "-_.":
            if not prev_dash:
                normalized += "-"
            prev_dash = True
        else:
            normalized += char
            prev_dash = False
    return normalized

def _windows_python_wheels_impl(rctx):
    lock = json.decode(rctx.read(rctx.path(rctx.attr.lock)))
    wheels = lock["wheels"]
    for wheel in wheels:
        rctx.report_progress("Downloading {}".format(wheel["filename"]))
        rctx.download(
            url = wheel["url"],
            output = wheel["filename"],
            sha256 = wheel["sha256"],
        )

    metadata_rules = []
    metadata_targets = []
    for wheel in wheels:
        name = _pep503_name(wheel["name"])
        target = "{}_metadata".format(name)
        metadata_rules.append(_METADATA_RULE.format(
            target = target,
            name = name,
            version = wheel["version"],
        ))
        metadata_targets.append('":{}"'.format(target))

    rctx.file("BUILD.bazel", _BUILD_FILE.format(
        metadata = "\n".join(metadata_rules),
        metadata_targets = ", ".join(metadata_targets),
    ))
    rctx.file(
        "requirements.bzl",
        "# Generated by windows_python_wheels.bzl — do not edit.\n" +
        "REQUIREMENTS = {}\n".format(
            json.encode([
                "{}=={}".format(wheel["name"], wheel["version"])
                for wheel in wheels
            ]),
        ),
    )

windows_python_wheels = repository_rule(
    implementation = _windows_python_wheels_impl,
    attrs = {
        "lock": attr.label(
            mandatory = True,
            allow_single_file = [".json"],
            doc = "windows_python_wheels.lock.json pin file (regenerate via refresh_wheel_pins.py).",
        ),
    },
    doc = "Downloads the pinned win_amd64 wheel closure for python-3.cab at fetch time.",
)
