# Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.
"""Fetch-phase repository for the Windows agent's pinned wheel closure.

``python-3.cab`` ships the Pipfile packages (and their transitive dependencies)
as ``win_amd64`` / ``cp3xx`` wheels.  This repository rule downloads that pinned
closure during Bazel's fetch phase — exactly like the ``python_msi_*``
``http_file`` repos and the Python source ``http_archive`` — so the
``python_cab`` build action stays hermetic (no in-action network).

The pins live in ``windows_python_wheels.lock.json`` (url + sha256 per wheel),
regenerated by ``refresh_wheel_pins.py``.  The downloaded wheels are exposed as a
single ``:wheels`` filegroup the rule stages into a ``pip --find-links`` dir, and
the locked ``name==version`` pins as ``REQUIREMENTS`` in ``requirements.bzl`` so
the install request always matches the closure exactly (every package — including
transitive deps — installs as explicitly REQUESTED, like the historic pipenv flow).
"""

_BUILD_FILE = """\
# Generated by windows_python_wheels.bzl — do not edit.
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "wheels",
    srcs = glob(["*.whl"]),
)
"""

def _windows_python_wheels_impl(rctx):
    lock = json.decode(rctx.read(rctx.path(rctx.attr.lock)))
    wheels = lock["wheels"]
    for wheel in wheels:
        rctx.report_progress("Downloading {}".format(wheel["filename"]))
        rctx.download(
            url = wheel["url"],
            output = wheel["filename"],
            sha256 = wheel["sha256"],
        )
    rctx.file("BUILD.bazel", _BUILD_FILE)
    rctx.file(
        "requirements.bzl",
        "# Generated by windows_python_wheels.bzl — do not edit.\n" +
        "REQUIREMENTS = {}\n".format(
            json.encode([
                "{}=={}".format(wheel["name"], wheel["version"])
                for wheel in wheels
            ]),
        ),
    )

windows_python_wheels = repository_rule(
    implementation = _windows_python_wheels_impl,
    attrs = {
        "lock": attr.label(
            mandatory = True,
            allow_single_file = [".json"],
            doc = "windows_python_wheels.lock.json pin file (regenerate via refresh_wheel_pins.py).",
        ),
    },
    doc = "Downloads the pinned win_amd64 wheel closure for python-3.cab at fetch time.",
)
