type = "Component"
display_name = "Plugins: Silver Peak"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["mohamed.saleh@checkmk.com"]
description = """
Plugin for Silver Peak VX SD-WAN appliances.
"""
