type = "Component"
display_name = "Plugins: JAR Signature"
has_support_component = true
members_required = 0
tier = 4
product_managers = ["andrea.vaccaro@checkmk.com"]
description = """
Plugin that verifies the signature of a Java JAR file.
"""
