#!/usr/bin/env python3
# Copyright (C) 2017 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

import sys

sys.stdout.write("""#
# This file has been created by OMD out of the following files:
#
""")

for fn in sys.argv[1:]:
    if fn.endswith("~"):
        continue
    sys.stdout.write("# %s\n" % fn)

sys.stdout.write("""#
# Do not edit this file. It will be recreated each time Nagios
# is started or reloaded. Rather change things in the original
# files.
#
# ------------------------------------------------------------

""")

for fn in sys.argv[1:]:
    if fn.endswith("~"):
        continue

    contline = ""
    with open(fn) as opened_file:
        for lineno, line in enumerate(opened_file):
            ls = line.strip()
            if ls == "" or ls.startswith("#"):
                continue
            if ls[-1] == "\\":
                contline += ls[:-1] + " "
                continue

            sys.stdout.write("# %s:%d\n" % (fn, lineno))
            sys.stdout.write(contline + line)
            contline = ""
