load("//:package_versions.bzl", "PYTHON_VERSION")

__PYTHON_VERSION_ARRAY = PYTHON_VERSION.split(".")
PYTHON_VERSION_MAJOR = __PYTHON_VERSION_ARRAY[0]
PYTHON_VERSION_MINOR = __PYTHON_VERSION_ARRAY[1]
PYTHON_MAJOR_DOT_MINOR = "%s.%s" % (PYTHON_VERSION_MAJOR, PYTHON_VERSION_MINOR)
