# generated by datamodel-codegen:
#   filename:  vue_types.json
#   timestamp: 2024-03-14T14:18:18+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List, Optional, Union


@dataclass
class VueBase:
    title: str
    help: Optional[str] = None


@dataclass
class VueInteger(VueBase):
    vue_type: str
    label: Optional[str] = None
    unit: Optional[str] = None


@dataclass
class VueFloat(VueBase):
    vue_type: str
    label: Optional[str] = None
    unit: Optional[str] = None


@dataclass
class VueText(VueBase):
    vue_type: str
    placeholder: Optional[str] = None


@dataclass
class Model:
    all_schemas: Optional[List[VueSchema]] = None


@dataclass
class VueList(VueBase):
    vue_type: str
    add_text: Optional[str] = None
    vue_schema: Optional[VueSchema] = None


@dataclass
class VueDictionaryElement:
    ident: str
    required: bool
    default_value: Any
    vue_schema: VueSchema


@dataclass
class VueDictionary(VueBase):
    vue_type: str
    elements: List[VueDictionaryElement]


VueSchema = Union[VueInteger, VueFloat, VueText, VueDictionary, VueList]
